### ISSUE TITLE
Can't find pod identity metrics in promethus

### ISSUE THREAD

**Issue by dawn-chu** [Azure/aad-pod-identity#1000]
Hi, 
      We have aad-pod-identity helm chart and promethus-operator helm chart installed and working on our AKS cluster. We are able to see metrics from promethus of the node (node_exporter) to the container (cAdvisor). But We are not able to see any pod identity metric. Is there anything else required to enable those metrics?
![image](https://user-images.githubusercontent.com/16061334/111207811-4f278000-8587-11eb-9b3b-bc56f3680561.png)

**Comment by dawn-chu** [comment]
https://azure.github.io/aad-pod-identity/docs/configure/prometheus_monitoring/

**Comment by aramase** [comment]
@dawn-chu By default MIC and NMI will post metrics on the port and url as mentioned in the doc. You can setup prometheus to scrape the metrics endpoint to collect the metrics.

**Comment by dawn-chu** [comment]
Thanks, I'll give it a try. BTW, it would be good to have configuration to enable it as what keda does: https://github.com/kedacore/charts/tree/master/keda

**Comment by dawn-chu** [comment]
@aramase  Our service is using [Promethus-operator](https://github.com/helm/charts/tree/master/stable/prometheus-operator) helm chart to install promethus on our AKS cluster, in promethus-operator, you need to create a podMonitor to scrape the metrics, However, it needs port field which is the name of the pod port this endpoint refers to. I'm able to get it all working by adding below to the nmi/mic pod spec
`ports:
  - containerPort: 8888/9090
    name: metrics
    protocol: TCP
`
without above, promethus-operator will not able to scrape the metrics from aad-pod-identity.

My podMonitor.yaml is below:
`apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: aadpodmonitor
  namespace: default
  labels:
    release: prometheus-operator
spec:
  podMetricsEndpoints:
    - honorLabels: true
      interval: 10s
      path: /metrics
      port: metrics
  selector:
    matchLabels:
     app.kubernetes.io/name: aad-pod-identity
  namespaceSelector:
    matchNames:
    - aadpodidentity`

**Comment by aramase** [comment]
@dawn-chu We already have the port in the helm charts:

https://github.com/Azure/aad-pod-identity/blob/ee1786f39d1e5fc012a5a6b1f2e8695c7b1edaf6/charts/aad-pod-identity/templates/mic-deployment.yaml#L156-L159

Are you using the deployment yamls? We should add this to the yamls as well. Would you be interested in opening a PR to add it to the manifests in [here](https://github.com/Azure/aad-pod-identity/tree/master/manifest_staging/deploy)?

**Comment by dawn-chu** [comment]
@aramase  I'm using the deployment yamls, I can repro with `helm template aad-pod-identity aad-pod-identity/aad-pod-identity`

below is the output mic yaml, which doesn't have the container port:

# Source: aad-pod-identity/templates/mic-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aad-pod-identity-mic
  namespace: default
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad-pod-identity
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity-3.0.3
    app.kubernetes.io/component: mic
  annotations:
    description: Deploy components for aad-pod-identity
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: aad-pod-identity
      app.kubernetes.io/instance: aad-pod-identity
      app.kubernetes.io/component: mic
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aad-pod-identity
        app.kubernetes.io/instance: aad-pod-identity
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: aad-pod-identity-3.0.3
        app.kubernetes.io/component: mic
    spec:
      serviceAccountName: aad-pod-identity-mic
      containers:
      - name: mic
        image: "mcr.microsoft.com/oss/azure/aad-pod-identity/mic:v1.7.4"
        imagePullPolicy: Always
        args:
          - "--cloudconfig=/etc/kubernetes/azure.json"
          - "--logtostderr"
        securityContext:
          runAsUser: 0
        env:
          - name: MIC_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: FORCENAMESPACED
            value: "false"
        volumeMounts:
          - name: k8s-azure-file
            mountPath: /etc/kubernetes/azure.json
            readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
            limits:
              cpu: 200m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
      - name: k8s-azure-file
        hostPath:
          path: /etc/kubernetes/azure.json
      nodeSelector:
        kubernetes.io/os: linux

**Comment by dawn-chu** [comment]
It is weird that port is in the mic-deployment.yaml but not in the actual deployment
 ports: 
   - containerPort: {{ .Values.mic.prometheusPort }} 
     name: metrics 
     protocol: TCP

**Comment by aramase** [comment]
@dawn-chu The port is only set when `{{- if .Values.mic.prometheusPort }}` prometheusPort is defined in the values file. By default we don't set it.

**Comment by dawn-chu** [comment]
Thanks, I saw that, I'll give a try. I think it would be better to have this in [configuration](https://github.com/Azure/aad-pod-identity/tree/master/charts/aad-pod-identity#configuration) and [doc](https://azure.github.io/aad-pod-identity/docs/configure/prometheus_monitoring/), which would be more clear.
