### ISSUE TITLE
Details regarding forcing namespace matching are not available?

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/aad-pod-identity#1004]
Team,

I've single team AKS environment  in which I'm already using AAD pod identities. But, now I'm migrating it to shared AKS environment so that other teams can also work on this. 

To safeguard ourselves from malicious pod I need to check this [feature: forced namespace matching](https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.namespaced.md). But, the readme is not available in the repository.

Could anyone please share the documents because currently, I don't know how to secure the shared environment of AKS if AAD pod identity is hosted at cluster level.

**Comment by aramase** [comment]
Please refer to https://azure.github.io/aad-pod-identity/docs/configure/match_pods_in_namespace/ for more details. All the markdown files have been moved to the docs site at https://azure.github.io/aad-pod-identity/docs

**Comment by smartaquarius10** [comment]
@aramase Thank you for sharing the details. Have a nice day. Take care.

**Comment by aramase** [comment]
Closing this issue with the docs url. Please feel free to open a new issue if you have any questions.
