### ISSUE TITLE
monitoring metrics for MIC's failed attempt to attach MSI to VM/VMSS

### ISSUE THREAD

**Issue by vickeyrihal1** [Azure/aad-pod-identity#1005]
Following the AAD outage that happened yesterday, MIC was unable to attach MSIs to few VMSS/VM. As a result, the newly scheduled pods were impacted.

Could you help us with setting up monitoring metrics and help logging for such failed MSI attempts? We couldn't find any related error logs in aad-pod-identity logs. Any help on sharing the related metrics should help:

- Log filters
- Monitoring metrics (prometheus)

Following metrics should help:
- Number of failed and non-existing identities
- The latency of Identity Assignment / Binding
- Overall token request
- successful/failed requests
- Mapping data, like "# of Pods per identity"...

**Have you**

- [x] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [x] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [x] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
There were no related logs/metrics at the time of failed msi attachment attempt to vmss.

**Steps To Reproduce**
make the msi attachment fail

**Expected behavior**
some sort of error codes or exceptions when MIC is unable to attach MSI to vm/vmss.

**AAD Pod Identity version**
1.6.1

**Kubernetes version**
1.8

**Additional context**

**Comment by aramase** [comment]
@vickeyrihal1 PTAL at https://azure.github.io/aad-pod-identity/docs/configure/prometheus_monitoring/ for metrics. We have error logs for failure to assign the identities. PTAL at https://azure.github.io/aad-pod-identity/docs/troubleshooting/ for more information.

**Comment by vickeyrihal1** [comment]
@aramase - Thanks for the clue. I tried implementing this monitoring, but somehow not getting relevant metrics. The one the endpoint is scrapping is following:

**MIC:**
- aadpodidentity_mic_new_leader_election_count
- aadpodidentity_mic_cycle_*

**NMI**
- cilium*

We are currently on version **1.6.1**

Btw, which metric will help identifying such failures?

 > We have error logs for failure to assign the identities
Incidentally, we didn't able to find the error logs for failed identity attachments.

**Comment by vickeyrihal1** [comment]
@aramase - could you take a look at last comment?

**Comment by aramase** [comment]
@vickeyrihal1 For NMI the default metrics port is 9090 and NMI runs on host network. So could you check if you're scraping the correct endpoint?

`aadpodidentity_cloud_provider_operations_errors_count` will be incremented for errors while getting vmss, assigning/un-assigning identities.

**Comment by vickeyrihal1** [comment]
Thanks @aramase . Incidentally there was some other service with conflicting prometheus port. Things worked for nmi with a different prometheus port.
