### ISSUE TITLE
Error while installing the latest version of AAD Pod Identity. Error: Internal error occurred: failed calling webhook "example.terraform.io": Post "https://example-service.default.svc:443/?timeout=10s": service "example-service" not found 

### ISSUE THREAD

**Issue by madhurichilaka** [Azure/aad-pod-identity#1006]
**Have you**

- [x] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [x] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [x] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
'Error: Internal error occurred: failed calling webhook "example.terraform.io": Post "https://example-service.default.svc:443/?timeout=10s": service "example-service" not found' is thrown when we tried to upgrade the AAD Pod Identity version by uninstalling the old version (1.7.1) and installing the new version (1.7.4)

**Steps To Reproduce**
We have used the below scripts for installing the AAD Pod identity. Since there is no upgrade command available, we are uninstalling and installing the AAD Pod Identity.

Helm Repo:
helm repo add aad-pod-identity https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts

Uninstall command:
Helm uninstall pod-identity

Install Command:
helm install pod-identity aad-pod-identity/aad-pod-identity --set mic.immutableUserMSIs=$ClientIDs

![image](https://user-images.githubusercontent.com/42635327/111469974-54362c00-874d-11eb-9856-7be271577f97.png)

**Expected behavior**
AAD Pod Identity installation should be successful

**AAD Pod Identity version**
1.7.4

**Kubernetes version**
1.19.7

**Additional context**

**Comment by aramase** [comment]
> 'Error: Internal error occurred: failed calling webhook "example.terraform.io": Post "https://example-service.default.svc:443/?timeout=10s": service "example-service" not found' is thrown when we tried to upgrade the AAD Pod Identity version by uninstalling the old version (1.7.1) and installing the new version (1.7.4)

@madhurichilaka That's not a pod identity error. You have a webhook deployed in the cluster which isn't responding. So any new pod creation will fail. I would recommend fixing the webhook and then retrying.

**Comment by madhurichilaka** [comment]
@aramase Thanks a lot for the prompt response! Actually the issue is raised only while installing the mic pods. nmi pod creation was successful. That's the reason I was suspecting some issue with AAD Pod Identity installation.

The issue is fixed now. We have removed the unwanted webhooks which was causing this issue from the cluster. Thanks again for the support!
