### ISSUE TITLE
Is Azure Active Directory Pod Identities decommissioning?

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/aad-pod-identity#1008]
Team,

I've seen on this [link ](https://docs.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity)that AAD pod identities is in preview mode now. Does that mean Microsoft is closing the support or totally decommissioning the feature.

In the latter case, do we have any other approach available through which pod can interact with the Azure resources in a secure way.

Sorry if my understanding is wrong here.

Thank you

**Comment by chewong** [comment]
Going forward, we will be maintaining both the open-source version and the managed version of aad-pod-identity.

**Comment by smartaquarius10** [comment]
@chewong , Ok. So basically Microsoft will not support aad in the near future due to which they have put it on preview mode. 

But, what is the managed version. Is it covering services like paid support or incident tickets etc. Do we have any documentation or details related to this version.

**Comment by chewong** [comment]
> Ok. So basically Microsoft will not support aad in the near future due to which they have put it on preview mode.

I don't think that is true.

Open-source version (this repo): have both standard and [managed mode](https://azure.github.io/aad-pod-identity/docs/configure/pod_identity_in_managed_mode/) and you can install it through Helm chart.

https://docs.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity: install and interact with aad-pod-identity via azure-cli. Regarding the support policy, based on the website above:

> they're excluded from the service-level agreements and limited warranty.

**Comment by smartaquarius10** [comment]
@chewong , Thank you for the details. But as far as I know microsoft puts anything in preview mode when they usually plans to decommission it. 

Other than that, could you please suggest me one thing. Is it correct to quote that manage mode can add one extra level of security especially in the case of shared instance. 

I haven’t read about forced name matching rules till now but I’m migrating my AKS instance to a shared resource. If I apply that rule and use manage mode then being an admin until I do not enable the roles and identities on all the worker nodes other users wont be able to access any new resource(whose identity is not added yet in all the node).

Is my understanding correct here?

**Comment by chewong** [comment]
> as far as I know microsoft puts anything in preview mode when they usually plans to decommission it.

As far as I know, that's not always the case. If something is in preview mode, we will either make it generally available to the public after a period of time OR decommission it.

> I haven’t read about forced name matching rules till now but I’m migrating my AKS instance to a shared resource. If I apply that rule and use manage mode then being an admin until I do not enable the roles and identities on all the worker nodes other users wont be able to access any new resource(whose identity is not added yet in all the node).

That's right, only pods within a namespace can access identities defined for the namespace.

**Comment by smartaquarius10** [comment]
@chewong , Great . Thanks a lot for helping. Closing the issue. Take care.. Have a nice day.
