### ISSUE TITLE
AAD Pod Identity takes a very long time ( tens of minutes to an hour) to bind a pod to the identity AzureAssignedIdentity. Azure Commercial

### ISSUE THREAD

**Issue by vsabella** [Azure/aad-pod-identity#1009]
- [ X ] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [ X ] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [ X ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

Currently on AAD Pod Identity, when deploying a pod with a bound identity, it takes a long time for that pod to have an entry created in AzureAssignedIdentities.

There is very little information in the MIC log. (running at --v=6) No errors, its as if it is completely missing the pod creation event until the next force resync time. This happens 100% of the time without fail.

Right after the force resync line, Binding shows up, but this can take up to 15-60 minutes at times.
```
I0318 01:29:40.208739 1 reflector.go:369] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: forcing resync
```

However if I force-restart the MIC deployment (both pods), it immediately picks up the change.

```
I0318 01:41:46.964284 1 crd.go:712] appending exception: kube-system/mic to list.
I0318 01:41:46.964291 1 crd.go:712] appending exception: kube-system/akv2k8s-mic-exception to list.
I0318 01:41:46.964297 1 crd.go:712] appending exception: kube-system/azureidentity-mic-exception to list.
I0318 01:41:46.964306 1 server.go:358] exception pod kube-system/aad-pod-identity-mic-65b49b4b8c-jvbdc token handling
I0318 01:41:46.964312 1 server.go:301] fetching token for user assigned MSI for resource: https://management.azure.com/
I0318 01:41:47.116248 1 server.go:192] status (200) took 152016703 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.53.4.199
```

What makes this strange is this only occurs on our Azure Commercial Instance, US West region. (Haven't tested other regions).
In our Azure Government region (usgovvirginia) it works correctly with little delay (~15-20 seconds to a minute).

Once that AzureIdentityAssignment completes, az login -i works. Until then it blocks on the metadata api call.

** Steps to Reproduce **
Reproduces 100% of the time.

```bash
kubectl run azure-cli -it --image=mcr.microsoft.com/azure-cli --labels=aadpodidbinding=<my-selector-here> /bin/bash
sleep 90s
# fails
az login -i --debug
kubectl get AzureAssignedIdentity -A -w

# Wait 5 minutes, 30 minutes, nothing
kubectl rollout restart deployment aad-pod-identity-mic -n kube-system
# Wait 15 seconds or so
## Success!
az login -i --debug
```

**Expected behavior**
The binding happens quickly, before the forced resync timeout occurs and without having to restart the MIC pod.

**Versions**
AKS 1.19.7 with AAD-RBAC enabled. Reproduces without RBAC enabled. Reproduces with 1.19.6
AAD Pod Identity 1.7.4
Chart 3.0.3
Region: Azure Commercial US West (US West, not US West 2)
Clean cluster, built from scratch with these versions and running only the stock AKS + cert-manager.

**Next Steps**
I just wanted to get this filed in case anyone else is seeing this, next I will check:

* Are there any API throttles in our subscription (if there are, AAD Pod Identity is not printing any logs or failed API calls)
* Is this a regional AKS issue with events? Will try a different region in our subscription.
* Try 1.20

Any thoughts?

Thanks so much! Everything was working great up until one or two weeks ago but exact failure timeline is unknown as we weren't monitoring this pre-release environment as regularly.

**Comment by vsabella** [comment]
Note: I've been able to verify that this problem does not reproduce in East US 2 - Opening an Azure Support Ticket.

Also we'll look into making a PR to add additional logging to aad-pod-identity :)

**Comment by aramase** [comment]
> There is very little information in the MIC log. (running at --v=6) No errors, its as if it is completely missing the pod creation event until the next force resync time. This happens 100% of the time without fail.

The force resync is done by the reflector in client-go library that we use. MIC and NMI establishes a watch connection with the API server to get pod create/update/delete events. If there are delays here then I assume the connection timed out but wasn't terminated. Do you see anything interesting in the API server logs around that time frame? 

> Right after the force resync line, Binding shows up, but this can take up to 15-60 minutes at times.

This establishes a new tcp connection so it'll get all the events. 

> Clean cluster, built from scratch with these versions and running only the stock AKS + cert-manager.

How long after the pods are deployed are you able to repro this?

> Note: I've been able to verify that this problem does not reproduce in East US 2 - Opening an Azure Support Ticket. Also now we understand how the flow process looks in the code will debug to see why its stuck.

Thanks for getting into it to debug.

**Comment by aramase** [comment]
I've also opened a PR to update the client-go library versions https://github.com/Azure/aad-pod-identity/pull/1010 to include  fixes for broken connections from client-go clients.

**Comment by aramase** [comment]
Could you also share the support ticket number?

**Comment by sunkararp** [comment]
This is happening in our AKS cluster. We are trying to pod-identity to a new kubernetes namespace that got added to our ASK cluster.

Any help is really appreciated.

Below is the command we execute.
```
az aks pod-identity add --resource-group $ResourceGroupName --cluster-name $ClusterName --namespace $sparkNamespace --name $PodIdentityName --identity-resource-id $IdentityResouceId
```
