### ISSUE TITLE
MIC Cloud Provider patch takes a long time around 16mins

### ISSUE THREAD

**Issue by dhilipkumars** [Azure/aad-pod-identity#1012]
**Have you**

- [ ] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [ ] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [ ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
Every now and then we see the below status in MIC logs
```
I0322 15:11:52.624455       1 stats.go:183] * stats collected *
 I0322 15:11:52.624467       1 stats.go:162] Pod listing: 98.902µs
 I0322 15:11:52.625200       1 stats.go:162] AzureIdentity listing: 415.807µs
 I0322 15:11:52.625236       1 stats.go:162] AzureIdentityBinding listing: 394.307µs
 I0322 15:11:52.625284       1 stats.go:162] AzureAssignedIdentity listing: 27.269375ms
 I0322 15:11:52.627825       1 stats.go:162] System: 38.375669ms
 I0322 15:11:52.627838       1 stats.go:162] CacheSync: 4.7µs
 I0322 15:11:52.627852       1 stats.go:162] Cloud provider GET: 60.136748ms
 I0322 15:11:52.627856       1 stats.go:162] Cloud provider PATCH: 16m30.551293183s
 I0322 15:11:52.627861       1 stats.go:162] AzureAssignedIdentity creation: 96.712987ms
 I0322 15:11:52.627865       1 stats.go:162] AzureAssignedIdentity update: 0s
 I0322 15:11:52.627869       1 stats.go:162] AzureAssignedIdentity deletion: 1.563855018s
 I0322 15:11:52.627876       1 stats.go:170] Number of cloud provider PATCH: 1
 I0322 15:11:52.627882       1 stats.go:170] Number of cloud provider GET: 1
 I0322 15:11:52.627886       1 stats.go:170] Number of AzureAssignedIdentities created in this sync cycle: 4
 I0322 15:11:52.627890       1 stats.go:170] Number of AzureAssignedIdentities updated in this sync cycle: 0
 I0322 15:11:52.627894       1 stats.go:170] Number of AzureAssignedIdentities deleted in this sync cycle: 3
 I0322 15:11:52.627898       1 stats.go:162] Find AzureAssignedIdentities to create: 71.301µs
 I0322 15:11:52.627902       1 stats.go:162] Find AzureAssignedIdentities to delete: 33.301µs
 I0322 15:11:52.627906       1 stats.go:162] Total time to assign or update AzureAssignedIdentities: 16m32.477918133s
 I0322 15:11:52.627911       1 stats.go:162] Total: 16m32.520356672s
 I0322 15:11:52.627916       1 stats.go:212] *******
```
it takes around 16mins only when Number of Cloud provider Patch is > 0? when it takes so much time does it block the entier MIC? what does it mean by Cloud provider patch? we see this happening only recently and when MIC is blocked in this state no logs are printed from MIC POD and we think this related to token generation from our pods failing too.
**Steps To Reproduce**
Intermittent 
**Expected behavior**

**AAD Pod Identity version** v1.6.3

**Kubernetes version** 1.18.4

**Additional context**
Aad is a very important component in our cluster.  We would like to know what is RCA for recent delays and timeouts generating token. 

cc: @aramase

**Comment by chewong** [comment]
Could you confirm that you are also seeing NMI errors similar to https://github.com/Azure/aad-pod-identity/issues/1011?

**Comment by dhilipkumars** [comment]
we do not see that error in the NMIs (i will double check on our other clusters as well) but MIC goes to blocked state as soon as we see below log entry from `cloudprovider.go`  as you can see from the below logs.  does `cloudprovider.go:210` performs an azure call? 

```
I0322 16:39:16.305200       1 cloudprovider.go:210] updating user-assigned identities on aks-agentpool-40830945-vmss, assign [2], unassign [1]

 

 

I0322 16:55:47.104928       1 mic.go:522] work done: true. Found 22 pods, 171 ids, 171 bindings
I0322 16:55:47.105011       1 mic.go:523] total work cycles: 7659, out of which work was done in: 113
I0322 16:55:47.105056       1 stats.go:183] ** stats collected **
I0322 16:55:47.105072       1 stats.go:162] Pod listing: 148.303µs
I0322 16:55:47.105100       1 stats.go:162] AzureIdentity listing: 395.007µs
I0322 16:55:47.105559       1 stats.go:162] AzureIdentityBinding listing: 421.807µs
I0322 16:55:47.105577       1 stats.go:162] AzureAssignedIdentity listing: 88.202µs
I0322 16:55:47.105581       1 stats.go:162] System: 5.269791ms
I0322 16:55:47.105585       1 stats.go:162] CacheSync: 4.4µs
I0322 16:55:47.105589       1 stats.go:162] Cloud provider GET: 205.99343ms
I0322 16:55:47.105593       1 stats.go:162] Cloud provider PATCH: 16m30.764552582s
I0322 16:55:47.105597       1 stats.go:162] AzureAssignedIdentity creation: 83.374228ms
I0322 16:55:47.105601       1 stats.go:162] AzureAssignedIdentity update: 0s
I0322 16:55:47.105605       1 stats.go:162] AzureAssignedIdentity deletion: 13.989798057s
I0322 16:55:47.105609       1 stats.go:170] Number of cloud provider PATCH: 2
I0322 16:55:47.105613       1 stats.go:170] Number of cloud provider GET: 2
I0322 16:55:47.105618       1 stats.go:170] Number of AzureAssignedIdentities created in this sync cycle: 4
I0322 16:55:47.105622       1 stats.go:170] Number of AzureAssignedIdentities updated in this sync cycle: 0
I0322 16:55:47.105625       1 stats.go:170] Number of AzureAssignedIdentities deleted in this sync cycle: 6
I0322 16:55:47.105628       1 stats.go:162] Find AzureAssignedIdentities to create: 52.701µs
I0322 16:55:47.105632       1 stats.go:162] Find AzureAssignedIdentities to delete: 29.8µs
I0322 16:55:47.105635       1 stats.go:162] Total time to assign or update AzureAssignedIdentities: 16m31.00577563s
I0322 16:55:47.105639       1 stats.go:162] Total: 16m31.014028772s
I0322 16:55:47.105643       1 stats.go:212] *********************
```

**Comment by dhilipkumars** [comment]
when the `Number of cloud provider PATCH: 0`   then `Total:` is always in sub-secs

**Comment by chewong** [comment]
> does cloudprovider.go:210 performs an azure call?

It does. PATCH call in this context means that MIC is trying to assign/unassign the user-assigned identity to the underlying VMSS instance via azure-sdk-for-go.

16 minutes is unusual because it usually takes at most 60 seconds to assign/unassign identities. I am suspecting that the MIC client is getting throttled and the error was not showing up correctly in the log because of a bug we recently discovered. We fixed the bug in the latest release. If possible, could you try upgrading to v1.7.4 (note that there are some breaking changes when upgrading to v1.7.4. See https://azure.github.io/aad-pod-identity/docs/#v17x-breaking-change)?

**Comment by dhilipkumars** [comment]
Thanks for the response @chewong , could you tell us what is the exact Azure API the patch uses, we will follow-up with Microsoft support team to to  confirm if we are being throttled?

In the meantime we will also look at upgrading to 1.7.4.

**Comment by chewong** [comment]
We use https://github.com/Azure/azure-sdk-for-go/blob/v40.4.0/services/compute/mgmt/2019-12-01/compute/virtualmachinescalesets.go#L1726-L1755 to assign/unassign identities from VMSS.

**Comment by dhilipkumars** [comment]
Closing the issue. Thanks
