### ISSUE TITLE
OpenAPI definitions for Custom Resource Definitions

### ISSUE THREAD

**Issue by tareks** [Azure/aad-pod-identity#1014]
**Describe the request**
It appears that the current CRDs do not define an OpenAPI spec such as openAPIV3Schema and uses OPA rego to enforce formatting. 

Sample: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/

**Explain why AAD Pod Identity needs it**
Would streamline the use of the current aad-pod-identity CRDs with tools such as the upcoming terraform kubernetes provider, specifically the `kubernetes_manifest` resource (currently still in alpha provider). This may also make it easier for operators.

The alpha provider currently fails with the following:
```
Error: No valid OpenAPI definition

  on kubernetes.tf line 237, in resource "kubernetes_manifest" "pod_azure_identity":
 237: resource "kubernetes_manifest" "pod_azure_identity" {

Resource AzureIdentity.v1.aadpodidentity.k8s.io does not have a valid OpenAPI
definition in this cluster.

Usually this is caused by a CustomResource without a schema.
```

**Describe the solution you'd like**
Extend the current CustomResoureDefinitions packaged with the Helm chart so that they include OpenAPI definitions (`openAPIV3Schema`)

**Describe alternatives you've considered**
Alternative is to apply manifests directly using kubectl or otherwise.

**Additional context**

**Comment by chewong** [comment]
Part of https://github.com/Azure/aad-pod-identity/issues/661.
