### ISSUE TITLE
Pod Identity In managed Mode Docs *typo*

### ISSUE THREAD

**Issue by tshaiman** [Azure/aad-pod-identity#1015]
looking at the docs here :
https://azure.github.io/aad-pod-identity/docs/configure/pod_identity_in_managed_mode/#managed-mode

the sample for assigning roles to VMSS is  : 
az vmss identity assign -g <VM resource group name> -n <**VM name**> --identities <resource ID of managed identity>
should be  :
az vmss identity assign -g <VM resource group name> -n <**Scale Set Name**> --identities <resource ID of managed identity>

**Comment by aramase** [comment]
@tshaiman Would you be interested in opening a PR to fix the typo in [here](https://github.com/Azure/aad-pod-identity/blob/master/website/content/en/docs/Configure/pod_identity_in_managed_mode.md)?

**Comment by tshaiman** [comment]
sure :
vmss typo by tshaiman · Pull Request #1016 · Azure/aad-pod-identity
(github.com) <https://github.com/Azure/aad-pod-identity/pull/1016>


also I accidentally Forked into Microsoft instead to my Account.
