### ISSUE TITLE
Removal Of MIC Controllers 

### ISSUE THREAD

**Issue by alexl2012** [Azure/aad-pod-identity#1017]
Hi , i have noticed that MIC controllers have been removed as Pod Identity has been added to AKS as an Addon.

Please please reconsider this design changes, it comes with some serious limitations which make it a lot less clear and a lot less workable to use. 

For example before we had a chart file that lives in the repo and was part of the service that it belonged to, this was created as part of a deployment and we could also be sure of what it was and if any changes were made they were also part of the repo. Now we have a disjointed implementation where by a pipeline task has to assign managed identities to the cluster and then a separate deployment of helm charts applys the binding and other associated files, this is a much less integrated solution and feels regressive from the current model.

Another issue with the new implementation method is that if the cluster is having any other updates or changes we cannot change identities, which means our pipelines will be failing much more frequently as they will add an identity each time and any other changes being made to the cluster or other apps concurrently trying to add identities will have issues and likely fail.

This seems like an extreamly regressive solution and has many drawbacks that didnt previously exist. Please can this decision be reverted and MIC pods reintroduced. 

Alternatively please implement this in a way that other cluster updates arent going to prevent changes to the identities being made.

Also i havent tried it yet but id imagine as we continuously deploy our arm templates for AKS this may remove any dynamically added identities causing yet another issue that we will then have to reassign them.

Please reconsider this frankly poor design change.

**Comment by davidwinchurch** [comment]
This change from a tested and working config as code solution to a pipeline task caused me to lose a day to deployment issues. It's hard to see what advantages this new approach provides to justify this disruption.

**Comment by chewong** [comment]
I can't comment on the AKS design choice, however, we will continue maintaining the open-source version of aad-pod-identity (this repo) so you are more than welcome to continue using it over the AKS add-on.

**Comment by alexl2012** [comment]
@chewong the reason i have added the comments here is because Microsoft support said this was the best place to give this kind of feedback, how would you suggest we best ensure it reaches the relevant team?

**Comment by chewong** [comment]
https://github.com/Azure/AKS/issues is a great place to reach out to the AKS team.
