### ISSUE TITLE
Helm chart: Provide user facing cluster roles

### ISSUE THREAD

**Issue by adhodgson1** [Azure/aad-pod-identity#1018]
I have seen some Helm charts for popular applications provide user facing cluster roles which allow various operations on the custom CRD resources which usually aggregate into the built-in Kubernetes admin, edit and view roles.

This would help in situations where you have service accounts for deployments and you want to either bind specific cluster roles or use the built-in Kubernetes namespace admin/edit roles to help secure the deployment accounts. 

Right now we solve this on our clusters by creating a custom role with access to the relevant CRDs for AAD Pod Identity as well as some other apps which don't provide user facing roles and bind them to the service accounts we create.

I think we would just need 2 roles, one which would aggregate to the admin and edit roles and allows full access to the CRDs, and a view role which aggregates to the view role. Currently our custom role allows access to the following resources:

- AzureIdentity
- AzureIdentityBinding

**Comment by aramase** [comment]
> I have seen some Helm charts for popular applications provide user facing cluster roles which allow various operations on the custom CRD resources which usually aggregate into the built-in Kubernetes admin, edit and view roles.

@adhodgson1 Could you provide a reference to any of the helm charts that package these user facing cluster roles?

The helm charts typically package all the applications manifests required to get the components up and running. I think defining the custom roles should be done separately outside of the application helm charts. But I'm open to being convinced 😄

**Comment by adhodgson1** [comment]
Here is one example:
https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/templates/rbac.yaml#L411

I made this request for another chart with custom CRDs and got a similar response so not sure what the best viewpoint is on this one going forward.

**Comment by adhodgson1** [comment]
I am happy to do a PR for this if required as I have got the code for my custom Helm chart.

**Comment by aramase** [comment]
Thanks for sharing the example. I think we can add it to our helm charts within a conditional. Please feel free to open a PR.
