### ISSUE TITLE
Refresh request failed. Status Code = '404'. Response body: getting assigned identities for pod kube-system/ingress-appgw-deployment

### ISSUE THREAD

**Issue by msmithrubbl** [Azure/aad-pod-identity#1030]
**Have you**

- [x ] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [x] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [x ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
Error: adal: Refresh request failed. Status Code = '404'. Response body: getting assigned identities for pod kube-system/ingress-appgw-deployment-5d4c77584c-mr5d9 in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors

**Steps To Reproduce**
Enable azure ingress on cluster. Kubectl the logs for the container.
az aks enable-addons -n glock-westus-rubbl-aks -g glock-app-westus -a ingress-appgw --appgw-id /subscriptions/xxxx

**Expected behavior**
Container should be able to authenticate and create the backendpools on the specificied application gaetway

**AAD Pod Identity version**
? Where do I find this?

**Kubernetes version**
1.18.14

**Additional context**

**Comment by aramase** [comment]
@msmithrubbl If you install aad-pod-identity from the repo here, you can check the version from the yaml you used for deploying. If deployed with helm, then please check `helm ls` in the namespace to get the chart version and app version.

Please check the MIC pod logs for the error. Here is our troubleshooting guide on how to get the logs: https://azure.github.io/aad-pod-identity/docs/troubleshooting/

**Comment by msmithrubbl** [comment]
Thanks aramase. This is what I used to get the aad-pod-identity installed.

kubectl create -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml

Here are the logs from the MIC pods:
C:\src\rubbl\shared\common> kubectl logs -l app=mic -f -n default
I0401 07:11:33.091134       1 stats.go:170] Number of cloud provider PATCH: 1
I0401 07:11:33.091141       1 stats.go:170] Number of cloud provider GET: 1
I0401 07:11:33.091147       1 stats.go:170] Number of AzureAssignedIdentities created in this sync cycle: 0
I0401 07:11:33.091152       1 stats.go:170] Number of AzureAssignedIdentities updated in this sync cycle: 0
I0331 19:35:16.076626       1 main.go:148] client QPS set to: 5. Burst to: 5
I0331 19:35:16.076655       1 mic.go:139] starting to create the pod identity client. Version: v1.7.4. Build date: 2021-02-12-01:42
I0401 07:11:33.091157       1 stats.go:170] Number of AzureAssignedIdentities deleted in this sync cycle: 1
I0401 07:11:33.091163       1 stats.go:162] Find AzureAssignedIdentities to create: 200ns
I0331 19:35:16.172899       1 mic.go:145] Kubernetes server version: v1.18.14
I0331 19:35:16.176166       1 probes.go:41] initialized health probe on port 8080
I0401 07:11:33.091169       1 stats.go:162] Find AzureAssignedIdentities to delete: 0s
I0401 07:11:33.091174       1 stats.go:162] Total time to assign or update AzureAssignedIdentities: 37.95605283s
I0331 19:35:16.176188       1 probes.go:44] started health probe
I0331 19:35:16.177415       1 metrics.go:341] registered views for metric
I0331 19:35:16.177866       1 prometheus_exporter.go:21] starting Prometheus exporter
I0401 07:11:33.091179       1 stats.go:162] Total: 37.95635403s
I0401 07:11:33.091185       1 stats.go:212] *********************
I0331 19:35:16.177890       1 metrics.go:347] registered and exported metrics on port 8888
I0331 19:35:16.177908       1 mic.go:240] initiating MIC Leader election
I0331 19:35:16.177931       1 leaderelection.go:243] attempting to acquire leader lease  default/aad-pod-identity-mic...

**Comment by msmithrubbl** [comment]
Sorry if I' not giving all the info here. Trying to learn. I will say I only tried to use helm to get my ingress controller going with a shared appgateway. I needed to create prohibit rules so the controller does not wipe out some of my custom redirects to other sites. I have since switched back to the azure enable-add-on like this:
az aks enable-addons -n henry-southcentralus-rubbl-aks -g henry-southcentralus -a ingress-appgw --appgw-id $appgwId/subscriptions/22dfe4c0-28a6-4742-af5a-951901cc62ca/resourceGroups/henry-app-southcentralus/providers/Microsoft.Network/applicationGateways/henry-southcentralus-rubbl-app-gateway

**Comment by aramase** [comment]
@msmithrubbl There are no error in the logs you shared. This might be a misconfiguration.

Could you post the following yamls with any sensitive information redacted?
1. `AzureIdentity` yaml used for app gateway pod
2. `AzureIdentityBinding` yaml used for app gateway pod
3. app gateway pod yaml

**Comment by aramase** [comment]
@msmithrubbl Any updates on this?
