### ISSUE TITLE
AKS clusters using system-assigned identity aren't supported?

### ISSUE THREAD

**Issue by irons** [Azure/aad-pod-identity#1033]
Since seeing #973 mentioned in the 1.7.5 release notes, I've been trying to find some insight into why these AKS clusters aren't supported anymore, and what the change means. We currently use AKS clusters in this configuration, which as recently as last September @chewong [described as OK](https://github.com/Azure/aad-pod-identity/issues/804#issuecomment-697859092). 

We've been struggling with some pod-identity failures that seem consistent, but aren't reproducible by other pods in the same namespace assuming the same identity. It now sounds like we need to blow away our clusters and reproduce the problem before trying to pursue a resolution. That's going to take a while, so I'd love to know if our issues are plausibly related to 1.7.5's withdrawal of support.

The [role assignment documentation](https://azure.github.io/aad-pod-identity/docs/getting-started/role-assignment/) still describes system-assigned identity as a supported configuration, and the current version of the [hack/role-assignment.sh](https://github.com/Azure/aad-pod-identity/blob/28777f591c1be86006e8f2ef60fa73a53e0d1884/hack/role-assignment.sh) script doesn't raise an objection.

Thanks for your time.

**Comment by aramase** [comment]
@irons v1.7.5 isn't withdrawing any support. That doc update was to say system-assigned managed identity is not supported for applications. We always supported user-assigned managed identity or service principal with applications (defined in `AzureIdentity`). 

This doesn't alter the credentials used by AAD pod identity to perform cloud operations. The role assignments are for cluster identity and that still works with user-assigned/system-assigned/service principal.

**Comment by irons** [comment]
Thanks. To restate, the intended message is just that one can't create an `AzureIdentity`/`AzureIdentityBinding` pair to grant the cluster identity its own access to arbitrary RBAC role assignments? 

I don't think anyone reading #973's change is going to arrive at that conclusion, coming as a footnote to the first sentence of the first page of documentation. It reads as a warning.
