### ISSUE TITLE
Identity Not Found

### ISSUE THREAD

**Issue by Eneuman** [Azure/aad-pod-identity#1040]
**Have you**

- [x] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [x] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [x] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
I have been trying to get this working for 2 days straight and I have dbl checked everything over and over.

I have a resource group containing a identity I want to use when calling Azure Blob Storage. The RG is in west europe but the identity in it is in north europe. My AzureIdentity.yaml holds the clientID and ResourceID of this Identity.

I create a AKS cluster with --managed-identity. 

NMI gives me this error:
```
I0411 21:22:07.559137       1 server.go:196] status (200) took 10258030 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.0.12
I0411 21:22:45.488377       1 server.go:362] exception pod dev/testapplication-8984c84b4-vxs2x token handling
I0411 21:22:45.488401       1 server.go:302] fetching token for system assigned MSI
E0411 21:22:45.556099       1 server.go:365] failed to get service principal token for pod:dev/testapplication-8984c84b4-vxs2x with error code 403, error: failed to get service principal token, error: failed to refresh token, error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}
I0411 21:22:45.556150       1 server.go:196] status (403) took 67826835 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.0.12
```

No errors in MIC loggs

- [x] Checked casing of properties in aadpodidentity and aadpodidentitybinding, 
- [x] Checked permissions and roles on resource groups
- [x] Checked that resourceID anc clientID of AzureIdentity is correct

```
az aks show -g <rg> -n <aks> --query "identity"
{
  "principalId": "28f4e944-470b-4ac5-8745-xxxxxxxxxxxxx",
  "tenantId": "f9070006-2d6b-41d1-a9ce-xxxxxxxxxxxxxx",
  "type": "SystemAssigned",
  "userAssignedIdentities": null
}
```

Troubleshooting using azure cli gives me this error:
```
urllib3.connectionpool: http://169.254.169.254:80 "GET /metadata/identity/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01 HTTP/1.1" 403 213
msrestazure.azure_active_directory: MSI: Retrieving a token from http://169.254.169.254/metadata/identity/oauth2/token, with payload {'resource': 'https://management.core.windows.net/', 'api-version': '2018-02-01'}
cli.azure.cli.core.adal_authentication: throw requests.exceptions.HTTPError when doing MSIAuthentication:
```

I have deleted my old AKS kluster en recreated it with the same name, can it be caching issue?
Is there a way to see what Identity it is looking for?
Whats else can I check?

**AAD Pod Identity version**
1.7.5

**Kubernetes version**
1.8.14

**Additional context**

**Comment by chewong** [comment]
Have you checked the log for both MIC pods? There should be two MIC pods running. Have you also followed https://azure.github.io/aad-pod-identity/docs/getting-started/role-assignment/?

**Comment by Eneuman** [comment]
Hi
Yes I have. Both pods running and no errors in any. Role assignment looks good. I have also dbl checked the assigned permissions to the RG and they look good.

**Comment by chewong** [comment]
Could you run `az vmss show -g <NodeResourceGroup> -n <VMSSName> --query 'identity.userAssignedIdentities'` to verify that your identity is assigned to your VMSS instance?

**Comment by Eneuman** [comment]
```
az vmss show -g MC_RG-WE-eClinic-Dev_AKS-WE-eClinic-Dev_westeurope -n aks-nodepool1-10741432-vmss --query 'identity.userAssignedIdentities'
"identity.userAssignedIdentities"
```

Can this be right ?

**Comment by Eneuman** [comment]
My bad, this was the return:
```
 "userAssignedIdentities": {
      "/subscriptions/7bc219a9-4af7-4574-9305-xxxxxxxxxxxxxx/resourceGroups/MC_RG-WE-eClinic-Dev_AKS-WE-eClinic-Dev_westeurope/providers/Microsoft.ManagedIdentity/userAssignedIdentities/AKS-WE-eClinic-Dev-agentpool": {
        "clientId": "2454f65e-04af-49b5-8d27-xxxxxxxxxxxxxx",
        "principalId": "a26574b6-b845-407e-b5d0-xxxxxxxxxxxxxx"
      },
      "/subscriptions/7bc219a9-4af7-4574-9305-xxxxxxxxxxxxxx/resourcegroups/rg-we-eclinic-dev/providers/microsoft.managedidentity/userassignedidentities/eclinicpodidentitydev": {
        "clientId": "52115ba9-ddee-43f5-bf36-xxxxxxxxxxxxxx",
        "principalId": "fe48cfcc-40fc-436d-9cd0-xxxxxxxxxxxxxx"
      }
    }
```

**Comment by chewong** [comment]
How are you requesting the token? Via an SDK? You might want to include the identity Client ID when requesting a token so NMI knows which identity to select.

**Comment by Eneuman** [comment]
Nice!
Using this: `var credentials = new ManagedIdentityCredential("52115ba9-ddee-43f5-bf36-XXXXXXXXXX")` did work and I could get access to AzureBlobStorage using Pod Identity.

I have not needed to add clientId before. Is there a way to make it automaticly select the identity that the resourceID in AzureIdentity is pointing to?

**Comment by aramase** [comment]
```bash
I0411 21:22:45.488377       1 server.go:362] exception pod dev/testapplication-8984c84b4-vxs2x token handling
```

Are you trying to disable the pod from pod identity validation for token request? (Ref: https://azure.github.io/aad-pod-identity/docs/configure/application_exception/). That log indicates that. If the pod is disabled from pod identity validation we just send the request as is to IMDS. 

If there is no `clientID` in the request and there are multiple identities assigned, IMDS will return an error.
```bash
bash-5.0# curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fmanagement.azure.com%2F' -H Metadata:true -s
{"error":"invalid_request","error_description":"Identity not found"}bash-5.0#
```

If your intent is not to disable pod identity validation, then ensure the label isn't exempted in the `AzurePodIdentityException`. Pod Identity will default to the first `clientID` for the pod.

**Comment by Eneuman** [comment]
@aramse I'm using azure devspaces and have added the exceptions for it's infrastructure as described here: https://docs.microsoft.com/en-us/azure/dev-spaces/troubleshooting#error-no-azureassignedidentity-found-for-podazdsazds-webhook-deployment-id-in-assigned-state

But my pod shouldn'nt be disabled from pod validation. So the solution is to remove one of the identities from the vmss so it will only have one?

Did Pod Identity add the XXX-agentpool managed identity (created my AKS create command) to the vmss or is it automaticly added when the cluster is created?

If I remove it, will Pod Identity add it back?

**Comment by aramase** [comment]
> But my pod shouldn'nt be disabled from pod validation. So the solution is to remove one of the identities from the vmss so it will only have one?

Using `AzurePodIdentityException` is the way to tell pod identity to disable all pod identity validation for the pod. So for pods that have labels defined in the exception, NMI will just forward the token request as is. 

> Did Pod Identity add the XXX-agentpool managed identity (created my AKS create command) to the vmss or is it automaticly added when the cluster is created?

The agentpool managed identity is added by AKS. It's created for all clusters created with `--enable-managed-identity`. If you delete that, the cluster will become non-operational as that's the kubelet identity.

Since this pod is excepted using the `AzurePodIdentityException`, the application would need to be responsible for sending the clientID as part of token request. In all other cases pod identity defaults to the clientID defined in the first `AzureIdentity` matched for the pod.

**Comment by Eneuman** [comment]
@aramase I see. The problem is that Azure DevOps injects init containers to my pod (they build the code etc) and thoose init containers needs to be excepted from pod validation, byt my pod should not. Can I somehow disable pod identity validation for just the init containers?

**Comment by aramase** [comment]
@Eneuman Gotcha! Unfortunately, exception for specific containers in a pod isn't possible. NMI finds the sender of the token request based on the source ip (which here is the pod IP). There is no way for NMI to know which container in the pod is making the token request.

**Comment by Eneuman** [comment]
@aramase & @daniv-msft 
I think we have found the root cacuse to the problem with Azure Dev-Spaces and Pod Identity :)

For Dev-Spaces init-containers to work, we need to except thoose from Pod Identity validation. But in doing so, we also except the pod itself, so `var identity = new ManagedIdentity()` will never work, and specifying a ClientId is now mandantory.

I think the problem started in Pod Identity version 1.5 where a PR enabled Init Containers to work with Pod Identity and hence cause Dev-Spaces to stop working. 

The problem with specifying a ClientId is that there is no good place to store it since you cant use ManagedIdentity to retrive it.
Our system has around 43 micro services and we can't hardcode this in the appclication.config.json file for all those, and since DevSpaces does not have a "release pipeline" there is no variable to store it in ither.

Quite a dilemma.

Any Ideas on how to handle this?
Is there a environment variable we can set to choose a "default" identity?

**Comment by daniv-msft** [comment]
Thanks @Eneuman and @aramase. Indeed, that's tricky. Would going back to a version of pod identity before 1.5 be an option?
@aramase Would you know if this would even be possible, or if such versions aren't available anymore?

**Comment by chewong** [comment]
It is possible but there are a ton of improvements we introduced since 1.5 so we wouldn't recommend using that.

**Comment by aramase** [comment]
> For Dev-Spaces init-containers to work, we need to except thoose from Pod Identity validation. But in doing so, we also except the pod itself, so var identity = new ManagedIdentity() will never work, and specifying a ClientId is now mandantory.

For excepted pods, pod identity doesn't mandate the existence of clientID in the token request. We just forward the request to IMDS and that is the IMDS behavior when there are multiple identities on the underlying VM/VMSS.

> I think the problem started in Pod Identity version 1.5 where a PR enabled Init Containers to work with Pod Identity and hence cause Dev-Spaces to stop working.

What exactly is the problem here with allowing init containers in pod identity? Could you elaborate more? `1.5` release was in 2019 AFAICT.

> The problem with specifying a ClientId is that there is no good place to store it since you cant use ManagedIdentity to retrive it.

If there are multiple identities, IMDS expects the clientID in token request. AAD Pod Identity provides an additional value here by setting the clientID on behalf of the user as part of the validation. However for excepted pods, we don't have authority to modify the request so we send the request to IMDS as send by the client. 

> Is there a environment variable we can set to choose a "default" identity?

I don't believe that's supported by IMDS.

**Comment by Eneuman** [comment]
@aramase The problem for me is that Dev-Spaces injects init containers to the pods. To make Dev-Spaces work you got to exclude Dev-Spaces infrastructur (se my post above) from Pod identity, doing this also excepts my pod (by design).
Since my pod is now excepted, validation does not run and I need to explicit say what ClientId to use.
This was not the case earlier (sorry I dont know what version I was running but it was an old cluster)

The thing is that my VMSS has two assigned Managed Identities, but I have only one AzureIdentity in the cluster, so It should be possible to figure out what ClientId I want to use, and automaticly use this, or am I missing something?

**Comment by aramase** [comment]
@Eneuman For pods excepted, there is no pod identity. `AzurePodIdentityException` is a pod identity construct which tells pod identity that this pod isn't managed by aad-pod-identity. Any token request from excepted pod is just sent to IMDS as if AAD Pod Identity doesn't exist in the token request path (proxy).

> This was not the case earlier (sorry I dont know what version I was running but it was an old cluster)

AAD Pod Identity added support for `AzurePodIdentityException` in 1.6 release and this has always been the case. It's possible you were using an AKS cluster with service principal before and there was only a single identity assigned to the VMSS. In that case not passing clientID would work because IMDS just picks the 1 available. But if you're cluster was deployed with `--enable-managed -identity`, then agentpool identity is created for cluster operations. So having 2 identities would mean the client needs to set the clientID in token request as IMDS no longer knows which one to pick.

> The thing is that my VMSS has two assigned Managed Identities, but I have only one AzureIdentity in the cluster, so It should be possible to figure out what ClientId I want to use, and automaticly use this, or am I missing something?

For excepted pods, no we can't set the clientID because exception means no AAD Pod Identity validation/defaulting.

**Comment by Eneuman** [comment]
@aramse Okey, I see. So If I dont have my pod excepted, and my VMSS has two identities but I have only one AzureIdentity, Pod Identity will set the ClientId and I won't need to set it explicitly?

**Comment by aramase** [comment]
> @aramse Okey, I see. So If I dont have my pod excepted, and my VMSS has two identities but I have only one AzureIdentity, Pod Identity will set the ClientId and I won't need to set it explicitly?

@Eneuman That's right! One hidden feature and value add of AAD Pod Identity is setting the clientID to the clientID in first `AzureIdentity` if not explicitly set by the client. However we can't do that for excepted pods.

**Comment by Eneuman** [comment]
@aramase Thanks for the help in understanding how Pod-Identity works.
I'm gonna close this issue since I now know this is by design.
