### ISSUE TITLE
Support identity in a container-level

### ISSUE THREAD

**Issue by idanlevin** [Azure/aad-pod-identity#105]
Hi,

There are multiple scenarios where you might want to give different identities to different containers in a pod.

For example, if you have an init-container that does some work that requires special permissions, you don't necessarily want to give that permission to the containers in the pod.

Is it possible to assign the identity at a container level? is it something we can support?

Idan

**Comment by khenidak** [comment]
@idanlevin you can do `something similar` today but with a bit of work. 

The idea is to use `User assigned identities` Each container should use the identity by name not as MSI. We translate these calls to get with `client_id`. This will give your pod the over all `feeling` of identity per container. But it will not stop container A from getting the identity assigned to identity B because the two calls will originate from the same pod ip which is what we use to gate the access to identities.

I am open for ideas on this.

**Comment by idanlevin** [comment]
@khenidak thanks, it helps but doesn't really solve the security problem around it.

I'm not a K8s networking expert, but since _NMI_ is a daemonset, maybe it can tell from which container a request is coming from instead of relying on the source IP? using a Docker network plugin or something else..

**Comment by khenidak** [comment]
Telling which container (without customized interface, breaking ADAL et al) is not possible today. as we depend on `src ip`.

**Comment by kwaazaar** [comment]
Initcontainers in Kubernetes are just one solution to the problem. I use initcontainers to upgrade databases used by the main container. The rolling upgrade strategy makes sure just 1 instance runs at a time, but for new deployments more than one will run, which causes race conditions. This is just an example where initcontainers could be used, but are not really the right solution. You could use a job or a release pipeline step (eg: kubectl run...) instead to do the job.

**Comment by idanlevin** [comment]
There are many valid use-cases to init-containers, and there are use-cases where an init-container might have more permissions than the long-lived running container. If you really want to adopt least-privileges approach, this should be supported.

**Comment by chewong** [comment]
Closing this issue as there is no further discussion. As @khenidak mentioned, aad-pod-identity works on a pod level (we use pod IP address to identify the caller who requests an AAD token from IMDS, and there is no way to know which container the request is originated from). I don't think we could support that with our current design.
