### ISSUE TITLE
Error while Installing aad-pod-identity - status CrashLoopBackOff for nmi pods

### ISSUE THREAD

**Issue by karthi-sn** [Azure/aad-pod-identity#1050]
Steps -
helm repo add aad-pod-identity https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts

# Helm 3
helm install aad-pod-identity aad-pod-identity/aad-pod-identity

"kubernetesVersion": "1.18.14"
"Network type (plugin)": kubenet
"Node count": 3 Nodes

![image](https://user-images.githubusercontent.com/41871740/115546565-d1137300-a2c2-11eb-86ba-d90e18aeeeb6.png)

**Comment by chewong** [comment]
Could you add `--set nmi.allowNetworkPluginKubenet=true` in your helm install/upgrade command? See --set nmi.allowNetworkPluginKubenet=true for more details.

**Comment by aramase** [comment]
You can also check the logs when it crashes. The logs should have a reference to https://azure.github.io/aad-pod-identity/docs/configure/aad_pod_identity_on_kubenet/ which has details on why it's disabled in clusters with kubenet and necessary steps to take before enabling them.

**Comment by karthi-sn** [comment]
> Could you add `--set nmi.allowNetworkPluginKubenet=true` in your helm install/upgrade command? See https://azure.github.io/aad-pod-identity/docs/#v17x-breaking-change for more details.

after adding --set nmi.allowNetworkPluginKubenet=true, not getting any error
thanks chewong
