### ISSUE TITLE
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated

### ISSUE THREAD

**Issue by zhiweiv** [Azure/aad-pod-identity#1051]
When applying https://raw.githubusercontent.com/Azure/aad-pod-identity/v1.7.5/deploy/infra/deployment-rbac.yaml, I get following output:
`Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition`

Since k8s 1.21 has been released, 1.22 will come soon, is it good to update it to v1 now?

**Comment by aramase** [comment]
The update to v1 has been merged to master already and will be included in v1.8 release: https://github.com/Azure/aad-pod-identity/pull/1035.

**Comment by zhiweiv** [comment]
Thanks for the update.
