### ISSUE TITLE
Support for aks1.20 and aks1.21

### ISSUE THREAD

**Issue by dhilipkumars** [Azure/aad-pod-identity#1052]
**Describe the request**
We are currently using v1.6.3 and moving to AKS 1.20 cluster, could you tell us If `aad-pod-identity` is supported in the latest AKS versions? 
In the future would we get similar information in Release notes? 

Thanks in advance
**Explain why AAD Pod Identity needs it**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aramase** [comment]
`v1.6.3` should be supported with AKS v1.20 and v1.21. Is there a reason for not using the latest available release? We have added quite a few improvements and fixes since v1.6.3.

**Comment by dhilipkumars** [comment]
Thanks @aramase for the info.  We are aiming to move to AKS's native AAD plugin soon but have a requirement to upgrade cluster to 1.20 even before that.
