### ISSUE TITLE
HTTP 400 invalid request; Identity not found when using User Managed Identity for AAD Pod identity assignment

### ISSUE THREAD

**Issue by zorg-the-blue** [Azure/aad-pod-identity#1054]
- [X] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [X] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [X] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
This may be similar to #1030. Receiving the following errors in the logs when MIC is trying to apply identities to a VMSS when using a User Assigned Managed Identity for AAD Identity Pods on an AKS cluster using managed identity:

MIC:
StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: failed to get service principal token, error: failed to refresh token, error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"

NMI:
I0428 21:05:06.899013       1 server.go:305] fetching token for user assigned MSI for resource: https://management.azure.com/
E0428 21:05:06.980772       1 server.go:365] failed to get service principal token for pod:azure/aad-pod-identity-mic-xxxxxxx85-qjkr5 with error code 403, error: failed to get service principal token, error: failed to refresh token, error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}

Maybe it is somewhere in my configuration, any pointers would be appreciated, hence the full deployment CLI/Helm parameters in case I have conflicting configuration settings. (Some values have been changed or masked regarding IPs/subscriptions/objects.)

**Steps To Reproduce**
Deployed new K8 cluster (v1.19.9)
CLI: 
`az aks create --name testcluster --resource-group "rg-test" --api-server-authorized-ip-ranges "1.2.3.4/24" --attach-acr "/subscriptions/<BLAH>" --dns-name-prefix "testcluster-dns" --dns-service-ip "192.168.0.10" --docker-bridge-address "192.168.1.1/16" --enable-managed-identity --enable-rbac --generate-ssh-keys --kubernetes-version "1.19.9" --load-balancer-managed-outbound-ip-count 1 --load-balancer-sku "standard" --location "eastus" --max-pods 30 --network-plugin "azure" --network-policy "calico" --node-count 2 --node-osdisk-size 30 --node-osdisk-type "ephemeral" --node-vm-size "Standard_B2ms" --nodepool-name "agentpool01" --outbound-type "loadBalancer" --service-cidr "192.168.0.0/16" --vm-set-type VirtualMachineScaleSets  --vnet-subnet-id  "/subscriptions/<BLAH>/k8-subnet"`

Create User Identity for AAD Pod 
CLI:
`az identity create -g MC_rg-test-testcluster_eastus -n id-testcluster-mic`
[MC* resource group IAM updated for Contributor and Identity Operator roles for this user]

Install AAD Pod Identity using output from above:
HELM:
`helm install --set-string forceNamespaced=true --set-string nmi.rbac.allowAccessToSecrets=false --set adminsecret.cloud=AzurePublicCloud --set adminsecret.subscriptionID=XXXXXXXXXXXXX --set adminsecret.resourceGroup=MC_rg-test-testcluster_eastus --set adminsecret.vmType=vmss --set adminsecret.tenantID=XXXXXXXXXXXXX --set adminsecret.clientID=msi --set adminsecret.clientSecret=msi --set-string adminsecret.useMSI=true --set adminsecret.userAssignedMSIClientID=<ClientID from identity> --set mic.logVerbosity=10 --set nmi.logVerbosity=10 aad-pod-identity aad-pod-identity/aad-pod-identity -n azure`

Create User Identity for AGIC:
`az identity create -g test-resourceGroup -n id-testcluster-agic`

Install AGIC:
Helm:
`helm install ingress-azure -f values.yaml application-gateway-kubernetes-ingress/ingress-azure -n azure`
Key Helm Identity Values:
```
armAuth:
    type: aadPodIdentity
    identityResourceID: /subscriptions/<BLAH>/id-testcluster-agic
    identityClientID:  XXXXXXXXXXXXX
```

**Expected behavior**
AAD MIC assigns the id-testcluster-agic user to the VMSS node

**AAD Pod Identity version**
1.7.5

**Kubernetes version**
1.19.9

**Additional context**
Calico running as the Network Policy. Added the Global network allow (after deployment) for the specified 127.0.0.1/TCP ports.
Validated at MIC startup via logs that the client ID defined in the AAD Pod deployment matched the user identity crated for the MIC.

**Comment by aramase** [comment]
@zorg-the-blue What is the clientID that you're configuring for MIC to be able assign/unassign the identities? MIC typically uses the cluster identity for this operation but since you're configuring it with `adminsecret.userAssignedMSIClientID=<ClientID from identity>` have you assigned the identity to the VM/VMSS? The identity that MIC needs to use to talk to Azure needs to exist on the underlying VM/VMSS for it to be able to use.

**Comment by zorg-the-blue** [comment]
After using the CLI to create the identity, I get something like this and I use the "clientId": "YYYYYYYYYYYYYYYYY" of this response in the subsequent Helm deployment value of "adminsecret.userAssignedMSIClientID":

```
{
  "clientId": "YYYYYYYYYYYYYYYYY",
  "clientSecretUrl": "<LONG URL>",        
  "id": "/subscriptions/<BLAH>/userIdentity-mic",  
  "location": "eastus",
  "name": "userIdentity-mic",
  "principalId": "XXXXXXXXXXXXXXXXXXXXXXXX",
  "resourceGroup": "MC_<testclusterRG>_eastus",
  "tags": {},
  "tenantId": "ZZZZZZZZZZZZZZZZZZZZZZ",
  "type": "Microsoft.ManagedIdentity/userAssignedIdentities"
}
```

Then, I've used this identity when assigning roles in the "MC_<testclusterRG>_eastus" resource group to have Contributor and Managed User Identity Operator.

I did not understand from the documentation that this user supplied managed identity used by the AAD Pod then also needed to be added manually to the VMSS. Are you saying it needs to be added as a User Assigned Identity on the VMSS?

Is that the difference between Operation Mode 'managed' and 'standard'? Though, I read that setting as being whether the pod identity was doing the assignments vs it being done outside of AAD Pod assignment.

**Comment by aramase** [comment]
So you're using a different managed identity (not cluster identity) to give MIC permission to access the cloud resources and do all cloud operations (assign/un-assign, GET VMSS). That identity needs to be assigned by you to the underlying VMSS so that it's available for use. 

MIC needs to get a token for that identity to assign all your workload identities. It's a chicken-egg problem. MIC can't assign the identity that it needs to use for accessing Azure. 

> Is that the difference between Operation Mode 'managed' and 'standard'? Though, I read that setting as being whether the pod identity was doing the assignments vs it being done outside of AAD Pod assignment.

Managed mode vs standard mode is the difference for identities that are configured using `AzureIdentity`. If you're using your own identity for MIC, then that needs to exist on the VMSS so MIC can get a token and do further operations.

**Comment by zorg-the-blue** [comment]
Makes sense that the identity for the AAD pod to use needs to exist on the VMSS for the AAD pod to use it.

I've added it and have gotten further. Believe it is now a permission gap on my AGIC identity I'm waiting for cache/creds to regenerate and distribute after setting. Will continue validating on Friday, maybe again from the ground up just to make sure all is good.

Thanks for the assistance.

**Comment by zorg-the-blue** [comment]
All came together once permissions propagated and refreshed. The AGIC pod came up and its user was added to the VMSS.

One follow up question - if we add a new VMSS pool to the cluster, will the AAD Pod identity have enough permissions to add itself to the new VMSS or will we need to manually add this User Assigned Identity to each new VMSS pool we create?

Thanks in advance.

**Comment by aramase** [comment]
> One follow up question - if we add a new VMSS pool to the cluster, will the AAD Pod identity have enough permissions to add itself to the new VMSS or will we need to manually add this User Assigned Identity to each new VMSS pool we create?

The identity that will be used by AAD Pod Identity will need to be assigned to each nodepool because that's BYO user-assigned identity. For the identities defined in `AzureIdentity`, MIC will assign the identity if not exists when a pod using it lands on the new nodepool.

**Comment by zorg-the-blue** [comment]
Thank you for the clarification, we will plan for adding the BYOL identity user to the baseline configuration on new VMSS pools.
