### ISSUE TITLE
pods running as root user security alerts

### ISSUE THREAD

**Issue by assaf-grth** [Azure/aad-pod-identity#1060]
**Have you**

- [X] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [X] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [X] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

I am using the helm installation of aad-pod-identity, (version 4.0.0, 1.7.5)
The installation creates pods which are defined to run as root user
When connected to Azure Security Center I get this recommendation: "Running containers as root user should be avoided"
Is there a practice to use a different permission level?
Should this ASC recommendation be ignored?

**Expected behavior**
Product should comply with ASC recommendations

**AAD Pod Identity version**
Chart: aad-pod-identity-4.0.0 
App version: 1.7.5

**Kubernetes version**
1.18.14

**Additional context**

**Comment by aramase** [comment]
@assaf-grth Pod Identity components need to be run as root to be able to access the `/etc/kubernetes/azure.json` from host and also update the iptables. If you deploy in `kube-system` namespace, there should be no alert.

**Comment by assaf-grth** [comment]
1. In case I remove the helm installation and redeploy it into the kube-system namespace, what would need to be recreated again due to the deletion?
2. Is there a way to tell for my cluster which services or objects are using the pod identity service?

**Comment by assaf-grth** [comment]
Anyone?

**Comment by aramase** [comment]
@assaf-grth I would recommend doing a clean-install. You can delete the existing `AzureIdentity and `AzureIdentityBinding` and recreate after deploying pod identity in `kube-system` namespace.

> Is there a way to tell for my cluster which services or objects are using the pod identity service?

If pod identity is deployed to the cluster, all token requests for managed identity will go through NMI. If the pod has the selector configured that matches `AzureIdentityBinding`, then NMI will be able to fetch a token. If not, it'll error out. If you need except pods from the pod identity validation, you can configure `AzurePodIdentityException`https://azure.github.io/aad-pod-identity/docs/configure/application_exception/

**Comment by aramase** [comment]
Closing this issue with the above comment. Please feel free to reopen if you've any questions.
