### ISSUE TITLE
AzureIdentityBinding field "azureIdentity" in spec missing. Unknow field "name" used instead.

### ISSUE THREAD

**Issue by harrycain72** [Azure/aad-pod-identity#1068]
**Have you**

- [ x] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [ x] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [ x] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
When deploying the helm chart with azureIdentities enabled.
i.e:

`
azureIdentities:
   "id-tam-sandbox-we-aad-pod-identity":
     # if not defined, then the azure identity will be deployed in the same namespace as the chart
     namespace: ""
     # type 0: User-assigned identity, type 1: Service Principal, type 2: Service principal with certificate
     type: 0
     # Required for type 0
     resourceID: "/subscriptions/9a67dc8a-5d3d-429f-a1b4-882c23ec71c9/resourcegroups/rg-tam-sandbox-containers-aks-nodes-we/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-tam-sandbox-we-aad-pod-identity"
     # Required for type 0, 1 and 2
     clientID: "c2083cdf-8a65-49df-b72e-xyz"

     binding:
       name: "id-tam-sandbox-we-aad-pod-identity-binding"
       # The selector will also need to be included in labels for app deployment
       selector: "id-tam-sandbox-we-aad-pod-identity"
`

You get the following error:
error: error validating "./output.yaml": error validating data: ValidationError(AzureIdentityBinding.spec): unknown field "name" in io.k8s.aadpodidentity.v1.AzureIdentityBinding.spec; if you choose to ignore these errors, turn validation off with --validate=false

**Steps To Reproduce**

**Expected behavior**
As it was the case in 1.7.5 the resource AzureIdentityBinding gets deployed without issues.

**AAD Pod Identity version**
 v1.8.0
**Kubernetes version**
v1.20.5
**Additional context**

Difference between the charts in v1.7.5 and v1.8.0

v1.8.0
`
  - apiVersion: "aadpodidentity.k8s.io/v1"
    kind: AzureIdentityBinding
    metadata:
      name: {{ $value.binding.name }}
      namespace: {{ default $.Release.Namespace $value.namespace }}
      labels:
        {{- include "aad-pod-identity.labels" $ | nindent 8 }}
    spec:
      name: {{ default $key $value.name  }}
      selector: {{ required "binding.selector is required!" $value.binding.selector }}
`

==> field spec/name  is not known!! and leads to an error

v1.7.5
`
  - apiVersion: "aadpodidentity.k8s.io/v1"
    kind: AzureIdentityBinding
    metadata:
      name: {{ $value.binding.name }}
      namespace: {{ default $.Release.Namespace .namespace }}
      labels:
        {{- include "aad-pod-identity.labels" $ | nindent 8 }}
    spec:
      azureIdentity: {{ $key }}
      selector: {{ required "binding.selector is required!" $value.binding.selector }}

`

**Comment by chewong** [comment]
Thanks for opening the issue, looks like https://github.com/Azure/aad-pod-identity/pull/1036 introduced a regression to the helm chart. #1069 should fix it.
