### ISSUE TITLE
NMI pods in non-mic subnet result in CrashLoopBackOff status when using kubenet

### ISSUE THREAD

**Issue by dutsmiller** [Azure/aad-pod-identity#1070]
**Describe the bug**
When deploying to an AKS cluster with kubenet with multiple node pools in separate subnets, the NMI pods in a subnet other than the one containing the MIC pods end up in CrashLoopBackOff status.  The same code works fine when using AzureCNI.

```
aad-pod-identity-mic-7fc99cff8b-b8gvj   1/1     Running            0          63m   10.244.0.4   aks-system-24605520-vmss000001   <none>           <none>
aad-pod-identity-mic-7fc99cff8b-px28v   1/1     Running            0          63m   10.244.1.5   aks-system-24605520-vmss000000   <none>           <none>
aad-pod-identity-nmi-2q2rg              1/1     Running            0          61m   10.1.1.7     aks-pool1-24605520-vmss000001    <none>           <none>
aad-pod-identity-nmi-4hxkb              0/1     CrashLoopBackOff   25         62m   10.1.2.4     aks-pool2-24605520-vmss000000    <none>           <none>
aad-pod-identity-nmi-7tqcw              1/1     Running            0          63m   10.1.1.4     aks-system-24605520-vmss000000   <none>           <none>
aad-pod-identity-nmi-dpz8p              0/1     CrashLoopBackOff   25         62m   10.1.2.5     aks-pool2-24605520-vmss000001    <none>           <none>
aad-pod-identity-nmi-q5rxt              1/1     Running            0          61m   10.1.1.6     aks-pool1-24605520-vmss000000    <none>           <none>
aad-pod-identity-nmi-xf674              1/1     Running            0          63m   10.1.1.5     aks-system-24605520-vmss000001   <none>           <none>
```

**Steps To Reproduce**
I have created an example workspace to demonstrate the issue.  The terraform code uses a random string and should run cleanly in any Azure subscription without inputs provided the credentials have the Owner permission.

[Sample Workspace](https://github.com/dutsmiller/aad-pod-identity-test)

**Expected behavior**
The NMI pods should reach Running status in all node pools.

**AAD Pod Identity version**
Tested in helm charts 4.0.0 (v1.7.5) and 4.1.0 (v1.8.0)

**Kubernetes version**
1.19

**Comment by aramase** [comment]
Hey @dutsmiller. AAD Pod Identity is disabled by default in clusters with kubenet. Refer to https://azure.github.io/aad-pod-identity/docs/configure/aad_pod_identity_on_kubenet/ on why and how to enable it for clusters with kubenet. The logs in NMI will also contain a reference to the doc.

**Comment by dutsmiller** [comment]
@aramase Were you able to look at the sample workspace?  I believe I have implemented all necessary pieces and pod both the MIC and NMI pods work fine in one subnet, just not the other.

**Comment by aramase** [comment]
@dutsmiller What is the error in the NMI pod that's in `CrashLoopBackOff`?

**Comment by dutsmiller** [comment]
```
Events:
  Type     Reason     Age                     From                                    Message
  ----     ------     ----                    ----                                    -------
  Warning  Unhealthy  9m50s (x147 over 139m)  kubelet, aks-pool2-24605520-vmss000001  Liveness probe failed: Get "http://10.1.2.5:8085/healthz": dial tcp 10.1.2.5:8085: connect: connection refused
  Warning  BackOff    4m44s (x562 over 138m)  kubelet, aks-pool2-24605520-vmss000001  Back-off restarting failed container
```

**Comment by aramase** [comment]
Could you also share the logs from the NMI pods that's in `CrashLoopBackOff`?

**Comment by dutsmiller** [comment]
@aramase that IS from a pod in CrashLoopBackOff.  Again, if you have 5 minutes to run terraform on that [sample workspace](https://github.com/dutsmiller/aad-pod-identity-test) above (it has been randomized and requires no inputs), you'll see exactly what I'm referring to.

**Comment by dutsmiller** [comment]
UPDATE:  The issue is with the second bullet here and unrelated to pod identity: 

https://docs.microsoft.com/en-us/azure/aks/configure-kubenet#bring-your-own-subnet-and-route-table-with-kubenet
