### ISSUE TITLE
No clientID in request log

### ISSUE THREAD

**Issue by lissff** [Azure/aad-pod-identity#1071]
We have an application that would refresh the Pod identity tokens on daily basis, and then use this token to access azure storage.
And each time when we are doing the token refresh, you saw logs in nmi pod: 

I0421 14:24:02.507179       1 standard.go:72] No clientID in request. fu***6d has been matched with azure identity default/sa**
I0421 14:24:02.507261       1 standard.go:165] matched identityType:0 clientid:4**f resource:https://vault.azure.net

sometimes these log lasts for 5 minutes or longer, and we saw authentication failures with the new token we just got:
**AuthenticationFailed|Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
AuthenticationErrorDetail:Lifetime validation failed. The token is expired.**

My questions are:
- lifetime for pod identity tokens, is it 24hr? according to: https://github.com/Azure/aad-pod-identity/issues/980#issuecomment-788157296  , does this mean if I manually refresh the token within 24 hours, then i will get a new token or still the same one?
- is there known issue with token propagation delay? e.g. if i using SDK to refresh the token, would it take effect immediately in AAD side?

**Comment by aramase** [comment]
> lifetime for pod identity tokens, is it 24hr? according to: #980 (comment) , does this mean if I manually refresh the token within 24 hours, then i will get a new token or still the same one?

Pod identity is essentially just a proxy that validates the token request and sends to IMDS (169.254.169.254). IMDS requests tokens from AAD and sends back to the caller. AAD tokens by default are valid for 24hr. If you refresh the token before expiry, then you'll get a new token. 

> is there is long issue with token propagation delay? e.g. if i using SDK to refresh the token, would it take effect immediately in AAD side?

If you're SDK is caching the token, then it'll have logic to fetch a new token when the cached token is close to expiry.
