### ISSUE TITLE
AADSTS7000222: The provided client secret keys are expired

### ISSUE THREAD

**Issue by Monta89** [Azure/aad-pod-identity#1075]
**Have you**

- [ ] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [ ] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [ ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
 keep getting the following error in the aad-pod-identity-mic 
```
E0521 19:03:53.218729 1 mic.go:1101] failed to get a list of user-assigned identites from node xxxxxxxx-vmss, error: failed to get identity resource, error: failed to get vmss xxxxxxxxx-vmss in resource group xxxxxxxxxxx, error: failed to get vmss xxxxxxxxxx-vmss in resource group xxxxxxxxxxxx, error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/xxxxxxxxxxx/resourceGroups/xxxxxxxxxxx/providers/Microsoft.Compute/virtualMachineScaleSets/xxxxxxxxxxxx-vmss?api-version=2019-07-01: StatusCode=401 -- Original Error: adal: Refresh request failed. Status Code = '401'. Response body: {"error":"invalid_client","error_description":"AADSTS7000222: The provided client secret keys are expired. Visit the Azure Portal to create new keys for your app, or consider using certificate credentials for added security: https://docs.microsoft.com/azure/active-directory/develop/active-directory-certificate-credentials\r\nTrace ID: xxxxxxxxxxxx\r\nCorrelation ID: xxxxxxxxxxxxxx\r\nTimestamp: 2021-05-21 19:03:53Z","error_codes":[7000222],"timestamp":"2021-05-21 19:03:53Z","trace_id":"xxxxxxxxxxx","correlation_id":"xxxxxxxxxxxxxx","error_uri":"https://login.microsoftonline.com/error?code=7000222"}
```
All roles are set for "managed identity operator" and "virtual machine contributor"
**Steps To Reproduce**

**Expected behavior**

**AAD Pod Identity version**
1.7.5
**Kubernetes version**
1.16.15
**Additional context**

**Comment by aramase** [comment]
@Monta89 What type of cluster is this? AKS/aks-engine? 

The cluster service principal credentials have expired. You'll need to refresh the credentials and update the secret. Then MIC will pick up the new secret for authentication with Azure.

**Comment by Monta89** [comment]
sorry for not giving more details.
Yes it's an aks cluster but the strange thing is that the cluster has an system assigned service principle which doesn't expire !!!

**Comment by aramase** [comment]
Are you referring to the cluster using a system-assigned managed identity or service-principal? 

Could you run this command to check:
```bash
SP_ID=$(az aks show --resource-group myResourceGroup --name myAKSCluster \
    --query servicePrincipalProfile.clientId -o tsv)
az ad sp credential list --id $SP_ID --query "[].endDate" -o tsv
```

Ref doc: https://docs.microsoft.com/en-us/azure/aks/update-credentials

**Comment by Monta89** [comment]
I get this 
`Service principal 'msi' doesn't exist`

Here are more details for the SP and identities for the cluster 

```
az aks show -g xxxxxxxxxxx -n xxxxxxxxxxxx --query "servicePrincipalProfile"
The behavior of this command has been altered by the following extension: aks-preview
{
  "clientId": "msi"
}
~ ❯❯❯ az aks show -g xxxxxxxxxx -n xxxxxxxxxxxxx --query "identity"
The behavior of this command has been altered by the following extension: aks-preview
{
  "principalId": "xxxxxxxxxxxxx",
  "tenantId": "xxxxxxxxxxxxxx",
  "type": "SystemAssigned",
  "userAssignedIdentities": null
}
```

**Comment by aramase** [comment]
Is pod identity configured with it's own SP instead of using the cluster identity? 

https://github.com/Azure/aad-pod-identity/blob/master/deploy/infra/noazurejson/deployment-rbac.yaml#L618-L627

**Comment by Monta89** [comment]
no it's configured to use the cluster identity so i didn't add this section if that's what you're asking 

```
adminsecret:
  cloud: <cloud environment name>
  subscriptionID: <subscription id>
  resourceGroup: <node resource group>
  ......
```

**Comment by aramase** [comment]
That's interesting. Could you provide the first few lines of logs from MIC pod? The redacted `clientID` used by pod identity will be in the log. That'll be helpful to see which id it is and why it's showing as expired.

**Comment by Monta89** [comment]
When I run the below command I get a different id from the commands that I shared before

`az aks show -g xxxxxxx -n xxxxxxxx --query identityProfile.kubeletidentity.clientId -otsv`

So I tried to deploy again using that id with the following parameters and it worked fine.

```
adminsecret:
  cloud: AzurePublicCloud
  subscriptionID: xxx
  resourceGroup: xx
  vmType: vmss
  tenantID: xxxx
  clientID: msi
  clientSecret: msi
  useMSI: "true"
  userAssignedMSIClientID: xxxxx
```

**Comment by hazzik** [comment]
Bot is really unhelpful.

**Comment by aramase** [comment]
@hazzik If you're facing any issues, please feel free to open a new issue with the relevant logs and we can help take a look. This issue was closed because there are no longer any errors based on the last message.
