### ISSUE TITLE
Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request

### ISSUE THREAD

**Issue by uthsab** [Azure/aad-pod-identity#1084]
**Have you**

- [ ] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [ ] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [ ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**

Getting token from pod fails. 
we are using [Default Azure Credential  (python)](https://docs.microsoft.com/en-us/python/api/azure-identity/azure.identity.defaultazurecredential?view=azure-python) in the code to fetch the managed identity credential. This is the error log from the same. 

Failed: No valid token received. EnvironmentCredential: Incomplete environment configuration.. ImdsCredential: Unexpected response '{'error': 'invalid_request', 'error_description': 'Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request'}'

The issue is intermittent. Restarting the pod / redeploying mitigates it.
What is the cause and resolution for this?
 
**Steps To Reproduce**

**Expected behavior**

**AAD Pod Identity version**
helm chart 2.0.1

**Kubernetes version**
1.18.10

**Additional context**

**Comment by aramase** [comment]
@uthsab Thank you for reporting the issue.

1. Could you share the logs from NMI pod running on the same node as your app? What is the error in NMI?
2. That error seems to indicate the token request is not being intercepted NMI. This could be because NMI isn't running on the node/ the pod label is included in `AzurePodIdentityException` (https://azure.github.io/aad-pod-identity/docs/configure/application_exception/). If configured in `AzurePodIdentityException` then the token request will be forwarded to IMDS as is without any defaulting from NMI. Refer to https://github.com/Azure/aad-pod-identity/issues/1077 which is a similar issue.

**Comment by uthsab** [comment]
The only exceptions defined are for the MIC itself and pods managed by aks. nothing additional
```
uthsa@Azure:~$ kubectl get azurepodidentityexception -A -o yaml
apiVersion: v1
items:
- apiVersion: aadpodidentity.k8s.io/v1
  kind: AzurePodIdentityException
  metadata:
    annotations:
      meta.helm.sh/release-name: aad-pod-identity
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2020-12-01T13:47:36Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
    name: mic
    namespace: default
    resourceVersion: "45688185"
    selfLink: /apis/aadpodidentity.k8s.io/v1/namespaces/default/azurepodidentityexceptions/mic
    uid: c585876b-33db-11eb-8261-96e3ca0273b1
  spec:
    podLabels:
      app: mic
      app.kubernetes.io/component: mic
      component: mic
- apiVersion: aadpodidentity.k8s.io/v1
  kind: AzurePodIdentityException
  metadata:
    annotations:
      meta.helm.sh/release-name: aad-pod-identity
      meta.helm.sh/release-namespace: default
    creationTimestamp: "2020-12-01T13:47:36Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
    name: aks-addon-exception
    namespace: kube-system
    resourceVersion: "45688187"
    selfLink: /apis/aadpodidentity.k8s.io/v1/namespaces/kube-system/azurepodidentityexceptions/aks-addon-exception
    uid: c58582f9-33db-11eb-8261-96e3ca0273b1
  spec:
    podLabels:
      kubernetes.azure.com/managedby: aks
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
uthsa@Azure:~$
```
Also the issue is intermittent. A pod restart / redeployment mitigates it. If it was due to the exception, it would have always failed. 

The nmi logs from the concerned node for the concerned time - 
The failures happened from around 10:35 UTC 06/02. There was a successful connection post mitigation at 11:35 UTC 06/02
```
uthsa@Azure:~$ kubectl logs aad-pod-identity-nmi-4d6h4
I0602 10:27:19.941431       1 main.go:60] starting nmi process. Version: 1.6.2. Build date: 2020-07-24-20:26.
I0602 10:27:20.411543       1 crd.go:444] CRD lite informers started
I0602 10:27:20.411572       1 main.go:87] running NMI in namespaced mode: false
I0602 10:27:20.411584       1 nmi.go:52] initializing in standard mode
I0602 10:27:20.411593       1 probes.go:41] initialized health probe on port 8085
I0602 10:27:20.411629       1 probes.go:44] started health probe
I0602 10:27:20.412510       1 metrics.go:329] registered views for metric
I0602 10:27:20.412596       1 prometheus_exporter.go:21] starting Prometheus exporter
I0602 10:27:20.412618       1 metrics.go:335] registered and exported metrics on port 9090
I0602 10:27:20.412654       1 server.go:96] listening on port 2579
W0602 10:27:20.608245       1 iptables.go:123] flushing iptables to add aad-metadata custom chains
W0606 17:24:00.521267       1 server.go:334] parameter resource cannot be empty
I0606 17:24:00.521300       1 server.go:190] status (400) took 54501 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.0.49
I0606 17:24:00.556286       1 standard.go:72] no clientID or resourceID in request. default/monitoring-d7d8b74d5-f6f2m has been matched with azure identity default/bm-dev-test-cluster-mi
I0606 17:24:00.556382       1 standard.go:178] matched identityType:0 clientid:588a##### REDACTED #####146c resource:https://vault.azure.net
I0606 17:24:00.728160       1 server.go:190] status (200) took 172974593 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.0.49
I0606 17:24:17.811895       1 standard.go:72] no clientID or resourceID in request. default/monitoring-d7d8b74d5-f6f2m has been matched with azure identity default/bm-dev-test-cluster-mi
I0606 17:24:17.811986       1 standard.go:178] matched identityType:0 clientid:588a##### REDACTED #####146c resource:https://ingest-bmprodoaicluster.centralus.kusto.windows.net
```

**Comment by aramase** [comment]
Is this the pod `bm-dev-test-cluster-mi` making the token request?

**Comment by uthsab** [comment]
yes, `bm-dev-test-cluster-mi` is the concerned azure identity here (it is the only one defined for the aks cluster). Should I check for some specific log to confirm if the request is made?

**Comment by aramase** [comment]
Yeah, could you see if the pod making the token request is in the NMI log? This is for the NMI pod running on the same node as your application. Also, is your app running on `hostNetwork`?

**Comment by uthsab** [comment]
The pod making the request is not running on hostnetwork. there is a separate daemonset which is on host network.

The failure happens when the default/monitoring-d7d8b74d5-f6f2m makes the token request itself. 
I attached all logs from the nmi pod on same node as monitoring pod during the duration of the failure. 
The failure timestamp is 10:35 UTC 06/02. There are no token request logs around this time. 
However after a redeployment of the same bits, the request goes through correctly. 
what could have caused this failure?

**Comment by uthsab** [comment]
@aramase Any updates on this issue?

**Comment by aramase** [comment]
@uthsab You're running an old version of pod identity (`v1.6.2`). Could you upgrade to the latest and let us know if you're seeing any issues? If you can repro with the latest, please share the entire NMI and MIC pod logs.

**Comment by Tenseiga** [comment]
I m getting the same error. I m using the 1.8.0 version

**Comment by ahmad-hamade** [comment]
I'm getting the same error as well. using latest version 1.8.1

**Comment by chewong** [comment]
Have you tried specifying the client ID of your identity when authorizing your application via the SDK?

**Comment by ahmad-hamade** [comment]
I have found what was the issue.

So my pod was running in system node pools with tolerations that I added `CriticalAddonsOnly` is `Exists` however, the NMI daemonset was not running in the system pool due to missing toleration. after getting the NMI running in the all `User` and `System` node pools issue got solved.
