### ISSUE TITLE
tutorial with mcr.microsoft.com/oss/azure/aad-pod-identity/demo:v1.8.0 image unused parameters

### ISSUE THREAD

**Issue by mmillard0** [Azure/aad-pod-identity#1086]
**Have you**

- [ ] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [ ] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [ ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
In the aad pod identity tutorial, some arguments of demo container are not taken into account.
In the section "3.2. Deploy demo", arguments "-resource-group" and "-subscription-id" for image "mcr.microsoft.com/oss/azure/aad-pod-identity/demo:v1.8.0" have no impacts.
![image](https://user-images.githubusercontent.com/77118562/120789078-64ca9700-c531-11eb-9616-c06259366081.png)

By the way, arguments names are not correct. The demo pod is not in running state as expected.
The pod logs shows this message:
/////
flag provided but not defined: -subscriptionid
Usage of demo:
  -identity-client-id string
        The user-assigned identity client ID
  -period duration
        The period that the demo is being executed (default 1m40s)
  -resource-group string
        The resource group name which the user-assigned identity read access to
  -resource-name string
        The resource name to grant the access token (default "https://management.azure.com/")
  -subscription-id string
        The Azure subscription ID
/////

After succeeded to make the tutorial working fine, I tried to use wrong values for "-resource-group" and "-subscription-id", it doesn't change the log results.

**Steps To Reproduce**
Follow the latest tutorial **but** in deployment.yaml, I set wrong values for "-resource-group" and "-subscription-id".
After deployment, the demo pod is running fine. The logs are fine too.

**Expected behavior**
Demo Pod should be running. The logs should display errors because the user-assigned identity **has no read access** on the given resource group. 

**AAD Pod Identity version**
1.7.3
**Kubernetes version**
1.19.7
**Additional context**
I'm not using the latest version of the plugin because I'm working on testing our current configuration before upgrading the plugins on ours clusters.

regards

**Comment by chewong** [comment]
Could you follow https://azure.github.io/aad-pod-identity/docs/demo/standard_walkthrough for now? I can open a PR to fix the typos above.

**Comment by mmillard0** [comment]
Thanks pour the response. The standard walkthrough is up to date with the arguments name.
My issue is to help beginners like me to do the tutorial without errors.
in the file master/cmd/demo/main.go the parameters resourceGroup & subscriptionID are not used.
I close the issue, it is fine for me.
