### ISSUE TITLE
Outbound Azure NSG rules for MIC controller

### ISSUE THREAD

**Issue by mynameisyz** [Azure/aad-pod-identity#1092]
**Have you**

- [x] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [x] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [x] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
I have a private AKS with running AAD pod identity with my workloads to access Azure resources. Part of my organization's policy is to fully lock down all inbound and outbound ports to and fro the cluster. However, once I put up a Deny Internet service tag outbound rule, the MIC stops working. Inspecting the logs reveals that the MIC is trying to access login.microsoftonline.com domain. Putting a Allow AzureActiveDirectory service tag doesn't work.

**Steps To Reproduce**
Set the following NSG outbound rules:
Priority | Port | Protocol | Source | Destination | Action
--- | --- | --- | ---| --- | ---
100 | 443 | TCP | Any | AzureActiveDirectory (service tag) | Allow
4096 | Any | Any | Any | Internet (service tag) | Deny

**Expected behavior**
MIC should be able to access login.microsoftonline.com with the appropriate outbound rule using service tag and all outbound internet connection denied. 

**AAD Pod Identity version**
1.8

**Kubernetes version**
1.19

**Additional context**

**Comment by chewong** [comment]
Did you deploy aad-pod-identity to the kube-system namespace?

**Comment by mynameisyz** [comment]
Hi @chewong , the aad-pod-identity is currently deployed in the default namespace as per guide in the docs.

I led to believe this is a issue with outbound rules? It works when I disable the Deny All Internet outbound rule

**Comment by chewong** [comment]
As per our [standard walkthrough](https://azure.github.io/aad-pod-identity/docs/demo/standard_walkthrough/#1-deploy-aad-pod-identity):

> Important: For AKS clusters with limited egress traffic, Please install aad-pod-identity in kube-system namespace using the helm charts.

https://github.com/Azure/aad-pod-identity/issues/467#issuecomment-577045311 has a good explanation on why it's necessary to deploy to the kube-system namespace.
