### ISSUE TITLE
"Identity not found" error occurred with managed identity already assigned on VM

### ISSUE THREAD

**Issue by SnowmanCharles** [Azure/aad-pod-identity#1102]
> Support resolved it for us by restarting IMDS on all nodes on our clusters,
> Below is the RCA:
> 
> > IMDS has a caching issue that AKS is highly susceptible due to the identity usage pattern for aad-pod-identity.
> > Whenever the identity is unassigned and reassigned to the VMs, MSI service will create a new VM entry with a new identifier.
> > The IMDS caching issue causes the VM to use the prior identifier.
> > When the VM attempts to request credentials from MSI service and presents the old identifier, MSI will respond with NotFound because the entry for the resource is associated with the new identifier.
> > IMDS will fall back and attempt to use the prior credentials for the prior identifier, which at this point had expired.
> > The solution is to restart IMDS on these nodes because that will cause the VM to retrieve the new config with the updated identifier.

I think this issue have not been resolved by the caching fix. I'm meeting the same issue now. Any instructions on how to restart the MSI server on the Virtual Machine? I can confirm that the client ID and object ID of the ManagedIdentity and the AzureIdentity are the same.

_Originally posted by @SnowmanCharles in https://github.com/Azure/aad-pod-identity/issues/681#issuecomment-867194941_

**Comment by dndao** [comment]
I'm having the same issue, the identity and binding are there with correct clientID but nmi log response:
 {"error":"invalid_request","error_description":"Identity not found"}

**Comment by B1T3X** [comment]
I'm facing the same issue using ExternalDNS from the Azure Marketplace on AKS using User-assigned managed identities. the ExternalDNS pod shows errors in the log, the exact same error @dndao has described. Why is this issue not getting any attention?
