### ISSUE TITLE
when will AAD pod identity v2 be available

### ISSUE THREAD

**Issue by pjgdexmach** [Azure/aad-pod-identity#1103]
There's a v2 for AAD pod identity in the making, we would like to know the eta on this, as we will make development decissions depending on this.

**Comment by chewong** [comment]
We are actively developing and testing v2 internally but we don't have a solid ETA yet. We will make sure we update this repository once v2 is available.

**Comment by roberthstrand** [comment]
@chewong, it would be great if that ETA got a little more solid, at least. I'm doing a lot of planing for future deployments and I would like to know if v2 is months away or more.

**Comment by aramase** [comment]
cc @phillipgibson

**Comment by zhiweiv** [comment]
Any update?

**Comment by aramase** [comment]
@zhiweiv There are solid dates yet but we have just private preview on AKS. When v2 repository is available we'll update the issues and the documentation here.

**Comment by zhiweiv** [comment]
@aramase 
I think you mean **_no solid dates_** yet. 

The most concern for me is Windows support, when it is public preview, will the Windows support available too?

**Comment by aramase** [comment]
@zhiweiv Pod Identity v2 will be supported for Linux and Windows. There is no NMI like component in v2, which means we no longer need host access for adding iptable rules/similar in windows. 

> Does Windows support rely on the new Windows privileged container in k8s 1.22?

No, it's not required.

**Comment by Tiemooowh** [comment]
Is there any progress on this "issue"?

**Comment by aramase** [comment]
@Tiemooowh We already announced [Azure Workload Identity](https://github.com/Azure/azure-workload-identity) which is v2 of AAD Pod Identity. Please see the announcement in the [docs](https://azure.github.io/aad-pod-identity/docs/).
