### ISSUE TITLE
Increase limit of 200 pod identities per cluster

### ISSUE THREAD

**Issue by nailuenlue** [Azure/aad-pod-identity#1105]
**Describe the request**
I know that there was initially a limit of 50 pod identities per Cluster, which has been increased to 200. We're now facing those limits as our plan is to share the AKS cluster for multiple applications, which are sitting in their dedicated namespaces. As some of the applications have multiple microservices, it's not unusual to have 10-15 identities used for a single application.

Where does the limitation of 200 come from? Is it NMI level limitations (although 200 Nodes per AKS Cluster is supported and NMI runs as a daemon set)? 

**Explain why AAD Pod Identity needs it**
In today's world, where applications use microservice patterns and isolate their databases, identities use to reach other Azure services, why is there such a low limit. One can potentially have 200 Nodes per cluster but only 200 identities, which doesn't make sense.

**Describe the solution you'd like**
Increase the limit or get rid of the limit if there are not real constraints.

**Describe alternatives you've considered**

**Additional context**

**Comment by chewong** [comment]
If you use the open-source solution (this repository), there is no limitation on the number of pod identities you can create. For more questions on the managed experience, you can open an issue at https://github.com/Azure/AKS/issues.
