### ISSUE TITLE
No effect of setting blockInstanceMetadata flag to true

### ISSUE THREAD

**Issue by shreeshsp** [Azure/aad-pod-identity#1107]
**Have you**

- [ ] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [ ] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [.] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
I enabled aad-pod-identity on the AKS cluster with the blockInstanceMetadata flag set to true in order to block the pod access to instance metadata. However from the pod I am able to access the instance metadata using curl command  with url http://169.254.169.254/metadata/instance.

**Steps To Reproduce**
Set blockInstanceMetadata flag to true
Install aad-pod-identity on AKS cluster
Deploy an nginx pod and run curl command with instance metadata url within the pod

**Expected behavior**
Instance metadata should be inaccessible from the pod.

**AAD Pod Identity version**
4.1.0
**Kubernetes version**
1.19
**Additional context**

**Comment by chewong** [comment]
Does your pod have host network enabled? If so, it should have access to it regardless of the flag value.

**Comment by shreeshsp** [comment]
> Does your pod have host network enabled? If so, it will have access to it regardless of the flag value.

No, host network is not enabled for the pod. However, the aks cluster is enabled with the following security features:
Azure AD integration 
Managed identities 
Host based encryption 
Disk encryption set with CMK
Azure policy add-on (few built in policies only assigned)

**Comment by aramase** [comment]
@shreeshsp How are you installing pod identity? If you're installing with helm the configuration value is `nmi.blockInstanceMetadata=true`. If you're deploying using yaml and then adding the arg, it's `-- block-instance-metadata=true` in the NMI daemonset container args. 

I just deployed using helm and can confirm it works as expected:

1. Deploy pod identity
```bash
➜ helm install pi aad-pod-identity/aad-pod-identity --set nmi.allowNetworkPluginKubenet=true --set nmi.blockInstanceMetadata=true
```

2. Run a pod on pod network
```bash
➜ kubectl run -it n0 --image=mcr.microsoft.com/azure-cli --labels "aadpodidbinding=testidentity" bash --overrides='{"spec": { "nodeSelector": {"kubernetes.io/os": "linux"}}}'
```

3. Run curl from the pod 
```bash
bash-5.1# curl http://169.254.169.254/metadata/instance.
Request blocked by AAD Pod Identity NMI
```

**Comment by shreeshsp** [comment]
@aramase I am installing aad pod identity with terraform using Helm as per the attached file (aad-pod-id.tf). 

Also created  Azure Identity and AzureIdentityBinding as per attachment (AzureIdentityBinding.yaml; where variable value for identityName is "my-pod-identity" and for identitySelector is "requires-vault".)

Deploying the nginx pod using the attached file (deploy.yaml)

Running curl command from the pod as :
curl -H Metadata:true http://169.254.169.254/metadata/instance/compute?api-version=2021-01-01&format=json

[deploy.txt](https://github.com/Azure/aad-pod-identity/files/6803115/deploy.txt)
[aad-pod-id.txt](https://github.com/Azure/aad-pod-identity/files/6803117/aad-pod-id.txt)
[AzureIdentityBinding.txt](https://github.com/Azure/aad-pod-identity/files/6803118/AzureIdentityBinding.txt)

**Comment by aramase** [comment]
@shreeshsp `blockInsanceMetadata` needs to be in nmi values. It's `nmi.blockInsanceMetadata=true`. In your terraform file, it's not within nmi.

**Comment by shreeshsp** [comment]
@aramase Oops! my bad ... after moving blockInsanceMetadata to nmi section, access to instance metadata from the pod is getting blocked by NMI 👍
