### ISSUE TITLE
Unable to set tenantID with --set Error: YAML parse error on aad-pod-identity/templates/identities.yaml: error converting YAML to JSON: yaml: line 19: did not find expected ',' or ']'

### ISSUE THREAD

**Issue by Dragonsong3k** [Azure/aad-pod-identity#1109]
**Have you**

- [ x] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [ x] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [x ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**

Trying to use the Helm template installation with the following parameter set:
--set azureIdentities.azure-identity.tenantID=xxxxxxxxx

No matter what format I try to enter the tenantID, I receive 

Error: YAML parse error on aad-pod-identity/templates/identities.yaml: error converting YAML to JSON: yaml: line 19: did not find expected ',' or ']'

**Steps To Reproduce**

Trying to run this full command

` helm upgrade aadpodidentity aad-pod-identity/aad-pod-identity --install --namespace support `
>>                 --set operationMode=managed `
>>                 --set adminsecret.cloud=$($infrastructureMeta.aad_pod_cloud_value.value) `
>>                 --set adminsecret.tenant_id=$($infrastructureMeta.aad_tenant_id.value) `
>>                 --set adminsecret.subscriptionID=$($infrastructureMeta.aad_subscription_id.value) `
>>                 --set adminsecret.resourceGroup=$($infrastructureMeta.resource_group_name.value) `
>>                 --set adminsecret.clientID=$($infrastructureMeta.identity_client_id.value) `
>>                 --set adminsecret.clientSecret=$($infrastructureMeta.identity_client_secret.value) `
>>                 --set adminsecret.useMSI=false `
>>                 --set nmi.allowNetworkPluginKubenet=true `
>>                 --set azureIdentities.azure-identity.namespace=project `
>>                 --set azureIdentities.azure-identity.name=aad-sp-id `
>>                 --set azureIdentities.azure-identity.type=1 `
>>                 --set azureIdentities.azure-identity.clientID=$($infrastructureMeta.identity_client_secret.value) `
>>                 --set azureIdentities.azure-identity.tenantID=xxxxxxxxx `
>>                 --set azureIdentities.azure-identity.clientPassword=$bindingClientPassword `
>>                 --set azureIdentities.azure-identity.binding.name=azure-identity-binding `
>>                 --set azureIdentities.azure-identity.binding.selector=project-sp-secrets`

**Expected behavior**

**AAD Pod Identity version**

4.1.2

**Kubernetes version**

1.21.1

**Additional context**

**Comment by aramase** [comment]
@Dragonsong3k Thank you for reporting the issue.

This seems to be an issue with helm when setting json strings (the clientPassword in case of pod identity charts). The json string is being parsed and converted into an array which is invalid. Ref: https://github.com/helm/helm/issues/5618.

The workaround suggested is to escape the entire string. I've tried that out with the values you provided it works.

```bash
➜ helm upgrade pi aad-pod-identity/aad-pod-identity --set operationMode=managed \
            --set adminsecret.cloud=cloud \
            --set adminsecret.tenant_id=tenantid \
            --set adminsecret.subscriptionID=sub_id \
            --set adminsecret.resourceGroup=rg \
            --set adminsecret.clientID=client_id \
            --set adminsecret.clientSecret=client_secret \
            --set adminsecret.useMSI=false \
            --set nmi.allowNetworkPluginKubenet=true \
            --set azureIdentities.azure-identity.namespace=default \
            --set azureIdentities.azure-identity.name=aad-sp-id \
            --set azureIdentities.azure-identity.type=1 \
            --set azureIdentities.azure-identity.clientID=client_secret_value \
            --set azureIdentities.azure-identity.tenantID=xxxxxxxxx \
            --set azureIdentities.azure-identity.clientPassword="\{\"name\":\"secret\"\,\"namespace\":\"namespace\"\}" \
            --set azureIdentities.azure-identity.binding.name=azure-identity-binding \
            --set azureIdentities.azure-identity.binding.selector=project-sp-secrets
Release "pi" has been upgraded. Happy Helming!
NAME: pi
LAST DEPLOYED: Tue Jul 13 10:16:53 2021
NAMESPACE: default
STATUS: deployed
REVISION: 4
TEST SUITE: None
NOTES:
You have successfully installed AAD Pod Identity in your Kubernetes cluster!

To verify that AAD Pod Identity has started in managed mode, run:
  kubectl --namespace=default get pods -l "app.kubernetes.io/component=nmi"

Now you can follow the demos to get familiar with AAD Pod Identity: https://azure.github.io/aad-pod-identity/docs/demo/
```

This is the special one which escapes the entire string:
```bash
            --set azureIdentities.azure-identity.clientPassword="\{\"name\":\"secret\"\,\"namespace\":\"namespace\"\}" \
```

**Comment by Dragonsong3k** [comment]
Thanks.  

I needed to use a "Verbatim" string in PowerShell with single ticks for the internal \ escaping to work. 

`--set azureIdentities.azure-identity.clientPassword='\{\"name\":\"secret\"\,\"namespace\":\"namespace\"\}'`
