### ISSUE TITLE
Docker file for mcr.microsoft.com/k8s/aad-pod-identity/demo:1.2

### ISSUE THREAD

**Issue by szikk** [Azure/aad-pod-identity#111]
Hello can you provide the docker file for the demo image. 
I want to create my own and I don't know what type of ADAL you have installed on it. 

Thanks

**Comment by kkmsft** [comment]
@szikk : Please find the Dockerfile here: 

https://github.com/Azure/aad-pod-identity/blob/77746b515984125965180efb71f64892c54d3fc2/images/demo/Dockerfile

Closing the issue with this information. Please reopen in case of more questions.
