### ISSUE TITLE
not able to pull the 1.8.1 version image

### ISSUE THREAD

**Issue by mingxiusu** [Azure/aad-pod-identity#1113]
**Have you**

- [ ] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [x] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [x] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
Failed to pull the image mcr.microsoft.com/k8s/aad-pod-identity/nmi:v1.8.1 and mcr.microsoft.com/k8s/aad-pod-identity/mic:v1.8.1
**Steps To Reproduce**
docker pull mcr.microsoft.com/k8s/aad-pod-identity/nmi:v1.8.1 on the pod or from local
**Expected behavior**
image successfully pulled
**AAD Pod Identity version**
1.8.1
**Kubernetes version**
v1.19.11
**Additional context**
I checked the image tags from docker hub as well (https://hub.docker.com/_/microsoft-k8s-aad-pod-identity-nmi), seems the latest tags are not available
![Screenshot 2021-07-16 211850](https://user-images.githubusercontent.com/87397860/126342413-291dc108-e856-4bab-8940-21c4d939ba16.png)

**Comment by aramase** [comment]
@mingxiusu The image registry `mcr.microsoft.com/k8s/aad-pod-identity` is incorrect. The images are at `mcr.microsoft.com/oss/azure/aad-pod-identity` as defined in the yaml and helm charts.

https://github.com/Azure/aad-pod-identity/blob/2b4e9716e2fedf39e53c705cd11007642428e39e/deploy/infra/deployment-rbac.yaml#L597

https://github.com/Azure/aad-pod-identity/blob/2b4e9716e2fedf39e53c705cd11007642428e39e/deploy/infra/deployment-rbac.yaml#L478

**Comment by mingxiusu** [comment]
ahh I see, my bad, our old value file overrides it with the previous registry
