### ISSUE TITLE
PodIdentityAddonUserAssignedIdentitiesNotAllowedInCreation on managedClusters

### ISSUE THREAD

**Issue by andre-lx** [Azure/aad-pod-identity#1123]
**Describe the bug**

Hi. 

Right now, it's impossible to have assigned user assigned identities on arm templates (and terraform) on cluster creation. I already tried a lot of things, and updates works great, after inserting manually with:
```
az aks pod-identity add --cluster-name my-aks-cn --resource-group myrg --namespace myns --name example-pod-identity --identity-resource-id /subscriptions/......
```

But, I want to have this done at once, with the deployment, so I need to insert the pod user identities to the cluster automatically. I also tried to run the command using the `DeploymentScripts` but the deployment scripts are not ready to use `preview aks extersion`.

My config looks like this:

```
    {
      "type": "Microsoft.ContainerService/managedClusters",
      "apiVersion": "2021-02-01",
      "name": "[variables('cluster_name')]",
      "location": "[variables('location')]",
      "dependsOn": [
        "[resourceId('Microsoft.Network/virtualNetworks', variables('vnet_name'))]"
      ],
      "properties": {
....
        "podIdentityProfile": {
        "allowNetworkPluginKubenet": null,
        "enabled": true,
        "userAssignedIdentities": [
            {
            "identity": {
                "clientId": "[reference(resourceId('Microsoft.ManagedIdentity/userAssignedIdentities', 'managed-indentity'), '2018-11-30').clientId]",
                "objectId": "[reference(resourceId('Microsoft.ManagedIdentity/userAssignedIdentities', 'managed-indentity'), '2018-11-30').principalId]",
                "resourceId": "[resourceId('Microsoft.ManagedIdentity/userAssignedIdentities', 'managed-indentity')]"
            },
            "name": "managed-indentity",
            "namespace": "myns"
            }
        ],
        "userAssignedIdentityExceptions": null
        },
....
      },
      "identity": {
        "type": "SystemAssigned"
      }
    },
```

I'm always getting the same issue:

`
        "statusMessage": "{\"error\":{\"code\":\"InvalidTemplateDeployment\",\"message\":\"The template deployment 'deployment_test' is not valid according to the validation procedure. The tracking id is '.....'. See inner errors for details.\",\"details\":[{\"code\":\"PodIdentityAddonUserAssignedIdentitiesNotAllowedInCreation\",\"message\":\"Provisioning of resource(s) for container service cluster-12344 in resource group myrc failed. Message: {\\n  \\\"code\\\": \\\"PodIdentityAddonUserAssignedIdentitiesNotAllowedInCreation\\\",\\n  \\\"message\\\": \\\"PodIdentity addon does not support assigning pod identities on creation.\\\"\\n }. Details: \"}]}}",
`

**Expected behavior**

The cluster is created with the azure managed identity on creation.

Related issue: https://github.com/Azure/AKS/issues/2199

Can you give some help please?

**Comment by aramase** [comment]
@miwithro @bcho

**Comment by miwithro** [comment]
This is a known limitation in the existing configuration.  We will fix this in the V2 implementation.

**Comment by andre-lx** [comment]
Thanks for the quick response @miwithro and @aramase 

Look forward to use that V2. 

Until that, I was trying to create the resources manually, but it only works after the `az aks pod-identity add`.

After cluster creation, I create the the AzureIdentity, AzureIdentityBinding and do the aadpodidbinding on the deployment labels:
```
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: example-pod-identity
  namespace: example_ns
spec:
  clientID: cabe4sdsadsad-11111-11111-111111-11111asdasdc
  resourceID:/subscriptions/...../resourceGroups/...../providers/Microsoft.ManagedIdentity/userAssignedIdentities/example/pod-identity
  type: 0

---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: example-pod-identity-binding
  namespace: ydata
spec:
  azureIdentity: example-pod-identity
  selector: example-pod-identity
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    metadata:
      labels:
        aadpodidbinding: example-pod-identity
```

But this is not working. Well, first, if I run again the template, the AzureIdentity, AzureIdentityBinding got deleted. But that's not hard to fix with some kyverno policy for example that ensures that the resources are always available. 

By the other hand, this only starts to work after run the command:

`
az aks pod-identity add --cluster-name my-aks-cn --resource-group myrg --namespace myns --name example-pod-identity --identity-resource-id /subscriptions/......
`

It looks like that I'm missing some configuration, or binding, or even resource on the cluster.
 

Can you give me some help please?

Thanks

**Comment by andre-lx** [comment]
A few more details on the implementation:

I basically create the cluster with:

```
    {
      "type": "Microsoft.ContainerService/managedClusters",
      "apiVersion": "2021-02-01",
      "name": "[variables('cluster_name')]",
      "location": "[variables('location')]",
      "dependsOn": [
        "[resourceId('Microsoft.Network/virtualNetworks', variables('vnet_name'))]"
      ],
      "properties": {
        "kubernetesVersion": "[variables('cluster_version')]",
        "dnsPrefix": "aks",
        "agentPoolProfiles": [
          {
            .... my pools ....
        ],
        "addonProfiles": {
          "aciConnectorLinux": {
            "enabled": false
          },
          "azurepolicy": {
            "enabled": false
          },
          "httpApplicationRouting": {
            "enabled": false
          },
          "kubeDashboard": {
            "enabled": false
          },
          "omsagent": {
            "enabled": false
          }
        },
        "podIdentityProfile": {
          "enabled": true
        },
        ......
        },
        "apiServerAccessProfile": {
          "enablePrivateCluster": false
        },
        "autoScalerProfile": {
          ...
        }
      },
      "identity": {
        "type": "SystemAssigned"
      }
    },
```

After creation, I can see the `nmi` pods on the kube-system namespace, but no mic pods. 

I also create the managed identities on the arm template.

After running the command:

`
az aks pod-identity add --cluster-name my-aks-cn --resource-group myrg --namespace myns --name example-pod-identity --identity-resource-id /subscriptions/......
`

I can see the `myns`namespace creation, and the AzureIdentity and AzureIdentityBinding.

And using it on the pod with the label: aadpodidbinding, everything works really great. 

I also tried out, running the cluster with the         

``
`
      "podIdentityProfile": {
          "enabled": false
        },
```

and do the installation manually and creating the AzureIdentity and AzureIdentityBinding manually, but nothing seems to work.

**Comment by bcho** [comment]
> A few more details on the implementation:
> 
> I basically create the cluster with:
> 
> ```
>     {
>       "type": "Microsoft.ContainerService/managedClusters",
>       "apiVersion": "2021-02-01",
>       "name": "[variables('cluster_name')]",
>       "location": "[variables('location')]",
>       "dependsOn": [
>         "[resourceId('Microsoft.Network/virtualNetworks', variables('vnet_name'))]"
>       ],
>       "properties": {
>         "kubernetesVersion": "[variables('cluster_version')]",
>         "dnsPrefix": "aks",
>         "agentPoolProfiles": [
>                     {
>             "name": "pool1",
>             "count": 3,
>             "vmSize": "Standard_D8s_v3",
>             "osDiskSizeGB": 128,
>             "osDiskType": "Managed",
>             "kubeletDiskType": "OS",
>             "maxPods": 30,
>             "type": "VirtualMachineScaleSets",
>             "vnetSubnetID": "[resourceId('Microsoft.Network/virtualNetworks/subnets', variables('vnet_name'), 'vnet')]",
>             "maxCount": 20,
>             "minCount": 3,
>             "enableAutoScaling": true,
>             "orchestratorVersion": "[variables('cluster_version')]",
>             "enableNodePublicIP": false,
>             "nodeLabels": {},
>             "mode": "System",
>             "osType": "Linux",
>             "osSKU": "Ubuntu",
>             "enableFIPS": false
>           },
>         ],
>         "addonProfiles": {
>           "aciConnectorLinux": {
>             "enabled": false
>           },
>           "azurepolicy": {
>             "enabled": false
>           },
>           "httpApplicationRouting": {
>             "enabled": false
>           },
>           "kubeDashboard": {
>             "enabled": false
>           },
>           "omsagent": {
>             "enabled": false
>           }
>         },
>         "podIdentityProfile": {
>           "enabled": true
>         },
>         "enableRBAC": false,
>         "networkProfile": {
>           "networkPlugin": "azure",
>           .....
>           },
>         ......
>         },
>         "apiServerAccessProfile": {
>           "enablePrivateCluster": false
>         },
>         "autoScalerProfile": {
>           ...
>         }
>       },
>       "identity": {
>         "type": "SystemAssigned"
>       }
>     },
> ```
> 
> After creation, I can see the `nmi` pods on the kube-system namespace, but no mic pods.
> 
> I also create the managed identities on the arm template.
> 
> After running the command:
> 
> `az aks pod-identity add --cluster-name my-aks-cn --resource-group myrg --namespace myns --name example-pod-identity --identity-resource-id /subscriptions/......`
> 
> I can see the `myns`namespace creation, and the AzureIdentity and AzureIdentityBinding.
> 
> And using it on the pod with the label: aadpodidbinding, everything works really great.
> 
> The nmi pods version installed by default is the v1.7.5. I also tried to update to version v1.8.2, no changes at all.
> 
> I also tried out, running the cluster with the
> 
> ```
>       "podIdentityProfile": {
>           "enabled": false
>         },
> ```
> 
> and do the installation manually and creating the AzureIdentity and AzureIdentityBinding manually, but nothing seems to work.

Setting the `podIdentityProfile.enabled = true` means we will enable the cluster with **managed** pod identity support, in this case:

1. no MIC pod will be created
2. the NMI pod / daemonset is controlled by AKS side, so, manually update the image will not work
3. to create and assign pod identities, we should use `az aks pod-identity add` command

If we set `podIdentityProfile.enabled = false`, this means we will disable the **managed** pod identity addon. If we install the 
 pod identity addon with **standard** mode, we need to 1. deploy the MIC component 2. create pod identity with custom resource

**Comment by andre-lx** [comment]
Thanks @bcho.

Based on your response, I made my implementation as the following:

Create the cluster without the managed pod identity support:

```
        "podIdentityProfile": {
          "enabled": false
        },
```

Then, I made the login to the cluster:

```
az aks get-credentials --name $MY_CLUSTER --resource-group $MY_RG
```

Since I don't have RBAC enabled:

```
az resource show -g $MY_RG -n $MY_CLUSTER --resource-type Microsoft.ContainerService/ManagedClusters --query properties.enableRBAC
> false
```

I made the installation as the docs:

```
For non-RBAC clusters:
kubectl apply -f https://raw.githubusercontent.com/Azure/aad-pod-identity/v1.8.2/deploy/infra/deployment.yaml

# For AKS clusters, deploy the MIC and AKS add-on exception by running -
kubectl apply -f https://raw.githubusercontent.com/Azure/aad-pod-identity/v1.8.2/deploy/infra/mic-exception.yaml
```

And since this is installed in the default namespace:

```
➜ kubectl get pods
NAME                   READY   STATUS    RESTARTS   AGE
mic-6f8c77ff59-fflvb   1/1     Running   0          25s
mic-6f8c77ff59-wr9cp   1/1     Running   0          25s
nmi-2595j              1/1     Running   0          25s
nmi-bg8b2              1/1     Running   0          25s
nmi-gw58k              1/1     Running   0          25s
```

Using the managed identity created in ARM, at the same time as the cluster using the `Microsoft.ManagedIdentity/userAssignedIdentities` type, I create the AzureIdentity and AzureIdentityBinding:

```
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: example-pod-identity
  namespace: myns
spec:
  clientID: cabe4sdsadsad-11111-11111-111111-11111asdasdc
  resourceID:/subscriptions/...../resourceGroups/...../providers/Microsoft.ManagedIdentity/userAssignedIdentities/example-pod-identity
  type: 0
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: example-pod-identity-binding
  namespace: myns
spec:
  azureIdentity: example-pod-identity
  selector: example-pod-identity
```

```
➜  kubectl get AzureIdentity --all-namespaces 
NAMESPACE   NAME                 TYPE   CLIENTID                               AGE
myns       example-pod-identity   0      cabe4sdsadsad-11111-11111-111111-11111asdasdc   7s
➜  kubectl get AzureIdentityBinding --all-namespaces            
NAMESPACE   NAME                         AZUREIDENTITY        SELECTOR             AGE
myns       example-pod-identity-binding   example-pod-identity   example-pod-identity   28s
```

The deployment:

```

```

**Comment by marawan31** [comment]
From what I understand running in managed mode does not require you to have the `Managed Identity Operator` or `Virtual Machine Contributor` role on the cluster, but from the `az aks pod-identity add` command a call is being made to [_ensure_managed_identity_operator_permission](https://github.com/Azure/azure-cli-extensions/blob/main/src/aks-preview/azext_aks_preview/custom.py#L3824) which seems to assign the role  `Managed Identity Operator` to the cluster. Is there a way to not give out this permission to the cluster? If so, do we specifically need to assign each given pod identity to the VMSS/VM as well?

**Comment by miwithro** [comment]
@bcho can you comment?

**Comment by bcho** [comment]
> From what I understand running in managed mode does not require you to have the `Managed Identity Operator` or `Virtual Machine Contributor` role on the cluster, but from the `az aks pod-identity add` command a call is being made to [_ensure_managed_identity_operator_permission](https://github.com/Azure/azure-cli-extensions/blob/main/src/aks-preview/azext_aks_preview/custom.py#L3824) which seems to assign the role `Managed Identity Operator` to the cluster. Is there a way to not give out this permission to the cluster? If so, do we specifically need to assign each given pod identity to the VMSS/VM as well?

Hi @marawan31 , in the managed mode we need this MIO permission to the cluster it's because in managed mode we will use the cluster identity to perform the user identities to VMSS assign operation. We can also assign the role to the managed cluster resource group (so the cluster can inherit from resource group).

This setup is similar to what we do in standard mode: https://azure.github.io/aad-pod-identity/docs/getting-started/role-assignment/ .


FYI, it would better to create a separated issue for new question. 😄
