### ISSUE TITLE
Document the need to create AzureIdentity in the resource group of the cluster's managed identity

### ISSUE THREAD

**Issue by ghost** [Azure/aad-pod-identity#1124]
**Describe the request**
Mention the need to create the User assigned Managed Identity (AzureIdentity) in the auto generated resource group for the cluster's managed identity in the documentation.

**Explain why AAD Pod Identity needs it**
When working through the ["Integrate AKS with Azure KeyVault with AAD pod identity"](https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-integrate-kubernetes#install-azure-active-directory-azure-ad-pod-identity) tutorial for our service, I hit a snag where the MIC did not have the permissions to assign identities on the cluster when using the User assigned managed Identity I had created. 

The solution turned out to be the same as #38 and creating the user assigned managed identity in the auto generated resource group of the cluster's managed identity fixed the problem. IMO this should be mentioned in the documentation as it is a significant road block with not a lot of resources to get over.

**Describe the solution you'd like**
[This section of documentation](https://azure.github.io/aad-pod-identity/docs/demo/standard_walkthrough/#2-create-an-identity-on-azure) is updated to include this information.

**Describe alternatives you've considered**

**Additional context**

**Comment by msft-tacox** [comment]
Hey @bhargav-voleti 

I am confused about this. 

Are you saying that the User Assigned Managed Identity to be used as the Pod Identity must be created in the AKS cluster autogenerated RG? 

_OR_ 

are you saying that the User Assigned Managed Identity that MIC uses to perform Identity Assignment must be created in the AKS cluster autogenerated RG?

If its the former - are you sure you have the right permissions set up? I have been able to use Pod Identity on MSI resources in any RG.

If its the latter - do you know why? Why does it matter what RG the MIC-identity lives in as long as it has "Managed Identity Operator" on the end Identity and "Virtual Machine Contributor" on the MC RG?

**Comment by bhargav-voleti** [comment]
It's the latter, and I'm not entirely sure why, but the MIC was only able to assign identities once I had created the user assigned identity in the auto generated RG.

**Comment by chewong** [comment]
Have you tried following https://azure.github.io/aad-pod-identity/docs/getting-started/role-assignment/
