### ISSUE TITLE
Worker node's IP tables aren't cleaned up after deleting CRDs

### ISSUE THREAD

**Issue by chewong** [Azure/aad-pod-identity#113]
Expected the aad metadata rules to be deleted from worker nodes' ip tables after deleting the CRDs (i.e. `kubectl delete -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml`).
Command executed in worker nodes: `sudo iptable -L -t nat`

**Comment by aramase** [comment]
@kkmsft can you assign this issue to me?
