### ISSUE TITLE
Enabled Managed Identity on AKS cluster and removed the old SPN secret, now it fails to pull tokens.

### ISSUE THREAD

**Issue by PunithKumarB** [Azure/aad-pod-identity#1133]
**Have you**

- [ ] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [ ] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [ ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
Enabled Managed Identity on AKS cluster and removed SP secret, now the PODs fails to pull tokens.

1. Before our AKS was based on Service principal, and we have our monitoring-service POD connects to other Az resources like Key Vault and Kusto DB. It was all working fine.

2. We enabled Managed identities recently and thought the old service principal is not used anymore and deleted the associated secret (just to be on safer side, did not delete the SP directly). After this we see our POD cannot connect to Kusto and KeyVault. 

`
az aks show --subscription "AzD DRP" --resource-group "bright-monitoring-prod-oai-cluster" --name "oai-cluster-cray-services-aks" --query "servicePrincipalProfile"
{
  "clientId": "msi"
}
`

 
3. We We tried restarting VMSS nodes but it does not help. We find below errors ---

**MIC log :**

E0804 22:34:35.914066       1 mic.go:1077] failed to update user-assigned identities on node aks-agentpool-84654957-vmss (add [4], del [0], update[0]), error: failed to update identities for aks-agentpool-84654957-vmss in MC_bright-monitoring-prod-oai-cluster_oai-cluster-cray-services-aks_centralus, error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/83e8cb0f-3f19-4c25-aeb2-3cf17219c6fd/resourceGroups/MC_bright-monitoring-prod-oai-cluster_oai-cluster-cray-services-aks_centralus/providers/Microsoft.Compute/virtualMachineScaleSets/aks-agentpool-84654957-vmss?api-version=2019-07-01: StatusCode=401 -- Original Error: adal: Refresh request failed. Status Code = '401'. Response body: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret is provided.\r\nTrace ID: 3ffc24f3-c65b-4589-ae9c-e7fd1446ad02\r\nCorrelation ID: cf224472-4bba-4fcd-9a9f-31dce780b0c7\r\nTimestamp: 2021-08-04 22:34:35Z","error_codes":[7000215],"timestamp":"2021-08-04 22:34:35Z","trace_id":"3ffc24f3-c65b-4589-ae9c-e7fd1446ad02","correlation_id":"cf224472-4bba-4fcd-9a9f-31dce780b0c7","error_uri":"https://login.microsoftonline.com/error?code=7000215"}

E0804 22:34:35.972586       1 mic.go:1080] failed to get a list of user-assigned identites from node aks-agentpool-84654957-vmss, error: identity info is nil

 
**NMI log :**

I0804 20:26:49.992532       1 server.go:190] status (404) took 100008962132 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.0.39
E0804 20:27:03.207108       1 server.go:369] failed to get matching identities for pod: default/monitoring-54d5d76f4d-k74bh, error: getting assigned identities for pod default/monitoring-54d5d76f4d-k74bh in ASSIGNED state failed after 20 attempts, retry duration [5]s, error: <nil>

 

**Steps To Reproduce**
- Happens every time and even when we try debugging with az login --identity using az-cli pod, same error logs can be found.

**Expected behavior**
- Get token must work after moving to Managed identities. 

**AAD Pod Identity version**
1.6.2

**Kubernetes version**
1.21.1

**Additional context**

**Comment by chewong** [comment]
Could you:
1. spawn a [node shell](https://github.com/kvaps/kubectl-node-shell) to one of your nodes.
2. `cat /etc/kubernetes/azure.json`.
3. verify that the field `useManagedIdentityExtension` is true.
4. verify that `userAssignedIdentityID` is the client ID of your cluster managed identity.

If not, you will have to modify the azure.json with the fields mentioned above, or you can upgrade aad-pod-identity to the latest stable release and see if you are still experiencing the same problem

**Comment by PunithKumarB** [comment]
Thank you @chewong for quick turn around, it worked by modifying the json file !! We do have plan to upgrade aad-pod-identity.
