### ISSUE TITLE
Authentication via Service Account

### ISSUE THREAD

**Issue by moolen** [Azure/aad-pod-identity#1135]
**Describe the request**
As a controller developer i would like to use Kubernetes service accounts to authenticate with azure. With the existing pod identity framework i can already have/use different identities from my controller pod using NMI. However, with this pod-based identity i can not implement multi tenant isolation where identities live in a particular namespace - i would need to create a pod that gets access to temporary credentials using the metadata api.

Other providers ([AWS/IRSA](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/), [GCP/WorkloadIdentity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity)) support credential-less authentication based on Kubernetes `serviceAccounts` via OIDC integration. I want to have something similar to that with azure/aad-pod-identity. 

I can get close to that using Service Principal authentication, however i don't want to manage credentials at all - this should be handled by the trusted platform. Is there a way to do credential-less authentication without having to rely on a pod?

relates to https://github.com/external-secrets/external-secrets/issues/317

**Comment by chewong** [comment]
> Other providers (AWS/IRSA, GCP/WorkloadIdentity) support credential-less authentication based on Kubernetes serviceAccounts via OIDC integration. I want to have something similar to that with azure/aad-pod-identity.

Our v2 solution uses what you describe above. We are actively developing and testing it and hope to open-source it by the end of this year.

**Comment by moolen** [comment]
Thanks for your insights, i'm looking forward to test & integrate v2 ;)
