### ISSUE TITLE
Feature request list/Backlog

### ISSUE THREAD

**Issue by kkmsft** [Azure/aad-pod-identity#114]

**Comment by kkmsft** [comment]
- [ ] VMSS support
- [ ] Crd in other namespaces than default.
- [ ] Use separate sp for MIC(not cluster sp).

**Comment by khenidak** [comment]
ref #115

**Comment by kkmsft** [comment]
Move here: https://github.com/Azure/aad-pod-identity/wiki/Feature-Backlog-list
