### ISSUE TITLE
AAD Pod fails to pull tokens after upgrade to 4.1.3 HELM version. 

### ISSUE THREAD

**Issue by sasound** [Azure/aad-pod-identity#1140]
**Have you**

- [ yes] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [ yes] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [ yes] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
In continuation of https://github.com/Azure/aad-pod-identity/issues/1133 , we are trying to upgrade the AAD pod and remove the workaround that was applied on /etc/kubernetes/azure.json file in each of the VMSS nodes.
After reverting the workaround, performed the AAD Pod upgrade to 4.1.3 version and started to hit the same error.

E0818 09:02:40.954789       1 server.go:378] failed to get matching identities for pod: default/monitoring-5684b49b9c-pndx8, error: getting assigned identities for pod default/monitoring-5684b49b9c-pndx8 in ASSIGNED state failed after 20 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors
...

**Steps To Reproduce**
 - Revert the changes applied to /etc/kubernetes/azure.json 
               "useManagedIdentityExtension": false,
               "userAssignedIdentityID": "",
 - Restarted the VMSS VMs
 - Deployed AAD Pod with version=4.1.3
 - Kubectl logs nmi-pod-name
E0818 09:02:40.954789       1 server.go:378] failed to get matching identities for pod: default/monitoring-5684b49b9c-pndx8, error: getting assigned identities for pod default/monitoring-5684b49b9c-pndx8 in ASSIGNED state failed after 20 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors

**Expected behavior**
 - Kubectl logs nmi-pod-name ## should be showing 200 response code
 
**AAD Pod Identity version**
 4.1.3

**Kubernetes version**
1.21.1

**Additional context**
 - With the workaround in-place, things are happening normally on the upgraded AAD Pod without any issues
 - The AAD pod upgrade is being done as recommended in https://github.com/Azure/aad-pod-identity/issues/1133

**Comment by sasound** [comment]
Do we have to retain the following in azure.json ?, even for the latest AAD Pod versions :

 "useManagedIdentityExtension": true,
    "userAssignedIdentityID": "<clientid-cluster-msi>",

**Comment by aramase** [comment]
@sasound What is it that you're attempting to do? Is the cluster configured to use service principal for auth or managed identity? MIC uses the azure.json file to get the credentials for authentication. If `useManagedIdentityExtension` is set to true and there is `userAssignedIdentityID`, then it'll use that for getting a token and authenticating. If `useManagedIdentityExtension` is false, then it'll use service principal for authentication. 

Check the MIC logs for more specific errors with authentication. 

Also, is this an `aks` or `aks-engine` cluster? Is the cluster being moved from using service principal to managed identities? Could you share the guide you're following for this transition?

**Comment by sasound** [comment]
Hi @aramase ... I gave the previous issue link for more context.
Anyways, I will provide the context again.

Here is the issue : 
 - We have AKS cluster running our deployment
 - The AKS cluster was migrated from SP to MSI. 
 - After this, the AAD NMI pods and MIC pods started to show the error mentioned above.
 - We had filed https://github.com/Azure/aad-pod-identity/issues/1133 and workaround was to manually update the azure.json file
 - The actual solution mentioned in https://github.com/Azure/aad-pod-identity/issues/1133 was to update the AAD pod to 4.1.3 HELM chart version
 - So , I reverted the workaround on azure.json by removing those 2 params. useManagedIdentityExtension=False & userAssignedIdentityID=""
 - Upgraded the AAD pods to 4.1.3  version
 - I Expected the upgrade to 4.1.3 to automatically set those params in the azure.json file  which wasn't the case
 - The error still gets reproduced even after the upgrade.

Qns for you : 
 - Is my expectation wrong ?
 - Are we supposed to manually edit the azure.json file ?

**Comment by sasound** [comment]
@aramase ... any updates on this issue ?

thanks

**Comment by aramase** [comment]
@sasound For AKS clusters, the `azure.json` should not be modified manually. This file is generated as part of cluster bootstrap and is used by pod identity and other cloud provider components. 

The fields relevant for aad-pod-identity in azure.json are:

```json
    "aadClientId": "msi",
    "aadClientSecret": "msi",
```
```json
    "useManagedIdentityExtension": true,
    "userAssignedIdentityID": "",
```

If `useManagedIdentityExtension` is set to true, then we'll use identity to authenticate with azure. The clientID defined in `userAssignedIdentityID` will be used to fetch a token. If `useManagedIdentityExtension` is false, then we'll use service principal for authentication with `aadClientId` as clientID and `aadClientSecret` as clientSecret. 

If you're cluster was migrated to managed identity, then `useManagedIdentityExtension` would be true and `userAssignedIdentityID` would be set to the kubelet-identity on AKS. This should not be manually modified.

**Comment by sasound** [comment]
Hi @aramase ... as i mentioned.
After we migrated to msi, the following is the settings we saw on our AKS cluster.

    "useManagedIdentityExtension": false,
    "userAssignedIdentityID": "",

So as suggested in the https://github.com/Azure/aad-pod-identity/issues/1133 , I have to manually edit these 2 fields for the AAD pod to work.

Now the question is AKS cluster is expected to update these 2 fields automatically ?

**Comment by aramase** [comment]
@sasound Yes, it should be updated by AKS! 

cc @miwithro

**Comment by sasound** [comment]
the issue has been resolved and got clarification from AKS team too.

Thanks @aramse for your help
