### ISSUE TITLE
"Cluster identity has no assignment permission over identity" in external subscription

### ISSUE THREAD

**Issue by johnri** [Azure/aad-pod-identity#1145]
I have a problem adding a pod identity, similar to this one: [Attempting to use an managed identity created in a different subscription from the cluster subscription fails. #1003](https://github.com/Azure/aad-pod-identity/issues/1003)

## Summary
- Cannot add a managed identity from Subscription B to a cluster in Subscription A, even though the cluster's user defined managed identity has the Managed Identity Operator role over both subscriptions. 
- The operation succeeds when the two subs are in our dev (corp) tenant
- The operation fails when the two subs are in our production (AME) tenant

## Details

I'm trying to add three different managed identities to the podidentity profile using an ARM template + ARM deployment. The cluster and the cluster's user-assigned managed identity are in Subscription A. The cluster managed identity has the Managed Identity Operator role over both Subscription A and Subscription B.

Two of the managed identities are also in Subscription A. Adding these two, by themselves, works in all cases. 

One of the managed identities in defined in Subscription B. Adding this one fails with the following message:
```
Cluster identity has no assignment permission over identity 'resourceId: /subscriptions/c57ef400-***/resourceGroups/***-ppe/providers/Microsoft.ManagedIdentity/userAssignedIdentities/***-ppe-app-id-***
```

**But:** The above scenario succeeds if subscriptions A and B are in our DEV (Corporate) tenant. But it fails for Subscription A' and Subscription B' from our PPE (AME) tenant. The RBAC is configured identically in both cases. Weird 😕 

FWIW, I get the same error using `az aks pod-identity add`.

**Comment by bcho** [comment]
Hi @johnri I need more details to investigate, could you open an IcM with your cluster and identities information to AKS? I can start the investigation in there. (My alias: bahe)

**Comment by johnri** [comment]
Sure.
