### ISSUE TITLE
upgrade aad-pod-identity version from 3.0.3 to 4.1.3 causing error

### ISSUE THREAD

**Issue by dawn-chu** [Azure/aad-pod-identity#1146]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [x] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [x] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
following the steps to upgrade aad-pod-identity from 3.0.3 to 4.1.3.
```
kubectl apply -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity/crds/crd.yaml
helm upgrade aad-pod-identity aad-pod-identity/aad-pod-identity
```

seeing errors:
Error: UPGRADE FAILED: cannot patch "azure-identity" with kind AzureIdentity: AzureIdentity.aadpodidentity.k8s.io "azure-identity" is invalid: spec.type: Invalid value: "null": spec.type in body must be of type integer: "null" 
##[error] at AADPodIdentityChartHandler.finish (/src/infrastructure/dist/package-handlers/helm/chart-handler/aadPodIdentityChartHandler.js:23:19) 
##[error] at Helm.installChart (/src/infrastructure/dist/package-handlers/helm/library.js:48:37) 
##[error] at processTicksAndRejections (internal/process/task_queues.js:95:5) 
##[error] at async K8ServiceDeploymentManager.deployHelmChart (/src/infrastructure/dist/deploymentManagers/k8ServiceDeploymentManager.js:418:9) 
##[error] at async K8ServiceDeploymentManager.deployComponent (/src/infrastructure/dist/deploymentManagers/k8ServiceDeploymentManager.js:185:17) 
##[error] at async K8ServiceDeploymentManager.deploy (/src/infrastructure/dist/deploymentManagers/k8ServiceDeploymentManager.js:63:13) 
##[error] at async deployToK8Cluster (/src/infrastructure/dist/common/deploymentHelpers.js:76:5) 
##[error] at async ClusterDeployment.deploy (/src/infrastructure/dist/common/deploymentHelpers.js:36:17) 
##[error] at async /src/infrastructure/dist/deploy.js:136:13

**Steps To Reproduce**

**Expected behavior**

**AAD Pod Identity version**

**Kubernetes version**
 1.20.5
**Additional context**

**Comment by chewong** [comment]
Yes, there is no default value for type and you would have to explicitly configure that.

**Comment by dawn-chu** [comment]
Sure, thanks. Though it is strange it works for al long time without the` type`

**Comment by aramase** [comment]
With the switch to `apiextensions.k8s.io/v1` API version for `CustomResourceDefinition` we added the OpenAPI v3 schema. This enables validation for the field types and values when the custom resource is created. That's the reason it needs to be explicitly set.

**Comment by dawn-chu** [comment]
@aramase  Thanks for the comment. This explains. I'll make the change....
