### ISSUE TITLE
MIC fails to un-assign and remove Azure Assigned Identities that are pending cleanup before shutdown leaving stale resources

### ISSUE THREAD

**Issue by ReinAchten-TomTom** [Azure/aad-pod-identity#1151]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [x] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [x] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**

We are using terraform to deploy an AKS cluster using azurerm provider and use both kubernetes and helm providers to manage the AKS cluster. We install aad-pod-identity using its helm chart. In setting up external dns in the cluster in which we want to use aad-pod-identity, we i.a. deploy a `AzureIdentity` and `AzureIdentityBinding` in a namespace specific for this aspect. After installing ExternalDNS through a helm chart in the same namespace, MIC creates an `AzureAssignedIdentity` resource according to expectations.

In trying to destroy all resources using `terraform destroy`, the process times out trying to terminate the namespace that contains aforementioned `AzureAssignedIdentity` resource. Order in which things are cleaned is as follows (merely indicating relevant parts):

1. Uninstall ExternalDNS using helm chart.
2. Remove `AzureIdentity` and `AzureIdentityBinding` resources related to external DNS
3. Uninstall aad-pod-identity using helm chart.

MIC (leader) last log lines are as follows - it intends to clean un-assigned the identity from the node, but never came to that which likely means the finalizer on the `AzureAssignedIdentity` resource has not been cleared and consequently the resource not deleted. MIC stops "immediately" after logging this:

```
I0830 14:11:00.933233       1 mic.go:648] external-dns-identity identity not found when using kube-addons/external-dns-id-binding binding
I0830 14:11:00.933334       1 mic.go:1036] processing node aks-default-(...)-vmss, add [0], del [1], update [0]
I0830 14:11:00.960377       1 cloudprovider.go:215] updating user-assigned identities on aks-default-(...)-vmss, assign [0], unassign [1]
```

In an attempt to troubleshoot, I added a delay between deletion of ExternalDNS related resources and aad-pod-identity. This seems to pose a rather simple, but nasty workaround for the problem at hand and as such one I'd like to avoid if possible. Logging of the MIC leader in that case looks as follows - note that it effectively unassigned the identity ~11s later:

```
10826 13:44:32.572142       1 mic.go:608] No AzureIdentityBinding found for pod kube-addons/external-dns-694d55db68-cmlng that matches selector: external-dns. it will be ignored
I0826 13:44:32.572224       1 mic.go:1036] processing node aks-default-98993367-vmss, add [0, del [1, update [0]
I0826 13:44:32.601378       1 cloudprovider.go:215] updating user-assigned identities on aks-default-98993367-vmss, assign [0], unassign [1]
I0826 13:44:43.233123       1 crd.go:777] updating AzureAssignedIdentity kube-addons/external-dns-694d55db68-cmlng-kube-addons-external-dns-identity status to Unassigned
I0826 13:44:43.275868       1 mic.go:525] work done: true. Found 1 pods, 1 ids, 0 bindings
I0826 13:44:43.275934       1 mic.go:526] total work cycles: 34, out of which work was done in: 2
```

I noticed the [Unable to remove AzureAssignedIdentity after MIC pods are deleted](https://azure.github.io/aad-pod-identity/docs/troubleshooting/#unable-to-remove-azureassignedidentity-after-mic-pods-are-deleted) article in the troubleshooting guide, which is related. I can get the destroy to commence if I clear the finalizers section as suggested there.

Note that my understanding might obviously be incorrect and consequently this not a bug. Please enlighten me if that's the case! Any help is appreciated :pray: 

**Steps To Reproduce**

I've simplified things a little - hope it suffices. We are using terraform, but I have no reason to believe this is due to terraform specifics. Then again I might be wrong :)

1. Spin up AKS cluster 
2. Setup roles required for 
3. Install aad-pod-identity using helm chart
4. Deploy `AzureIdentity` and `AzureIdentityBinding` for ExternalDNS 
5. Install ExternalDNS using helm chart
6. Tear down things in reverse order.

**Expected behavior**
MIC un-assigns and removes Azure Assigned Identities that are pending cleanup immediately before shutting down.

**AAD Pod Identity version**
1.8.1 (through helm chart 4.1.2)

**Kubernetes version**
1.20.7

**Comment by phillipgibson** [comment]
@ReinAchten-TomTom does Terraform provide a log when using the terraform destroy command? If it does are you able to provide it?

**Comment by aramase** [comment]
@ReinAchten-TomTom The MIC component in pod identity assigns the identity to the underlying VMSS when the first pod using the identity is created and unassigns the identity when the last pod using the identity is deleted. This assign/unassign operation is equivalent to `az vmss identity assign|unassign`. This PATCH request could take 10s-1m. MIC adds a [finalizer](https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/) to the `AzureAssignedIdentity` to prevent deletion of it before the identity is unassigned. This is the expected flow:

1. Delete `AzureIdentity`, `AzureIdentityBinding` and pod
2. Wait for `AzureAssignedIdentity` to be deleted
3. Delete aad-pod-identity components

If you wish to skip the wait for identity to be unassigned and want to force delete the `AzureAssignedIdentity` please check out: https://azure.github.io/aad-pod-identity/docs/troubleshooting/#unable-to-remove-azureassignedidentity-after-mic-pods-are-deleted

**Comment by ReinAchten-TomTom** [comment]
Thanks for the quick responses, guys!

@aramase, thanks for elaborating! I take it the expected flow depicted in your answer is a deliberate decision? From an aad-pod-identity user-perspective, would be nice if we could skip (2) :) - I mean, if MIC is responsible for managing the lifecycle of AzureAssignedIdentity, why can't it wait for pending unassign request(s) to complete and remove the assigned identities as part of its shutdown procedure? (just curious)

**Comment by ReinAchten-TomTom** [comment]
@aramase gentle reminder :point_up: Thnx!

**Comment by aramase** [comment]
@ReinAchten-TomTom We can certainly look into running the sync loop one last time when MIC starts terminating. Note, this would still only help with scenarios where MIC is gracefully terminated. If the MIC pods are force deleted, then the `AzureAssignedIdentities` will still be find.

**Comment by ReinAchten-TomTom** [comment]
@aramase thanks for the update! We have worked around things for now by making the kubernetes namespace(s) dependent on our aad-pod-identity terraform module. This ensures aad-pod-identity is uninstalled only after those namespace(s) has / have successfully been deleted, which means MIC gets sufficient time to remove pending AzureAssignedIdentity resources.

Such a dependency is not intuitive unless one understands the intricacies of aad-pod-identity, so adding a final sync loop as part of MIC's graceful (clear that it will not help in case of non-graceful shutdowns) shutdown procedure would be appreciated. I might contribute myself at a later stage.
