### ISSUE TITLE
Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request

### ISSUE THREAD

**Issue by sasound** [Azure/aad-pod-identity#1152]
**Have you**

- [ ] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [ ] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [ ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
Getting token from pod fails.
we are using[ Default Azure Credential (python) ](https://docs.microsoft.com/en-us/python/api/azure-identity/azure.identity.defaultazurecredential?view=azure-python)  in the code to fetch the managed identity credential. This is the error log from the same.

Failed: No valid token received. EnvironmentCredential: Incomplete environment configuration.. ImdsCredential: Unexpected response '{'error': 'invalid_request', 'error_description': 'Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request'}'

The issue is intermittent. Restarting the pod / redeploying mitigates it.
What is the cause and resolution for this?

The issue was already raised in https://github.com/Azure/aad-pod-identity/issues/1084 but was closed due to a lower AAD pod version. 
Now even after upgrading to 4.1.3 HELM chart version , still hitting the same error

**Steps To Reproduce**

**Expected behavior**

**AAD Pod Identity version**
helm chart 4.1.3

**Kubernetes version**
1.20.7

**Additional context**
Our AKS cluster-size=3 and The NMI pods are running as a daemonset .
I am attaching the logs from each of the NMI pod and MIC pod

[mni-pod-1.txt](https://github.com/Azure/aad-pod-identity/files/7083798/mni-pod-1.txt)
[mic-pod-2.txt](https://github.com/Azure/aad-pod-identity/files/7083800/mic-pod-2.txt)
[mic-pod-1.txt](https://github.com/Azure/aad-pod-identity/files/7083801/mic-pod-1.txt)
[mni-pod-3.txt](https://github.com/Azure/aad-pod-identity/files/7083802/mni-pod-3.txt)
[mni-pod-2.txt](https://github.com/Azure/aad-pod-identity/files/7083803/mni-pod-2.txt)

**Comment by chewong** [comment]
Based on the error, have you tried specifying the client ID of the managed identity when calling `DefaultAzureCredential`?

**Comment by sasound** [comment]
Hi @chewong ... by "client ID of the managed identity " are you referring to the MSI from the AKS cluster ?
We do have a "bm-prod-oai-cluster-mi" that is used for accessing the Kusto DB and the AKV. This value is currently being passed into our code .

**Comment by chewong** [comment]
The error suggests that the node that your workload got scheduled to has multiple identities assigned to it. Have you tried `DefaultAzureCredential(managed_identity_client_id=<client id of your desired>)`?

**Comment by sasound** [comment]
@chewong ...
 - The issue is seen on AKS prod cluster and adding the clientID toDefaultAzureCredential  would imply lot of code changes on our side. So I haven't tried setting managed_identity_client_id. 
 -  I wanted to clearly understand the issue and the absolute need for this code change to be implemented.

For your query on the node where these workloads are scheduled , we see the following value in azure.json and there hasn't been any change to it for the past 1 month. The values remain the same on all the 3 nodes of the AKS cluster

-----------------------------------------------------
"cloud": "AzurePublicCloud",
"tenantId": "33e01921-4d64-4f8c-a055-5bdaffd5e33d",
"subscriptionId": "83e8cb0f-3f19-4c25-aeb2-3cf17219c6fd",
"aadClientId": "msi",
"aadClientSecret": "msi",

...

"useManagedIdentityExtension": true,
"userAssignedIdentityID": "2cb9bab8-a68f-44a8-21322a8e9d16",
-----------------------------------------------------

**Comment by sasound** [comment]
@chewong ... are there any other files that could have been used for getting the Assigned Identity values ?

**Comment by chewong** [comment]
The azure.json file isn't related to the issue. It just describes what credential your cluster is using. Is your workload running on host network by any chance?

**Comment by sasound** [comment]
Hi @chewong ... Can you add further details around what you mean by "workload running on host network ?"

**Comment by chewong** [comment]
https://kubernetes.io/docs/concepts/policy/pod-security-policy/#host-namespaces

The error that you had might be due to host network being enabled so I was wondering if that's the case.

**Comment by sasound** [comment]
Hi @chewong ... No we don't enable HostNetwork in any of our pods except for the geneva daemonset ( [link](https://dev.azure.com/msazure/One/_git/Compute-Runtime-Tux-GenevaContainers?path=%2Fdocker_geneva_samples%2FAKSGenevaSample%2FREADME.md) )

**Comment by chewong** [comment]
@aramase any idea why this could happen?

**Comment by sasound** [comment]
@aramase ... I have already attached the NMI and MIC pod logs from the timestamp to this bug.
Since the issue was repro-ed on PROD setup, we have already mitigated by restarting the pod.

**Comment by chewong** [comment]
I took a second look at the log and I don't see any relevant errors. Since the error is not part of the NMI log, I am suspecting that the token request is not originated from NMI.

AAD Pod Identity defaults to the client ID defined in your AzureIdentity as part of the token request to IMDS if you don't specify a client ID in your Default Azure Credential. Based on your log, the identity with a client ID starting with 588a is used for authentication:

```
I0831 08:54:00.770244       1 standard.go:179] matched identityType:0 clientid:588a##### REDACTED #####146c resource:https://ingest-bmprodoaicluster.centralus.kusto.windows.net
```


* What's the name of the affected pod (Is it `monitoring-54cc9b7fc7-bkmgh`?)
* Could you share a code snippet on how your application uses the default azure credential?
* Could you share additional stack trace?

**Comment by sasound** [comment]
Hi @aramase  / @chewong ... I was out sick and also had issues with my SAW. So couldn't respond appropriately.
I will share the details that you have asked.

**Comment by sasound** [comment]
> I took a second look at the log and I don't see any relevant errors. Since the error was not part of the NMI log, I am suspecting that the token request was not originated from NMI.
> 
> AAD Pod Identity defaults to the client ID defined in your AzureIdentity as part of the token request to IMDS if you don't specify a client ID in your Default Azure Credential. Based on your log, the identity with a client ID starting with 588a is used for authentication:
> 
> ```
> I0831 08:54:00.770244       1 standard.go:179] matched identityType:0 clientid:588a##### REDACTED #####146c resource:https://ingest-bmprodoaicluster.centralus.kusto.windows.net
> ```
> 
> * What's the name of the affected pod (Is it `monitoring-54cc9b7fc7-bkmgh`?)
yes
> * Could you share a code snippet on how your application uses the default azure credential?
I am not getting this question. Which default azure credential you are asking here ?
> * Could you share additional stack trace?
Are you talking about the stack trace from the code ?. All the error that was gathered is already shared in the ticket.
Since the issue is intermittent and not consistent, getting the trace again might be difficult

**Comment by andyw248** [comment]
I just experienced the same issue. I have one additional detail that may or may not have been present in sasound's case.

Scenario:
Before running into this issue I had enabled the "Insights" feature (i.e. Log Analytics) for the affected cluster. After a few minutes, horizontal auto-scaling tried to create new pods, and they failed with the same error that is discussed here.

Managed Identities:
I found that enabling "Insights" had silently created another managed identity in the VMSS resource group. This is how it looks like:
- Resource group: MC_GuestConfigCluster_guestconfigcluster_[region]
- Existing managed identity: guestconfigcluster-agentpool
- New managed identity: omsagent-guestconfigcluster

Maybe sasound had enabled Insights as well when this happened?

**Comment by sasound** [comment]
@andyw248 ... thnx for your input.
I will have to check on this.

Will revert in a day

**Comment by jdimmerman** [comment]
@sasound @andyw248 Any further update here?

About a week ago, I ran into the exact issue as @andyw248 described it - We have 3 clusters. We enabled the "insights" feature on a single cluster. Shortly after doing so, we started to run into this issue only on that one cluster when attempting to refresh the token during our deployment process (during which we refresh secrets from Key Vault). We saw the same omsagent managed identity created. Upon disabling insights a few days ago, the oms agent managed identity was deleted but we are still experiencing this issue.

**Comment by zouyc1990** [comment]
We ran into similar issue as @@andyw248 @jdimmerman  described it. The Azure design concept was so crazy that one resource had 2 identities, which was unimaginable in AWS，May I ask who has the solution? Our production business is broken down now

**Comment by aramase** [comment]
> We ran into similar issue as @@andyw248 @jdimmerman described it. The Azure design concept was so crazy that one resource had 2 identities, which was unimaginable in AWS，May I ask who has the solution? Our production business is broken down now

Multiple managed identities can be assigned to the single VMSS resource. If there are multiple identities, then the client_id of the identity for which a token is required needs to be sent as part of the request. There is an option to pass the clientID parameter in all the SDKs.

Speaking for pod identity, we default to first client ID based on the `AzureIdentity` that matches the pod. If you're not using pod identity or the request is directly being sent to IMDS, then the client ID needs to be explicitly specified when there are multiple identities.

**Comment by jdimmerman** [comment]
@zouyc1990 - Exactly, all we needed to do was add the client ID to our helm charts. For us, that meant adding `userAssignedIdentityID` parameter for our `SecretProviderClass` resource

**Comment by ankur8** [comment]
for me also this error is reported in agic ingress controller logs after i upgrade to agic 1.5.2 and with aadpodidentity version 1.6.3

E0922 14:33:16.419671       1 client.go:170] Code="ErrorApplicationGatewayUnexpectedStatusCode" Message="Unexpected status code '400' while performing a GET on Application Gateway." InnerError="azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/-4ca0-9571-626b22a1a6cf/resourceGroups/***23-dcp-aks-rg/providers/Microsoft.Network/applicationGateways/***-p-content-apgw?api-version=2021-03-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request"} Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%!A(MISSING)%!F(MISSING)%!F(MISSING)management.azure.com%!F(MISSING)"
I0922 14:33:16.419691       1 retry.go:33] Retrying in 10s
E0922 14:33:26.480421       1 client.go:170] Code="ErrorApplicationGatewayUnexpectedStatusCode" Message="Unexpected status code '400' while performing a GET on Application Gateway." InnerError="azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/****/resourceGroups/****-aks-rg/providers/Microsoft.Network/applicationGatewaysd-content-apgw?api-version=2021-03-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request"} Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%!A(MISSING)%!F(MISSING)%!F(MISSING)management.azure.com%!F(MISSING)"

**Comment by eranbar** [comment]
we are running into the same issue here.
we added new node pool to our cluster then the issue started.
i will be glad to understand how to resolve this issue, up until now we had only one node pool and multiple managed identity so when doing new DefaultazureCredentials without providing any id worked for us.

**Comment by ankur8** [comment]
I resolved it

From: eranbar ***@***.***>
Date: Tuesday, 22 November 2022 at 3:54 PM
To: Azure/aad-pod-identity ***@***.***>
Cc: Ankur ***@***.***>, Comment ***@***.***>
Subject: Re: [Azure/aad-pod-identity] Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request (#1152)

we are running into the same issue here.
we added new node pool to our cluster then the issue started.
i will be glad to understand how to resolve this issue, up until now we had only one node pool and multiple managed identity so when doing new DefaultazureCredentials without providing any id worked for us.

**Comment by eranbar** [comment]
Can you please share how did you solve this issue?

**Comment by ankur8** [comment]
Add these two yaml exception to your namespace like kube-system or where your ingress controller are installed

 please apply the yaml as the following and observe the MIC logs

apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzurePodIdentityException
metadata:
  name: mic-exception
  namespace: default
spec:
  podLabels:
    app: mic
    component: mic
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzurePodIdentityException
metadata:
  name: aks-addon-exception
  namespace: kube-system
spec:
  podLabels:
    kubernetes.azure.com/managedby: aks





From: eranbar ***@***.***>
Date: Tuesday, 22 November 2022 at 4:25 PM
To: Azure/aad-pod-identity ***@***.***>
Cc: Ankur ***@***.***>, Comment ***@***.***>
Subject: Re: [Azure/aad-pod-identity] Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request (#1152)
Can you please share how did you solve this issue?

**Comment by ankur8** [comment]
Above solve mine as after lot of dig i got to know that there is no more exception in my mic log but i missed these exception so tried above and resolved till now no restart but yes we have to move to workload identity

**Comment by eranbar** [comment]
So, if I understand it right you added those 2 yamls under the required NS and this gave you additional information how to resolve the issue?
In addition, did you have to move to work load identity due to this issue?

Thanks,

**Comment by ankur8** [comment]
No we will move and have to as no more support from azure on this project

From: eranbar ***@***.***>
Date: Tuesday, 22 November 2022 at 4:36 PM
To: Azure/aad-pod-identity ***@***.***>
Cc: Ankur ***@***.***>, Comment ***@***.***>
Subject: Re: [Azure/aad-pod-identity] Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request (#1152)
So, if I understand it right you added those 2 yamls under the required NS and this gave you additional information how to resolve the issue?
In addition, did you have to move to work load identity due to this issue?

Thanks,

**Comment by eranbar** [comment]
Thanks for your reply, just want to verify, does adding AzurePodIdentityException yaml solved your issue? If so, can you please explain how did it solve your issue?

**Comment by husain021995** [comment]
I managed to sort this error..

The simple solution is as you might be using multiple node pools so each node pool must have system assigned identity enabled. In order to do that:

Go to individual VMSS in the infrastructure resource group  ---> identity --> system assigned  --> ON

This will assign your nodepools a system assigned identity.
For me I was integrating with Key vault so I added the object ID of the identity in the keyvault and it worked

**Comment by NikolayBieliashov** [comment]
> I just experienced the same issue. I have one additional detail that may or may not have been present in sasound's case.
> 
> Scenario: Before running into this issue I had enabled the "Insights" feature (i.e. Log Analytics) for the affected cluster. After a few minutes, horizontal auto-scaling tried to create new pods, and they failed with the same error that is discussed here.
> 
> Managed Identities: I found that enabling "Insights" had silently created another managed identity in the VMSS resource group. This is how it looks like:
> 
> * Resource group: MC_GuestConfigCluster_guestconfigcluster_[region]
> * Existing managed identity: guestconfigcluster-agentpool
> * New managed identity: omsagent-guestconfigcluster
> 
> Maybe sasound had enabled Insights as well when this happened?

Hi! How did you resolve those issue? I did the same and have this error. What should I do if I what to keep Insights?

**Comment by NikolayBieliashov** [comment]
I added AZURE_CLIENT_ID with specifying client ID from my identity (I chose not an omsagnet one) and it's working fine.
