### ISSUE TITLE
MSI endpoint not available in some nodes 

### ISSUE THREAD

**Issue by midhun-mohan** [Azure/aad-pod-identity#1154]
**Describe the bug**
We are using aad-pod-identity in our cluster. Setup is working fine for more than an year now. But suddenly in some of the nodes we started seeing issues when pods started up. 
On inspecting the logs from nmi pod on the same node, below where the error.  Below behavior is completely random and particular to only some nodes in the cluster

```
1 standard.go:179] matched identityType:0 clientid:******************************** resource:https://vault.azure.net
E0906 10:40:34.581881       1 server.go:392] failed to get service principal token for pod:*************************************, error: failed to refresh token, error: the MSI endpoint is not available. Failed HTTP request to MSI endpoint: Get http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01: context deadline exceeded
I0906 10:40:34.581959       1 server.go:199] status (403) took 500686197 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.211.6.10
```

I tried creating a support ticket and after some of the trouble shooting section, support engineer found that the ip tables rules was not set.  Is this somehow related to the error metadata endpoint is not available ? 
The response from the support Engineer : 
```
", it seems the rule for 169.254.169.254 was not set to intercept the traffic to NMI pod, We suggest to compare the 169.254.169.254 rule with the iptables output on the “working” node?
-A aad-metadata ! -s 127.0.0.1/32 -d 169.254.169.254/32 -p tcp -m tcp --dport 80 -j DNAT [unsupported revision]
-A aad-metadata -j RETURN
"
```

**Steps To Reproduce**

Since this is completely Random, I am not entirely sure how i can reproduce this error. But one thing is once the error started happening in any of the node, the node never recovers from it.

**Expected behavior**
Works Every time

**AAD Pod Identity version**
we are using version 1.8.2

**Kubernetes version**
1.21.2

**Additional context**
The error which we had observed where on spot instances in Azure. Not sure if it is only in Spot instances. This is just FYI.

**Comment by aramase** [comment]
@midhun-mohan Thanks for reporting the issue. Is this issue on all the spot instances or just some? Also, what's the iptables version in the working and non-working node?

**Comment by midhun-mohan** [comment]
@aramase Nope. This is not an issue on every spot instances. Just some of the nodes in our cluster.  we had 22 spot instances at a point and 2 of them where having this issue. 

we used iptables-save in the cluster node that is not working (on 7th of september) and from the output from it, the version is `iptables-save v1.6.1` . 

The cluster where having multple issues with pod identity being very unstable and also ACR integration, we provisioned a new cluster and switched the traffic over. so i am not able to get hold of the node that was not working as the cluster auto scaler removed it from the cluster.

**Comment by aramase** [comment]
@midhun-mohan we had similar issue internally that I was investigating. It turned out IMDS was unreachable because the [wireserver](https://docs.microsoft.com/en-us/azure/virtual-network/what-is-ip-address-168-63-129-16) wasn't running on the node. This is not a specific pod identity issue. Could you provide the node details when the issue occurs again? We can then forward the details to the wireserver team for investigation.

**Comment by aramase** [comment]
cc @rkammara12

**Comment by midhun-mohan** [comment]
@aramase I was also suspecting an issue with the metadata endpoint. Sure will provide the details of the node if the issue occurs again. How should i provide the resourceid and node name if issue occurs again ? do you need it via a support ticket.

**Comment by midhun-mohan** [comment]
@aramase I have now found out a node in one of my lower environment which is having this error. Interestingly this is also a spot node. 
Let me know how should i share the resourceid / name of the node in the cluster so that wireserver team can investigate more. 

Also i did checked logs for the past 7 days and i have only seen this error in spot instances in azure.

**Comment by midhun-mohan** [comment]
@aramase Will be great if you can give me your email where i can share the ResourceIDs.

**Comment by aramase** [comment]
@midhun-mohan Do you still have the support ticket open? If yes, you can add the resourceID to that and share the case number.

**Comment by midhun-mohan** [comment]
@aramase Here is the support ticket number. #2109050050000256. Let me know if you need more details.

**Comment by aramase** [comment]
Thanks for the support ticket number. I got the resource ID from the support engineer and will forward them to the wireserver team. Also, the next time the issue happens, could you get on the node and try to ping the IMDS endpoint? `ping 169.254.169.254`.

**Comment by aramase** [comment]
@midhun-mohan The IMDS team confirmed the issue was with wireserver and the node was unhealthy from 09/08 to 09/14. The node is fixed now. If you hit the issue again, try `ping 169.254.169.254` from the node with issue. If that fails, then open a support ticket and we can route that to the wireserver team.

**Comment by midhun-mohan** [comment]
@aramase That is great. Was that a bug in the wireserver? Was the root cause fixed? 
Also it will be great if you can provide me an overview of what the issue was  :)

**Comment by aramase** [comment]
@midhun-mohan yeah, the issue was with wireserver. The regression was caught by the team and the rollout was stopped. The regression causes wireserver to crash during startup and fail to run. As wireserver is down, IMDS can't be reached. The next time the issue happens, you can get on the node and try `ping 169.254.169.254`. If there is no response, then I would recommend opening a support ticket that can be routed to the appropriate team.

**Comment by mxrss2** [comment]
@aramase what is the bug or issue number tracked on their github because this might be impacting us as well - would like to be able to track it to see if this showed at about the time we started to have major issues. Link would be greatly appreciated.

**Comment by aramase** [comment]
> @aramase what is the bug or issue number tracked on their github because this might be impacting us as well - would like to be able to track it to see if this showed at about the time we started to have major issues. Link would be greatly appreciated.

@mxrss2 This is an internal issue and is not tracked in github. If you're facing similar issues and see `ping 169.254.169.254` fail from the node, please open a support ticket. The wireserver team would use that for investigation and resolution. 

If you're able to ping, then it might not be the same issue.

**Comment by mxrss2** [comment]
@aramase first off thank you for replying. 

I can not ping but i can curl the endpoint / tested pinging some known ip and cant get a response so i don't think ping is a good diagnostic. -- I believe some type of ICMP firewall is enabled --

**Comment by annerajb** [comment]
Yeah I tried pinging and it hangs but a curl to port 80 instantly returns bad request.
