### ISSUE TITLE
AAD pod Identity in a Cluster AKS with Kubenet

### ISSUE THREAD

**Issue by calvinShan** [Azure/aad-pod-identity#1157]
Hello , 

I have a question about kubenet, based on these articles 
https://azure.github.io/aad-pod-identity/docs/configure/aad_pod_identity_on_kubenet/ 
https://docs.microsoft.com/en-au/azure/governance/policy/concepts/policy-for-kubernetes 

We could not deploy AAD pod Identity in a Cluster with Kubenet.  I have tried and the NMI pods are on status **CrashOff**. 
In this situation, how can we use managed identity to request token from azure ad and communicate with other resources  in Azure? 

If there is no other way, it proposed to add the ConstraintTemplate of type K8sPSPCapabilities in the cluster.  In order to do that, 
1 how to Activate Gatekeeper in AKS? 
2 After configuring K8sPSPCapabilities with NET_RAW capability, the NMI servers could be running? 
3 If it is complexed, how could we use managed identity within the network mode kubenet, any other solutions please. 

Thanks

**Comment by chewong** [comment]
Have you tried setting the `--allow-network-plugin-kubenet=true` arg in the NMI container or `--set nmi.allowNetworkPluginKubenet=true` if deploying with Helm?

**Comment by calvinShan** [comment]
> Have you tried setting the `--allow-network-plugin-kubenet=true` arg in the NMI container or `--set nmi.allowNetworkPluginKubenet=true` if deploying with Helm?

Yes, i have tried this. And it seems like ok but, it is not recommanded at all. In this document, it proposed to add the ConstraintTemplate of type K8sPSPCapabilities in the cluster, for the issues of security. we need to activate gatekeeper. But how to do that exactly?
thanks

**Comment by chewong** [comment]
1. You should be able to follow https://docs.microsoft.com/en-au/azure/governance/policy/concepts/policy-for-kubernetes#install-azure-policy-add-on-for-aks to enable gatekeeper for your AKS cluster. Alternatively, you can check out https://github.com/open-policy-agent/gatekeeper for the open-source solution.
2. You'd have to deploy aad-pod-identity to kube-system since the [policy](https://azure.github.io/aad-pod-identity/docs/configure/aad_pod_identity_on_kubenet/) excludes kube-system namespace.
3. No other solution for now.

**Comment by calvinShan** [comment]
> 1. You can follow https://docs.microsoft.com/en-au/azure/governance/policy/concepts/policy-for-kubernetes#install-azure-policy-add-on-for-aks to enable gatekeeper for your AKS cluster. Alternatively, you can check out https://github.com/open-policy-agent/gatekeeper for the open-source solution.
> 2. No, you'd have to re-deploy aad-pod-identity to kube-system since the [policy](https://azure.github.io/aad-pod-identity/docs/configure/aad_pod_identity_on_kubenet/) excludes kube-system namespace.
> 3. No other solution for now.

@chewong  Thanks for your reply.
So we after enabling gatekeeper and configuring K8sPSPCapabilities  for AKS, the pods about AAD pod Identity could be running automatically?

Do we still need to set --set nmi.allowNetworkPluginKubenet=true by deploying NMI with Helm? 
The question is about the way to correct the status of NMI pods

Thanks

**Comment by chewong** [comment]
If you deploy aad-pod-identity to kube-system with `--set nmi.allowNetworkPluginKubenet=true`, it should work. Gatekeeper and the K8sPSPCapabilities template we provided are separate components that mitigate the vulnerability we described in [here](https://azure.github.io/aad-pod-identity/docs/configure/aad_pod_identity_on_kubenet/#why-this-change) at a cluster level.

**Comment by calvinShan** [comment]
@chewong thanks for your reply.

We have well deployed NMI and MIC on AKS with --set nmi.allowNetworkPluginKubenet=true.  Based on this article, we have deployed the pod demo: https://docs.microsoft.com/en-au/azure/aks/use-azure-ad-pod-identity

However, it does not work at all : 

kubectl logs aad-pod-identity-nmi-99r6m 
```
E0911 15:06:57.154136       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.6/tools/cache/reflector.go:156: Failed to watch *v1.AzurePodIdentityException: failed to list *v1.AzurePodIdent
ityException: Get "https://10.0.0.1:443/apis/aadpodidentity.k8s.io/v1/azurepodidentityexceptions?resourceVersion=9037500": dial tcp 10.0.0.1:443: connect: connection refused
E0911 15:07:04.673404       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.6/tools/cache/reflector.go:156: Failed to watch *v1.AzureAssignedIdentity: failed to list *v1.AzureAssignedIden
tity: Get "https://10.0.0.1:443/apis/aadpodidentity.k8s.io/v1/azureassignedidentities?labelSelector=nodename%3Daks-nodepool1-32828295-vmss000001&resourceVersion=9037500": dial tcp 10.0.0.1:4
43: connect: connection refused
E0911 15:07:05.366458       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.6/tools/cache/reflector.go:156: Failed to watch *v1.AzurePodIdentityException: failed to list *v1.AzurePodIdent
ityException: Get "https://10.0.0.1:443/apis/aadpodidentity.k8s.io/v1/azurepodidentityexceptions?resourceVersion=9037500": dial tcp 10.0.0.1:443: connect: connection refused
E0911 15:07:06.176008       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.6/tools/cache/reflector.go:156: Failed to watch *v1.Pod: failed to list *v1.Pod: Get "https://10.0.0.1:443/api/
v1/pods?fieldSelector=spec.nodeName%3Daks-nodepool1-32828295-vmss000001&resourceVersion=9754238": dial tcp 10.0.0.1:443: connect: connection refused
```

kubectl logs aad-pod-identity-mic-f7cd576b4-gmjfc
```
E0902 16:39:21.338014       1 leaderelection.go:329] error initially creating leader election record: endpoints "aad-pod-identity-mic" already exists
E0911 15:07:05.709177       1 leaderelection.go:325] error retrieving resource lock default/aad-pod-identity-mic: Get "https://10.0.0.1:443/api/v1/namespaces/default/endpoints/aad-pod-identi
ty-mic": dial tcp 10.0.0.1:443: connect: connection refused
```
What do these errors about pls?

Thanks a lot

**Comment by chewong** [comment]
Could you follow https://azure.github.io/aad-pod-identity/docs/demo/standard_walkthrough/ instead? https://docs.microsoft.com/en-au/azure/aks/use-azure-ad-pod-identity is a bit outdated and it is meant for managed aks add-on only. If you are using the open-source solution (this repo), you should check out the first link.

**Comment by calvinShan** [comment]
@chewong  Thanks for your reply, after following the article  https://azure.github.io/aad-pod-identity/docs/demo/standard_walkthrough/ .

I have still some errors as bellow:
kubectl logs demo:
E0915 16:37:14.743923       1 main.go:65] failed to refresh the service principal token, error: adal: Failed to execute the refresh request. Error = 'context deadline exceeded'

kubecl logs NMI:
```
915 16:33:13.786221       1 client.go:208] list pod error: pod list is empty. Retrying, attempt number: 1
W0915 16:33:14.086801       1 client.go:208] list pod error: pod list is empty. Retrying, attempt number: 2
E0915 16:34:33.786017       1 server.go:378] failed to get matching identities for pod: default/demo, error: context canceled
I0915 16:34:33.786095       1 server.go:199] status (404) took 79999921111 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.1.103
W0915 16:34:33.788059       1 server.go:343] parameter resource cannot be empty
```

kubectl logs MIC
```
 1 mic.go:1453] failed to generate identity assignment state, error: failed to get a list of user-assigned identites from node aks-nodepool1-32828295-vmss, error: 
failed to get identity resource, error: failed to get vmss aks-nodepool1-32828295-vmss in resource group MC_***, error: failed to
 get vmss aks-nodepool1-32828295-vmss in resource group MC_***, error: azure.BearerAuthorizer#WithAuthorization: Failed to refres
h the Token for request to https://management.azure.com/subscriptions/***/resourceGroups/MC_***/
providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool1-32828295-vmss?api-version=2019-07-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = '
Post "https://login.microsoftonline.com/e4e1abd9-eac7-4a71-ab52-da5c998aa7ba/oauth2/token?api-version=1.0": dial tcp: i/o timeout'
I0915 16:38:35.733249       1 mic.go:1036] processing node aks-nodepool1-32828295-vmss, add [0], del [0], update [1]
```

I have already assigned the role: az role assignment create --role "Virtual Machine Contributor" --assignee "$IDENTITY_CLIENT_ID" --scope $NODES_RESOURCE_ID

What is the problem please

**Comment by chewong** [comment]
Did you assign "Managed Identity Operator" to the identity as well?

**Comment by calvinShan** [comment]
@chewong how to assign "Managed Identity Operator" to the identity, do you mean assigne the role 'Managed Identity Operator' to the identity for which ressource?  
who : managed identity 
what : Managed Identity Operator
where: ?
It is for which ressource please?

**Comment by chewong** [comment]
You can run the script in https://azure.github.io/aad-pod-identity/docs/getting-started/role-assignment/ to automate your all role assignments for your managed identity-enabled AKS cluster.

**Comment by calvinShan** [comment]
@chewong Thanks for your help

Do you know how can I use pod identity to authenticate cosmosdb and eventhub.
I know I need to assign the roles and set aadpodidbinding in the deployment.yaml.

But how to develop the fonction(.net/java) to use this aadpodid in order to access to cosmosdb please?

Thanks

**Comment by chewong** [comment]
You can follow our Java example: https://azure.github.io/aad-pod-identity/docs/demo/java-blob/. All you need to add in your application is the [`DefaultAzureCredential`](https://github.com/Azure/aad-pod-identity/blob/master/examples/java-blob/src/main/java/com/microsoft/cse/storageexample/config/BlobConfigLoader.java#L29-L31), which uses the underlying identity you defined to authenticate your application.
