### ISSUE TITLE
Support for Managed Mode without forceNamespaced

### ISSUE THREAD

**Issue by bdschaap** [Azure/aad-pod-identity#1162]
Can you tell me when Managed Mode will be supported without the forceNamespaced argument?  I'd like my aad pod identity resources to all be in a single namespace instead of across many.

**Comment by aramase** [comment]
@bdschaap There is no plan to support managed mode without force namespaced. It's best practice to have the custom resources namespaced scope. For standard mode, it's not default because force namespaced was introduced in a later release and we don't want to break existing users. The recommendation for standard mode is also to use pod identity in force namespaced mode to prevent unauthorized access of identities by workloads across all namespaces.

**Comment by aramase** [comment]
cc @bcho

**Comment by bdschaap** [comment]
Thanks for the feedback.  I can understand that perspective but I believe it assumes namespaces are being used as a security boundary.  I would to suggest allowing it as an opt-in feature and noting the security implications in the documentation.

**Comment by aramase** [comment]
> Thanks for the feedback. I can understand that perspective but I believe it assumes namespaces are being used as a security boundary. I would to suggest allowing it as an opt-in feature and noting the security implications in the documentation.

Without namespaced mode, any pod will have access to any identity in the cluster. This would just become similar to not having pod identity in the cluster as all managed identities are now accessible by all pods.

Given the best practice is to keep CRDs namespaced and namespace being the security boundary for pod identity, I don't think we want to support non namespaced option in managed mode.

**Comment by bdschaap** [comment]
Thank you.  Hoping that providing a little more context on our use case may help.

We currently use AAD Pod Identity for both on-prem and AKS clusters in Azure.  AAD Pod Identity supports our on-prem use case by providing managed identity authentication tied to service principals.  The pod would only have access to a different identity if a change was made and then went through a deployment pipeline and both require reviews/approvals.
