### ISSUE TITLE
Upgrading 1.5.5 to 1.8.4 version.

### ISSUE THREAD

**Issue by pipezapata1986** [Azure/aad-pod-identity#1168]
Hi, I have to upgrade the version mentioned on the title for a production environment. are there any known issues with this procedure? do you have any advice? thank you very much!

**Comment by aramase** [comment]
You can review the [changelog](https://azure.github.io/aad-pod-identity/changelog/) and the [breaking changes](https://azure.github.io/aad-pod-identity/docs/#breaking-changes) to make the necessary changes as you upgrade from an older version to the latest.
