### ISSUE TITLE
Which AKS security restrictions can be applied to Pod Identity containers?

### ISSUE THREAD

**Issue by joecanman** [Azure/aad-pod-identity#1171]
I'm eager to know which restrictions can be applied to the Pod Identity containers (MIC / NMI) without resulting in any impact
- can they be run as non-root?
- can be be run in non-privileged mode?
- Can they be set with a read only file system?
- Do they need the Service Account Token mounted?
regards

**Comment by aramase** [comment]
> can they be run as non-root?

Both MIC and NMI needs to run as root. MIC needs to access `/etc/kubernetes/azure.json` and NMI need root permissions to modify iptables on the host.

> can be be run in non-privileged mode?

MIC and NMI run in non-privileged mode.

> Can they be set with a read only file system?

Yes, read only file system should be sufficient.

> Do they need the Service Account Token mounted?

Yes, service account token is required to be able to communicate with the kube-apiserver.
