### ISSUE TITLE
Migrating from Standard to Managed Mode

### ISSUE THREAD

**Issue by tshaiman** [Azure/aad-pod-identity#1172]
Please add remark / explanation whether the manual-mode role assignments described here :
https://azure.github.io/aad-pod-identity/docs/getting-started/role-assignment/#performing-role-assignments
are still required.

I think that Virtual Machine Contributor role can be skipped when working in Managed-Mode.

**Comment by aramase** [comment]
If you're migrating from standard to managed mode following this doc: https://azure.github.io/aad-pod-identity/docs/configure/standard_to_managed_mode/ then no role assignments are required. The role assignment in the above doc are only required for standard mode as MIC component will assign/un-assign the identity. In [managed mode](https://azure.github.io/aad-pod-identity/docs/configure/pod_identity_in_managed_mode/) there is no MIC.

Thanks for the feedback. We'll add a note in the role assignment doc to say role assignment not required for OSS managed mode.
