### ISSUE TITLE
Error in MIC pod

### ISSUE THREAD

**Issue by nasimkhli** [Azure/aad-pod-identity#1174]
**Describe the bug**
I am seeing the following error in MIc log:
pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.AzureIdentityBinding: failed to list *v1.AzureIdentityBinding: Get "https://10.0.0.1:443/apis/aadpodidentity.k8s.io/v1/azureidentitybindings?resourceVersion=73508366": dial tcp 10.0.0.1:443: connect: connection refused
E1004 18:10:29.377273       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.AzureIdentity: failed to list *v1.AzureIdentity: Get "https://10.0.0.1:443/apis/aadpodidentity.k8s.io/v1/azureidentities?resourceVersion=73466745": dial tcp 10.0.0.1:443: connect: connection refused
E1004 18:10:29.403906       1 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://10.0.0.1:443/api/v1/nodes?resourceVersion=73764615": dial tcp 10.0.0.1:443: connect: connection refused
I1004 18:10:56.788883       1 mic.go:1449] reconciling identity assignment for [/subscriptions/{}/resourcegroups/{}/Microsoft.ManagedIdentity/userAssignedIdentities/{}/subscriptions/{}/resourcegroups/{}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/{}] on node aks-agentpool-{}-vmss

**Steps To Reproduce**

**Expected behavior**
To see the MIC is running fine.

**AAD Pod Identity version**
v1.7.1

**Kubernetes version**
1.18.10

**Additional context**

**Comment by aramase** [comment]
Chatted with @nasimkhli on teams.

1. `v1.7.1` is an old version of aad-pod-identity. Recommended upgrading to the latest and see if the issue is resolved.
2. If issue persists after upgrade, open a support ticket with AKS to debug connection failure to kube-apiserver.

**Comment by aramase** [comment]
> What does it mean when it update the AzureAssignedIdentity to unassigned?

`AzureAssignedIdentity` is created to map the status of the `AzureIdentity` with the pod. It gets set to `Unassigned` when either the pod/AzureIdentity/AzureIdentityBinding are deleted.

Ref: https://azure.github.io/aad-pod-identity/docs/concepts/

**Comment by nasimkhli** [comment]
The issue is we can't hit our services endpoint in k8s starting 9/30 and we did not change anything in our cluster.
So, I started looking into logs.
our pods under our namespace show they are running fine and I don't see any error in our services pod log.
I looked at the nmi log and I don't see any issue with getting token, the following is what I see:
I1005 18:50:18.240866       1 main.go:87] starting nmi process. Version: v1.8.4. Build date: 2021-09-16-23:40.
I1005 18:50:18.240936       1 main.go:100] features for scale clusters enabled
I1005 18:50:18.351318       1 crd.go:448] CRD lite informers started
I1005 18:50:18.351530       1 main.go:114] running NMI in namespaced mode: false
I1005 18:50:18.351634       1 nmi.go:53] initializing in standard mode
I1005 18:50:18.351737       1 probes.go:41] initialized health probe on port 8085
I1005 18:50:18.351824       1 probes.go:44] started health probe
I1005 18:50:18.352027       1 metrics.go:341] registered views for metric
I1005 18:50:18.352198       1 prometheus_exporter.go:21] starting Prometheus exporter
I1005 18:50:18.352289       1 metrics.go:347] registered and exported metrics on port 9090
I1005 18:50:18.352486       1 server.go:105] listening on port 2579
W1005 18:50:18.566502       1 iptables.go:123] flushing iptables to add aad-metadata custom chains
I1005 18:54:09.470603       1 server.go:365] exception pod kube-system/omsagent-vqndn token handling
I1005 18:54:09.470621       1 server.go:308] fetching token for user assigned MSI for resource: https://monitoring.azure.com/
I1005 18:54:09.619374       1 server.go:199] status (200) took 148858787 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.8.36
I1005 19:25:09.481602       1 server.go:365] exception pod kube-system/omsagent-vqndn token handling
I1005 19:25:09.481621       1 server.go:308] fetching token for user assigned MSI for resource: https://monitoring.azure.com/
I1005 19:25:09.564756       1 server.go:199] status (200) took 83190620 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.8.36
I1005 19:55:10.271125       1 server.go:365] exception pod kube-system/omsagent-vqndn token handling
I1005 19:55:10.271149       1 server.go:308] fetching token for user assigned MSI for resource: https://monitoring.azure.com/
I1005 19:55:10.396469       1 server.go:199] status (200) took 125400508 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.8.36
I1005 20:26:10.074805       1 server.go:365] exception pod kube-system/omsagent-vqndn token handling
I1005 20:26:10.074824       1 server.go:308] fetching token for user assigned MSI for resource: https://monitoring.azure.com/
I1005 20:26:10.159874       1 server.go:199] status (200) took 85115424 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.8.36
I1005 20:57:10.438760       1 server.go:365] exception pod kube-system/omsagent-vqndn token handling
I1005 20:57:10.438912       1 server.go:308] fetching token for user assigned MSI for resource: https://monitoring.azure.com/
I1005 20:57:10.596088       1 server.go:199] status (200) took 157448467 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.8.36
I1005 21:27:11.004823       1 server.go:365] exception pod kube-system/omsagent-vqndn token handling
I1005 21:27:11.004845       1 server.go:308] fetching token for user assigned MSI for resource: https://monitoring.azure.com/
I1005 21:27:11.094599       1 server.go:199] status (200) took 89831800 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.8.36

Then I looked at the MIC log and I see the following:

1005 19:17:22.691473       1 mic.go:1040] processing node aks-agentpool-[number]-vmss, add [0], del [1], update [0]
I1005 19:17:22.691511       1 cloudprovider.go:186] No identities to assign or un-assign
I1005 19:17:22.691531       1 crd.go:777] updating AzureAssignedIdentity default/apisecurityrp-deployment-[number]-apisecurityrp-rp-client-principal status to Unassigned
I1005 19:17:22.749252       1 mic.go:525] work done: true. Found 6 pods, 2 ids, 2 bindings
I1005 19:17:22.749272       1 mic.go:526] total work cycles: 114, out of which work was done in: 6
I1005 19:17:22.749280       1 stats.go:183] ** stats collected **
I1005 19:17:22.749285       1 stats.go:162] Pod listing: 44.502µs
I1005 19:17:22.749293       1 stats.go:162] AzureIdentity listing: 17.501µs
I1005 19:17:22.749297       1 stats.go:162] AzureIdentityBinding listing: 5.7µs
I1005 19:17:22.749301       1 stats.go:162] AzureAssignedIdentity listing: 26.001µs
I1005 19:17:22.749305       1 stats.go:162] System: 174.508µs
I1005 19:17:22.749308       1 stats.go:162] CacheSync: 8.501µs
I1005 19:17:22.749313       1 stats.go:162] Cloud provider GET: 0s
I1005 19:17:22.749317       1 stats.go:162] Cloud provider PATCH: 0s
I1005 19:17:22.749320       1 stats.go:162] AzureAssignedIdentity creation: 0s
I1005 19:17:22.749324       1 stats.go:162] AzureAssignedIdentity update: 0s
I1005 19:17:22.749328       1 stats.go:162] AzureAssignedIdentity deletion: 33.065954ms
I1005 19:17:22.749332       1 stats.go:170] Number of cloud provider PATCH: 0
I1005 19:17:22.749336       1 stats.go:170] Number of cloud provider GET: 0
I1005 19:17:22.749340       1 stats.go:170] Number of AzureAssignedIdentities created in this sync cycle: 0
I1005 19:17:22.749343       1 stats.go:170] Number of AzureAssignedIdentities updated in this sync cycle: 0
I1005 19:17:22.749347       1 stats.go:170] Number of AzureAssignedIdentities deleted in this sync cycle: 1
I1005 19:17:22.749351       1 stats.go:162] Find AzureAssignedIdentities to create: 12.901µs
I1005 19:17:22.749355       1 stats.go:162] Find AzureAssignedIdentities to delete: 21.001µs
I1005 19:17:22.749358       1 stats.go:162] Total time to assign or update AzureAssignedIdentities: 57.772915ms
I1005 19:17:22.749362       1 stats.go:162] Total: 58.384144ms
I1005 19:17:22.749367       1 stats.go:212] *********************
I1005 19:19:47.663677       1 mic.go:1466] reconciling identity assignment for [/subscriptions/[subId]/resourcegroups/[rg]/providers/Microsoft.ManagedIdentity/userAssignedIdentities/rp-client-principal /subscriptions/[subid]/resourcegroups/[rg]/providers/Microsoft.ManagedIdentity/userAssignedIdentities/client-principal] on node aks-agentpool-[number]-vmss
I1005 19:22:47.629795       1 mic.go:1466] reconciling identity assignment for [/subscriptions/[subId]/resourcegroups/[rg]/providers/Microsoft.ManagedIdentity/userAssignedIdentities/client-principal /subscriptions/[subId]/resourcegroups/[rg]/providers/Microsoft.ManagedIdentity/userAssignedIdentities/rp-client-principal] on node aks-agentpool-30985909-vmss

So, I can't figure out what the root cause is. I was wondering if you could take a look at these logs and let me know what's wrong with the set up.

**Comment by nasimkhli** [comment]
closing the issue.
