### ISSUE TITLE
Error in pod identity binding

### ISSUE THREAD

**Issue by nasimkhli** [Azure/aad-pod-identity#1181]
**Describe the bug**

I can not deploy to the cluster , the pod stays at containerCreation status. I did the describe on the pod and I got the following:
 Warning  FailedMount  43m (x9 over 58m)     kubelet            MountVolume.SetUp failed for volume "" : rpc error: code = Unknown desc = failed to mount secrets store objects for pod [], err: rpc error: code = Unknown desc = failed to mount objects, error: failed to get keyvault client: failed to get key vault token: nmi response failed with status code: 404, err: <nil>

And in the describe of pod identity binding I see the following:

Warning  binding apply error  3m41s (x565 over 14h)  aadpodidentity.k8s.io  (combined from similar events): 
failed to apply binding [] node aks-agentpool-[] for pod [], error: failed to update identities for aks-agentpool-[] in MC_[], error: azure.BearerAuthorizer#WithAuthorization: 
Failed to refresh the Token for request to https://management.azure.com/subscriptions/e[]/resourceGroups/[]/providers/Microsoft.Compute/virtualMachineScaleSets/aks-agentpool-[]?api-version=2019-07-01: 
StatusCode=401 -- Original Error: adal: Refresh request failed. Status Code = '401'. 
Response body: {"error":"invalid_client","error_description":"AADSTS7000222: 
The provided client secret keys are expired. 
Visit the Azure Portal to create new keys for your app, or consider using certificate credentials for added security: https://docs.microsoft.com/azure/active-directory/develop/active-directory-certificate-credentials\r\nTrace ID: e41f3310-ff29-44ba-927b-d477a20d5400\r\nCorrelation ID: 00a0eec0-c23f-40b0-9580-82444616e7a5\r\nTimestamp: 2021-10-13 16:43:31Z","error_codes":[7000222],"timestamp":"2021-10-13 16:43:31Z","trace_id":"e41f3310-ff29-44ba-927b-d477a20d5400","correlation_id":"00a0eec0-c23f-40b0-9580-82444616e7a5","error_uri":"https://login.microsoftonline.com/error?code=7000222"}

But the thing is it is managed identity, I am not sure what does "create new key" here mean. 

Can you please take a look and let me know what the issue is?

AAD Pod Identity version
v1.8

Kubernetes version
1.18.10

**Additional context**

**Comment by aramase** [comment]
Could you get on the host and get the `/etc/kubernetes/azure.json` file? MIC uses the `azure.json` to determine if it needs to use SP/user-assigned managed identity/system-assigned managed identity to assign/un-assign identities on the VM/VMSS.

**Comment by hazzik** [comment]
Getting similar issue started today.

**Comment by ghostika** [comment]
I also started to have this issue since yesterday. I have v1.8.5. I tried to do a `cat /etc/kubernetes/azure.json` in `nmi` and `mic` pods, but I didn't found any file. 
Because of this issue the app-gatway-ingress-conroller doesn't work and I have to manually update the IPs of the new pods.

**Comment by chewong** [comment]
@hazzik & @ghostika do you have an AKS cluster or other type of cluster?

**Comment by ghostika** [comment]
@chewong yes, I have 2 Aks cluster, where I use this. Interestingly, in one cluster I saw the error, but the sync with the appgw still worked, in the other one it stopped working.

**Comment by ghostika** [comment]
@nasimkhli for me the problem was the expired token for my AKS cluster. You have to renew it yearly, but the problem only arise, when one of my nodes died and a new instance of `agic` was created and that one wasn't able to connect with appgw.

Maybe this will help you also: https://docs.microsoft.com/en-us/azure/aks/update-credentials
