### ISSUE TITLE
container images are not pinned

### ISSUE THREAD

**Issue by KnicKnic** [Azure/aad-pod-identity#1189]
Container images should include the sha256 so that if there is a supply chain attack users are less vulnerable.

https://github.com/Azure/aad-pod-identity/blob/0fbc00f8b572ee780199ddb4489a94f1f01d3815/charts/aad-pod-identity/values.yaml#L44-L46

**Comment by aramase** [comment]
@KnicKnic Thank you for the feedback. We'll add the `version@sha` for the image tag.

**Comment by aramase** [comment]
The image is built after the release and tag is cut, so we don't know the sha at the time of the release. The tag in helm charts is configurable, so can be set when deploying. 

I think this is something that can be accomplished with `gatekeeper` + https://github.com/sozercan/tagToDigest-provider with the new external mutation capability in the future.

cc @sozercan

**Comment by aramase** [comment]
Going to close this issue now as there is no further action.
