### ISSUE TITLE
Assign manage identity fails

### ISSUE THREAD

**Issue by RomanDvorsky** [Azure/aad-pod-identity#1192]
**Have you**

- [ ] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [ ] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [ ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
The manage identity is not assigned when there are multiple services using manage identity and one service has wrong configuration.

**Steps To Reproduce**
have service A and B.
configure wrong service A:
```yaml
  podIdentity:
    clientID: something which does not exists
    enabled: true
    resourceID: /subscriptions/<subcription id>/resourceGroups/rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity
```
configure service B correctly.

**Expected behavior**
Identity for service A is not assigned, however for service B is assigned correctly.

**AAD Pod Identity version**
    chart: aad-pod-identity/aad-pod-identity
    version: 4.1.4

**Kubernetes version**
1.19.13

**Additional context**
Seems that there is alphabetical order to process identity and once the higher identity assign crash the rest is never processed.

service errors: 
```
Unhandled exception. Azure.Identity.AuthenticationFailedException: ManagedIdentityCredential authentication failed: Retry failed after 4 tries. Retry settings can be adjusted in ClientOptions.Retry. (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.)
```

mic pod logs:
```
E1116 11:00:07.343470       1 mic.go:1107] failed to update user-assigned identities on node aks-primary-xxxx-vmss (add [4], del [0], update[0]), error: failed to get identity resource, error: failed to get vmss aks-primary-xxxx-vmss in resource group MC_Rxxxxx, error: VMSSGet client throttled, retry after: 2021-11-16 11:01:30.671527551 +0000 UTC m=+160986.513418635
E1116 11:00:07.343497       1 mic.go:1110] failed to get a list of user-assigned identites from node aks-primary-39285164-vmss, error: failed to get identity resource, error: failed to get vmss aks-primary-xxxxx-vmss in resource group MC_xxxx, error: VMSSGet client throttled, retry after: 2021-11-16 11:01:30.671527551 +0000 UTC m=+160986.513418635
```

**Comment by chewong** [comment]
It looks like the Azure client in MIC was throttled, meaning there were too many requests made and you can't make additional requests until a certain period of time. 

AAD Pod Identity assigns identities in batches instead of serially to minimize the number of identity assignment requests made to Azure. MIC should omit identities with erroneous resource IDs from the batch and retry but I am not sure if it will retry on incorrect client IDs. I'd suggest temporarily removing that particular AzureIdentity or correct the client ID.

**Comment by RomanDvorsky** [comment]
Well, the thing is that we do run multiple services on one aks cluster. Each service has a different team behind it. 
Each team is encapsulated in its own namespace to minimize the risk to disrupt other services.
But this bug is quite unpleasant because one service (one team) can disrupt the whole cluster and other teams as well.
Luckily we have discovered this on the testing cluster but imagine a situation when one wrong service destroys scaling on the live cluster (no new identity no scaling!).

Currently, I have no idea how to systematically solve this risk.

**Comment by RomanDvorsky** [comment]
Any news, ideas regarding this bug?

**Comment by chewong** [comment]
> the whole batch seems to fail - in case of error you should try it one by one

That isn't scalable and will also cause throttling faster in the case of hundreds or thousands of identities, which is why we switched to batch-assigning instead since it will only require one API call. In addition, due to the architecture design, if one of the identities  (out of our control)

> you should add some circuit breaker there - like do retry, next retry with a longer period after certain retries stop to retry given identity till new deploy or some other trigger you have there (to avoid throttling)

We already have built-in logic to apply delays in case of throttling.

Could you share your MIC logs by any chance? I'd like to see what caused the throttling.

**Comment by RomanDvorsky** [comment]
sure, can I send you those logs in any private way? thx, R.

**Comment by chewong** [comment]
You can create a github repo / fork this repo, make it private, and grant read access to me.

**Comment by chewong** [comment]
Did you modify the syncRetryDuration flag to 1 second? With no new pods, MIC attempts to run the sync loop every hour instead of every second. With this many API calls and identities, it will get throttled easily.

Also, incorrect client ID in AzureIdentity shouldn't cause an error when assigning the identity to the VMSS. Did you ensure that the resource ID of the identity in AzureIdentity is correct?

**Comment by RomanDvorsky** [comment]
> Did you modify the syncRetryDuration flag to 1 second? With no new pods, MIC attempts to run the sync loop every hour instead of every second. With this many API calls and identities, it will get throttled easily.

nope I did change anything like this - standard helm installation without any additional configuration

> Also, incorrect client ID in AzureIdentity shouldn't cause an error when assigning the identity to the VMSS and the error in your log does not appear to be related to client ID, but instead subscription ID. Did you ensure that the resource ID of the identity in AzureIdentity is correct?

well actually this is the issue - I did fix it afterwards but the problem is that we have many teams and mistakes can happen which is a quite unpleasant situation that one team can destroy the whole cluster. I have no idea how to check such a mistake - how can I validate the resource id before it gets broken or even after it gets broken - how can I get notified that the identity is throttling...

**Comment by chewong** [comment]
Currently, there is no way we can validate the resource ID of the identity until we tried to assign it to the node. We could technically do a GET operation to see if we get a 404 but that will also cause throttling very easily when you have a lot of identities. You can programmatically get the resource ID with `az identity show -g ... -n ... --query id -otsv` to minimize human errors.

**Comment by RomanDvorsky** [comment]
yep, of course, we have an exact tutorial but anyway it happens - now we are facing this risk which we would like to minimize - we are not able to validate therefore the logical step is whether the service can survive such an error - from my perspective it could react better - wdyt?

**Comment by chewong** [comment]
Yes, there is definitely room to improve, which is why we are launching v2 of pod identity at the beginning of next year where we completely got rid of the identity assignment step.

**Comment by RomanDvorsky** [comment]
ok, so we will pay attention and wait for the next version - is it possible to be assigned to preview of v2? we could use it on our testing clusters...

**Comment by chewong** [comment]
Unfortunately, a preview won't be available. However, as I mentioned above, we will open-source the next iteration of aad-pod-identity at the beginning of next year to the general public.
