### ISSUE TITLE
What extra work is needed to support non-aks, non-aks-engine k8s cluster hosted in azure?

### ISSUE THREAD

**Issue by mingaliu** [Azure/aad-pod-identity#1193]
**Describe the request**
For the cluster setup (for example, using kubeadm), what is required to use aad-pod-identity?

From https://azure.github.io/aad-pod-identity/docs/getting-started/role-assignment/, 
   _If you deploy the VMs and install Kubernetes instead of using tools like aks-engine or capz, you’ll need to assign the user-assigned managed identity to the underlying VMs.__
Is "assign the user-assigned managed identity to the underlying VMs" the only requirement?

**Explain why AAD Pod Identity needs it**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chewong** [comment]
If you are using helm to install aad-pod-identity, you will have to deploy it using a service principal and fill out [these values](https://github.com/Azure/aad-pod-identity/blob/master/charts/aad-pod-identity/values.yaml#L28-L40).

**Comment by mingaliu** [comment]
@chewong,  the question is whether we can use aad-pod-identity in manually created cluster in azure. (no, I am not using helm, why this is related to helm?)

**Comment by chewong** [comment]
The answer is yes you can as long as you have access to IMDS. Here are the steps you can follow:
1. create [`/etc/kubernetes/azure.json`](https://kubernetes-sigs.github.io/cloud-provider-azure/install/configs/) in each node if it doesn't exist. This file contains the configuration needed to authenticate with Azure.
2. If you are not creating `/etc/kubernetes/azure.json`, then you can manually create a service principal to authenticate aad pod identity with Azure. You can check out https://azure.github.io/aad-pod-identity/docs/configure/deploy_aad_pod_dedicated_sp/ or my above comment on how to deploy aad-pod-identity with a dedicated service principal.
