### ISSUE TITLE
Vulnerabilities found in NMI 1.8.0

### ISSUE THREAD

**Issue by mkroitor2** [Azure/aad-pod-identity#1194]
Our scans found the below:

Debian has released security update for lz4 to fix the vulnerabilities.<P><BR><BR>Note: The preceding description block is extracted directly from the security advisory. Using automation, we have attempted to clean and format it as much as possible without introducing additional issues.Malicious users could use this vulnerability to change partial contents or configuration on the system. Additionally this vulnerability can also be used to cause a limited denial of service in the form of interruptions in resource availability.

Which NMI version is taking care of this vulnerability?
Debian Security Update for lz4 (DSA 4919-1)

**Comment by aramase** [comment]
@mkroitor2 The latest available release for aad-pod-identity is `v1.8.5` and there are no vulnerabilities in that release images. Please upgrade to the latest available release.

```shell
➜ trivy --exit-code 1 --ignore-unfixed --severity MEDIUM,HIGH,CRITICAL mcr.microsoft.com/oss/azure/aad-pod-identity/nmi:v1.8.5
2021-11-18T17:09:39.543Z	INFO	Need to update DB
2021-11-18T17:09:39.543Z	INFO	Downloading DB...
24.80 MiB / 24.80 MiB [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 13.48 MiB p/s 2s
2021-11-18T17:09:43.527Z	INFO	Detected OS: debian
2021-11-18T17:09:43.527Z	INFO	Detecting Debian vulnerabilities...
2021-11-18T17:09:43.536Z	INFO	Number of language-specific files: 1
2021-11-18T17:09:43.536Z	INFO	Detecting gobinary vulnerabilities...

mcr.microsoft.com/oss/azure/aad-pod-identity/nmi:v1.8.5 (debian 11.0)
=====================================================================
Total: 0 (MEDIUM: 0, HIGH: 0, CRITICAL: 0)


bin/nmi (gobinary)
==================
Total: 0 (MEDIUM: 0, HIGH: 0, CRITICAL: 0)
```
