### ISSUE TITLE
Migration step not clear

### ISSUE THREAD

**Issue by tshaiman** [Azure/aad-pod-identity#1196]
1. in the migration doc : 
there is this section 

"Assign the pod identities to the VM/VMSS" which is not clear :
1. why are we doing this ? isnt the new managed mode supposed to handle this ? 
2. Will this be required AFTER the migration when adding new Node Pools ?
3. After all if you re-install your service after the migration , and part of your installation also has "AzureIdentity" and "AzureIdentityBinding" , isnt that Sufficient ?

**Comment by aramase** [comment]
> why are we doing this ? isnt the new managed mode supposed to handle this ?

Assigning identities is only handled in standard mode. There is no MIC in managed mode which means the identities need to be manually assigned by the user. If you're referring the AKS managed pod-identity addon, then `az vmss identity assign` isn't required. But if you're just installing aad-pod-identity in managed mode from this repo, then identity assignment needs to be manually performed.

> Will this be required AFTER the migration when adding new Node Pools ?

Could you please provide more info on what migration you're doing? Are you migrating from `standard` mode to `managed` mode from this repo or migrating from `standard` mode to [AKS managed pod-identity addon](https://docs.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity)?

> After all if you re-install your service after the migration , and part of your installation also has "AzureIdentity" and "AzureIdentityBinding" , isnt that Sufficient ?

There is no difference in AzureIdentity and AzureIdentityBinding for any of the modes. If you're switching to managed mode, then just have the identities assigned and the existing config will work. In standard mode, MIC is the component that assigns the identity based on the AzureIdentity and AzureIdentityBinding. In managed mode, there is no MIC.

**Comment by tshaiman** [comment]
Thank you very much for the details explanation Anish. 
yes , I was referring to the migration between manual mode and managed-aad-pod-identity from the git-hub repo ,not from the AKS Add on.
Actually I never though there is a difference between the two, but you have clarified that when using this repo then assigning the identity with "az vmss identity assign" is required.
this means that it will be required for ANY use case that uses this repo, either migrated or not : but the steps to run this AZ CLI command only appears on the migration docs , thus letting the user think that its only valid when doing migration.
according to what you explained, and correct me if I'm wrong, this will be required anyhow since MIC is not present.
I think if this is the case then this section should appear on the managed-mode page and not on the migration page.

having said that, it does feel "half-managed" and not "managed" since we do have to patch the VMSS each time we change node pool on our AKS cluster, and forgetting to do this for new NodePool will result breaking changes. 

Did I got that right ?
