### ISSUE TITLE
Is aad-pod-identity supports Azure Key Vault Provider for Secrets Store CSI Driver?

### ISSUE THREAD

**Issue by dmakeienko** [Azure/aad-pod-identity#1197]
Hello, 
we are actively using aad-pod-identity to access Azure resources but now we want to also use the Azure Key Vault Provider for Secrets Store CSI Driver to read secrets into pods directly from Key Vault. 
As of now, it is possible with the add-on https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver
THe question is, is it possible to use it in conjunction with the aad-pod-identity (not an add-on)? 
The only documents that i've found refer to AAD Pod Identity **Add-On** as a prerequisite. https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-identity-access

I have tried to experiment with it but stuck on a step when I now have 2 different identities that should be assigned to pod (which is might be incorrect) 
Is there any documentation or is anyone tried it? Is it possible at all?

**Comment by aramase** [comment]
Hello 👋🏻 

In the docs link you shared, there is a reference in usage to setup the pod identity using the AKS addon: https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-identity-access#usage. If you're using aad-pod-identity from open-source, there are instructions in the project on how to get started: https://azure.github.io/secrets-store-csi-driver-provider-azure/configurations/identity-access-modes/pod-identity-mode/

**Comment by dmakeienko** [comment]
Thank you for help, this issue is indeed can be closed.

**Comment by aramase** [comment]
Thank you for confirming. Closing this issue now.
