### ISSUE TITLE
mic restarting often (lost leader lease)

### ISSUE THREAD

**Issue by deyanp** [Azure/aad-pod-identity#1199]
**Have you**

- [X] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [X ] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [ X] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
mic pods restart from time to time (e.g. 1x/day or 1x/week, or once every couple of days). 

kubectl logs -p gives:

E1202 11:18:55.421940       1 leaderelection.go:361] Failed to update lock: Put "https://10.100.0.1:443/api/v1/namespaces/default/endpoints/aad-pod-identity-mic": context deadline exceeded
I1202 11:18:55.422723       1 leaderelection.go:278] failed to renew lease default/aad-pod-identity-mic: timed out waiting for the condition
E1202 11:18:55.422778       1 mic.go:271] lost leader lease

**Steps To Reproduce**
N/A

**Expected behavior**
No restarts

**AAD Pod Identity version**
mic:v1.8.3
nmi:v1.8.3

**Kubernetes version**
1.21.2 (AKS)

**Additional context**

**Comment by aramase** [comment]
Thanks for reporting the issue.

1. Could you enable verbose logs in the MIC pod (set `-v=5` in MIC args) and share the errors during the failure? This will print the client-go library logs.
2. Do you have the `kube-apiserver` logs at the time of the error. Based on the error message above it looks like the apiserver request timed out. This could be intermittent issues with the kube-apiserver.
3. Could you upgrade to the latest version of aad-pod-identity `v1.8.5` as that contains latest kubernetes packages and check if that resolves your issue?

**Comment by deyanp** [comment]
@aramase , we are still having mic restarted every couple of days, sometimes even more often. We upgraded to v1.8.6, but that did not help ...

How can we get kube-apiserver logs in AKS? Pls note that we have the SLA activated for this AKS cluster, so I hope the availability of it is not a problem ...

**Comment by deyanp** [comment]
@aramase, just FYI, to avoid a potential double/parallel investigation, I have opened MS Support ticket 2203210050000972 for this ...

**Comment by pkcsf** [comment]
@deyanp , I have done further investigation from Support Ticket 2203210050000972, and I can confirm that there was readiness/liveness probe failure from apiserver probe for **around 15 second**,  due to AKS Control Plane maintenance. Please note that this is an expected behavior from AKS, so ideally mic should be tolerate such transient failure.

**Comment by aramase** [comment]
Thanks for updating the issue @pkcsf! 

MIC establishes a WATCH connection with the kube-apiserver at startup. If the connection to the apiserver fails, it triggers a restart to resolve any intermittent connection issues.

**Comment by deyanp** [comment]
@pkcsf, isn't the point of AKS Uptime SLA (for which we pay) to guarantee high availability of AKS control plane? How come it goes down for 15 seconds?

**Comment by deyanp** [comment]
@aramase , we have an alert set up for our cluster to notify us for any pod restarting. We do not treat pod restart as "normal", for us pod restarts are either related to deployment, or must be investigated as an incident ...

**Comment by jchauncey** [comment]
@palma21 can you comment on the uptime sla

**Comment by deyanp** [comment]
@palma21 My custom application pods running on the nodes did not experience issues, however this mic pod gets restarted from time to time (2 times in April, about 8 times in March, 2 times in Feb) and I do not understand why. 

Let's assume the SLA accommodates 15 seconds downtime of the control plane, fine, but do you think it is normal to have the mic restarted from time to time? I thought that is not OK, and the root cause must be identified and fixed ...

Wondering if I am the only customer with this problem ...

**Comment by deyanp** [comment]
@aramase , my custom app pods are a few daemonsets and many replicasets, with some of the latter having 1,2 or 3 replicas, distributed automatically across the 3 nodes in the AKS cluster. Having said that, none of our custom pods use "single active pod/leader election" approach, all replicas process in parallel (http requests, event hub messages, etc) ...

Do you mean that the mic pod is the only replicaset in my AKS cluster with this leader election mechanism, and that is why it is so sensitive towards API server downtimes, hence I see only the mic pod restarting from time to time?

**Comment by aramase** [comment]
> @aramase , my custom app pods are a few daemonsets and many replicasets, with some of the latter having 1,2 or 3 replicas, distributed automatically across the 3 nodes in the AKS cluster. Having said that, none of our custom pods use "single active pod/leader election" approach, all replicas process in parallel (http requests, event hub messages, etc) ...

Got it! Thanks for the details.

> Do you mean that the mic pod is the only replicaset in my AKS cluster with this leader election mechanism, and that is why it is so sensitive towards API server downtimes, hence I see only the mic pod restarting from time to time?

I can only speak about MIC as I know it uses leader lease. Increasing the timeout will make it less susceptible to API server downtime. I did look at similar queries in another cluster before and came across contour which runs into similar issues with leader election when connection to API server times out: https://github.com/bitnami/charts/issues/9337#issuecomment-1067775785
