### ISSUE TITLE
"no AzureAssignedIdentity found for pod" error in NIC logs

### ISSUE THREAD

**Issue by l4z4rus** [Azure/aad-pod-identity#1201]
**Describe the bug**
After updating the certificates of our AKS cluster and the credentials of the service principal associated with it (as they have expired), the AGIC pod has failed in crashLoopBackOff and the mic and nmi pods show errors related to the managed identity.

**Steps To Reproduce**

**Expected behavior**
 To just keep working
**AAD Pod Identity version**
 1.5.4, installed using yaml
**Kubernetes version**
1.19.7 (1.14 when it was created)
**Additional context**
Logs from AGIC:
```
I1206 13:37:33.607319       1 auth.go:90] Creating authorizer from Azure Managed Service Identity
```
Logs from MIC pod:
```
I1206 13:42:33.952843       1 cloudprovider.go:199] Updating user assigned MSIs on aks-nodepool2-xxxxxxx-vmss
E1206 13:42:34.010155       1 vmss.go:75] compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client has permission to perform action 'Microsoft.Compute/galleries/images/versions/read' on scope '/subscriptions/xxxxxxxxxxx/resourceGroups/xxxxxxxxx/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool2-xxxxxxxxxxx-vmss', however the current tenant 'xxxxxxxxxxx' is not authorized to access linked subscription 'xxxxxxxxxxxxx'."
E1206 13:42:34.010230       1 mic.go:831] Updating msis on node aks-nodepool2-xxxxxxx-vmss, add [13], del [12] failed with error compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client has permission to perform action 'Microsoft.Compute/galleries/images/versions/read' on scope '/subscriptions/xxxxxxxxxxxxxxxxxx/resourceGroups/xxxxxxxxxxxxxxxxxxxxxxxx/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool2-xxxxxxxx-vmss', however the current tenant 'xxxxxxxxxxxxxxxxxx' is not authorized to access linked subscription 'xxxxxxxxxxxxxxxxxxxx'."
E1206 13:42:34.150009       1 mic.go:834] Getting list of msis from node aks-nodepool2-xxxxxxxxx-vmss resulted in error identity info is nil
```
Logs from NIM pod:
```
time="2021-12-06T13:44:53Z" level=info msg="Status (404) took 69477053765 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=172.25.16.34
time="2021-12-06T13:45:53Z" level=error msg="no AzureAssignedIdentity found for pod:default/frontend-ingress-azure-6f9cb67494-kcldp in assigned state, context canceled" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=172.25.16.34
time="2021-12-06T13:45:53Z" level=info msg="Status (404) took 59501526795 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=172.25.16.34
```

**Comment by aramase** [comment]
`1.5.4` version of aad-pod-identity is old and is no longer supported. The earlier versions (1.5.x) used a PUT REST API call to assign the identities which required more permissions. In 1.6.x we updated to PATCH API call for this reason. Please see https://github.com/Azure/aad-pod-identity/issues/753 for more details.

I would recommend reviewing our release notes and updating to the latest supported release.

- Changelog: https://azure.github.io/aad-pod-identity/changelog/
- Breaking changes across releases: https://azure.github.io/aad-pod-identity/docs/#breaking-changes

**Comment by l4z4rus** [comment]
Hi @aramase,
thanks for the reply.

I have some questions about it:

1. do i have to delete the old version of aad-pod-identity before deploying the new one?
2. is it recommended to use the latest release (v1.8.5) or is it sufficient that it is 1.6+?
3. our AKS cluster has an AGIC pod (v1.0.0) deployed with Helm v2. According to the documentation at this link (https://azure.github.io/application-gateway-kubernetes-ingress/troubleshootings/troubleshooting-agic-fails-with-aad-pod-identity-breakingchange/), the aad-pod-identity with version >= 1.6.0 breaks this AGIC version. Do you confirm this? Do I first have to delete the old version of the AGIC, install the new one and then deploy the new version of the AAD pod identity? Do I have to use Helm v3 to deploy the new AGIC or can I install the AKS AGIC add-on from the portal?

**Comment by aramase** [comment]
> do i have to delete the old version of aad-pod-identity before deploying the new one?

If you would like to do a clean install, then you can delete and recreate pod identity. Please review the breaking changes as 1.5.x is a really old version.

> is it recommended to use the latest release (v1.8.5) or is it sufficient that it is 1.6+?

The current supported versions are 1.7.x and 1.8.x. So our recommendation is to use the latest as they contain performance improvements and bug fixes. The older versions are no longer maintained/tested.

For AGIC related questions and AGIC compatibility with aad-pod-identity, I would recommend reaching out to the maintainers of the AGIC project.

**Comment by l4z4rus** [comment]
Hi @aramase,
we solved the issue by updating the aad-pod-identity, as recommended by you.
Thanks for your support.

I close the issue.
