### ISSUE TITLE
Allow to create identity without creating namespace

### ISSUE THREAD

**Issue by RoSk0** [Azure/aad-pod-identity#1204]
**Describe the request**

When creating and identity with `az aks pod-identity add` pod identity creates the namespace. I want to have an option to NOT created it. 

We use Terraform to better manage application resources in Rancher and existing namespace makes it really hard to the first deployment as Terraform tries to create it for us. 

**Explain why AAD Pod Identity needs it**

Having option to not create a namespace when identity is created will improve developer experience and as result Azure posture in developers eyes. 

**Describe the solution you'd like**

Option , like `--namespace-do-not-create` , added to the CLI of `az aks pod-identity add` command.

**Describe alternatives you've considered**

**Additional context**

**Comment by aramase** [comment]
cc @bcho @miwithro for the AKS add-on

**Comment by bcho** [comment]
Hi @RoSk0 , thanks for your feedback! I have a question: are you creating the whole cluster and pod identities during the cluster creation with terraform? Asking this because I want to understand the usage pattern here.

**Comment by RoSk0** [comment]
No. Clustervis set up, than pod identities. Not sure about the cluster creation,  but pod identities are created with a shell script using `az aks pod-identity add` command as per description.  The application is then deployed with Terraform via Rancher provider.

Thinking more about it I believe claim made in the description is not correct namespace is not created at the time of the pod identities creation. Namespace is however re-created if there was access from pods inside it, e.g. if it is deleted after pods from within used associated identities. So it looks like this should be closed. Sorry for the noise.

**Comment by RoSk0** [comment]
We re-created one of the clusters and after running the script to create pod identities for all required namespaces those namespaces was created confirming original claim in the description. 

All namespaces have `addonmanager.kubernetes.io/mode: EnsureExists` label on them.

**Comment by bcho** [comment]
Hi @RoSk0 , this is expected when adding the pod identity through `az aks pod-identity add` command. This is because in the managed addon version, we want to make sure the pod identity custom resource exists as part of the cluster provision process. For example, missing the pod identity custom resource after running some operations might introduce application down time. To archive such requirements, AKS will create the ns and custom resource with above annotations set.

May I know what exactly the issue you met when trying to use with Rancher?

**Comment by aramase** [comment]
As this enhancement request is specific to AKS managed add-on, I would recommend opening an issue at https://github.com/Azure/aks if this is still required.

**Comment by RoSk0** [comment]
> Hi @RoSk0 , this is expected when adding the pod identity through `az aks pod-identity add` command. This is because in the managed addon version, we want to make sure the pod identity custom resource exists as part of the cluster provision process. For example, missing the pod identity custom resource after running some operations might introduce application down time. To archive such requirements, AKS will create the ns and custom resource with above annotations set.
> 
> May I know what exactly the issue you met when trying to use with Rancher?

As said in description, the problem is not with Rancher but with the fact that namespace exists. We want to manage all application related resources, including namespaces, with the Terraform. When application is created, Terraform state is empty and it tries to create the namespace to place the other application resources in it. Obviously this fails when the namespace is already there, created by addon manager.

@aramase is this the addon in question?

**Comment by aramase** [comment]
> @aramase is this the addon in question?

@RoSk0 `az aks pod-identity add` is the AKS managed pod-identity addon: https://docs.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity. The add-on uses aad-pod identity in managed mode, so AKS issues would be the appropriate channel for questions.
