### ISSUE TITLE
After upgrading to 1.85 started to see a lot of : failed to acquire a token using the MSI VM extension, error: MSI not available

### ISSUE THREAD

**Issue by digeler** [Azure/aad-pod-identity#1207]
After upgrading to 1.8.5 from 1.8.0 i see the following issue : 
ManagedIdentityCredential authentication failed: Service request failed.
Status: 403 (Forbidden)

Content:
failed to acquire a token using the MSI VM extension, error: MSI not available

Headers:
X-Content-Type-Options: REDACTED
Date: Mon, 13 Dec 2021 14:44:35 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 79

the above is from the nmi log.

is there any changes made that can cause this behavior.
we are using aks 1.21.1 with aad 1.8.5

before we had the 1.8.0 and we had no issues.

can you please explain this error and how we can avoid this.
thank you.

**Comment by digeler** [comment]
here are some errors i saw :
I1213 14:57:28.257169       1 server.go:199] status (403) took 586168248 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.45.126 
E1213 14:57:28.257303       1 server.go:392] failed to get service principal token for pod: default/enricher-6, error: failed to acquire a token using the MSI VM extension, error: MSI not available
I1213 14:57:28.257334       1 server.go:199] status (403) took 194273295 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.45.126
E1213 14:57:28.257343       1 server.go:392] failed to get service principal token for pod: default/enricher-6, error: failed to acquire a token using the MSI VM extension, error: MSI not available
I1213 14:57:28.257370       1 server.go:199] status (403) took 397841367 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.45.126
E1213 14:57:28.257485       1 server.go:392] failed to get service principal token for pod: default/enricher-6, error: failed to acquire a token using the MSI VM extension, error: MSI not available
I1213 14:57:28.257523       1 server.go:199] status (403) took 586606757 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.45.126
E1213 14:57:28.257598       1 server.go:392] failed to get service principal token for pod: default/enricher-6, error: failed to acquire a token using the MSI VM extension, error: MSI not available
I1213 14:57:28.257749       1 server.go:199] status (403) took 586845961 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.45.126
E1213 14:57:28.264559       1 server.go:392] failed to get service principal token for pod: default/enricher-6, error: failed to acquire a token using the MSI VM extension, error: MSI not available
I1213 14:57:28.264593       1 server.go:199] status (403) took 500392016 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.45.126
E1213 14:57:28.264561       1 server.go:392] failed to get service principal token for pod: default/enricher-6, error: failed to acquire a token using the MSI VM extension, error: MSI not available
I1213 14:57:28.264737       1 server.go:199] status (403) took 500542020 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.45.126
E1213 14:57:28.264971       1 server.go:392] failed to get service principal token for pod: default/enricher-6, error: failed to acquire a token using the MSI VM extension, error: MSI not available

**Comment by aramase** [comment]
Thank you for reporting the issue!

This is the related to the aggressive health check performed in the go-autorest SDK as part of every token request call. We have an issue open for this: https://github.com/Azure/go-autorest/issues/660

**Comment by chewong** [comment]
We have upgraded the go-autorest package in https://github.com/Azure/aad-pod-identity/pull/1208 in the latest release. Feel free to give aad-pod-identity v1.8.6.
