### ISSUE TITLE
Pods failed to get token when VMSS rebooted

### ISSUE THREAD

**Issue by PunithKumarB** [Azure/aad-pod-identity#1212]
**Have you**

- [ ] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [ ] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [ ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
After rebooting AKS VMSS node pool, two of our pods (monitoring-687644f955-ltvnj & cs-metrics-monitoring-68cd76487c-xjvdt) failed to get token during their init(startup). The VMSS nodepool has 3 nodes and nmi pods are deployed on all the 3 nodes using aad-pod-identity helm charts https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts. 
This flow is time tested, but breaks occasionally during restarts.

*Error details :*
1. monitoring-687644f955-ltvnj -- 
`2021-12-15T07:51:41.247484185Z	monitoring-687644f955-ltvnj	No valid token received. EnvironmentCredential: Incomplete environment configuration.. ImdsCredential: Unexpected response '{'error': 'invalid_request', 'error_description': 'Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request'}'`

    Code snippet being used python : uses [default Azure Credentials](https://docs.microsoft.com/en-us/python/api/azure-identity/azure.identity.defaultazurecredential?view=azure-python) and gets secret from keyvault
   ```
   credential = DefaultAzureCredential() 
   client = SecretClient(vault_url=self.__vault_url, credential=credential)
   ```

2. cs-metrics-monitoring-68cd76487c-xjvdt shows below logs -- generated from SDK azure/cli/core/auth/adal_authentication.py 
`2021-12-15T07:48:33.158569416Z	cs-metrics-monitoring-68cd76487c-xjvdt	ERROR: Failed to connect to MSI. Please make sure MSI is configured correctly.`
`2021-12-15T07:48:33.158608619Z	cs-metrics-monitoring-68cd76487c-xjvdt	Get Token request returned http error: 400, reason: Bad Request`

   POD executes CLI command to login and then tries to download secrets from KV
   ```
   az login --identity --allow-no-subscriptions
   USERNAME=$(az keyvault secret show --name $USERNAME_SECRET --vault-name $KEYVAULT_NAME | jq -r .value)
   ```

Part of the problem was reported earlier as well, reference to older bug - #1152

**Steps To Reproduce**
  Reproduces when VMSS is restarted

**Expected behavior**
   works normally even during node reboot or pod reset.

**AAD Pod Identity version**
helm chart 4.1.3

**Kubernetes version**
1.20.7

**Additional context**
   1.  Log shows an interesting pattern - in both the above pod cases, the nmi pod on the corresponding vmss node was either rebooting or stopped at that moment. Can we confirm if both these pods are facing problem due to nmi rebooting?
   2.  if the above is true, then how can we solve this completely, adding retry inside our pod / passing explicit client Id / imposing sequential init containers will not help us
   3. [Attached entire cluster logs](https://github.com/Azure/aad-pod-identity/files/7730143/All.pod.logs.from.cluster.xlsx)
   4. Initial code walk of identity SDK shows IDMS endpoint metadata failure for monitoring pod.
   5. Restarting the POD again works
   6. Config details 
        ```
          "cloud": "AzurePublicCloud",
          "tenantId": "33e01921-****-4f8c-a055-5bdaffd5e33d",
          "subscriptionId": "83e8cb0f-****-4c25-aeb2-3cf17219c6fd",
          "aadClientId": "msi",
          "aadClientSecret": "msi",
          "useManagedIdentityExtension": true,
          "userAssignedIdentityID": "2cb9bab8-****-****-21322a8e9d16",
        ```

Feel free if you need other details.

**Comment by PunithKumarB** [comment]
Would like to have some feedback on this.

**Comment by vahidmosi** [comment]
Any update on this? We have a similar issue.

**Comment by aramase** [comment]
Hello 👋🏻 

By "vmss is restarted" do you mean the node is rebooted and pods recreated/rescheduled? If that's the case it's possible the NMI pod is not yet running on the node before the workload pod requests the token. If you don't provide a clientID as part of your token request, NMI defaults to the first clientID matched based on `AzureIdentity`. However if NMI is not yet running and your workload makes a token request, the request will directly go to IMDS which needs the clientID to choose the correct identity. Otherwise it'll return an error.

**Comment by PunithKumarB** [comment]
hi @aramase , yep that's right, we did scheduled reboot of our VMSS nodes and pods got recreated and then we met this incident.

There are two versions of the problem
1. monitoring-687644f955-ltvnj - client ID is not received by IMDS, so it returns error. Maybe sending client ID would help us. 
2. cs-metrics-monitoring-68cd76487c-xjvdt - it gets different error, `2021-12-15T07:48:33.158608619Z cs-metrics-monitoring-68cd76487c-xjvdt Get Token request returned http error: 400, reason: Bad Request`. Does this error point to NMI not running on the VMSS node? 

Follow up questions
1.Do we have sample code that covers this edge case and any better way to solve, other than using Client ID?
2.Can NMI support load balancing request across pods?

**Comment by aramase** [comment]
When there are multiple identities assigned to the VMSS, IMDS expects the clientID to be part of the token request to know which identity to pick. If there is no clientID in the request, then the token request will fail with "Multiple identities exist" error. AAD Pod Identity makes it easier in this scenario by defaulting to the first clientID that matches the pod. 

In this scenario, when NMI isn't yet running on the new node, all token requests are going directly to IMDS and hence the error. 

> cs-metrics-monitoring-68cd76487c-xjvdt - it gets different error, 2021-12-15T07:48:33.158608619Z cs-metrics-monitoring-68cd76487c-xjvdt Get Token request returned http error: 400, reason: Bad Request. Does this error point to NMI not running on the VMSS node?

Yeah, this seems like an error from IMDS which could mean NMI isn't running on the node yet.

> Can NMI support load balancing request across pods?

There is a dedicated NMI for every node, so there would be no load balancing. Acquiring a token is node local operation (pod on node -> NMI on node -> IMDS).

**Comment by michail-nikolaev** [comment]
Got the same issues, pod redeploy fixed it....

**Comment by NikolayBieliashov** [comment]
> Got the same issues, pod redeploy fixed it....

Hey, Michail! Did you also have two Identities and got this error? 
For now I  have 1 running pod and can't start new version of it.
Did you mean I should just kill previous deployment and it will be okay? 
Do a next deployment will start properly after this?

**Comment by nkey0** [comment]
> Did you mean I should just kill previous deployment and it will be okay?
> Do a next deployment will start properly after this?

Yes, as far as I remember.
