### ISSUE TITLE
MIC using high CPU every 10 minutes.

### ISSUE THREAD

**Issue by brandonpollett** [Azure/aad-pod-identity#1221]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [x] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [x] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
We are seeing an increased CPU utilization from the MIC controller for a particular cluster that we're running. The CPU spike appears to happen about every 10 minutes. It doesn't seem to scale linearly with the number of identities in use. 

Affected cluster: (approx. 170 identity bindings)
![CPU_SCUS](https://user-images.githubusercontent.com/18427011/147002097-3b05cb63-92bc-4c6b-8b43-6234ac141372.png)

Unaffected cluster: (approx. 116 identity bindings)
![CPU_NORTHEU](https://user-images.githubusercontent.com/18427011/147002134-25a753ca-2681-40da-be7e-583ab279a3b6.png)

From what I can tell, the only thing in the codebase that appears to run with that schedule is https://github.com/Azure/aad-pod-identity/blob/17ccce341e5c0e4bccabbad6a97a79c18773a4d9/pkg/crd/crd.go#L184-L187 which, if I'm reading it correctly, means that the the state is going to be re-synced every 10 minutes.

We are deploying via helm and have already doubled the default limit for CPU from 200m to 400m to alleviate alerting.

**Expected behavior**
We would expect CPU to either be somewhat stable or that it would scale with the number of identities.

**AAD Pod Identity version**
v1.8.5

**Kubernetes version**
1.20.9

**Additional context**

**Comment by aramase** [comment]
Hello 👋🏻 

1. Could you share the MIC logs for a period of time when the spike occurs?  
2. Can you check if there are `AzureIdentity` or `AzureIdentityBinding` with same name in multiple namespaces?
3. Are you running pod identity in force namespaced mode?

**Comment by brandonpollett** [comment]
Sorry for the long time getting back to you.

1. I can share these out of band with you
2. Yes, there appear to be two `AzureIdentity` that share a name and one `AzureIdentityBinding` that shares a name. This is likely the same in all of our clusters. 
3. The `forcenamespaced` value is false.
