### ISSUE TITLE
Kubenet - policy NET_RAW capability

### ISSUE THREAD

**Issue by koninko** [Azure/aad-pod-identity#1226]
**Have you**

- [ ] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [x] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [x] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**

We have applied a policy to avoid pods with NET_RAW capability to be deployed.
However this policy makes it impossible to deploy the nmi pod, because it required NET_RAW.

Error message on the daemon set:

Error creating: admission webhook "validation.gatekeeper.sh" denied the  request: [azurepolicy-container-allowed-capabilities-b0510cec315f099722a]  container <nmi> has a disallowed capability. Allowed capabilities are []

**Steps To Reproduce**

https://azure.github.io/aad-pod-identity/docs/configure/aad_pod_identity_on_kubenet/#why-this-change

Apply Azure policy 'Kubernetes cluster containers should only use allowed capabilities'

**AAD Pod Identity version**

latest from master 

**Kubernetes version**

1.21.2

**Comment by koninko** [comment]
AAD Pod identity is deployed in the default namespace? We could exclude the namespace from the policy, or deploy it to another namespace. But this does not give me a good feeling of mitigating the problem.. Or am I wrong?

**Comment by aramase** [comment]
Hello 👋🏻  By default there is no namespace field defined in the pod identity manifests. The recommendation is to deploy it in `kube-system` namespace as this is high privilege pod. If you run it in `kube-system` you can exclude that namespace that contains system pods from the policy.

**Comment by koninko** [comment]
> Hello 👋🏻 By default there is no namespace field defined in the pod identity manifests. The recommendation is to deploy it in `kube-system` namespace as this is high privilege pod. If you run it in `kube-system` you can exclude that namespace that contains system pods from the policy.

Hi, 
when you use the deployment yaml, it deploys to default namespace.

https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml

From my tests I could also see azureidentitybindings and mic / nmi should be in the same namespace. Shouldn't azureidentitybindings should be deployed to default namespace?

Thx

**Comment by aramase** [comment]
> From my tests I could also see azureidentitybindings and mic / nmi should be in the same namespace. Shouldn't azureidentitybindings should be deployed to default namespace?

The `AzureIdentity` and `AzureIdentityBinding` don't need to be in the same namespace as the MIC and NMI pods. If you run pod identity in force namespace mode: https://azure.github.io/aad-pod-identity/docs/configure/match_pods_in_namespace/, then the `AzureIdentity` and `AzureIdentityBinding` would need to be in the same namespace as your workload pod. This is the recommended configuration.

**Comment by koninko** [comment]
> > From my tests I could also see azureidentitybindings and mic / nmi should be in the same namespace. Shouldn't azureidentitybindings should be deployed to default namespace?
> 
> The `AzureIdentity` and `AzureIdentityBinding` don't need to be in the same namespace as the MIC and NMI pods. If you run pod identity in force namespace mode: https://azure.github.io/aad-pod-identity/docs/configure/match_pods_in_namespace/, then the `AzureIdentity` and `AzureIdentityBinding` would need to be in the same namespace as your workload pod. This is the recommended configuration.

That worked for me thanks
