### ISSUE TITLE
Roadmap of AAD-Pod-Identity

### ISSUE THREAD

**Issue by ECNUJason** [Azure/aad-pod-identity#1227]
**Describe the request**
Hello team, 
May I tentatively ask the road map of AAD-Pod-Identity and some ETA for key milestone?

**Explain why AAD Pod Identity needs it**
AAD-Pod-Identity v2 is mentioned in this issue: https://github.com/Azure/aad-pod-identity/issues/570.

**Describe the solution you'd like**
N.A.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by chewong** [comment]
[Azure Workload Identity](https://azure.github.io/azure-workload-identity), the next generation of AAD Pod Identity, is now available. Feel free to check it out.
