### ISSUE TITLE
aad_pod_identity taking ages to create

### ISSUE THREAD

**Issue by isaacdan** [Azure/aad-pod-identity#1228]
@aleoli
**Have you**

- [ ] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [ ] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [ ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
aad pod identity creation failing with error 
failled to install CRD crds/crd.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
This was working fine till last month
**Steps To Reproduce**
resource "helm_release" "aad_pod_identity" {
null_resource.aks_blob_driver]
  provider   = helm.akshelmconfig
  name       = "aad-pod-identity"
  repository = "https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts"
  chart      = "aad-pod-identity"
  version    = "4.1.7"
  timeout    = 1200

  values = [<<-EOF
azureIdentities:
- name: "${data.azurerm_user_assigned_identity.ingress_identity[0].name}"
  Labels:
        app=atria-helm
        release="${var.deployment_name}"
  type: 0
  resourceID: "${data.azurerm_user_assigned_identity.ingress_identity[0].id}"
  clientID: "${data.azurerm_user_assigned_identity.ingress_identity[0].client_id}"
  binding:
    name: "${data.azurerm_user_assigned_identity.ingress_identity[0].name}-binding"
    selector: "${var.deployment_name}-atria-helm-ingress-nginx"

  rbac:
    allowAccessToSecrets: true
  installCRDs: true
  nmi:
    allowNetworkPluginKubenet: true
  EOF
  ]
}
**Expected behavior**

**AAD Pod Identity version**
2.0.1. Also tried with latest it runs forever
**Kubernetes version**
1.22.4
**Additional context**

**Comment by aleoli** [comment]
@isaacdan you probably tagged the wrong person 😅

**Comment by isaacdan** [comment]
Okay sorry @aleoli

**Comment by isaacdan** [comment]
Looks like nmi pods are in CrashLoopBackOff   
ad-pod-identity-nmi-227wk               0/1     CrashLoopBackOff   1          12s
aad-pod-identity-nmi-rw6rj               0/1     CrashLoopBackOff   1          12s

 kubectl logs -f aad-pod-identity-nmi-227wk -n default
F0111 10:10:11.354617       1 main.go:83] AAD Pod Identity is not supported for Kubenet. Review https://azure.github.io/aad-pod-identity/docs/configure/aad_pod_identity_on_kubenet/ for more details.
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x1)
        /go/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:1038 +0x8a
k8s.io/klog/v2.(*loggingT).output(0x2592840, 0x3, 0x0, 0xc0001405b0, 0x0, {0x1d055b3, 0x0}, 0xc0000bd200, 0x0)
from the logs I see that recom 
Set the --allow-network-plugin-kubenet=true arg in the NMI container (or --set nmi.allowNetworkPluginKubenet=true if deploying with Helm) to continue running on clusters with Kubenet.

nmi:
allowNetworkPluginKubenet: true
the above setting is already there yet no luck
Can someone please assist

**Comment by isaacdan** [comment]
@palexster can you please assist if you are the right person

**Comment by palexster** [comment]
@isaacdan you probably tagged the wrong person
