### ISSUE TITLE
User-assigned identities are intermittently missing from VMs

### ISSUE THREAD

**Issue by CBaud** [Azure/aad-pod-identity#123]
Our k8s cluster is experiencing issues where services will intermittently fail to authenticate with AAD. Closer inspection of the virtual machine that hosted the failing service will show that the user-assigned managed identity is missing. Manually re-adding the managed identity onto the virtual machine resolves the issue. However, it is unclear how individual virtual machines in our cluster are getting into this broken state.

**Comment by kkmsft** [comment]
@CBaud - 

1. Can you please provide us with the MIC logs (is possible with increased verbosity) and the NMI logs to determine if there are some activities going on from aad-pod-identity side to which causes the identity to be missing. 

2. Also, do you see any actions of explicitly removing the identity in the Azure portal event logs ? 

3. Another question is are AzureAssignedIdentities still present for the given pod-node-identity combination ?

4. Do you see any pattern when this happens - every hour or few minutes etc ? 

5. Are the pods which are deployed having any life cycle event - like being stopped, restarted or so ?

**Comment by CBaud** [comment]
Closing the loop - upgrading to the 1.3.0-mic-1.4.0-nmi release has made things much more stable.
