### ISSUE TITLE
Getting this sporadic exception: Tried to get token using Managed Service Identity. Unable to connect to the Instance Metadata Service (IMDS). Skipping request to the Managed Service Identity (MSI) token endpoint.  

### ISSUE THREAD

**Issue by saurabhvagrawal** [Azure/aad-pod-identity#1232]
**Have you**

- [ ] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/): Yes
- [ ] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/): Yes
- [ ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues): Yes

**Describe the bug**
We are running aadpodidentity in managed mode in our K8s clusters. We are seeing sporadic error like this for all tenants for different services:

GetAccessTokenAsync: Failed to acquire access token with MSI for resource https://ingest-wcdscrubbedweu3.westeurope.kusto.windows.net/, Exception: 

Exception Details
===================================
Exception Type: Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException
Target Site: Void MoveNext()
Message: Parameters: Connection String: RunAs=App;MsiRetryTimeout=120, Resource: https://<service>.westeurope.kusto.windows.net/, Authority: . Exception Message: Tried to get token using Managed Service Identity. Unable to connect to the Instance Metadata Service (IMDS). Skipping request to the Managed Service Identity (MSI) token endpoint.
Help Link: 
Source: Microsoft.Azure.Services.AppAuthentication
HResult: -2146233088

Stack Trace Details 
-----------------------------------
   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAuthResultAsyncImpl(String resource, String authority, Boolean forceRefresh, CancellationToken cancellationToken)
   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAccessTokenAsync(String resource, String tenantId, Boolean forceRefresh, CancellationToken cancellationToken)
   at WDATP.Infra.App.AuthenticationProvider.Extensions.Wrappers.Concrete.AzureServiceTokenProviderWrapper.GetAccessTokenAsync(String resource, Boolean forceRefresh)
   at WDATP.Infra.App.AuthenticationProvider.Providers.MsiAccessTokenProvider.GetAccessTokenAsync(String resourceId, Boolean forceRefresh)

also this:

GetAccessTokenAsync: Failed to acquire access token with MSI for resource https://MSPublicCloud.onmicrosoft.com/<resourcename>, Exception: 

Exception Details
===================================
Exception Type: Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException
Target Site: Void MoveNext()
Message: Parameters: Connection String: [No connection string specified], Resource: https://MSPublicCloud.onmicrosoft.com/<resourcename>, Authority: . Exception Message: Tried the following 3 methods to get an access token, but none of them worked.
Parameters: Connection String: [No connection string specified], Resource: https://MSPublicCloud.onmicrosoft.com/<resourcename>, Authority: . Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. Received a non-retryable error. MSI ResponseCode: Forbidden, Response: failed to acquire a token using the MSI VM extension, error: MSI not available

Parameters: Connection String: [No connection string specified], Resource: https://MSPublicCloud.onmicrosoft.com/<resourcename>, Authority: . Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. Environment variable LOCALAPPDATA not set.
Parameters: Connection String: [No connection string specified], Resource: https://MSPublicCloud.onmicrosoft.com/<resourcename>, Authority: . Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. /bin/bash: az: command not found

Help Link: 
Source: Microsoft.Azure.Services.AppAuthentication
HResult: -2146233088

Stack Trace Details 
-----------------------------------
   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAuthResultAsyncImpl(String resource, String authority, Boolean forceRefresh, CancellationToken cancellationToken)
   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAccessTokenAsync(String resource, String tenantId, Boolean forceRefresh, CancellationToken cancellationToken)
   at WDATP.Infra.App.AuthenticationProvider.Extensions.Wrappers.Concrete.AzureServiceTokenProviderWrapper.GetAccessTokenAsync(String resource, Boolean forceRefresh)
   at WDATP.Infra.App.AuthenticationProvider.Providers.MsiAccessTokenProvider.GetAccessTokenAsync(String resourceId, Boolean forceRefresh)

We observed that we got this exception sometimes, but eventually service will get the token from MSI. This is not looking good and we want to know the exact issue so that we can fix this.

**Steps To Reproduce**
This is sporadic issue and happening in every cluster , every tenant and almost every services.

**Expected behavior**
We shouldn't get these exceptions

**AAD Pod Identity version**
Chart Version: 4.1.6 and appversion: 1.8.5

**Kubernetes version**
1.19

**Additional context**
We are using AKS based clusters and using VMSS as compute instances.

**Comment by aramase** [comment]
There was an [issue](https://github.com/Azure/go-autorest/issues/660) with aggressive IMDS health check in go-autorest that causes this failure. We've updated to the latest version of that package that contains the fix. Could you try using the latest [v1.8.6](https://github.com/Azure/aad-pod-identity/releases/tag/v1.8.6) release?

**Comment by saurabhvagrawal** [comment]
Thanks for prompt response Anish.. Really appreciate. Will check internally and would update it to latest.

**Comment by saurabhvagrawal** [comment]
Also, as you said that it only failing IMDS health check. So, that means application will still be intact(should not be degraded) and will not miss any token from NMI, right?

**Comment by aramase** [comment]
> Also, as you said that it only failing IMDS health check. So, that means application will still be intact(should not be degraded) and will not miss any token from NMI, right?

In older versions of the library, every token request initiated a IMDS health check. This health check was aggressive and would time out very quickly. If the health check request fails. the library would return and not try to get a token which is why token request fails with "MSI not available". In the newer release of the library they have removed the health check on every token request which should be more performant.

**Comment by saurabhvagrawal** [comment]
Hi Anish. After upgrade we encountered a issue with keda authentication. Issue is described in this bug( https://github.com/Azure/aad-pod-identity/issues/1236). This is urgent for us since its impacting our customers. Could you please check this.

**Comment by aramase** [comment]
Closing this issue in favor of #1236

**Comment by abuzaforfagun** [comment]
@aramase I am using `v1.8.9` and facing the same issue.
