### ISSUE TITLE
Error 401 on keda scalers when nmi pods are restarted/upgraded

### ISSUE THREAD

**Issue by saurabhvagrawal** [Azure/aad-pod-identity#1236]
**Have you**

- [ ] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [ ] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [ ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**

Hi Team.. While we upgrade/restart nmi, we encountered a strange issue where we get following error in keda(advanced autoscaling) when it continues to fetch tokens from IMDS through nmi.

{"error": "error code: 401, Details: MalformedToken: The credentials contained in the authorization header are not in the WRAP format.

or 

error code: 401, Details: claim is empty or token is invalid.

For now the mitigation step is to restart the keda container, which in turn reauthenticate(to azure resources or scaled objects) itself though nmi and starts working properly. It seems like keda looses its claim once nmi is restarted. This is haunting us from long time in production and happening in different versions. Is there any way we can fix this. 

Let us know if you need further information on this.

**Steps To Reproduce**

Restart NMI pods or upgrade it.

**Expected behavior**

Keda should not be restarted 

**AAD Pod Identity version**

nmi v1.8.6

**Kubernetes version**

1.19.15

**Additional context**

**Comment by aramase** [comment]
Thanks for reporting the issue!

Could you provide the logs from NMI pods at the timeframe the issue is occuring? Are the token requests failing or are the tokens you receive not in the expected format?

**Comment by atiasadir** [comment]
#1243  should nail this issue

**Comment by aramase** [comment]
Closed with https://github.com/Azure/aad-pod-identity/pull/1243
