### ISSUE TITLE
nmi.metadataHeaderRequired does not respect false value

### ISSUE THREAD

**Issue by jarrettprosser** [Azure/aad-pod-identity#1237]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [x] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [x] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
We deployed a new installation of `aad-pod-identity` into a Kubernetes cluster with the Helm chart and deployed our application, which has historically worked with pod identity. The application was unable to get a token, and we could see an error in the NMI logs saying `Required metadata header not specified`. 

I found #1230 which explained that this is because the requirement for metadata is now enabled by default. Our application doesn't provide the Metadata header, and was previously connecting with an older version of `aad-pod-identity` without this requirement. 

I set the chart value `nmi.metadataHeaderRequired` to `false` and redeployed. When the NMI pods restarted, we kept seeing the error. 

I suspect that since the change in 1.8.4, `--metadata-header-required` is now enabled by default, and we need to pass an explicit `--metadata-header-required=false` as an argument. The chart value `nmi.metadataHeaderRequired` will only add `--metadata-header-required=true` when true, it will remove the argument entirely when set to `false`. From `nmi-daemonset.yaml`:

```
{{- if .Values.nmi.metadataHeaderRequired}}
- --metadata-header-required={{ .Values.nmi.metadataHeaderRequired }}
{{- end }}
```

Again from the comments in #1230 (thanks!) we resolved this temporarily by downgrading the NMI pod to 1.8.3.

**Steps To Reproduce**
- Deploy `aad-pod-identity` 1.8.4+ with the helm chart
- Set `nmi.metadataHeaderRequired` to `false`
- Attempt to authenticate without providing the header `Metadata: true`

**Expected behavior**
`nmi.metadataHeaderRequired: false` should pass an explicit `--metadata-header-required=false` argument to the pod. Alternately, if the metadata header is definitely required moving forward, this option should be removed from the chart as it's not functioning as expected.

**AAD Pod Identity version**
1.8.6

**Kubernetes version**
1.19

**Comment by chewong** [comment]
Thanks for reporting this. Looks like the helm chart is indeed not respecting the chart value. Would you be interested in opening a PR to fix this?

**Comment by jarrettprosser** [comment]
thanks for the fix!
