### ISSUE TITLE
metadata header issues

### ISSUE THREAD

**Issue by PSanetra** [Azure/aad-pod-identity#1239]
After upgrading from 1.7.4 to 1.8.6 we had some issues with pods using the Azure .NET SDK which aparently could be solved by restarting those pods. (The Azure .NET SDK seemed to send the metadata header only after a restart.)

As far as I know we don't have any issues with any pods now, but there are still error logs in some `nmi` pods related to the metadata header, but unrelated to the token endpoint:

```
I0119 10:00:37.359679       1 server.go:199] status (200) took 202958896 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.0.2.199
E0119 10:12:13.871629       1 server.go:518] metadata header is not specified, req.method=GET reg.path=/latest/meta-data/hostname req.remote=10.0.2.187
E0119 10:12:13.872182       1 server.go:518] metadata header is not specified, req.method=GET reg.path=/latest/meta-data/instance-id req.remote=10.0.2.187
E0119 10:12:14.187564       1 server.go:518] metadata header is not specified, req.method=GET reg.path=/computeMetadata/v1/instance/hostname req.remote=10.0.2.187
E0119 10:12:14.188108       1 server.go:518] metadata header is not specified, req.method=GET reg.path=/computeMetadata/v1/instance/name req.remote=10.0.2.187
E0119 10:12:14.194333       1 server.go:518] metadata header is not specified, req.method=GET reg.path=/computeMetadata/v1/ req.remote=10.0.2.187
E0119 10:12:14.228989       1 server.go:518] metadata header is not specified, req.method=GET reg.path=/computeMetadata/v1/instance/network-interfaces/ req.remote=10.0.2.187
E0119 10:12:14.229483       1 server.go:518] metadata header is not specified, req.method=GET reg.path=/latest/meta-data/network/interfaces/macs req.remote=10.0.2.187
```

Does someone know what could cause those requests and how it is possible to add the metadata header to those requests?

**Steps To Reproduce**
Update to aad-pod-identity 1.8.6 (?)

**Expected behavior**
No metadata header related errors in nmi logs

**AAD Pod Identity version**
1.8.6

**Kubernetes version**
AKS 1.22

**Comment by chewong** [comment]
NMI intercepts all IMDS traffics and it looks like it's intercepting traffics to the AWS Instance Metadata service as well,e.g. `/latest/meta-data/hostname`, `/latest/meta-data/instance-id`.  I'd recommend creating an [AzurePodIdentityException](https://azure.github.io/aad-pod-identity/docs/concepts/azurepodidentityexception/) to allow AWS IMDS traffic for your workload. You can also check out our newest project - [Azure Workload Identity](https://github.com/Azure/azure-workload-identity), which doesn't fetch tokens from IMDS.

**Comment by PSanetra** [comment]
@chewong Thank you for that suggestion. We will try to do create the exception. I think using Azure Workload Identity is currently not possible for us as it would need to support Managed Identities first, but looks like a promising project :+1: 

Do you plan to patch the NMI to ignore the metadata header requirement for requests other than to the token endpoint?

**Comment by chewong** [comment]
No, it will be enabled by default going forward to prevent SSRF attacks (https://azure.github.io/aad-pod-identity/docs/configure/feature_flags/#metadata-header-required-flag) but you can disable it by adding `--metadataHeaderRequired=false` flag to NMI.

**Comment by PSanetra** [comment]
For anyone who is searching for a possible source of those requests which were still missing the metadata header: In our case it was the datadog agent pod.

**Comment by dan-jackson-github** [comment]
@PSanetra we have run into this issue, have tried creating an AzurePodIdentityException  resource to discount the traffic from datadog agents, but it seems unable to stop the calls to AWS still, could you share the config you have for your AzurePodIdentityException resource, I'm making a mistake there clearly.

**Comment by PSanetra** [comment]
@dan-jackson-github I just checked and I saw, that we did not try to create that exception and currently just live with the logs. Instead we have created an issue for the datadog-agent to support disabling non-Azure cloud provider checks: https://github.com/DataDog/datadog-agent/issues/10635
