### ISSUE TITLE
Failure deleting Azure Pod identity

### ISSUE THREAD

**Issue by vinayada1** [Azure/aad-pod-identity#1244]
**Have you**

- [ ] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [ ] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [ ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**

One of our tests creates an Azure pod identity and deletes it as a part of cleanup. The deletion is failing and the issue started on 2/4/2022.

cli.go:194: [rad] Error: delete application error: {"status":"Failed","error":{"code":"DownstreamEndpointError","message":"The resource provider 'radiusv3' received a non-success response 'InternalServerError' from the downstream endpoint for the request 'DELETE' on 'Application/azure-resources-container-azurekvcsidriver/Container/backend'. Please refer to additional info for details.","details":[{"code":"Downstream","message":"{\"error\":{\"code\":\"Internal\",\"message\":\"failed to delete pod identity on the cluster: containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>\",\"target\":\"/subscriptions/85716382-7362-45c3-ae03-2126e459a123/resourceGroups/rad-6919fa271c764e4d98b95e80a5a447c3/providers/Microsoft.CustomProviders/resourceProviders/radiusv3/Application/azure-resources-container-azurekvcsidriver/Container/backend\"}}"}]}}

**Steps To Reproduce**

**Expected behavior**

**AAD Pod Identity version**

**Kubernetes version**

**Additional context**

Could you please help us root cause the reason for deletion failure of the pod identity. Our code deletes the managed identity only after the pod identity is deleted.

**Comment by chewong** [comment]
What tool are you using to clean up pod identity resources?

**Comment by vinayada1** [comment]
We are calling the go-sdk API:-
```
func (handler *azurePodIdentityHandler) Delete(ctx context.Context, options DeleteOptions) error {
	if options.ExistingOutputResource.Identity.Kind != resourcemodel.IdentityKindAADPodIdentity {
		return fmt.Errorf("unexpected identity kind %q, needs to be %q", options.ExistingOutputResource.Identity.Kind, resourcemodel.IdentityKindAADPodIdentity)
	}

	identityData := options.ExistingOutputResource.Identity.Data.(resourcemodel.AADPodIdentityIdentity)
	podIdentityName := identityData.Name
	podidentityCluster := identityData.AKSClusterName

	// Conceptually this resource is always 'managed'

	mcc := clients.NewManagedClustersClient(handler.arm.SubscriptionID, handler.arm.Auth)

	// Get the cluster and modify it to remove pod identity
	managedCluster, err := mcc.Get(ctx, handler.arm.K8sResourceGroup, podidentityCluster)
	if err != nil {
		return fmt.Errorf("failed to get managed cluster: %w", err)
	}

	var identities []containerservice.ManagedClusterPodIdentity
	if managedCluster.ManagedClusterProperties.PodIdentityProfile.UserAssignedIdentities == nil {
		// Pod identity does not exist
		return nil
	}

	identities = *managedCluster.PodIdentityProfile.UserAssignedIdentities

	var i int
	var identity containerservice.ManagedClusterPodIdentity
	for i, identity = range *managedCluster.ManagedClusterProperties.PodIdentityProfile.UserAssignedIdentities {
		if *identity.Name == podIdentityName {
			break
		}
	}

	// Remove the pod identity at the matching index
	identities = append(identities[:i], identities[i+1:]...)

	mcFuture, err := mcc.CreateOrUpdate(ctx, handler.arm.K8sResourceGroup, podidentityCluster, containerservice.ManagedCluster{
		ManagedClusterProperties: &containerservice.ManagedClusterProperties{
			PodIdentityProfile: &containerservice.ManagedClusterPodIdentityProfile{
				Enabled:                   to.BoolPtr(true),
				AllowNetworkPluginKubenet: to.BoolPtr(false),
				UserAssignedIdentities:    &identities,
			},
		},
		Location: managedCluster.Location,
	})

	if err != nil {
		return fmt.Errorf("failed to delete pod identity on the cluster: %w", err)
	}

	err = mcFuture.WaitForCompletionRef(ctx, mcc.Client)
	if err != nil {
		return fmt.Errorf("failed to delete pod identity on the cluster: %w", err)
	}

	// Delete the managed identity
	err = handler.deleteManagedIdentity(ctx, *identity.Identity.ResourceID)
	if err != nil {
		return fmt.Errorf("failed to delete user assigned managed identity: %w", err)
	}

	return nil
}
```

Our delete code has been unchanged for around 9-10 months

**Comment by chewong** [comment]
I don't see how the problem is related to pod identity. The problem can either be related to ARM, AKS, or the Azure Go SDK.
