### ISSUE TITLE
After AKS cert renewal get token fails

### ISSUE THREAD

**Issue by PunithKumarB** [Azure/aad-pod-identity#1245]
**Have you**

- [ ] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [ ] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [ ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
1. We carried out [aks certs renewal](https://docs.microsoft.com/en-us/azure/aks/certificate-rotation) and as guide says - it does recreate the AKS nodes and their OS disks 
2. Before doing this operation all flows were normal. Our pods were getting the required token from AAD pod. After this step-1, we started seeing failure and MIC logs show error 403 - 
`E0207 10:57:10.547926 1 mic.go:1125] failed to apply binding default/mon-pod-id-binding node aks-agentpool-84******-vmss000000 for pod default/cs-metrics-monitoring-5687dcc8f4-jp6rr,error: failed to update identities for aks-agentpool-84******-vmss in MC_bright-monitoring-prod-oai-cluster_oai-cluster-cray-services-aks_centralus, error: compute.VirtualMachineScaleSetsClient#Update: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client '5627a48a-****-****-a530-049d27969aa4' with object id '5627a48a-****-****-a530-049d27969aa4' has permission to perform action 'Microsoft.Compute/virtualMachineScaleSets/write' on scope '/subscriptions/83e8cb0f-****-4c25-aeb2-3cf17219c6fd/resourceGroups/MC_bright-monitoring-prod-oai-cluster_oai-cluster-cray-services-aks_centralus/providers/Microsoft.Compute/virtualMachineScaleSets/aks-agentpool-84******-vmss'; however, it does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action' on the linked scope(s) '/subscriptions/83e8cb0f-****-4c25-aeb2-3cf17219c6fd/resourcegroups/bright-monitoring-prod-oai-cluster/providers/microsoft.managedidentity/userassignedidentities/bm-prod-oai-cluster-mi' or the linked scope(s) are invalid."`

3. We carried out the workaround discussed here - [585](https://github.com/Azure/aad-pod-identity/issues/585) and it worked 
`az aks show -g bright-****-prod-oai-cluster -n oai-cluster-cray-services-aks --query identityProfile.kubeletidentity.clientId -o tsv
az role assignment create --role "Contributor" --assignee 5627a48a-****-****-a530-049d27969aa4 --scope /subscriptions/83e8cb0f-****-4c25-aeb2-3cf17219c6fd/resourcegroups/bright-****-prod-oai-cluster`

**Steps To Reproduce**
Execute az aks renew certs, it can happen again

**Expected behavior**
Certificate renewal must not impact existing identity flows

**AAD Pod Identity version**
helm chart 4.1.3

**Kubernetes version**
1.20.7

**Additional context**
1. We want to confirm - why was this action of assigning the clientid to resource group as contributor required? Is this AAD problem or AKS?
2. The workaround steps carried out won't have other impacts during AAD upgrade?

**Comment by chewong** [comment]
As far as I know, rotating certificates won't affect the ability to acquire tokens. Based on the errors, your cluster identity doesn't have the permission to assign identities to the underlying VMSS. #585 or https://azure.github.io/aad-pod-identity/docs/troubleshooting/#linkedauthorizationfailed are the solution to this problem.

**Comment by sasound** [comment]
Hi @chewong ... The cluster identity (msi) in our AKS had the neccessary roles "Managed Identity Operator" & "Virtual Machine Contributor" on the AKS cluster resource. 
This setup was working fine for past several months. 

Post this cert activity, we had hit this issue.

Now why do we need to set privilege for the cluster identity at the Resource group level ?

**Comment by chewong** [comment]
> The cluster identity (msi) in our AKS had the necessary roles "Managed Identity Operator" & "Virtual Machine Contributor" on the AKS cluster resource.

Those roles should be assigned to the node resource group of the AKS cluster instead of the resource group of the AKS cluster (to get the node resource group of the aks cluster - `az aks show -g ... -n ... --query nodeResourceGroup -otsv`)
