### ISSUE TITLE
MIC reports HTTP 404 ( ResourceNotFound )  for nodes that are running and already part of cluster.

### ISSUE THREAD

**Issue by midhun-mohan** [Azure/aad-pod-identity#1246]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [x] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [x] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**

We are having a 6 node pool AKS cluster which is in version 1.22.4 and there are two nodes in our cluster with an error in our MIC pod logs. 
The two nodes with error are from 2 different nodepools.  The error is as below : 
`
E0202 12:28:32.412024       1 mic.go:1110] failed to get a list of user-assigned identites from node aks-monitorpool-xxxxxx-vmss000002, error: failed to get identity resource, error: failed to get vm aks-monitorpool-xxxxxx-vmss000002 in resource group MC_xxxxxxx_aks-prod-blue_westeurope, error: failed to get vm aks-monitorpool-xxxxxxx-vmss000002 in resource group MC_xxxxxx-rg_aks-prod-blue_westeurope, error: compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Compute/virtualMachines/aks-monitorpool-xxxxxxx-vmss000002' under resource group 'MC_xxxxxxx_aks-prod-blue_westeurope' was not found. For more details please go to [https://aka.ms/ARMResourceNotFoundFix]`

This error started after we upgraded our cluster from 1.21.2 to 1.22.4 last week. 

As a result of this, pods running in this nodes are not able to get identities.  

**Steps To Reproduce**

Not sure, if this is reproducible. But we have this errors in multiple nodes in multiple clusters in our subscription.  This started after an upgrade of cluster from version 1.21.2 to 1.22.4 using portal. 

**Expected behavior**
MIC pod does not have any errors and hence pods that are getting assigned to the nodes are running successfully and able to get access token to access azure resources.

**AAD Pod Identity version**
1.8.2

**Kubernetes version**
1.22.4

**Additional context**
I have a support ticket open with MS and the support ticket number is #2202020050001431

**Comment by aramase** [comment]
Hello 👋🏻 

That error is being returned from ARM for a GET call from MIC. Could you check the list of vmss by running `az vmss list -g <rg>`?

**Comment by midhun-mohan** [comment]
@aramase when using az vmss, the virtual machine scale set is listed. When using az vmss list-instances, the instance itself is is being listed. 
Support engineer had verified this from the backend too. 
Weird thing is in both the nodepools, 1/3 instances is having issues. 
Feel free to reach out to me if you need more info.

**Comment by aramase** [comment]
MIC adds a user agent as part of the API requests. Could the support engineer check for requests with `aad-pod-identity` user agent to see why the ARM calls are returning an error?

**Comment by midhun-mohan** [comment]
@aramase I will ask the support engineer to check  with the engineering team to check the backend logs of management APIs. 

Is there a chance you can take this internally with the team managing the API internally.  All the details of the instances are present in the support ticket mentioned above.

**Comment by midhun-mohan** [comment]
@aramase The support engineer was able to find the back end logs and found out that the resource id format used in the payload is malformed. 

Below is a snippet from the email which I am having with the support engineer
```
by searching for the userAgent of aad-pod-identity it seems that the requests are sent for the following resource: 

/subscriptions/xxxxxxxxxxxx/resourceGroups/MC_vipps-prod-blue-rg_aks-prod-blue_westeurope/providers/Microsoft.Compute/virtualMachines/aks-monitorpool-xxxxxxxxxx-vmss000002

The correct Id for this should be

/subscriptions/xxxxxxxxxxxxx/resourceGroups/MC_vipps-prod-blue-rg_aks-prod-blue_westeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aks-monitorpool-xxxxxxxx-vmss/virtualMachines/aks-monitorpool-xxxxxxx-vmss_2
```
Can you please shed some insight on what can cause this issues and what should be the way forward so that we can fix this issue ?

**Comment by zhiweiv** [comment]
We hit this error too.

**Comment by midhun-mohan** [comment]
@aramase Do you have some insights on this ?
@zhiweiv Did it happen for you after an upgrade of cluster / nodepool ?

**Comment by aramase** [comment]
> Can you please shed some insight on what can cause this issues and what should be the way forward so that we can fix this issue ?

MIC uses the providerID in the kubernetes node to determine if the VM is part of a VM/VMSS. Could you share the `kubectl describe node` output for the nodes with the issue? Also, could you enable debug logging in MIC by setting `-v=5` in MIC args and share the logs?

**Comment by aramase** [comment]
@chmill-zz from AKS shared the output from `kubectl describe node` output for instance 2 which has the issue. Only that node is missing the `providerID` which is why MIC can't determine if it's part of a VM/VMSS. The `providerID` not being set would be a bug with cloud provider and the AKS team will look at it to see why it's missing only for this single node.

**Comment by midhun-mohan** [comment]
@aramase That is interesting find.  We do have multiple clusters in our environment affected by this **"bug".** 
Do you still want me to enable more verbose logging in MIC and share the logs as the issue seems to be identified.

**Comment by aramase** [comment]
> @aramase That is interesting find. We do have multiple clusters in our environment affected by this "cloud provider bug".
Do you still want me to enable more verbose logging in MIC and share the logs as the issue seems to be identified.

No, we don't need the MIC logs anymore. If the `providerID` is set and MIC still thinks it's a VM, then we can look at the MIC logs. For now just the root cause from AKS for why providerID is not set should help resolve the issue.

**Comment by midhun-mohan** [comment]
I looked on one of the problematic nodes from my environment and i can also confirm **ProviderID** is not set. 
Is there a way I can know the status of the investigation by the AKS team as it progresses ?

**Comment by aramase** [comment]
> I looked on one of the problematic nodes from my environment and i can also confirm ProviderID is not set.
Is there a way I can know the status of the investigation by the AKS team as it progresses ?

You can track the status with the support ticket you've open

**Comment by midhun-mohan** [comment]
Thanks. I will follow the support ticket to know the status.

**Comment by zhiweiv** [comment]
Any update? we have more pools which hit this error,  it did happen after aks/nodepool upgrade.

**Comment by zhiweiv** [comment]
It seems traced in https://github.com/kubernetes-sigs/cloud-provider-azure/issues/1155.

**Comment by zhiweiv** [comment]
The fix has been in latest cloud provider azure release, we can wait AKS to update the cloud-node-manager.

**Comment by zhiweiv** [comment]
In my AKS the cloud-node-manager version is 1.23.5 which contains the fix.
