### ISSUE TITLE
"getting assigned identities for pod ... in CREATED state failed after 16 attempts" due to problems in MIC container

### ISSUE THREAD

**Issue by darose** [Azure/aad-pod-identity#1255]
**Describe the bug**
We are regularly running into issues using aad-pod-identity on our AKS clusters.  This is happening several times a day on each of our clusters.

Pods will generally be able to use aad-pod-identity fine most of the time.  Then suddenly, there will be a problem in the MIC pod, and any new pods that launch during this time fail with "getting assigned identities for pod ... in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors".  After 10-15 minutes the problem clears up and pods can run again as normal.

The problems in the MIC pod seem to take one of a few forms:
1. The MIC container/pod dies and gets restarted.
2. The MIC container/pod dies and gets restarted, and takes a long time (like 15m) to re-acquire the leader lease.
3. The MIC container/pod remains running, but takes a long time (again, like 15m) to perform a call to assign identity

During any of these 3 scenarios pods that are trying to acquire an identity will fail with a "getting assigned identities for pod ... in CREATED state failed after 16 attempts ..." message.

**Steps To Reproduce**
I do not have steps to reliably reproduce.  But the issue does keep recurring intermittently.

**Expected behavior**
aad-pod-identity should work properly and be able to assign identities nearly all the time.  (Should not have recurring problems.)

**AAD Pod Identity version**
1.8.7

**Kubernetes version**
1.20.13

**Additional context**
I've managed to capture some log output from the MIC pod for the failure scenarios I mentioned above.

General failure messages we're seeing:
```
E0304 14:45:19.050652       1 server.go:399] failed to get matching identities for pod: <redacted>, error: getting assigned identities for pod <redacted> in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors
I0304 14:45:19.050693       1 server.go:213] status (404) took 80020519607 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=172.18.9.63
```

For scenario #2 (takes a long time to re-acquire the leader lease):

Note that the following call to acquire the lease takes over 15 minutes to complete:
```
I0304 14:58:34.050255       1 leaderelection.go:248] attempting to acquire leader lease default/aad-pod-identity-mic...
I0304 15:16:36.385681       1 leaderelection.go:258] successfully acquired lease default/aad-pod-identity-mic
```

For scenario #3 (takes a long time to perform a call):

Note that the following call to assign an identity takes over 15 minutes to complete:
```
I0310 11:19:36.380328       1 mic.go:587] pod <redacted> has no assigned node yet. it will be ignored
I0310 11:19:36.424498       1 mic.go:1040] processing node aks-nodepool<redacted>-vmss, add [1], del [0], update [0]
I0310 11:19:36.424573       1 crd.go:514] creating assigned id <redacted>
I0310 11:36:24.041685       1 crd.go:777] updating AzureAssignedIdentity <redacted> status to Assigned
```

Stats from a normal set of calls:
```
I0310 19:34:06.650110       1 stats.go:183] ** stats collected **
I0310 19:34:06.650199       1 stats.go:162] Pod listing: 60.699µs
I0310 19:34:06.650211       1 stats.go:162] AzureIdentity listing: 43.2µs
I0310 19:34:06.650217       1 stats.go:162] AzureIdentityBinding listing: 32.7µs
I0310 19:34:06.650222       1 stats.go:162] AzureAssignedIdentity listing: 312.799µs
I0310 19:34:06.650228       1 stats.go:162] System: 722.898µs
I0310 19:34:06.650233       1 stats.go:162] CacheSync: 4.2µs
I0310 19:34:06.650238       1 stats.go:162] Cloud provider GET: 90.046983ms
I0310 19:34:06.650244       1 stats.go:162] Cloud provider PATCH: 0s
I0310 19:34:06.650250       1 stats.go:162] AzureAssignedIdentity creation: 21.275749ms
I0310 19:34:06.650266       1 stats.go:162] AzureAssignedIdentity update: 0s
I0310 19:34:06.650272       1 stats.go:162] AzureAssignedIdentity deletion: 0s
I0310 19:34:06.650278       1 stats.go:170] Number of cloud provider PATCH: 0
I0310 19:34:06.650284       1 stats.go:170] Number of cloud provider GET: 1
I0310 19:34:06.650289       1 stats.go:170] Number of AzureAssignedIdentities created in this sync cycle: 1
I0310 19:34:06.650294       1 stats.go:170] Number of AzureAssignedIdentities updated in this sync cycle: 0
I0310 19:34:06.650299       1 stats.go:170] Number of AzureAssignedIdentities deleted in this sync cycle: 0
I0310 19:34:06.650304       1 stats.go:162] Find AzureAssignedIdentities to create: 171.299µs
I0310 19:34:06.650311       1 stats.go:162] Find AzureAssignedIdentities to delete: 147µs
I0310 19:34:06.650318       1 stats.go:162] Total time to assign or update AzureAssignedIdentities: 124.623101ms
I0310 19:34:06.650324       1 stats.go:162] Total: 136.622572ms
I0310 19:34:06.650329       1 stats.go:212] *********************
```

Stats from the set of calls that takes > 15 mins to complete:
```
I0310 11:36:24.068346       1 mic.go:525] work done: true. Found 48 pods, 11 ids, 11 bindings
I0310 11:36:24.068381       1 mic.go:526] total work cycles: 1166, out of which work was done in: 420
I0310 11:36:24.068410       1 stats.go:183] ** stats collected **
I0310 11:36:24.068415       1 stats.go:162] Pod listing: 32.2µs
I0310 11:36:24.068423       1 stats.go:162] AzureIdentity listing: 20.8µs
I0310 11:36:24.068427       1 stats.go:162] AzureIdentityBinding listing: 34µs
I0310 11:36:24.068431       1 stats.go:162] AzureAssignedIdentity listing: 211.299µs
I0310 11:36:24.068434       1 stats.go:162] System: 566.897µs
I0310 11:36:24.068438       1 stats.go:162] CacheSync: 4.1µs
I0310 11:36:24.068441       1 stats.go:162] Cloud provider GET: 16m47.588432053s
I0310 11:36:24.068445       1 stats.go:162] Cloud provider PATCH: 0s
I0310 11:36:24.068559       1 stats.go:162] AzureAssignedIdentity creation: 28.58795ms
I0310 11:36:24.068567       1 stats.go:162] AzureAssignedIdentity update: 0s
I0310 11:36:24.068571       1 stats.go:162] AzureAssignedIdentity deletion: 0s
I0310 11:36:24.068575       1 stats.go:170] Number of cloud provider PATCH: 0
I0310 11:36:24.068579       1 stats.go:170] Number of cloud provider GET: 1
I0310 11:36:24.068583       1 stats.go:170] Number of AzureAssignedIdentities created in this sync cycle: 1
I0310 11:36:24.068586       1 stats.go:170] Number of AzureAssignedIdentities updated in this sync cycle: 0
I0310 11:36:24.068596       1 stats.go:170] Number of AzureAssignedIdentities deleted in this sync cycle: 0
I0310 11:36:24.068616       1 stats.go:162] Find AzureAssignedIdentities to create: 96µs
I0310 11:36:24.068624       1 stats.go:162] Find AzureAssignedIdentities to delete: 77.399µs
I0310 11:36:24.068631       1 stats.go:162] Total time to assign or update AzureAssignedIdentities: 16m47.643854438s
I0310 11:36:24.068638       1 stats.go:162] Total: 16m47.682799834s
I0310 11:36:24.068645       1 stats.go:212] *********************
```

**Comment by aramase** [comment]
Thanks for the detailed info!

From the logs, it looks like the cloud GET API calls are taking time: 
```
I0310 11:36:24.068441       1 stats.go:162] Cloud provider GET: 16m47.588432053s
```

That is a ARM GET api call to get the VM/VMSS. If you're seeing this GET call take time in the order of minutes, I would recommend opening a support ticket for this so that team can investigate. 

For scenario (2), are both the MIC pods stuck in acquiring leader lease? At any time one of the MIC pods would be the leader. The other pod will keep retrying to acquire the lease in case the leader goes down.

Could you provide more info on why MIC pod is dying and restarting in your cluster? Is it failing livenessprobe?

Pod Identity also has a managed mode: https://azure.github.io/aad-pod-identity/docs/configure/pod_identity_in_managed_mode/. This mode has no MIC and no identity assignment delays, just NMI. Check it out!

Also, As mentioned in the [announcement](https://cloudblogs.microsoft.com/opensource/2022/01/18/announcing-azure-active-directory-azure-ad-workload-identity-for-kubernetes/), we are planning to replace AAD Pod Identity with [Azure Workload Identity](https://azure.github.io/azure-workload-identity). I would recommend checking out Azure Workload Identity.

**Comment by darose** [comment]
Thanks much for the feedback @aramase.

> That is a ARM GET api call to get the VM/VMSS. If you're seeing this GET call take time in the order of minutes, I would recommend opening a support ticket for this so that team can investigate.

I opened a ticket for this yesterday.  (2203160040008847)
> For scenario (2), are both the MIC pods stuck in acquiring leader lease? At any time one of the MIC pods would be the leader. The other pod will keep retrying to acquire the lease in case the leader goes down.

IIRC, only one pod was stuck acquiring the lease.

> Could you provide more info on why MIC pod is dying and restarting in your cluster? Is it failing livenessprobe?

I don't have too much visibility into this, but doing a "kubectl describe pods" on one of the mic pods on one of our clusters currently shows the following:

```
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Sun, 13 Mar 2022 12:36:49 -0400
      Finished:     Sun, 13 Mar 2022 12:36:51 -0400
```

> Pod Identity also has a managed mode: https://azure.github.io/aad-pod-identity/docs/configure/pod_identity_in_managed_mode/. This mode has no MIC and no identity assignment delays, just NMI. Check it out!

I'll look into this and see if it's an option.  However, as I wrote above, I'm speculating that these delays/outages might be caused by the Azure API throttling our calls.  If that is indeed the case, then wouldn't we just experience the same issue in managed mode?

> Also, As mentioned in the [announcement](https://cloudblogs.microsoft.com/opensource/2022/01/18/announcing-azure-active-directory-azure-ad-workload-identity-for-kubernetes/), we are planning to replace AAD Pod Identity with [Azure Workload Identity](https://azure.github.io/azure-workload-identity). I would recommend checking out Azure Workload Identity.

Sounds like that might be useful for the future.  But if I'm reading correctly, it sounds like Workload doesn't yet work with managed identities, and so wouldn't solve this problem for us.

**Comment by wanglijun378617** [comment]
Hi @aramase , regarding the ARM GET api call to get the VM/VMSS, 
I0310 11:36:24.068441       1 stats.go:162] Cloud provider GET: 16m47.588432053s
I checked around the above timestamp, I did observe that there are multiple ARM requests coming to GET the VMSS around that time, but no incoming requests for like 16 minutes(from 11:19~11:36), and I didn't observe there is 429 request throttling. May I know how to check further?

====================
<HTML><HEAD><TITLE>From Clipboard</TITLE></HEAD><BODY>

PreciseTimeStamp | clientIpAddress | httpMethod | httpStatusCode | userAgent | operationName
-- | -- | -- | -- | -- | --
2022-03-10 11:18:39.3050993 | 52.167.251.49 | GET | -1 | Go/go1.17.6 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v57.2.0 compute/2019-12-01 aad-pod-identity/MIC/v1.8.7/360d96f/2022-02-10-01:11 | GET/SUBSCRIPTIONS/RESOURCEGROUPS/PROVIDERS/MICROSOFT.COMPUTE/VIRTUALMACHINESCALESETS/
2022-03-10 11:18:39.3604607 | 52.167.251.49 | GET | 200 | Go/go1.17.6 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v57.2.0 compute/2019-12-01 aad-pod-identity/MIC/v1.8.7/360d96f/2022-02-10-01:11 | GET/SUBSCRIPTIONS/RESOURCEGROUPS/PROVIDERS/MICROSOFT.COMPUTE/VIRTUALMACHINESCALESETS/
2022-03-10 11:19:04.3388032 | 52.167.251.49 | GET | -1 | Go/go1.17.6 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v57.2.0 compute/2019-12-01 aad-pod-identity/MIC/v1.8.7/360d96f/2022-02-10-01:11 | GET/SUBSCRIPTIONS/RESOURCEGROUPS/PROVIDERS/MICROSOFT.COMPUTE/VIRTUALMACHINESCALESETS/
**2022-03-10 11:19:04.3799494** | 52.167.251.49 | GET | 200 | Go/go1.17.6 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v57.2.0 compute/2019-12-01 aad-pod-identity/MIC/v1.8.7/360d96f/2022-02-10-01:11 | GET/SUBSCRIPTIONS/RESOURCEGROUPS/PROVIDERS/MICROSOFT.COMPUTE/VIRTUALMACHINESCALESETS/
**2022-03-10 11:36:23.9710420** | 52.167.251.49 | GET | -1 | Go/go1.17.6 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v57.2.0 compute/2019-12-01 aad-pod-identity/MIC/v1.8.7/360d96f/2022-02-10-01:11 | GET/SUBSCRIPTIONS/RESOURCEGROUPS/PROVIDERS/MICROSOFT.COMPUTE/VIRTUALMACHINESCALESETS/
2022-03-10 11:36:24.0286249 | 52.167.251.49 | GET | 200 | Go/go1.17.6 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v57.2.0 compute/2019-12-01 aad-pod-identity/MIC/v1.8.7/360d96f/2022-02-10-01:11 | GET/SUBSCRIPTIONS/RESOURCEGROUPS/PROVIDERS/MICROSOFT.COMPUTE/VIRTUALMACHINESCALESETS/
2022-03-10 11:36:24.2816739 | 52.167.251.49 | GET | -1 | Go/go1.17.6 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v57.2.0 compute/2019-12-01 aad-pod-identity/MIC/v1.8.7/360d96f/2022-02-10-01:11 | GET/SUBSCRIPTIONS/RESOURCEGROUPS/PROVIDERS/MICROSOFT.COMPUTE/VIRTUALMACHINESCALESETS/
2022-03-10 11:36:24.4197927 | 52.167.251.49 | GET | 200 | Go/go1.17.6 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v57.2.0 compute/2019-12-01 aad-pod-identity/MIC/v1.8.7/360d96f/2022-02-10-01:11 | GET/SUBSCRIPTIONS/RESOURCEGROUPS/PROVIDERS/MICROSOFT.COMPUTE/VIRTUALMACHINESCALESETS/


</BODY></HTML>

**Comment by aramase** [comment]
> IIRC, only one pod was stuck acquiring the lease.

That is expected and is the leader election model. At any given time, 1 pod is the leader and other pod is waiting to acquire the lease. When the leader dies, the backup pod will acquire the lease and become the leader. 

> I'll look into this and see if it's an option. However, as I wrote above, I'm speculating that these delays/outages might be caused by the Azure API throttling our calls. If that is indeed the case, then wouldn't we just experience the same issue in managed mode?

In case of the default mode, pod identity has MIC and NMI. MIC does a lazy identity assignment (assigns the identity to the VMSS when the first pod using it is created and deletes the identity when the last pod using it is deleted). In case of managed mode, there is no MIC, just NMI. The identities are manually assigned which means there are no identity assignment delays when the workload pods are created. NMI will still ensure only pods that have access to the identity can request a token for the identity. 

> Sounds like that might be useful for the future. But if I'm reading correctly, it sounds like Workload doesn't yet work with managed identities, and so wouldn't solve this problem for us.

AAD Managed identity support is in progress. The current model with Azure AD applications + workload identity doesn't require any secrets either.

**Comment by darose** [comment]
OK, thanks.  I'm working on testing pod identity in managed mode.  Will see how that goes.

**Comment by ryanbradley7** [comment]
In case it helps anyone else, using AAD Pod Identity in "managed mode" resolved this issue for us. 

see
[https://github.com/Azure/aad-pod-identity/issues/1267](url)

**Comment by 64J0** [comment]
I'm also getting this error
