### ISSUE TITLE
Supportability of AAD-POD

### ISSUE THREAD

**Issue by sasound** [Azure/aad-pod-identity#1257]
Hi @aramase  / @chewong 

With no more feature additions to AAD-POD identity project. I have a few compatibility related qns :
 - Currently I have AKS  cluster with 1.20.7 & 1.21.9 . Will AAD pod continue to work as expected ?
 - What is the max compatibility level after which AAD pod identity will break ?

**Comment by chewong** [comment]
1. Yes it will continue working.
2. I don't see why it wouldn't work on future Kubernetes releases but we recommend checking out https://github.com/Azure/azure-workload-identity.

**Comment by ondrejhlavacek** [comment]
I have a similar question. We have some issues with AAD Pod Identity - it seems to slow down significantly with peaking traffic and it throws some errors or log messages I don't fully understand. What is the best place to start debugging and where to report/ask for help? Thanks

**Comment by aramase** [comment]
> I have a similar question. We have some issues with AAD Pod Identity - it seems to slow down significantly with peaking traffic and it throws some errors or log messages I don't fully understand. What is the best place to start debugging and where to report/ask for help? Thanks

- Here is our troubleshooting guide: https://azure.github.io/aad-pod-identity/docs/troubleshooting/. You can look at the logs to determine what's taking time.
- If you run into any problems/bug, you can open a GitHub issue in this repo. This project is currently in maintenance mode and we'll continue patching critical bugs and security vulnerabilities.
- We recommend evaluating and switching to https://github.com/Azure/azure-workload-identity as it overcomes the limitations with the current AAD Pod Identity design.

**Comment by ondrejhlavacek** [comment]
@aramase Thanks, I have opened an issue here. Is Azure Workload Identity in GA? It seems to be still in preview - https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#oidc-issuer-preview.
