### ISSUE TITLE
Renewing Service Principal credentials fails to update Kubernetes Secret if aad-pod-identity was installed via Helm

### ISSUE THREAD

**Issue by florianpiesche** [Azure/aad-pod-identity#1262]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [x] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [x] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
We have an AKS cluster with some microservices that pull configuration information from an Azure Key Vault, using aad-pod-identity and a service principal. As per standard Azure behaviour, the service principal credentials will expire after a year and need updating manually [as per the Azure documentation](https://docs.microsoft.com/en-us/azure/aks/update-credentials#update-aks-cluster-with-new-service-principal-credentials).

Following the above documentation to update the service principal credentials appears to work and the call to `az aks update-credentials` causes the nodes in the cluster to be re-created with the updated credentials in `/etc/kubernetes/azure.json`. However, the `aad-pod-identity` pods still fail to authenticate with the key vault; after some investigation we figured out that this is because the `aad-pod-identity-mic` Kubernetes `Secret` in the cluster still had the old `ClientSecret` in it, which in turn is exported into the pods as an environment variable.

This means that when just running the `az aks update-credentials` step as per the Azure documentation, this appears to work, takes down each node and brings it back up, but in fact doesn't work a the new aad-pod-identity containers fail to authenticate with the service principal and instead receive a HTTP 401 response (sadly we no longer have .

Manually updating the `ClientSecret` value in the `aad-pod-identity` Kubernetes Secret resource to the new Service Principal password immediately resolved the issue.

**Steps To Reproduce**

Our setup is very complex so I've not been able to try building a minimal reproduction case, but I believe this should do the job:

* Create an AKS cluster, an Azure key vault and a service principal allowing access to the key vault
* Deploy `aad-pod-identity` to the cluster via Helm:
  ```
    helm repo add aad-pod-identity https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts
    helm upgrade --install aad-pod-identity aad-pod-identity/aad-pod-identity \
        --set nmi.allowNetworkPluginKubenet=true \
        --set adminsecret.cloud="AzurePublicCloud" \
        --set adminsecret.subscriptionID=$AZURE_SUBSCRIPTION_ID \
        --set adminsecret.resourceGroup=$K8S_NODE_RESOURCE_GROUP_NAME \
        --set adminsecret.vmType=vmss \
        --set adminsecret.clientID=$SERVICE_PRINCIPAL_APPID \
        --set adminsecret.tenantID=$SERVICE_PRINCIPAL_APP_OWNER_TENANT_ID \
        --set adminsecret.clientSecret=$SERVICE_PRINCIPAL_PASSWORD```
* Deploy an app to the cluster that uses the key vault

This should give you the initial state, where the aad-pod-identity service is running in the cluster and the app can connect to the key vault. To break this now:

* Regenerate the Service Principal's password: `SERVICE_PRINCIPAL_SECRET=$(az ad sp credential reset --name "$SERVICE_PRINCIPAL_APPID" --query password -o tsv)`
* Update the cluster with the new details:
   ```
    az aks update-credentials \
    --resource-group $K8S_NODE_RESOURCE_GROUP_NAME \
    --name myAKSCluster \
    --reset-service-principal \
    --service-principal "$SERVICE_PRINCIPAL_APPID" \
    --client-secret "${SERVICE_PRINCIPAL_SECRET:Q}"
    ```
* Wait for the process to finish and check the logs on the aad-pod-identity containers to see (hopefully) 401 errors.

* Manually find the `aad-pod-identity-mic` Secret in the AKS cluster and edit it, updating the `ClientSecret` value to the new Service Principal password. Restart the aad-pod-identity pods and note the authentication now works.

**Expected behavior**

The nodes restart and the service in the cluster can access the key vault. I'm not sure if the non-Helm installation option for aad-pod-identity also uses an in-cluster Secret for the authentication; is it possible that this isn't getting updated because it has the `app.kubernetes.io/managed-by: helm` annotation?

**AAD Pod Identity version**: 1.7.4
**AAD Pod Identity Helm Chart version**: 3.0.3
**Kubernetes version**: 1.21.9
**Additional context**: None.

**Comment by chewong** [comment]
adminsecret is only used if you don't want MIC to reuse the same credential as the AKS cluster. Based on your setup, it looks like MIC and your AKS cluster is sharing the same credential so `az aks update-credentials` should work after you remove adminsecret.

Also, using a service principal is an `anti-pattern` due to the risk of leaking the secret. I'd suggest using managed identity when possible.
