### ISSUE TITLE
AAD Pod Identity to Event Hub

### ISSUE THREAD

**Issue by juliolopez-mx** [Azure/aad-pod-identity#1268]
**Describe the request**

Can I use AAD Pod Identity to connect to an Azure Event Hub topic?  Is there some Java code sample I can view.  I'm using a AuthenticateCallbackHandler and I'm trying to see how this fits with the DefaultAzureCredential.

**Comment by aramase** [comment]
@juliolopez-mx AAD Pod Identity is only a proxy that intercepts managed identity token requests to IMDS. It doesn't require any code changes specifically to work with this project. If you already have an application that's using Azure Identity SDKs, it should work with AAD Pod Identity installed in the cluster too. Here are some examples we have: https://github.com/Azure/aad-pod-identity/tree/master/examples

Please note, AAD Pod Identity is soon going to be replaced with Azure Workload Identity. I would recommend starting off with [Azure Workload Identity](https://github.com/Azure/azure-workload-identity).

ref: https://github.com/Azure/aad-pod-identity#aad-pod-identity
❗ IMPORTANT: As mentioned in the [announcement](https://cloudblogs.microsoft.com/opensource/2022/01/18/announcing-azure-active-directory-azure-ad-workload-identity-for-kubernetes/), we are planning to replace AAD Pod Identity with [Azure Workload Identity](https://azure.github.io/azure-workload-identity). Going forward, we will no longer add new features to this project in favor of Azure Workload Identity. However, we will continue patching critical bugs and security vulnerabilities until further notice.

**Comment by ozgen** [comment]
I wrote the sample code in [stackoverflow](https://stackoverflow.com/questions/63978696/azure-aad-pod-identity-with-azure-event-hub) in java.
