### ISSUE TITLE
MIC PODs crashing - panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ernesto1596** [Azure/aad-pod-identity#1269]
**Describe the bug**
I0418 16:48:04.883307       1 main.go:114] starting mic process. Version: v1.7.3. Build date: 2021-02-05-22:16
W0418 16:48:04.883362       1 main.go:119] --kubeconfig not passed will use InClusterConfig
I0418 16:48:04.883369       1 main.go:136] kubeconfig () cloudconfig (/etc/kubernetes/azure.json)
I0418 16:48:04.883495       1 main.go:144] running MIC in namespaced mode: false
I0418 16:48:04.883507       1 main.go:148] client QPS set to: 5. Burst to: 5
I0418 16:48:04.883524       1 mic.go:139] starting to create the pod identity client. Version: v1.7.3. Build date: 2021-02-05-22:16
I0418 16:48:04.901684       1 mic.go:145] Kubernetes server version: v1.21.7
I0418 16:48:04.901954       1 cloudprovider.go:123] MIC using user assigned identity: 2f42##### REDACTED #####e308 for authentication.
I0418 16:48:04.976389       1 probes.go:41] initialized health probe on port 8080
I0418 16:48:04.976409       1 probes.go:44] started health probe
I0418 16:48:04.976503       1 metrics.go:341] registered views for metric
I0418 16:48:04.976564       1 prometheus_exporter.go:21] starting Prometheus exporter
I0418 16:48:04.976579       1 metrics.go:347] registered and exported metrics on port 8888
I0418 16:48:04.976585       1 mic.go:240] initiating MIC Leader election
I0418 16:48:04.976593       1 leaderelection.go:243] attempting to acquire leader lease  default/aad-pod-identity-mic...
I0418 16:48:04.987891       1 leaderelection.go:253] successfully acquired lease default/aad-pod-identity-mic
I0418 16:48:04.993478       1 mic.go:328] type upgrade status configmap found from version: v1.7.3. Skipping type upgrade!
I0418 16:48:05.293850       1 crd.go:456] CRD informers started
I0418 16:48:06.393760       1 pod.go:72] pod cache synchronized. Took 1.400244506s
I0418 16:48:06.393780       1 pod.go:79] pod watcher started !!
I0418 16:48:06.393795       1 mic.go:398] sync thread started.
I0418 16:48:06.398194       1 mic.go:1023] processing node aks-default-10878206-vmss, add [69], del [73], update [0]
I0418 16:52:28.403124       1 cloudprovider.go:210] updating user-assigned identities on aks-default-10878206-vmss, assign [5], unassign [0]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xe17be8]

goroutine 137 [running]:
github.com/Azure/aad-pod-identity/pkg/cloudprovider.(*VMSSClient).UpdateIdentities(0xc000498000, 0xc0002c1000, 0x3d, 0xc0027062e3, 0x19, 0x0, 0x0, 0x0, 0x0, 0xc00234d350, ...)
	/go/src/github.com/Azure/aad-pod-identity/pkg/cloudprovider/vmss.go:66 +0x68
github.com/Azure/aad-pod-identity/pkg/cloudprovider.(*Client).getIdentityResource.func1(0x22bcd18507519, 0x18076f31)
	/go/src/github.com/Azure/aad-pod-identity/pkg/cloudprovider/cloudprovider.go:256 +0xd5
github.com/Azure/aad-pod-identity/pkg/retry.(*client).Do(0xc0002bce20, 0xc00125c180, 0xc001945560, 0x0, 0x18c2fc6)
	/go/src/github.com/Azure/aad-pod-identity/pkg/retry/retry.go:49 +0x2b
github.com/Azure/aad-pod-identity/pkg/cloudprovider.(*Client).UpdateUserMSI(0xc00013c1a0, 0xc002802000, 0x5, 0x8, 0x0, 0x0, 0x0, 0xc0027062e3, 0x19, 0x1, ...)
	/go/src/github.com/Azure/aad-pod-identity/pkg/cloudprovider/cloudprovider.go:237 +0x3de
github.com/Azure/aad-pod-identity/pkg/mic.(*Client).updateUserMSI(0xc0001a00e0, 0xc0024003f0, 0xc0027062e3, 0x19, 0xc002772000, 0x45, 0x80, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:1092 +0x8cd
created by github.com/Azure/aad-pod-identity/pkg/mic.(*Client).updateNodeAndDeps
	/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:1016 +0x19b

**AAD Pod Identity version**
- 1.7.3

**Kubernetes version**
- 1.21.7

**Additional context**

Similar issue to #959 

Our AKS cluster was running with this configuration for 3 months before running into this issue. Now it is unable to get out of this state. We deployed another AKS cluster with the same MIC version and AKS version and the issue is not reproducing.

**Comment by aramase** [comment]
Thanks for opening the issue!

Looks like you're running `v1.7.3` release which is at least a year old. We have patches numerous bugs including this in the later releases. I would recommend upgrading to the latest.

If you run into similar issues with the latest release, please let us know here and we can look at the logs.

**Comment by ernesto1596** [comment]
@aramase thanks for the suggestions. I'll work on getting the latest version of the MIC running on our new clusters. The issue/confusion comes from why it works on one cluster but not another.

**Comment by aramase** [comment]
> @aramase thanks for the suggestions. I'll work on getting the latest version of the MIC running on our new clusters. The issue/confusion comes from why it works on one cluster but not another.

AFAIK, the nil pointer bug was caused because of an unhandled exception when the VMSS is in provisioning state. That can explain the difference in behavior between clusters.

**Comment by ernesto1596** [comment]
How long would a VMSS be in a provisioning state though? The cluster has been like this for over a week without any changes.

**Comment by ernesto1596** [comment]
I've upgraded the cluster to the latest version (1.8.8). We are no longer seeing this issue but still unable to get the pod identity assigned to the pods.

```
I0419 23:39:28.244314       1 main.go:88] starting nmi process. Version: v1.8.8. Build date: 2022-04-01-20:31.
I0419 23:39:28.244365       1 main.go:101] features for scale clusters enabled
I0419 23:39:28.347033       1 crd.go:448] CRD lite informers started 
I0419 23:39:28.547226       1 main.go:115] running NMI in namespaced mode: false
I0419 23:39:28.547258       1 nmi.go:53] initializing in standard mode
I0419 23:39:28.547266       1 probes.go:41] initialized health probe on port 8085
I0419 23:39:28.547273       1 probes.go:44] started health probe
I0419 23:39:28.547345       1 metrics.go:341] registered views for metric
I0419 23:39:28.547439       1 prometheus_exporter.go:21] starting Prometheus exporter
I0419 23:39:28.547451       1 metrics.go:347] registered and exported metrics on port 9090
I0419 23:39:28.547518       1 server.go:107] listening on port 2579
W0419 23:39:28.649169       1 iptables.go:123] flushing iptables to add aad-metadata custom chains
I0419 23:39:29.190231       1 standard.go:73] no clientID or resourceID in request. <pod-name> has been matched with azure identity <identity-name>
I0419 23:39:29.190306       1 standard.go:179] matched identityType:0 clientid:2c88##### REDACTED #####e49a resource:https://vault.azure.net
I0419 23:41:00.126588       1 standard.go:73] no clientID or resourceID in request. <pod-name> has been matched with azure identity <identity-name>
I0419 23:41:00.126649       1 standard.go:179] matched identityType:0 clientid:ad7d##### REDACTED #####1a9f resource:https://vault.azure.net
E0419 23:41:13.874750       1 server.go:399] failed to get matching identities for pod: <pod-name>, error: getting assigned identities for pod <pod-name> in ASSIGNED state failed after 20 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors
I0419 23:41:13.874868       1 server.go:213] status (404) took 100014941899 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.2.5.65
E0419 23:41:14.871587       1 server.go:399] failed to get matching identities for pod: <pod-name>, error: getting assigned identities for pod <pod-name> in ASSIGNED state failed after 20 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors
I0419 23:41:14.871651       1 server.go:213] status (404) took 100017992641 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.2.5.119
E0419 23:42:53.044178       1 server.go:399] failed to get matching identities for pod: <pod-name>, error: context canceled
I0419 23:42:53.044227       1 server.go:213] status (404) took 98067959601 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.2.5.119
E0419 23:42:53.991554       1 server.go:399] failed to get matching identities for pod: <pod-name>, error: getting assigned identities for pod <pod-name> in ASSIGNED state failed after 20 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors
I0419 23:42:53.991611       1 server.go:213] status (404) took 100012169960 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.2.5.65
E0419 23:43:51.199687       1 server.go:261] failed to get service principal token for pod:<pod-name>, error: adal: Failed to execute the refresh request. Error = 'Get "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&client_id=<client-id>&resource=https%3A%2F%2Fvault.azure.net": dial tcp 169.254.169.254:80: i/o timeout'
I0419 23:43:51.199736       1 server.go:213] status (503) took 262009720370 ns for req.method=GET reg.path=/host/token/ req.remote=127.0.0.1
I0419 23:43:51.201807       1 standard.go:73] no clientID or resourceID in request. <pod-name> has been matched with azure identity <identity-name>
I0419 23:43:51.201863       1 standard.go:179] matched identityType:0 clientid:2c88##### REDACTED #####e49a resource:https://vault.azure.net
E0419 23:44:13.040241       1 server.go:399] failed to get matching identities for pod: <pod-name>, error: context canceled
I0419 23:44:13.040283       1 server.go:213] status (404) took 78744219280 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.2.5.65
I0419 23:45:02.218809       1 standard.go:73] no clientID or resourceID in request. <pod-name> has been matched with azure identity <identity-name>
I0419 23:45:02.218859       1 standard.go:179] matched identityType:0 clientid:ad7d##### REDACTED #####1a9f resource:https://vault.azure.net
```

one of the MIC pods got the following error as well:
```
E0420 14:17:11.137806       1 mic.go:1457] failed to generate identity assignment state, error: failed to get a list of user-assigned identites from node aks-default-10878206-vmss, error: failed to get identity resource, error: failed to get vmss aks-default-10878206-vmss in resource group <resource name>, error: failed to get vmss aks-default-10878206-vmss in resource group <resource name>, error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/<subscription-id>/resourceGroups/<resource name>/providers/Microsoft.Compute/virtualMachineScaleSets/aks-default-10878206-vmss?api-version=2019-12-01: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: failed to get service principal token, error: adal: Failed to execute the refresh request. Error = 'Get "http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&client_id=<client-id>&resource=https%3A%2F%2Fmanagement.azure.com%2F": dial tcp 169.254.169.254:80: i/o timeout'
 Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&client_id=<client-id>&resource=https%3A%2F%2Fmanagement.azure.com%2F
```

**Comment by aramase** [comment]
It looks like the first token request from MIC is also being intercepted by NMI. As part of the installation, you also need to configure `AzurePodIdentityException` to except the MIC token requests from being excepted. The command to install the exception is 

```bash
kubectl apply -f https://raw.githubusercontent.com/Azure/aad-pod-identity/v1.8.8/deploy/infra/mic-exception.yaml
```

Refer to our [quick install](https://azure.github.io/aad-pod-identity/docs/getting-started/installation/#quick-install) guide for the steps and more information.

**Comment by ernesto1596** [comment]
Are these not installed with the helm chart?

**Comment by aramase** [comment]
Synced up offline with @ernesto1596!

1. The `AzurePodIdentityException` was deployed in all the clusters as recommended.
2. They have a dev cluster which was upgraded to `v1.8.8` and is working fine.
3. The above error indicates a network issue in the cluster. Multiple pods in `kube-system` namespace are in `CrashloopBackOff` and this is not related to pod identity.

The original query is resolved, so closing this issue as discussed offline. Please feel free to re-open if you have any questions.
