### ISSUE TITLE
AAD Pod-identity intermittent issues with applications

### ISSUE THREAD

**Issue by mdaslamansari** [Azure/aad-pod-identity#1287]
Introduction - We have application pods running in AKS (Azure Kubernetes Services) and the pods are using managed identity to access Azure resources like KeyVault as soon as pod starts running. What we are seeing is that few times apps are failing to read KV with the error - 

_error in obtaining secret: ManagedIdentityCredential authentication failed. Status code: 500
More details:
unknown_error Status code: 500
More details:
An unknown error has occurred. Response body:
pod list is empty_

We suspect it could be token retrieval thing as mentioned in the article at [https://azure.github.io/aad-pod-identity/docs/best-practices/](url)

Now as discussed in the above article, we first created DaemonSet [https://azure.github.io/aad-pod-identity/docs/best-practices/#daemonsethttpskubernetesiodocsconceptsworkloadscontrollersdaemonset](url)

It is created fine but what we are seeing is that the DaemonSet pod is getting into Crashloopbackoff even after running the above command as given in the definition correctly and it is also generating logs properly with the token retrieval success message. DaemonSet is continuously retrying and getting into Crashloopbackoff... [DaemonSet states --> Running --> completed --> Crashloopbackoff --> multiple retries --> and then same states as given finally to Crashloopbackoff]

We then tried adding InitContainer in our application container as given in the above article and got the same behavior as the DaemonSet and init validation is failing with crashloopbackoff...   

I have attached the init container logs for your reference.
[cli-logs.txt](https://github.com/Azure/aad-pod-identity/files/8933698/cli-logs.txt)

Additional Info -

AKS version - 1.21.7
Pod Identity Version - 1.7.4

We will appreciate if you can guide us how to investigate and fix the intermittent issues that we are getting.... Is there better/recommended approach we can implement to efficiently use the pod identity?

**Comment by chewong** [comment]
Duplicated issue: https://github.com/Azure/aad-pod-identity/issues/1011.

Can you try upgrading to v1.7.5+ or to the latest version?

**Comment by mdaslamansari** [comment]
Thanks @chewong... We are getting same even with 1.8.9 version...

**Comment by chewong** [comment]
Can you share the MIC and NMI logs?
