### ISSUE TITLE
Pod-Identity NMI v1.8.9 detected with Debian vulnerability (Azure Defender)

### ISSUE THREAD

**Issue by rupendra-kpmg** [Azure/aad-pod-identity#1291]
**Have you**

- [ ] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [ ] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [ ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**

Pod-Identity image is detected with Debian Security Update for Open Secure Sockets Layer (OpenSSL) (DSA 5139-1) and Debian Security Update for dpkg (DSA 5147-1)

**Steps To Reproduce**

Scan pod-identity image with Azure Defender 

**Expected behavior**

![image](https://user-images.githubusercontent.com/103521123/176406724-b1e746a2-1770-4d7a-aceb-75ba01ba7a95.png)

**AAD Pod Identity version**

NMI:  v1.8.4.4

**Kubernetes version** : 1.23.5

**Additional context**

**Comment by aramase** [comment]
Hello 👋🏻 

Please reference our [release doc](https://github.com/Azure/aad-pod-identity/blob/master/docs/RELEASE.md) for more details on how we patch CVEs in releases.

1. I would recommend using the latest release as it will always contain CVE patches for CVEs at the time of release.
2. For the newer CVEs, they have been patched in the main branch and will be part of the next release which as mentioned in the release doc is planned for the first week of every month. The next release will be next week that'll contain patches for all CVEs with fixed versions.

**Comment by aramase** [comment]
@rupendra-kpmg As I mentioned in the previous comment, if the CVE has a fixed version, that patch will be included in the next release. Those CVEs have been patched in the master branch and will be part of release next week.

**Comment by sozercan** [comment]
Closing this since the vulnerability has been fixed and the fix will be available in the next version.

**Comment by rupendra-kpmg** [comment]
@sozercan When you have plan to release the next version ? would be very helpfull if i can get the link. Thanks!

**Comment by aramase** [comment]
> @sozercan When you have plan to release the next version ? would be very helpfull if i can get the link. Thanks!

@rupendra-kpmg The release cadence doc I shared in the comment above has the release plan. We will cut a release 1st week of every month, which means the next release will be this week.
