### ISSUE TITLE
Is it mandatory to deploy in default name space?

### ISSUE THREAD

**Issue by callppatel** [Azure/aad-pod-identity#1295]
**Have you**

- [ ] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [ ] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [ ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
Doesnt work or identity gets hung when deploying outside of default namespace.

**Steps To Reproduce**
Use file which mentioned and replace "namespace: default" with "namespace=aadpod" here https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml
**Expected behavior**
Should work
**AAD Pod Identity version**
latest

**Comment by aramase** [comment]
No, it is not required to deploy aad-pod-identity component in default namespace. It should work fine in any namespace. The NMI and MIC pod logs should have more details on the error. Here is our troubleshooting guide - https://azure.github.io/aad-pod-identity/docs/troubleshooting/

**Comment by SOFSPEEL** [comment]
There is another problem with namespaces, if you try to deploy helm to 2 different namespaces in the same cluster you will get the following error:
`ClusterRole "aad-pod-identity-mic" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "uat": current value is "dev"`

To reproduce start with a clean cluster, then do

```
helm install aad-pod-identity aad-pod-identity/aad-pod-identity --namespace dev
helm install aad-pod-identity aad-pod-identity/aad-pod-identity --namespace uat
```

To debug, to try to understand the issue, I did:

```
kubectl describe ClusterRole aad-pod-identity-mic 

and

kubectl describe ClusterRole aad-pod-identity-mic --namespace dev
```

**both** of which returned:

```
Name:         aad-pod-identity-mic
Labels:       app.kubernetes.io/component=mic
              app.kubernetes.io/instance=aad-pod-identity
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=aad-pod-identity
              helm.sh/chart=aad-pod-identity-4.1.11
Annotations:  meta.helm.sh/release-name: aad-pod-identity
              meta.helm.sh/release-namespace: dev
....
```

The fact that both the kubectl describe ClusterRole commands (with different namespaces) return the same cluster role may be telling.

**Comment by aramase** [comment]
> There is another problem with namespaces, if you try to deploy aad-pod-identity to 2 different namespaces in the same cluster you will get the following error:

@SOFSPEEL Only one pod identity instance is required and supported per cluster. NMI binds to the host network and if you try to deploy in a different namespace will result in host port conflicts. 

ClusterRole and ClusterRoleBinding are not namespaced resources but rather cluster resources. Helm adds labels when it installs the manifests and trying to deploy 2 instances of the cluster resource will give the error as expected.

**Comment by aramase** [comment]
Closing this issue with https://github.com/Azure/aad-pod-identity/issues/1295#issuecomment-1189538967. If there any additional questions, please feel free to reopen.
