### ISSUE TITLE
Vulnerabilities are coming in NMI 1.8.10

### ISSUE THREAD

**Issue by smartaquarius10** [Azure/aad-pod-identity#1301]
Team,

Prisma cloud is showing these vulnerabilities in nmi 1.8.10

`Release details:- OS distribution Debian GNU/Linux 11 (bullseye)`

---

![image](https://user-images.githubusercontent.com/7824529/182873551-f05256c4-3a97-434b-a981-ffb407bc5f99.png)

![image](https://user-images.githubusercontent.com/7824529/182871807-e2a3fea9-82fe-425e-a669-683220cddefc.png)

---
![image](https://user-images.githubusercontent.com/7824529/182873711-0f54e391-9822-4ce0-a53e-8953e7093f8d.png)

![image](https://user-images.githubusercontent.com/7824529/182871857-fcacc9bf-5059-4b66-a42c-4c9cc40d8b5a.png)

Could you please suggest any resolution on this. Are there any chances of resolving them in upcoming releases?

Looking forward to your reply. Thank you.

Kind Regards,
Tanul

**Comment by smartaquarius10** [comment]
@aramase Sure anish. We have the latest release only. The issue is only in the nmi. Will wait for the next release. Hoping it to be free from these vulnerabilities.

Take care.. Have a great day ahead. :)

**Comment by smartaquarius10** [comment]
@aramase I forgot to ask one question. Is it a good practice to build using docker file and deploy or use the latest image already there in mcr.microsoft.com

**Comment by smartaquarius10** [comment]
@aramase Because currently we are building using Dockerfile and from there we deploy aad

**Comment by sozercan** [comment]
@smartaquarius10 Answer depends on your environment and policies. If your organization is comfortable with consuming images from mcr.microsoft.com, it'll be less time-consuming to grab from there instead of rebuilding.

**Comment by smartaquarius10** [comment]
@sozercan , Got it thanks. :)

**Comment by BobbySchmitt** [comment]
Most of these CVE are still present in 1.8.11 and 1.8.11.1 versions of the nmi container. 

I think you need to update the base image you are using for the nmi container. I do not think Debian-iptables:bullseye-v1.5.0 is still being updated.
