### ISSUE TITLE
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(AzureIdentity): unknown field "spec" in io.k8s.aadpodidentity.v1.AzureIdentity

### ISSUE THREAD

**Issue by adi2025NOrtheastern** [Azure/aad-pod-identity#1305]
**Have you**

- [X ] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [X ] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [X ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
Unable to install aadpodidentity. Getting below error:

Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(AzureIdentity): unknown field "spec" in io.k8s.aadpodidentity.v1.AzureIdentity
Please let me know if any other data is needed from my end.  Thank you.

**Steps To Reproduce**
1.  helm repo add aad-pod-identity https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts
2.  helm install aad-pod-id aad-pod-identity/aad-pod-identity -n=monitoring

**Expected behavior**
aad pod identity should be installed

**AAD Pod Identity version**

**Kubernetes version**
![image](https://user-images.githubusercontent.com/71220629/183225839-6edddc23-0a21-46e9-8a65-e6abd891ab7c.png)

**Additional context**
![image](https://user-images.githubusercontent.com/71220629/183225779-4f9375dc-91e6-49d9-9c5f-042bfb98dbf0.png)

**Comment by aramase** [comment]
@adi2025NOrtheastern This might be because your kubectl (client minor version) is greater than your server version. I would recommend downgrading the kubectl version or upgrading your server version.

I tried this on 1.24 client and server version, and can confirm it works as expected:

```bash
➜ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-23T22:20:14Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```

```bash
➜ helm install aad-pod-id aad-pod-identity/aad-pod-identity -n monitoring --create-namespace
NAME: aad-pod-id
LAST DEPLOYED: Mon Aug 15 16:48:43 2022
NAMESPACE: monitoring
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
You have successfully installed AAD Pod Identity in your Kubernetes cluster!

To verify that AAD Pod Identity has started in standard mode, run:
  kubectl --namespace=monitoring get pods -l "app.kubernetes.io/component=mic"
  kubectl --namespace=monitoring get pods -l "app.kubernetes.io/component=nmi"


Now you can follow the demos to get familiar with AAD Pod Identity: https://azure.github.io/aad-pod-identity/docs/demo/
```

**Comment by jainaditims** [comment]
@aramase Thank you for looking into this. I resolved this issue and no longer getting such error.
I tried creating a new cluster and then installing aad-pod-identity. It worked. Thank you again!
