### ISSUE TITLE
AAD PodIdentity NMI v1.8.11 detected with high vulnerabilities

### ISSUE THREAD

**Issue by rpushpkar** [Azure/aad-pod-identity#1315]
**Have you**

- [ ] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [ ] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [ ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
 180920
Debian Security Update for libtirpc (DSA 5200-1)
Debian
Yes
OS
libtirpc-common
1.3.1-1
1.3.1-1+deb11u1
High

180920
Debian Security Update for libtirpc (DSA 5200-1)
Debian
Yes
OS
libtirpc3
1.3.1-1
1.3.1-1+deb11u1
High

180922
Debian Security Update for gnutls28 (DSA 5203-1)
Debian
Yes
OS
libgnutls30
3.7.1-5+deb11u1
3.7.1-5+deb11u2
High

180965
Debian Security Update for zlib (DSA 5218-1)
Debian
Yes
OS
zlib1g
1:1.2.11.dfsg-2+deb11u1
1:1.2.11.dfsg-2+deb11u2

**Steps To Reproduce** : Scan NMI v1.8.11 with Azure Defender

**Expected behavior** : Vulnerability must be rsolved.

**AAD Pod Identity version** : v1.8.11

**Kubernetes version** : 1.23.5

![image](https://user-images.githubusercontent.com/61583661/188549261-da26482f-5efb-4a34-8e77-735581bb131a.png)

**Comment by aramase** [comment]
Hello 👋🏻 

Please reference our [release doc](https://github.com/Azure/aad-pod-identity/blob/master/docs/RELEASE.md) for more details on how we patch CVEs in releases.

1. I would recommend using the latest release as it will always contain CVE patches for CVEs at the time of release.
2. For the newer CVEs that have a fixed version, they have been patched in the main branch and will be part of the next release which as mentioned in the release doc is planned for the first week of every month. The next release will be next week that'll contain patches for all CVEs with fixed versions.

The next release will be available this week.
