### ISSUE TITLE
Unable to install aad-pod-identity after updating it to 1.8.1

### ISSUE THREAD

**Issue by radhikajain99** [Azure/aad-pod-identity#1318]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [x] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [x] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
Unable to install aad-pod-identity after updating it to 1.8.1. Error message -
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(AzurePodIdentityException): unknown field "spec" in io.k8s.aadpodidentity.v1.AzurePodIdentityException

**Steps To Reproduce**
1. Add aad-pod-identity to our repo from https://github.com/Azure/aad-pod-identity/archive/refs/tags/v1.8.1.zip
2. Run ./helm upgrade aad-pod-id-rel aad-pod-identity-1.0.020770001.tgz --install --create-namespace --wait --force --timeout 10m --namespace aad-pod-id -f pod-id-values.yaml

**Expected behavior**
aad-pod-identity should be installed

**AAD Pod Identity version**
1.8.1

**Kubernetes version**
1.24.3

**Additional context**
We tried updating our kubectl client version to 1.24.3 to match server version but we are still getting this error. It was working previously with aad-pod-identity version 1.6.2 and AKS version 1.21.9

**Comment by aramase** [comment]
Please see similar issues before - https://github.com/Azure/aad-pod-identity/issues/1305. This typically happens where is a version mismatch. I would recommend having the same client and server version and then doing a clean install. 

> We tried updating our kubectl client version to 1.24.3 to match server version but we are still getting this error. It was working previously with aad-pod-identity version 1.6.2 and AKS version 1.21.9

`1.6.2` doesn't define a openapi schema for the CRDs. This was only added in `v1.7.x`.

**Comment by aramase** [comment]
Also, the latest available release is `v1.8.12`, so I would recommend using that to get the latest CVE patches and bug fixes.

**Comment by radhikajain99** [comment]
Thanks @aramase. It worked after deleting the AKS and deploying it in a new AKS.

**Comment by aramase** [comment]
Closing this issue now.
