### ISSUE TITLE
E2E Tests are not running against the produced images

### ISSUE THREAD

**Issue by pjbgf** [Azure/aad-pod-identity#132]
The current e2e tests are always executed against docker images already published, instead of using the ones generated as part of the build process. Impairing the ability to fully test changes either locally or as part of a build pipeline. 

### Steps to Reproduce

1. **Clone repo and get dependencies**
```
git clone git@github.com:Azure/aad-pod-identity.git
go get -v -t -d ./...
```

2. **Configuration Setup**
As per test\e2e\README.md, including set `REGISTRY=my-docker-hub-registry`.

3. **Break the code**
Remove the `RUN` command from all the Dockerfiles in the project. Things such as iptables, curl and bash will not be installed into the target images.

3. **Kick-off build/e2e process** 
```
make build
make image
make push
make e2e
```

### Result
The tests pass, although they **should not**:

```
Ran 4 of 4 Specs in 92.214 seconds
SUCCESS! -- 4 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestAADPodIdentity (92.11s)
PASS
ok  	github.com/Azure/aad-pod-identity/test/e2e	92.218s
```

Images deployed into the cluster:
```
chewong/identityvalidator:1.0
mcr.microsoft.com/k8s/aad-pod-identity/nmi:1.2
mcr.microsoft.com/k8s/aad-pod-identity/mic:1.2
```

### Proposed changes
- Template all the yaml files used to deploy components for the E2E tests. Add placeholders for registry and docker version tag.
- Change Makefile to be able to consume version ids from environment variables.
- Change e2e code to apply registry and version tags before deploy component on the cluster.

Any thoughts on this @rite2nikhil @khenidak @ritazh ?

**Comment by kkmsft** [comment]
Thank you @pjbgf for opening this issue and PR #129 
@CecileRobertMichon created #218 based on these changes, updated these changes and made it work with the latest e2e in #218. Closing this issue with the merge of #218.
