### ISSUE TITLE
Non-default namespace

### ISSUE THREAD

**Issue by dhkhan** [Azure/aad-pod-identity#133]
Does this sample work on a non-default namespace? I am getting a 403 error from the demo pod if I do that. The AD Binding seems to be not working. I have set the namespace to the demo application, the infra(AzureIdentity and AzureIdentityBinding). Is there anything else we would need to do?

**Comment by pjbgf** [comment]
This is the same as #76 .

@dhkhan this currently works as long as AzureIdentity and AzureIdentityBinding are placed in the default namespace. 

On #115 there is a proposal to change this in order to support both those types to be placed within custom namespaces.

**Comment by samisq** [comment]
Just ran into this exact issue. Thanks for the tip @pjbgf !

**Comment by pjbgf** [comment]
@samisq I got a working version with this, but I still need to add some tests before creating a pull request. Here's the branch: https://github.com/pjbgf/aad-pod-identity/commits/features/support-multi-namespaces

**Comment by khenidak** [comment]
fixed with PR #140
