### ISSUE TITLE
Required capabilities for MIC pods

### ISSUE THREAD

**Issue by jacklwm90** [Azure/aad-pod-identity#1344]
Hi can anyone share on the required capabilities for MIC, found the required capabilities for NMI but not MIC? MDC flagged the both MIC and NMI pod for "Least privileged Linux capabilities should be enforced for containers".

Thank you in advance!

**Comment by aramase** [comment]
We have `securityContext` configured for the MIC deployment

https://github.com/Azure/aad-pod-identity/blob/5c6556d5155b83e57f94c57905c40053595cc833/deploy/infra/deployment-rbac.yaml#L602-L604

In terms of the capabilities, AFAIK you should be able to drop all capabilities for MIC. Only NMI requires `NET_ADMIN`.

**Comment by aramase** [comment]
Closing this issue now. Please feel free to reopen if you have any questions.
