### ISSUE TITLE
Migrating from Standard to Managed Mode

### ISSUE THREAD

**Issue by jordansafer** [Azure/aad-pod-identity#1347]
Hi! What are MIC and NMI from [this](https://azure.github.io/aad-pod-identity/docs/configure/standard_to_managed_mode/) documentation page? I'm a little confused about these, and am wondering if there are links to the definitions.

Thank you!

**Comment by jordansafer** [comment]
I found the answer here! https://learn.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity#operation-mode-options
Can I link this page/explanation to the Standard to Managed Mode page?

**Comment by sozercan** [comment]
Definitions are here: https://azure.github.io/aad-pod-identity/docs/concepts/

Keep in mind this project is deprecated, we are encouraging users to migrate to workload identity. See readme for details.

Closing this, feel free to open it if you need further questions.
