### ISSUE TITLE
📣 AAD Pod Identity is deprecated

### ISSUE THREAD

**Issue by sozercan** [Azure/aad-pod-identity#1349]
**❗ IMPORTANT**: As of Monday 10/24/2022, AAD Pod Identity is **deprecated**. As mentioned in the [announcement](https://cloudblogs.microsoft.com/opensource/2022/01/18/announcing-azure-active-directory-azure-ad-workload-identity-for-kubernetes/), AAD Pod Identity has been replaced with [Azure Workload Identity](https://azure.github.io/azure-workload-identity). Going forward, we will no longer add new features to this project in favor of Azure Workload Identity. We will continue to provide critical bug fixes until Azure Workload Identity reaches general availability. Following that, we will provide CVE patches until September 2023, at which time the project will be archived.

**Comment by 64J0** [comment]
Is there any tutorial teaching how to migrate to this new project?

Related to https://github.com/Azure/azure-workload-identity/issues/731.

**Comment by sozercan** [comment]
Workload Identity (OSS) has reached stable (v1.0.0) milestone: https://github.com/Azure/azure-workload-identity/releases/tag/v1.0.0

Workload Identity for AKS is now generally available (GA): https://techcommunity.microsoft.com/t5/apps-on-azure-blog/general-availability-for-azure-active-directory-ad-workload/ba-p/3798292#M1196

How to migrate from Azure Pod Identity to Azure Workload Identity:
https://learn.microsoft.com/en-us/azure/aks/workload-identity-migrate-from-pod-identity

**Comment by aramase** [comment]
> is there a solution for `EAS` data centers? https://learn.microsoft.com/en-us/azure/active-directory/workload-identities/workload-identity-federation-considerations#unsupported-regions-user-assigned-managed-identities

There is context in the [issue](https://github.com/Azure/azure-workload-identity/issues/838) and response from AAD team.

cc @isolenov who last responded on the other issue.

**Comment by michalfotyga** [comment]
>  Following that, we will provide CVE patches until September 2023, at which time the project will be archived.

What does "archived" mean in practice? AAD Pod Identity, as a solution, will still be a working, just no more work will be done to maintain it, right?

**Comment by sozercan** [comment]
@michalfotyga GitHub repo will be read-only, there will be no changes made (https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories)
