### ISSUE TITLE
The index.yaml file references the master branch, instead of the labeled release branch

### ISSUE THREAD

**Issue by MattMcL4475** [Azure/aad-pod-identity#1354]
The `index.yaml` file references the `master` branch, instead of the labeled release branch:

This file:
https://github.com/Azure/aad-pod-identity/blob/v1.8.13/charts/index.yaml

Is referencing the `master` branch:
https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts/aad-pod-identity-4.1.14.tgz

When instead, it should be referencing the release label `v1.8.13`
https://raw.githubusercontent.com/Azure/aad-pod-identity/v1.8.13/charts/aad-pod-identity-4.1.14.tgz

This is to ensure it's a permanent link and not broken if `master` is changed.

**Comment by aramase** [comment]
The `index.yaml` references the `master` branch as that's the only one that hosts all the packages. AAD Pod Identity doesn't use release branches. The common practice even with hosting it in gh-pages is to have the index.yaml reference the branch that hosts all the packages.

> This is to ensure it's a permanent link and not broken if master is changed.

There is no plan to change the branch name as this project has been deprecated. We recommend using [Azure Workload Identity](https://github.com/Azure/azure-workload-identity). 

https://github.com/Azure/aad-pod-identity#-announcement

**Comment by MattMcL4475** [comment]
Hi @aramase , I was actually referring to the "tag" or "label" that is applied during release:

https://github.com/Azure/aad-pod-identity/tree/v1.8.13/charts

I still think this is better than referring to master, since master could be broken at any time, whereas the label/tag ensures the links are permanent.  All the packages are available here.

Understood about Azure Workload Identity .
