### ISSUE TITLE
Docker Images with Vulnerabilities

### ISSUE THREAD

**Issue by pjbgf** [Azure/aad-pod-identity#136]
The current version **1.2** of both nmi and mic are based on the previous hyperkube base image. Running the snyk vulnerability scanning on those images results in over 200 vulnerabilities.
They are currently the images we are providing for anyone using `deploy/infra/deployment-rbac.yaml`:

![image](https://user-images.githubusercontent.com/5452977/49864871-63ee9980-fdfb-11e8-8dac-62e4a026c68e.png)

![image](https://user-images.githubusercontent.com/5452977/49864949-8aacd000-fdfb-11e8-985e-b51462d7dae8.png)

We seem to only have published the version **1.3** for nmi, which is what we are referencing on `deploy/infra/deployment.yaml`. That version seems to be fine:

![image](https://user-images.githubusercontent.com/5452977/49865142-13c40700-fdfc-11e8-965a-b0355454fbab.png)

However, we have no alpine version published for mic.
Can we please publish a new version of both images with latest from master?

**Comment by kkmsft** [comment]
Closing this in lieu of #139
