### ISSUE TITLE
Cannot delete pod identity when rolee was unassigned or is already gone

### ISSUE THREAD

**Issue by Thaval** [Azure/aad-pod-identity#1361]
**Have you**

- [ ] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [ ] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [ ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
When the role assignment or the managed identity was deleted, the command `az aks pod-identity delete --name ${POD_IDENTITY_NAME} --namespace ${POD_IDENTITY_NAMESPACE} --resource-group myResourceGroup --cluster-name myAKSCluster` will fail with a strange message:
`Please grant at least 'Managed Identity Operator' permission before assigning pod identity.`

I should always be able to delete the pod identity, because the namespace is auto-generated whenever the AzureIdentity or AzureIdentityBinding object is created....

**Comment by aramase** [comment]
If you're using the AKS managed pod-identity add-on (https://learn.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity), please open an issue here: https://github.com/Azure/AKS.

cc @karataliu
