### ISSUE TITLE
MIC binding not happening - help required

### ISSUE THREAD

**Issue by simonness** [Azure/aad-pod-identity#137]
Hi, I've followed the demo instructions but can't seem to get the MIC to pick up new deployments.  I'm using AKS and no RBAC.

The NMI logs have lines like:

`time="2018-12-17T10:55:50Z" level=error msg="no AzureAssignedIdentity found for pod:default/demo-777c774cd9-g4dtj, <nil>" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.244.0.20`

The MIC logs only have:

```
I1212 20:59:10.343756       1 main.go:29] kubeconfig (/etc/kubernetes/kubeconfig/kubeconfig) cloudconfig (/etc/kubernetes/azure.json)
I1212 20:59:10.344923       1 mic.go:53] Starting to create the pod identity client. Version: 1.2. Build date: 2018-08-11-02:06
I1212 20:59:10.448002       1 pod.go:80] Pod cache synchronized. Took 100.464089ms
I1212 20:59:10.448220       1 pod.go:86] Pod watcher started !!
I1212 20:59:10.448316       1 crd.go:156] CRD watchers started
I1212 20:59:10.448331       1 main.go:42] AAD Pod identity controller initialized!!
I1212 20:59:10.448359       1 mic.go:126] Sync thread started
```

The demo app has logs like:

```
time="2018-12-17T11:02:06Z" level=error msg="failed list all vm azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/SUBSCRIPTION_ID/resourceGroups/RESOURCE_GROUP/providers/Microsoft.Compute/virtualMachines?api-version=2017-12-01: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: no AzureAssignedIdentity found for pod:default/demo-777c774cd9-g4dtj\n" podip=10.244.0.20 podname=demo-777c774cd9-g4dtj podnamespace=demo-777c774cd9-g4dtj
time="2018-12-17T11:02:06Z" level=error msg="failed to refresh ServicePrincipalTokenFromMSI using the MSI VM extension, msiEndpoint(http://169.254.169.254/metadata/identity/oauth2/token)" podip=10.244.0.20 podname=demo-777c774cd9-g4dtj podnamespace=demo-777c774cd9-g4dtj
time="2018-12-17T11:02:06Z" level=error msg="testMSIEndpoint failed, <nil>" podip=10.244.0.20 podname=demo-777c774cd9-g4dtj podnamespace=demo-777c774cd9-g4dtj
```

I have:
1. Deployed the azure-aad-identity infra (MIC and NMI)
1. Created User Azure Identity with the name demo
1. Assigned Reader Role to this Identity 
1. Given "Managed Identity Operator" role to the Service Principal used by the AKS cluster (actually this step wasn't necessary as the AKS SP had been automatically created with this Role as described the demo)
1. Installed the User Azure Identity on k8s cluster (using the MSI resource and client id)
1. Installed the Pod to Identity Binding on k8s cluster (using the selector "demo")
1. Deployed the demo app

Everything uses the default namespace and the Managed Service Identity name is less than 24 characters and doesn't include special characters.

Given the steps taken and the logs above are there any pointers to what could be going wrong?  Should I expect some further logs from MIC after the demo app is deployed?

**Comment by simonness** [comment]
Hi @kkmsft sorry for the delay!  I got to the bottom of this, please see #138.

**Comment by kkmsft** [comment]
Thank you, @simonness for raising the issue and the PR to clarify this in documentation. I have merged your PR. Closing this issue.
