### ISSUE TITLE
Upgrading helm chart of aad-pod-identity forces CRD and its corresponding object to be deleted

### ISSUE THREAD

**Issue by MageshSrinivasulu** [Azure/aad-pod-identity#1388]
Upgrading the helm chart from aad-pod-identity-4.1.13.tgz --> aad-pod-identity-4.1.14.tgz

While upgrading the existing CRD's are getting deleted. Below are the ones that need to be re-created after the chart upgrade. Because of this, all the aad-pod-identity pods are crashing stating the CRD's are not found.

```
customresourcedefinition.apiextensions.k8s.io/azureidentities.aadpodidentity.k8s.io created
customresourcedefinition.apiextensions.k8s.io/azureidentitybindings.aadpodidentity.k8s.io created
customresourcedefinition.apiextensions.k8s.io/azurepodidentityexceptions.aadpodidentity.k8s.io created
```

Further, it removes all of the AzureIdentity objects from the cluster. That causes disruption to the app running in the cluster since it relies on these identities to communicate with azure objects.

I am able to consistently reproduce this issue

**Comment by sozercan** [comment]
@MageshSrinivasulu AAD Pod Identity is deprecated, no new features or bugfixes are planned. It will be end of life in Sept.
Please see announcement: https://github.com/Azure/aad-pod-identity#-announcement
