### ISSUE TITLE
AAD Podidentity NMI v1.8.14 and MIC v1.8.14 detected with vulnerability

### ISSUE THREAD

**Issue by rupendra-kpmg** [Azure/aad-pod-identity#1394]
![image](https://user-images.githubusercontent.com/103521123/220320316-5ab57404-5f8e-4148-8f47-053250b7ae92.png)

**Comment by aramase** [comment]
The next release `v1.8.15` is planned for this week. That'll contain the base image CVE patches that contain fixes.
