### ISSUE TITLE
AAD Pod Identity not working with Service Principal + Certificate.

### ISSUE THREAD

**Issue by shraddha1411** [Azure/aad-pod-identity#1408]
**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [x] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [x] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
We are trying to use aad-pod-identity with Service Principal and Certificate. 
We followed the below document to create a Certificate secret and register the AzureIdentity with Service Principal. 
[Document steps for configuring pod identity with sp + certificate · Issue #1272 · Azure/aad-pod-identity (github.com)](https://github.com/Azure/aad-pod-identity/issues/1272)

Although we observed that MIC is not able to find any identity to assign, it has created the AzureAssignedIdentity.
The same approach worked for us with User assigned MSI.

MIC logs
```
I0306 20:01:15.146707       1 mic.go:1040] processing node aks-agentpool01-24708587-vmss, add [1], del [0], update [0]
I0306 20:01:15.146741       1 crd.go:514] creating assigned id default/sparktest-sp7-driver-spark-main-azid-sp7
I0306 20:01:15.160906       1 cloudprovider.go:181] No identities to assign or un-assign
I0306 20:01:15.160940       1 crd.go:777] updating AzureAssignedIdentity default/sparktest-sp7-driver-spark-main-azid-sp7 status to Assigned
I0306 20:01:15.171990       1 mic.go:525] work done: true. Found 5 pods, 2 ids, 2 bindings
I0306 20:01:15.172011       1 mic.go:526] total work cycles: 2992, out of which work was done in: 63
I0306 20:01:15.172029       1 stats.go:183] ** stats collected **
I0306 20:01:15.172034       1 stats.go:162] Pod listing: 39.901µs
I0306 20:01:15.172043       1 stats.go:162] AzureIdentity listing: 5.3µs
I0306 20:01:15.172047       1 stats.go:162] AzureIdentityBinding listing: 8.8µs
I0306 20:01:15.172050       1 stats.go:162] AzureAssignedIdentity listing: 6.8µs
I0306 20:01:15.172055       1 stats.go:162] System: 77.302µs
I0306 20:01:15.172059       1 stats.go:162] CacheSync: 9.6µs
I0306 20:01:15.172063       1 stats.go:162] Cloud provider GET: 0s
I0306 20:01:15.172067       1 stats.go:162] Cloud provider PATCH: 0s
I0306 20:01:15.172071       1 stats.go:162] AzureAssignedIdentity creation: 14.131738ms
I0306 20:01:15.172076       1 stats.go:162] AzureAssignedIdentity update: 0s
I0306 20:01:15.172080       1 stats.go:162] AzureAssignedIdentity deletion: 0s
I0306 20:01:15.172084       1 stats.go:170] Number of cloud provider PATCH: 0
I0306 20:01:15.172088       1 stats.go:170] Number of cloud provider GET: 0
I0306 20:01:15.172092       1 stats.go:170] Number of AzureAssignedIdentities created in this sync cycle: 1
I0306 20:01:15.172096       1 stats.go:170] Number of AzureAssignedIdentities updated in this sync cycle: 0
I0306 20:01:15.172100       1 stats.go:170] Number of AzureAssignedIdentities deleted in this sync cycle: 0
I0306 20:01:15.172104       1 stats.go:162] Find AzureAssignedIdentities to create: 4.5µs
I0306 20:01:15.172109       1 stats.go:162] Find AzureAssignedIdentities to delete: 2.2µs
I0306 20:01:15.172112       1 stats.go:162] Total time to assign or update AzureAssignedIdentities: 25.267305ms
I0306 20:01:15.172117       1 stats.go:162] Total: 25.543611ms
I0306 20:01:15.172121       1 stats.go:212] ********************
```

NMI logs
```
E0306 20:04:19.521870       1 server.go:427] failed to get matching identities for pod: spark-main/sparktest-sp7-driver, error: context canceled
I0306 20:04:19.521914       1 server.go:239] status (404) took 30027995171 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.1.150
```

**Steps To Reproduce**
Follow this document
https://github.com/Azure/aad-pod-identity/issues/1272

**Expected behavior**
MIC should find the identity to assign and NMI should be able to get the token 

**AAD Pod Identity version**
v.1.8.14

**Kubernetes version**
```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"08d3594304660f86cfbd17bbb862041b4b75fe6c", GitTreeState:"clean", BuildDate:"2023-02-08T17:22:59Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
```
**Additional context**
As we are taking a dependency on another team who is hosting/managing the Kubernetes Cluster for the entire Org, we can't move to workload identity until they start supporting it. We expect that transition will happen in the next 4-5 months, until then we will be using aad pod identity.

**Comment by aramase** [comment]
`error: context canceled`

Context canceled usually means the client requesting the token canceled the request before it could be complete. You'll need to increase the client timeout.

I see you opened https://github.com/Azure/aad-pod-identity/issues/1402 too and marked it as resolved. If you own the client, increase the token request timeout. NMI is not failing with any error here, rather the client that request for the token canceled the request before the token request could complete.

**Comment by shraddha1411** [comment]
@aramase what does this log mean in MIC logs? 
I0306 20:01:15.160906       1 cloudprovider.go:181] No identities to assign or un-assign

while tracking back this error from https://github.com/Azure/aad-pod-identity/blob/437104fe20b8a0b3003c922e0a4362b9223f34dc/pkg/cloudprovider/cloudprovider.go#L181
I found that it is always checking if the identity type is User assigned identity or not. 

https://github.com/Azure/aad-pod-identity/blob/437104fe20b8a0b3003c922e0a4362b9223f34dc/pkg/mic/mic.go#L932

Does this mean only User assigned MSI is supported? 

I also verified that no identity was assigned to the VMSS
Token requests are being done by Spark, the same spark job works with User Assigned MSI

**Comment by shraddha1411** [comment]
@aramase any update on this?

**Comment by aramase** [comment]
> Does this mean only User assigned MSI is supported?

Both are supported. User-assigned managed identities need to be assigned to the underlying VMSS before they can be used. Service principals don't need to be assigned as they are just client ID and password/certificate. That's what the informational message indicates. 

> I also verified that no identity was assigned to the VMSS

Only User-assigned managed identities need to be assigned to VMSS.
