### ISSUE TITLE
Error While trying to Deploy AAD Pod Identities on AKS clusters

### ISSUE THREAD

**Issue by mkurukun** [Azure/aad-pod-identity#1420]
❗ AAD Pod Identity is [deprecated](https://github.com/Azure/aad-pod-identity#-announcement) and [Azure Workload Identity](https://github.com/Azure/azure-workload-identity) has reached stable (OSS) and GA (AKS) milestones. AAD Pod Identity has transitioned to CVE fixes only.

**Have you**

- [x] Read [Troubleshooting Guide](https://azure.github.io/aad-pod-identity/docs/troubleshooting/)
- [x] Read [Known Issues](https://azure.github.io/aad-pod-identity/docs/known-issues/)
- [x] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)
- [x] Acknowledge AAD Pod Identity is [deprecated](https://github.com/Azure/aad-pod-identity#-announcement) in favor of [Azure Workload Identity](https://github.com/Azure/azure-workload-identity)

**Describe the bug**
We recently noticed the Following Error while trying to Deploy Pod Identities for our AKS Clusters. We have been using Terraform to run a bash script  to Deploy Pod Identities using az cli commands. 

Waiting for AAD role to propagate[################################    ]
│ 90.0000%ERROR: **'RoleAssignmentsOperations' object has no attribute 'config'**
│ ERROR: Could not grant Managed Identity Operator permission for cluster
│ Sleeping for 30 seconds....
│ ERROR: 'RoleAssignmentsOperations' object has no attribute 'config'

**Steps To Reproduce**

Here is the code from the bash script that is executed.
az aks pod-identity add --resource-group $AKS_RESOURCE_GROUP --cluster-name $AKS_CLUSTER_NAME \
      --namespace $namespace --identity-resource-id $managed_identity_resource_id --binding-selector $binding_selector

was able to reproduce this by running the az cli commands manually.(not from Terraform bash script)
These are the command I used 
 
az aks update --resource-group aksloadbalancer --name aksloadbalancer --enable-pod-identity --enable-pod-identity-with-kubenet
 
az aks pod-identity add --cluster-name aksloadbalancer --identity-resource-id /subscriptions/<mysubidgoeshere>/resourcegroups/myIdentityResourceGroup/providers/Microsoft.ManagedIdentity/userAssignedIdentities/application-identity --namespace default --resource-group aksloadbalancer --name application-identity
 
 
and I got the error:

![image](https://user-images.githubusercontent.com/117755595/233649203-5f1d4aeb-12ea-4236-b876-42d7ff05bc1f.png)

**Expected behavior**
Pod Identities Get deployed in the provided namespace

**AAD Pod Identity version**

Terraform version: 
+ terraform -version
Terraform v1.4.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.42.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1

"azure-cli": "2.47.0",
azure-cli-core": "2.47.0"
azure-cli-telemetry": "1.0.8"
extensions": {}

**Kubernetes version**
1.24.10

**Additional context**

**Comment by aramase** [comment]
@mkurukun This issue is with the AKS add-on, so I recommend opening an issue [here](https://github.com/Azure/AKS) or opening a support ticket.

@karataliu PTAL!

**Comment by karataliu** [comment]
This is known CLI issue: https://github.com/Azure/azure-cli-extensions/pull/6203
Please try install latest aks-preview cli extension for a fix.
