### ISSUE TITLE
Identity assignment performance issues resulting in slow scale out

### ISSUE THREAD

**Issue by ankrause** [Azure/aad-pod-identity#145]
CloudProvider: Azure VMSS
Version: Latest from source

The below data is all based on VMSS, though I would guess that other scenarios like VMAS using user-assigned identities would be impacted as well.

I've been testing scale scenarios in a test cluster running VMSS built from AKS-Engine. Since the VMSS support commit hasn't been released yet, I've built and published images from current source to my own registry for testing purposes. From what I've seen, all operations are very fast except for CloudProvider.Put. Overall, it generally takes MIC a few seconds to create one identity binding.

```
I0119 21:29:17.404782       1 mic.go:314] Found 3 pods, 2 ids, 2 bindings
I0119 21:29:17.404820       1 stats.go:63] ** Stats collected **
I0119 21:29:17.404825       1 stats.go:59] Pod listing: 32.201µs
I0119 21:29:17.404831       1 stats.go:59] ID listing: 199.438823ms
I0119 21:29:17.404834       1 stats.go:59] Binding listing: 192.956583ms
I0119 21:29:17.404837       1 stats.go:59] Assigned ID listing: 201.481236ms
I0119 21:29:17.404860       1 stats.go:59] System: 593.916043ms
I0119 21:29:17.404863       1 stats.go:59] Cloud provider get: 31.137391ms
I0119 21:29:17.404866       1 stats.go:59] Cloud provider put: 38.190984112s
I0119 21:29:17.404869       1 stats.go:59] Assigned ID addition: 212.117301ms
I0119 21:29:17.404897       1 stats.go:59] Assigned ID deletion: 0s
I0119 21:29:17.404900       1 stats.go:59] Find assigned ids to create: 1.8µs
I0119 21:29:17.404904       1 stats.go:59] Find assigned ids to delete: 800ns
I0119 21:29:17.404907       1 stats.go:59] Total time to add assigned IDs: 38.434392305s
I0119 21:29:17.404910       1 stats.go:59] Total time to delete assigned IDs: 0s
I0119 21:29:17.404913       1 stats.go:59] Event recording: 20.7µs
I0119 21:29:17.404917       1 stats.go:59] Total: 39.028374148s
I0119 21:29:17.404920       1 stats.go:86] *********************
```

Based on my understanding of the code, the Put operation occurs for every new AzureIdentity/Binding  discovered during the current sync iteration. Testing a scale out scenario from 2 to 50 pods, MIC takes up to 30 _minutes_ to create all bindings.

```
I0119 22:37:09.375391       1 mic.go:314] Found 51 pods, 2 ids, 2 bindings
I0119 22:37:09.375405       1 stats.go:63] ** Stats collected **
I0119 22:37:09.375409       1 stats.go:59] Pod listing: 138.601µs
I0119 22:37:09.375433       1 stats.go:59] ID listing: 3.581427ms
I0119 22:37:09.375436       1 stats.go:59] Binding listing: 10.266576ms
I0119 22:37:09.375439       1 stats.go:59] Assigned ID listing: 16.985226ms
I0119 22:37:09.375442       1 stats.go:59] System: 30.97703ms
I0119 22:37:09.375445       1 stats.go:59] Cloud provider get: 1.847651332s
I0119 22:37:09.375448       1 stats.go:59] Cloud provider put: 30m20.235338902s
I0119 22:37:09.375451       1 stats.go:59] Assigned ID addition: 2.14883362s
I0119 22:37:09.375454       1 stats.go:59] Assigned ID deletion: 8.180368555s
I0119 22:37:09.375457       1 stats.go:59] Find assigned ids to create: 299.703µs
I0119 22:37:09.375460       1 stats.go:59] Find assigned ids to delete: 299.202µs
I0119 22:37:09.375462       1 stats.go:59] Total time to add assigned IDs: 30m24.238389098s
I0119 22:37:09.375465       1 stats.go:59] Total time to delete assigned IDs: 8.183649978s
I0119 22:37:09.375468       1 stats.go:59] Event recording: 1.87411ms
I0119 22:37:09.375471       1 stats.go:59] Total: 30m32.453785412s
I0119 22:37:09.375473       1 stats.go:86] *********************
```

In my scenario, this means that the pods that are scaling out are stuck in the "ContainerCreating" state waiting for an identity to be assigned so that they can acquire access to necessary resources required to run (Key Vault, a Key Vault Flex Volume, anything else that requires authentication).

The culprit appears to be this:

```
	if id.Spec.Type == aadpodid.UserAssignedMSI {
		err = c.CloudClient.AssignUserMSI(id.Spec.ResourceID, node)
```

Commenting out this line results in the blazing fast performance I would expect from the recorded stats without the put operation. Removing the line is of course is not ideal, particularly once namespace-specific identities are supported.

I think there are 2 things here -

1. For all new identities created, only send one identity update operation per user-assigned identity per node.
2. If the identity has already been assigned, there is no explicit need to send another update unless the identity has become out of sync (removed somehow) or another process/user manually removed the identity.

Deletion of identities may already have the solution with the `inUse` check, though it relies on at least one pod on the node already having a dependency on the user-assigned identity.  A sudden scale out from 0 nodes all using the same identity wouldn't satisfy this check.

**Comment by kkmsft** [comment]
Closing with #219
