### ISSUE TITLE
Aggregate Issue: Demos and How-Tos

### ISSUE THREAD

**Issue by khenidak** [Azure/aad-pod-identity#153]
Our demos and How-Tos are missing the following component:
1. Create a demo based on applications that uses aad as idp. Example .NET core rest-api that show case how aad + pod identity can be used seamlessly. The demo should contain code sample and steps. 

2. Create a demo based on rest api that connects to Azure sql using aad identities. The demo should contain code sample and steps.

#148

**Comment by kkmsft** [comment]
@khenidak - ping :-)
