### ISSUE TITLE
NMI and MIC can not start after installation

### ISSUE THREAD

**Issue by AndreasM009** [Azure/aad-pod-identity#162]
I tried to install NMI and MIC on a new RBAC enabled cluster. The pod don't run. I get the following error:
```Shell
Error: failed to start container "nmi": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"--host-ip=16.0.0.66\": executable file not found in $PATH": unknown 
Back-off restarting failed container
```
Any ideas?

**Comment by AndreasM009** [comment]
And here is the error I get for MIC:

```Shell
Error: failed to start container "mic": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"--cloudconfig=/etc/kubernetes/azure.json\": stat --cloudconfig=/etc/kubernetes/azure.json: no such file or directory": unknown 
Back-off restarting failed container
```

**Comment by kkmsft** [comment]
@AndreasM009 : Can you please confirm whether the deployment file used was from:

a) the head of the tree - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml
or
b) from the release - https://raw.githubusercontent.com/Azure/aad-pod-identity/1.3.0-mic-1.4.0-nmi/deploy/infra/deployment-rbac.yaml 

Head of the tree is currently broken and (b) needs to be used for now, until the merge of  this PR will fix shortly - https://github.com/Azure/aad-pod-identity/pull/155/files

**Comment by AndreasM009** [comment]
@kkmsft option b) works. Thx

**Comment by kkmsft** [comment]
Thank you, @AndreasM009 . Closing this issue since #155 is merged now.
