### ISSUE TITLE
deployment is failing with error CRD already exists

### ISSUE THREAD

**Issue by rhollins** [Azure/aad-pod-identity#164]
Hi 

The deployment is failing with the following error:

Error: release mangy-vulture failed: customresourcedefinitions.apiextensions.k8s.io "azureidentities.aadpodidentity.k8s.io" already exist

This is the command: helm upgrade aad-pod-identity . --install --namespace kube-system --values values.yaml --kube-context cluster-name --wait --force --timeout 600

The custom resource definitions are not present in a cluster before I run the deployment but its created even thought deployment fails after first run.

I'm deploying this to AKS 1.12.5 helm version v2.12.0

**Comment by kkmsft** [comment]
Hi @rhollins , Thank you for using aad-pod-identity. Looks like this is known issue with helm chart. Here is a link which was posted by another user in helm related bug: 
https://github.com/SparebankenVest/public-helm-charts/tree/master/stable/aad-pod-identity#known-issues
Learning from there, manual deletion seems the way to go for now, until the bugs mentioned in upstream helm is resolved.

**Comment by kkmsft** [comment]
Please let me know if manually deletion works for the issue you saw above.

**Comment by kkmsft** [comment]
Since this is not a Aad-pod-idenitity but helm chart specific issue, closing this bug with manual deletion as work around. Kindly re-open if needed.

**Comment by fawohlsc** [comment]
How can you perform this manual deletion @kkmsft?
