### ISSUE TITLE
Gracefully handle DuplicateIdentityIds errors

### ISSUE THREAD

**Issue by yarinm** [Azure/aad-pod-identity#167]
I've been playing with aad-pod-identity and I tried to apply it on VMs that already have an identity assigned.

To my surprise the MIC was unable to assign the same identity again to the VM:

`I0226 13:06:30.233868       1 crd.go:178] Creating assigned Id: test-bbbb5865c-7fmph-default-azure-identity
I0226 13:06:30.418311       1 cloudprovider.go:132] Find aks-agentpool-15594153-1 in resource group: MC_Adallom-yarin_Flink-RS-Test_westeurope
E0226 13:06:30.542207       1 vm.go:42] compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="DuplicateIdentityIds" Message="The request content has the following duplicate identity ids '/subscriptions/91d8605f-b80a-4b1c-bca1-6ec55bfd1deb/resourcegroups/RS_02_Components_EUW/providers/Microsoft.ManagedIdentity/userAssignedIdentities/yarin-test'."
E0226 13:06:30.542275       1 mic.go:415] compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="DuplicateIdentityIds" Message="The request content has the following duplicate identity ids '/subscriptions/91d8605f-b80a-4b1c-bca1-6ec55bfd1deb/resourcegroups/RS_02_Components_EUW/providers/Microsoft.ManagedIdentity/userAssignedIdentities/yarin-test'."
E0226 13:06:30.674354       1 mic.go:269] compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="DuplicateIdentityIds" Message="The request content has the following duplicate identity ids '/subscriptions/91d8605f-b80a-4b1c-bca1-6ec55bfd1deb/resourcegroups/RS_02_Components_EUW/providers/Microsoft.ManagedIdentity/userAssignedIdentities/yarin-test'."
I0226 13:06:30.674466       1 mic.go:291] Found 1 pods, 1 ids, 1 bindings`

Since the identity is already assigned to the VM why doesn't the MIC gracefully accept it and registers the assignment and leave it as it is?

**Comment by kkmsft** [comment]
#271 - handles the case variability, which ends up resulting in a duplicate ids.
