### ISSUE TITLE
What's the EMSI stated in https://github.com/Azure/aad-pod-identity/blob/master/docs/design/concept.png

### ISSUE THREAD

**Issue by wuhanyumsft** [Azure/aad-pod-identity#168]
What's the meaning of EMSI? And what's it used for?

Thanks,

**Comment by kkmsft** [comment]
EMSI was an old name used for User Assigned Identity.

**Comment by feiyushi** [comment]
"Explicit Managed Service Identity"

**Comment by wuhanyumsft** [comment]
Thanks!

**Comment by stewartadam** [comment]
Could we update the diagram to keep pace with upstream AAD terminology?
