### ISSUE TITLE
Unable to use pod identity inside init containers

### ISSUE THREAD

**Issue by yarinm** [Azure/aad-pod-identity#169]
I'm trying to use MSI in an init container and I get the error: 
`time="2019-03-04T06:36:21Z" level=error msg="missing podname for podip:11.6.0.45, match failed, ip:11.6.0.45 matching pods:&PodList{ListMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ListMeta{SelfLink:/api/v1/pods,ResourceVersion:31310752,Continue:,},Items:[],}" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=11.6.0.45
`

After some testing it seems that problem is with NMI service and the way to queries the pod name [by pod ip](https://github.com/Azure/aad-pod-identity/blob/master/pkg/k8s/client.go#L80)

You can see that because it uses the field selector with the status.phase=Running it can't work in an init container since the pod status during that time is Pending.

I think this needs to change to status.phase==Running or status.phase==Pending. Note that you can use OR in field selector syntax. Only thing that seems to be working doing several not equals.

WDYT?

**Comment by kkmsft** [comment]
cc @rite2nikhil

**Comment by yarinm** [comment]
I've created a PR for this issue - https://github.com/Azure/aad-pod-identity/pull/170

**Comment by kkmsft** [comment]
Thank you, @yarinm for the PR #191 . Closing with with the merge of that PR.
