### ISSUE TITLE
failing to list crds

### ISSUE THREAD

**Issue by AndyMoore** [Azure/aad-pod-identity#172]
getting a lot of errors very quickly in the mic pod:

```E0308 16:59:48.222227       1 crd.go:197] unknown (get azureidentitybindings.aadpodidentity.k8s.io)
E0308 16:59:48.427221       1 crd.go:197] unknown (get azureidentitybindings.aadpodidentity.k8s.io)
E0308 16:59:48.622282       1 crd.go:197] unknown (get azureidentitybindings.aadpodidentity.k8s.io)
E0308 16:59:48.823124       1 reflector.go:205] github.com/Azure/aad-pod-identity/pkg/crd/crd.go:155: Failed to list *v1.AzureIdentity: unknown (get azureidentities.aadpodidentity.k8s.io)
E0308 16:59:49.022428       1 crd.go:197] unknown (get azureidentitybindings.aadpodidentity.k8s.io)
```

aks api server logs say:

```
I0308 16:49:17.523417 1 authorization.go:73] Forbidden: "/apis/aadpodidentity.k8s.io/v1/azureidentitybindings", Reason: "no RBAC policy matched"
--
I0308 16:49:17.523837 1 wrap.go:47] GET /apis/aadpodidentity.k8s.io/v1/azureidentitybindings: (1.183205ms) 403 [Go-http-client/2.0 172.31.15.1:43202]
--
```

which lines up with the above, however the cluster role ('aad-pod-id-mic-role') has:

```
- apiGroups:
  - aadpodidentity.k8s.io
  resources:
  - azureidentitybindings
  - azureidentities
  verbs:
  - get
  - list
  - watch
  - post
  - '*'
```

(i've manually added '*' but to no avail)

the binding:

```roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aad-pod-id-mic-role
subjects:
- kind: ServiceAccount
  name: aad-pod-id-mic-service-account
  namespace: default
```

and the service account matches:

```kubectl get pod mic-5d475449dd-ngck8 -o json | jq ".spec.serviceAccount"
"aad-pod-id-mic-service-account"
```

have i missed anything obvious, or does this look like a cluster specific issue?

**Comment by kkmsft** [comment]
Your setup seems reasonable and should have worked. 
 
Can you please confirm that you used: https://github.com/Azure/aad-pod-identity/blob/master/deploy/infra/deployment-rbac.yaml 
to deploy your setup ?

**Comment by AndyMoore** [comment]
it's basically https://github.com/Azure/aad-pod-identity/tree/master/charts/aad-pod-identity

**Comment by AndyMoore** [comment]
i've done some digging - the mic deployment has the following:

```        args:
          - mic
          - "--kubeconfig=/etc/kubernetes/kubeconfig/kubeconfig"
```

That kubeconfig it uses is the one it mounts from the node, which has:

```        Subject: O=system:nodes, CN=nodeclient
```

So the go client isn't able to read from the api because nodeclient cluster role doesnt have access to the CRDs


When I look at https://github.com/Azure/aad-pod-identity/blob/master/deploy/infra/deployment-rbac.yaml#L190 this doesnt exist

(the offending line I copied was in https://github.com/Azure/aad-pod-identity/blob/master/charts/aad-pod-identity/templates/infra.yaml#L154

I'm pretty sure this worked a month ago though, so 🤷‍♂️ 

I deleted the line above, and there's a new error

```E0310 22:58:17.961576       1 reflector.go:205] github.com/Azure/aad-pod-identity/pkg/mic/node.go:27: Failed to list *v1.Node: nodes is forbidden: User "system:serviceaccount:default:aad-pod-id-mic-service-account" cannot list resource "nodes" in API group "" at the cluster scope
```

Will work through this/other errors and raise a PR against the helm charts..

**Comment by kkmsft** [comment]
cc @ritazh since its a helm chart related issue.

**Comment by AndyMoore** [comment]
fwiw this was all fixed by taking the rbac from https://github.com/Azure/aad-pod-identity/blob/master/deploy/infra/deployment-rbac.yaml and combining with the helm chart (nodes issue was also fixed by it)
