### ISSUE TITLE
Sensible Memory Limits for MIC?

### ISSUE THREAD

**Issue by markusdresch** [Azure/aad-pod-identity#180]
Currently i have a 256 MiB default memory limit on the default namespace where the mic pod resides. Right now it's using 100%. What memory consumption is to be expected and if it depends on how many pods are using aad-pod-identity, how to calculate a sensible memory limit?

*EDIT:* After increasing the memory limit to 512 for this deployment, mic is down to 16Mi. Is this previous increase in memory expected?

**Comment by kkmsft** [comment]
Thank you, @markusdresch for using Aad pod identity. There is logic where the list of pods, list of azure dentities and list of azure identity bindings and captured in memory for comparison logic to work and azureassignedidentities created. How many pods, identities, and binding do you have when you were seeing high memory usage ?

**Comment by markusdresch** [comment]
@kkmsft currently in development i'm using one shared pod idenity for about 40 pods. they only use it to access a key vault on startup to get some connection strings and other configuration data. the pods are pretty idle most of the time. mic memory then increases over time more or less linear from 16 MiB by roughly 20 MiB per day until reset. so after a week it's at ~150 MiB, after two weeks ~300 MiB and so on.

**Comment by kkmsft** [comment]
Thank you for the details @markusdresch . I will attempt a repro and get back. Just so that we are in sync - can you also please let me know how you  are checking the memory state of the mic and which fields were you checking ?

**Comment by markusdresch** [comment]
@kkmsft thanks for looking into it. i'm checking container memory working set in aks insights and with `kubectl top pod`, both provide the same results.

current mic pod uptime: 9d
> NAMESPACE       NAME                                                          CPU(cores)   MEMORY(bytes)
> default         mic-78bc5c847d-bg8ws                                          15m          220Mi

**Comment by kkmsft** [comment]
@markusdresch - I have a setup now which has 41 identities:

`
kubectl get azureassignedidentities | wc -l
      41
`

This is since ~7 hours, but I have seen slight growth in the memory:

`
kubectl top pod mic-7bd7b9cc67-9dfsf 
NAME                   CPU(cores)   MEMORY(bytes)   
mic-7bd7b9cc67-9dfsf   12m          23Mi    
`

Will dig more.

**Comment by kkmsft** [comment]
Performed a go pprof analysis. Although the kubectl top shows 47M, the internal in use from proof was showing only 11M. Digging into why this discrepancy is there to get to the root of why the growth is happening.

**Comment by markusdresch** [comment]
@kkmsft thanks for your effort. just to let you know, the cluster was pretty much idle for the last 4 days and mic memory did not increase. i have a feeling it has to do with pod creation, will have an eye on it.

**Comment by markusdresch** [comment]
it seems like every pod creation adds some memory footprint to mic without releasing memory for deleted pods. so everytime a deployment is updated and pods are recreated, mic memory increases. is there a way to show pod memory in kilobytes? because it seems to be less than 1 MiB per pod creation, so it isn't visible immediately using `kubectl top pod`

**Comment by markusdresch** [comment]
probably not an exact value but 5 pod recreations (`kubectl pod delete`) roughly equal 1 MiB. i just deleted 10 pods and a bit later `kubectl top pod` shows 2 MiB more for mic.

**Comment by BernieWhite** [comment]
Any further thoughts on this issue. I'm seeing a similar behavior.

**Comment by markusdresch** [comment]
this seems to be fixed in the latest release
