### ISSUE TITLE
client_id missing from credential

### ISSUE THREAD

**Issue by fxgsell** [Azure/aad-pod-identity#186]
I ran a test using the same user managed identity between AKS and a VM, and the code works well on the WM but I get slightly different credentials  on AKS:

1.	they have a  similar token with only the last part (after the second '.') is different
2.	`refresh_token` is an empty string
3.	`client_id` is missing.
 
I’m using the same code and same python/sdk versions. At the end of the day I get an error “AuthorizationFailed” only on AKS.

Versions:
'_user_agent': 'python/3.6.7 '
                '(Linux-4.18.0-1014-azure-x86_64-with-Ubuntu-18.04-bionic) '
                'msrest/0.6.6 msrest_azure/0.6.0'

**Comment by kkmsft** [comment]
@fxgsell - Thank you for using aad-pod-identity. Can you please refer to the debugging steps here: https://github.com/Azure/aad-pod-identity/wiki/Debugging and check if everything is in order ?

**Comment by fxgsell** [comment]
I redeployed it on a new cluster and din't get the issue again, not sure what it was but I can't reproduce it.
