### ISSUE TITLE
Cache MSI ServicePrincipalToken

### ISSUE THREAD

**Issue by abhisheknsit** [Azure/aad-pod-identity#193]
NMI is hitting the IMDS endpoint for each call it recieves.

A bad tenant on that node could throttle IMDS endpoint for that node, affecting all other tenants on that Node.
A solution for this can be addition of a cache of tokens, then ServicePrinicalToken can be served through the cache instead of the IMDS endpoint.

**Comment by aramase** [comment]
The problem with this is if the managed identity permissions are changed, then NMI will need to be restarted in order to fetch the new token. This can be a disruptive process. 

Closing this issue since it's been open for a while. Please feel free to reopen if you have any more questions.
