### ISSUE TITLE
Multi-Node AKS Cluster with MSI - Issues 

### ISSUE THREAD

**Issue by droessmj** [Azure/aad-pod-identity#196]
When running with more than 1 node, we're encountering issues with the pod identity not being available to the running pods. 

MIC Logs: 
E0419 18:11:44.286393       1 reflector.go:205] github.com/Azure/aad-pod-identity/pkg/pod/pod.go:70: Failed to list *v1.Pod: Get https://REDACTED.azmk8s.io:443/api/v1/pods?limit=500&resourceVersion=0: dial tcp: lookup REDACTED.azmk8s.io on 172.20.0.10:53: read udp 10.244.1.5:48894->172.20.0.10:53: i/o timeout
E0419 18:11:44.286397       1 reflector.go:205] github.com/Azure/aad-pod-identity/pkg/crd/crd.go:155: Failed to list *v1.AzureIdentity: Get https://REDACTED.azmk8s.io:443/apis/aadpodidentity.k8s.io/v1/azureidentities?limit=500&resourceVersion=0: dial tcp: lookup REDACTED.azmk8s.io on 172.20.0.10:53: read udp 10.244.1.5:48894->172.20.0.10:53: i/o timeout
E0419 18:12:15.287106       1 reflector.go:205] github.com/Azure/aad-pod-identity/pkg/mic/node.go:27: Failed to list *v1.Node: Get https://REDACTED.azmk8s.io:443/api/v1/nodes?limit=500&resourceVersion=0: dial tcp: i/o timeout
E0419 18:12:15.287972       1 reflector.go:205] github.com/Azure/aad-pod-identity/pkg/crd/crd.go:154: Failed to list *v1.AzureIdentityBinding: Get https://REDACTED.azmk8s.io:443/apis/aadpodidentity.k8s.io/v1/azureidentitybindings?limit=500&resourceVersion=0: dial tcp: i/o timeout
E0419 18:12:15.289208       1 reflector.go:205] github.com/Azure/aad-pod-identity/pkg/pod/pod.go:70: Failed to list *v1.Pod: Get https://REDACTED.azmk8s.io:443/api/v1/pods?limit=500&resourceVersion=0: dial tcp: i/o timeout
E0419 18:12:15.290293       1 reflector.go:205] github.com/Azure/aad-pod-identity/pkg/crd/crd.go:155: Failed to list *v1.AzureIdentity: Get https://REDACTED.azmk8s.io:443/apis/aadpodidentity.k8s.io/v1/azureidentities?limit=500&resourceVersion=0: dial tcp: i/o timeout

The exact same configuration works without issue when scaled down to 1 node. 

AzureIdentity Information

apiVersion: v1
items:
- apiVersion: aadpodidentity.k8s.io/v1
  kind: AzureIdentity
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"aadpodidentity.k8s.io/v1","kind":"AzureIdentity","metadata":{"annotations":{},"name":"msi-myapp1-d","namespace":"default"},"spec":{"ClientID":"xxxxxxxx","ResourceID":"xxxxxxx","type":0}}
    creationTimestamp: 2019-04-04T22:29:44Z
    generation: 1
    name: msi-myapp1-d
    namespace: default
    resourceVersion: "6698"
    selfLink: /apis/aadpodidentity.k8s.io/v1/namespaces/default/azureidentities/msi-myapp1-d
    uid: 25473c47-5729-11e9-8ab5-663a797ff600
  spec:
    ClientID: xxxxxxxxx
    ResourceID: xxxxxxxxx
    type: 0

kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

Pod Info:
NAME                                         READY     STATUS    RESTARTS   AGE
mic-ddbdd6475-hs7rg                          1/1       Running   0          2h
nmi-4tv7w                                    1/1       Running   0          3h
nmi-69fdj                                    1/1       Running   0          3h
nmi-czm8v                                    1/1       Running   0          3h

Node Info:
NAME                    STATUS    ROLES     AGE       VERSION
aks-agentpool-XXXXX-0   Ready     agent     14d       v1.12.6
aks-agentpool-XXXXX-1   Ready     agent     3h        v1.12.6
aks-agentpool-XXXXX-2   Ready     agent     3h        v1.12.6

The cluster's SP has appropriate permissions on the MSI, as mentioned by how this works without having multiple nodes in play. 

If there's any configuration that appears off, it's possibly my redaction.

**Comment by khenidak** [comment]
Do you have any other controllers running on the cluster. Controllers that perform `list+watch`.. are they healthy?

**Comment by droessmj** [comment]
Four other Deployments exist on the cluster, all of which are healthy. One is an Nginx Ingress. If that doesn't qualify as a Controller, apologies as it's a newer term I'm just digging into. Aside from the pods associated with said Deployments, the only other resources on the cluster are the AAD pod identity components and Services associated with the pods.

**Comment by khenidak** [comment]
The error above indicates that `mic` can not access the DNS server of the cluster running on `172.20.0.10:53` that is a service IP. There can be many reasons for that. But as a suspect is `kube-proxy` Ngnix might have already cached the ip. The easy way to check this is to run a pod on the same node as `mic` and exec into it to test DNS connectivity from that node.

**Comment by droessmj** [comment]
So if I'm following correctly, running `mic` on the same node as nginx would be expected to work and running it on separate nodes could be the cause of this issue?

`exec`-ing into a pod on the same node as `mic` . Dumping /etc/resolv.conf shows my nameserver as 172.20.0.10, which aligns with above. 

Should I be looking to resolve the FQDN for the AKS management domain above? Or am I just testing general DNS connectivity? I can confirm DNS lookups to 172.20.0.10 for internal cluster resources resolve.

**Comment by droessmj** [comment]
The more I poke, the more it does appear that the pod(s) cannot resolve DNS for the domain. When I drop into a shell on the node itself, it doesn't have any issues resolving the endpoint, but the pod networking fails. I believe that should confirm our NSGs are appropriately configured for the scenario and further demonstrate the issue is contained within the cluster.

**Comment by khenidak** [comment]
Yes please. resolve anything actually. Typically something inside the cluster and something outside the cluster. You can use `nslookup` command

**Comment by droessmj** [comment]
When I first tested DNS, I was getting failures in resolving DNS entries using cluster DNS capabilities, both internal and external. DNS resolution from the node itself was fine, but within the cluster it wasn't. After kicking the CoreDNS pods, I was able to resolve DNS internally and externally, and the AAD pod identity capabilities were functioning. However, no more than 30 minutes later the pod identity returned to showing the same issues above. Again this morning I'm seeing CoreDNS issues. Killing the existing pods and starting fresh seems to again resolve the DNS lookup problem identified above. 

Normally at this point I'd open a ticket with MSFT on the CoreDNS pods, but we've only seen this issue on clusters running AAD pod identity. Knowing that this works with iptables, I'm wondering if there's conflicting behavior in play?

**Comment by khenidak** [comment]
We have not seen this behavior elsewhere. What i can tell is there is an issue resolving DNS entries on the cluster generally. Yes it depends on iptables but that shouldn't be a problem. What else are you running on the node that can be wrangling iptables?

**Comment by khenidak** [comment]
Also, I am mostly free today (PST timezone). Do you want to jump on a call, share screens? 

I am: khnidk at microsoft com

**Comment by droessmj** [comment]
I would love to jump on a call and screen share. We have a support ticket open with Microsoft, and our support engineer was going to engage you. The only things I know of wrangling iptables are AAD pod identity and whatever runs in the kube-system Microsoft managed namespace. 

We have TwistLock running on these clusters, but I don't believe that touches iptables.

**Comment by khenidak** [comment]
To close, The RCA is, cluster subnet was not tied to the route table in which the controller manager was assigning routes. This is needed in `kubenet` setup. Without it any pod->pod traffic across nodes will fail. Once the we linked the subnet to the route table everything fell in the right place.
