### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by gb-42** [Azure/aad-pod-identity#200]
Please add --forceNamespaced to mic and nmi in yaml file. It would be great to replace true || false (what ever is the default) in the deploy pipeline. 

Please add .Release.Namespace in the helm charts. If I read right...aad-pod-identity can now be deployed to any namespace, if possible please use something like aadpodidentity-system (i.e. similar to kube-system, istio-system, etc...)

**Comment by kkmsft** [comment]
Duplicate of #285 . Please follow that issue for further updates. The forceNamespaced is provided as option in the PR.
