### ISSUE TITLE
Pod Identity should not use azure.json

### ISSUE THREAD

**Issue by khenidak** [Azure/aad-pod-identity#204]
Please switch Pod Identity to use its own configuration. Azure Pod Identity should depend on its own configuration/identity to run `mic`. 

ref: https://github.com/kubernetes/kubernetes/issues/77309

@kkmsft

**Comment by kkmsft** [comment]
@feiyushi had already started working on this.

**Comment by kkmsft** [comment]
Released with https://github.com/Azure/aad-pod-identity/releases/tag/v1.5
