### ISSUE TITLE
default namespace used for azureassignedidentity (the rest in non-default ns)

### ISSUE THREAD

**Issue by erjosito** [Azure/aad-pod-identity#212]
I am using AKS 1.13.5. I deployed all the components (mic:1.3, nmi:1.4, azureidentity, azureidentitybinding, serviceaccount, clusterrolebinding and demo pod (nikhilbh/demo:1.0) in a non-default namespace. 

All seems to work fine, but the azureassignedidentity is created in the default namespace. I would have expected to see it under the non-default namespace where the rest of the stuff is?

**Comment by aramase** [comment]
@kkmsft For namespaced identities, the pod ns == azureid ns == azure binding ns. So I can make the change to use the namespace to be derived from that. But for non namespaced identities, it's possible that the azureidentity, binding and pods can exist in different namespaces. In that scenario do we want to use the namespace of the azure identity/binding/pod ns?

**Comment by aramase** [comment]
@erjosito Thank you for trying out aad-pod-identity. I had a question - Are you using namespaced identities? https://github.com/Azure/aad-pod-identity#understanding-namespaced-identities

**Comment by erjosito** [comment]
Nope. But I deployed mic and nmi in a non-default ns.

**Comment by aramase** [comment]
@erjosito That is the expected behavior today. If namespaced identities are used, then we create the assigned identity in the same namespace as the identity, binding and pods. Otherwise, the assigned identities will always be created in the default namespace.
