### ISSUE TITLE
AAS Pod Identity with virtual nodes

### ISSUE THREAD

**Issue by samrobillard** [Azure/aad-pod-identity#236]
Hi,

I tried to use aad-pod-identity with AKS virtual nodes but as soon as I add the 'args' and 'env' parts to my deployment yaml, the pods get depoyed in ACI but are instantly in a 'waiting' state and I can't connect to them or pull the logs. Using the same yaml to deploy on regular nodes works flawlessly. I know there are limitations with daemonsets and virtual-kubelet but I'm not sure if it applies to this product. Anybody got this issue or can point me to a solution?

Thanks,

**Comment by aramase** [comment]
@samrobillard Can you try the describe the pods that are in waiting state? That should give us more info as to what's happening.

**Comment by jsturtevant** [comment]
What are logs for the MIC and NMI (https://github.com/Azure/aad-pod-identity/blob/master/README.md#components)?  

I dont think this will work becuase the "MIC adds or deletes assigned identities as needed."  And ACI doesnt have underlying nodes.  The NMI also uses IP tables to intercept trafic which will also probably wont work in this scenario.

Another point is that Virtual Nodes, which is ACI deployed into a vnet, doesn't currently support Managed Identities(https://docs.microsoft.com/en-us/azure/container-instances/container-instances-vnet#virtual-network-deployment-limitations)

The MIC amd NMI can probably be worked around but given MSI support for vnets, I think this will not work until that is resolved.

**Comment by samrobillard** [comment]
@jsturtevant thanks for the insight! I was leaning toward this thinking as well but wanted to get another opinion. I'll close this ticket.
