### ISSUE TITLE
Getting iptables: Resource temporarily unavailable from NMI

### ISSUE THREAD

**Issue by abhisheknsit** [Azure/aad-pod-identity#249]
**Describe the bug**
We are getting the following error from NMI on subset of the nodes. NMI is restarting continuously with this error.
```time="2019-06-06T09:16:54Z" level=fatal msg="running [/sbin/iptables -t nat -F aad-metadata --wait]: exit status 4: iptables: Resource temporarily unavailable.\n```

NMI is using iptables version: iptables v1.6.2
Kubeproxy is using iptables version: iptables v1.6.0
Cilium is using iptables version: iptables v1.6.1

**Steps To Reproduce**
Not able to reproduce

**Expected behavior**
Should not restart and run as expected.

**AAD Pod Identity version**
NMI version 1.4
**Kubernetes version**

**Additional context**
Not an expert on Iptables, would love if some direction could be provided for troubleshooting.

**Comment by kkmsft** [comment]
@abhisheknsit : Can you please let us know if this issue still exists ?

**Comment by abhisheknsit** [comment]
@kkmsft Yes the issue still exists. The problem is not with error, the problem is NMI exits on this error.

**Comment by kkmsft** [comment]
@abhisheknsit - Setting up iptables is the core functionality for NMI. Hence its essential for it to restart to indicate the issue to cluster operator. If we move this to Error from Fatal, the issue will be present and NMI will keep operating without doing what it should do. Hence we feel that the Fatal should continue to be there - WDYT ?

**Comment by kkmsft** [comment]
@abhisheknsit - Thoughts on the above ^^ ?

**Comment by aramase** [comment]
Closing this issue. Please reopen if you still have the issue.
