### ISSUE TITLE
Monitoring?

### ISSUE THREAD

**Issue by omerlh** [Azure/aad-pod-identity#263]
**Describe the request**
How can I monitor AAD pod identity? Taking a quick look at the code, I didn't see any prometheus metrics exposed. 

**Explain why AAD Pod Identity needs it**
AAD pod identity is a service that other applications depend upon, therefore it's pretty critical to monitor it and ensure it's working.

**Describe the solution you'd like**
Good visibility to AAD pod identity (prometheus metrics) that can be used to detect errors. 
It will be nice to have detailed documentation on what to monitor.

**Describe alternatives you've considered**

**Additional context**

**Comment by kkmsft** [comment]
@omerlh - would the liveliness probe and the corresponding "Active/Non-Active" state returned in the contents of the /healthz (in both MIC and NMI) fulfill the requirement you had with checking of the state of Aad-pod-identities working ?

**Comment by omerlh** [comment]
That will be a very good start, I wonder what relevant metrics should be expert on Prometheus?

**Comment by elutsky** [comment]
We think about the following metrics (with representative cluster dimensions, like pod, service, release, namespace, identityName, identityBinding, ...):
		

- # of "active" AzureAssignedIdentities
- # of Failed / non-existing identities 
- Latency of Identity Assignment / Binding
- Overall token request
- mapping data, like "# of Pods per identity"...
- something we missed ...

**Comment by omerlh** [comment]
Looks good :)
