### ISSUE TITLE
Handle case sensitivity in resourceID format

### ISSUE THREAD

**Issue by aramase** [Azure/aad-pod-identity#269]
**Describe the bug**
When identity is manually assigned to node using az cli, the resourceID uses `resourceGroups` in the format `/subscriptions/[REDACTED]/resourceGroups/devcluster/providers/Microsoft.ManagedIdentity/userAssignedIdentities/keyvault-identity` . When a new identity is created the resourceID returned however has `resourcegroups` `/subscriptions/[REDACTED]/resourcegroups/devcluster/providers/Microsoft.ManagedIdentity/userAssignedIdentities/keyvault-identity`. We need to normalize the resourceID format before performing a check to see if they are equal.

**Steps To Reproduce**

**Expected behavior**

**AAD Pod Identity version**

**Kubernetes version**

**Additional context**

**Comment by kkmsft** [comment]
Closing it via #271
