### ISSUE TITLE
will identity assignment work for cronjob?

### ISSUE THREAD

**Issue by smartpcr** [Azure/aad-pod-identity#278]
when I add aadpodidbinding label to `CronJob`, I don't see identity assignment using the following command:
```
kubectl get AzureAssignedIdentities --all-namespaces -o yaml
```

Should I do something different than other normal deployments?

thanks!

**Comment by aramase** [comment]
@smartpcr Thank you for using aad-pod-identity. aad-pod-identity is currently supported only for pods. So this will not work for cronjobs.

**Comment by smartpcr** [comment]
thanks, got it fixed.

**Comment by gimlichael** [comment]
> @smartpcr Thank you for using aad-pod-identity. aad-pod-identity is currently supported only for pods. So this will not work for cronjobs.

When will cronjob be supported? I just used a lot of time to get a cronjob to work .. have a dockerized console app that needs to run .. and secrets are stored in keyvault .. don't want to use the FlexVol approach.

Thanks.

**Comment by JerrySantana92** [comment]
Is this supported now?

Same here! I have one Job and one CronJob that fetches data from key vault, when is this going to be available?

**Comment by gimlichael** [comment]
> Is this supported now?
> 
> Same here! I have one Job and one CronJob that fetches data from key vault, when is this going to be available?

Yes, it is working quite fine .. was acutally supported when i added my question .. just never updated in documentation.

**Comment by JerrySantana92** [comment]
> > Is this supported now?
> > Same here! I have one Job and one CronJob that fetches data from key vault, when is this going to be available?
> 
> Yes, it is working quite fine .. was acutally supported when i added my question .. just never updated in documentation.

@gimlichael would it be possible for you to share your yaml file? I have been looking for documentation on how to use the AzureIdentity (PodIdentity) but I couldn't find anything.

**Comment by gimlichael** [comment]
> > > Is this supported now?
> > > Same here! I have one Job and one CronJob that fetches data from key vault, when is this going to be available?
> > 
> > 
> > Yes, it is working quite fine .. was acutally supported when i added my question .. just never updated in documentation.
> 
> @gimlichael would it be possible for you to share your yaml file? I have been looking for documentation on how to use the AzureIdentity (PodIdentity) but I couldn't find anything.

Just follow the guide here: https://github.com/Azure/aad-pod-identity
In case of issues, they are most likely related to typo or similar.

The powershell script shared in this article helped me: https://dev.to/cmendibl3/aks-read-azure-key-vault-secrets-using-aad-pod-identity-2f3i

Good luck.
