### ISSUE TITLE
Helm charts

### ISSUE THREAD

**Issue by kkmsft** [Azure/aad-pod-identity#285]

**Comment by lodejard** [comment]
I noticed this is "In Review" - I'm eagerly anticipating what form the chart will take. Is there a PR in an official repo where this is being reviewed?

**Comment by kkmsft** [comment]
@lodejard - please find the PR here: https://github.com/helm/charts/pull/15306

**Comment by lodejard** [comment]
Hi, @kkmsft thanks for the link!

Say, @aramase, we've been using a copy of your chart where we've updated the metadata labels to follow the newer `app.kubernetes.io/...` recommendations. It also organizes the resources templates by mic- and nmi- prefixes, which seems to be a common practice in charts that have more than one distinct component.

Hope you don't mind, I took the liberty of sending you a PR aramase/charts#1 containing those adjustments. Would you like to take a look and consider merging it into your fork before the merge into the official repo is complete? We'd love to be able to delete our adjusted copy and use the official chart directly. :)

**Comment by aramase** [comment]
Closing with https://github.com/Azure/aad-pod-identity/pull/373
