### ISSUE TITLE
NMI logs show `can't initialize iptables table 'nat': Permission denied`

### ISSUE THREAD

**Issue by uipo78** [Azure/aad-pod-identity#294]
**Describe the bug**
The NMI pods aren't able to run successfully. This appears in their logs:
```
time="2019-07-16T22:26:05Z" level=fatal msg="running [/sbin/iptables -t nat -N aad-metadata --wait]: exit status 3: iptables v1.6.2: can't initialize iptables table `nat': Permission denied (you must be root)\nPerhaps iptables or your kernel needs to be upgraded.\n"
```

**Steps To Reproduce**
Follow the installation instructions that you provide on a PSP-enabled cluster, where the PSP associated with the nmi `DaemonSet`'s `ServiceAccount` is `privileged`.

**Expected behavior**
Able to update the table `nat`

**AAD Pod Identity version**
nmi `1.4`

**Kubernetes version**
`v1.13.5`

**Additional context**

**Comment by kkmsft** [comment]
Closing this with merge of #354

**Comment by donngchao** [comment]
For my situation, I just install the rpm package of the NAT kernel module(modules-nat).
