### ISSUE TITLE
next release

### ISSUE THREAD

**Issue by bnookala** [Azure/aad-pod-identity#297]
I'm working on a project that would only like to use releases of the aad-pod-identity project. We noted that the last release was in January (https://github.com/Azure/aad-pod-identity/releases/tag/1.3.0-mic-1.4.0-nmi), but there have been a number of commits to the project since. Just wondering if this next milestone reflects the progress towards the next release? https://github.com/Azure/aad-pod-identity/milestone/1

**Comment by sukhong** [comment]
We are also currently blocked by this issue, because current aad-pod-identity only works in Azure Public Cloud (https://github.com/Azure/aad-pod-identity/issues/224). We have an immediate need to move to USGov and China.

I see that fix has already been checked into master on May 22.

Is there a guide on how to build a custom image from master branch and use it until new release is out?

**Comment by kkmsft** [comment]
@bnookala , @sukhong - Thank you for the issue and interest in aad-pod-identity. We are planning for a release around July end/early August as we wrap up the project items in https://github.com/Azure/aad-pod-identity/milestone/1. We are planning to release an RC version from the current code next week. Will update this thread with the information on running those  images next week. 

@sukhong - 
for custom image building you can use the the following steps:
make build
make image
make push
Please note that the variable values for REGISTRY, MIC_IMAGE, NMI_IMAGE, IDENTITY_VALIDATOR_IMAGE,  DEMO_IMAGE, MIC_VERSION, NMI_VERSION, IDENTITY_VALIDATOR_VERSION, DEMO_VERSION

should be set as per the required image names and version. 

For example, if the repo name is 'test.azurecr.io', then the 
export REGISTRY=test.azurecr.io 
after setting the USE_VERSION variable to custom version update, export the following for getting  the mic image. Please set the rest of variables for other images.
export MIC_IMAGE=mic:$USE_VERSION
export MIC_VERSION=$USE_VERSION

Also, please note that the deployment files should be changed to use the new images in the corresponding acr. Hope that helps.

**Comment by kkmsft** [comment]
1.5-rc2 is available now. Please provide us with valuable feedback toward 1.5 release. https://github.com/Azure/aad-pod-identity/releases/tag/1.5-rc2

**Comment by kkmsft** [comment]
FYI ^^ 

@bnookala @sukhong @markusdresch omerlh @xenalite @droessmj  @woutervanvliet @ankrause @zhiweiv  @abhisheknsit

**Comment by kkmsft** [comment]
We just released 1.5: https://github.com/Azure/aad-pod-identity/releases/tag/v1.5
With this closing the bug. Please reopen if there are more questions.
