### ISSUE TITLE
mic fails to launch because deployment.yaml (with azure.json) does not pass --cloudconfig correctly

### ISSUE THREAD

**Issue by sukhong** [Azure/aad-pod-identity#298]
In the latest build from master, I have noticed that mic, with azureconfig.json, fails to launch with following errors:
````
E0723 04:04:28.619751       1 main.go:35] Starting mic process. Version: 0.0.0-899996. Build date: 2019-07-23-03:33
E0723 04:04:28.622686       1 main.go:37] --cloudconfig not passed will use aadpodidentity-admin-secret
E0723 04:04:28.622701       1 main.go:40] --kubeconfig not passed will use InClusterConfig
E0723 04:04:28.622705       1 main.go:43] kubeconfig () cloudconfig ()
E0723 04:04:28.624110       1 cloudprovider.go:69] Get cloud env error: autorest/azure: There is no cloud environment matching the name ""
F0723 04:04:28.624323       1 main.go:53] Could not get the MIC client: autorest/azure: There is no cloud environment matching the name ""
````
In the current mic deployment yaml file, it passes --cloudconfig via following:
````
      containers:
      - args:
        - mic
        - --cloudconfig=/etc/kubernetes/azure.json
        - --logtostderr
        - --forceNamespaced
````
However, this is wrong because it is also treating "mic" as an argument. Flag package sees mic as an invalid argument, and stops parsing immediately. It never parses --cloudconfig correctly, and always defaults to an empty string.

I was immediately able to fix this by removing mic from args:
````
      containers:
      - args:
        - --cloudconfig=/etc/kubernetes/azure.json
        - --logtostderr
        - --forceNamespaced
````
Docker image already comes with entry point "mic". We don't need to pass mic or nmi as arguments.

The same parsing bug applies to other nmi as well.

**Steps To Reproduce**

Simply run the latest mic with a deployment.yaml file with azure.json file (using --cloudconfig flag) WITHOUT aadpodidentity-admin-secrets set. It simply fail to launch, because it fails to parse --cloudconfig, tries to load from aadpodidentity-admin-secrets (which is empty), and cloudconfig parsing eventually fails.

**Expected behavior**

mic controller should correctly parse --cloudconfig argument and launch successfully.

**AAD Pod Identity version**

I pulled the latest image, commit hash: 899996

**Kubernetes version**

1.14.1

**Comment by kkmsft** [comment]
@sukhong - the master binaries do not need the mic/nmi entry points as parameters. The deployment yaml was not changed since the released images had the need to pass the parameter of image name. Please check if the issues go away after removing mic and nmi parameters from the yaml file.

**Comment by sukhong** [comment]
I looked at the code, and could not find anywhere it required the image name as parameters.

For mic, if I remove mic from arguments, it works. But for nmi, it fails when I remove nmi from arguments.

But if I make it more explicit and separate them into command and arguments, it succeeds for both:
````
    - command: ["mic"]
      args: ["--cloudconfig=/etc/kubernetes/azure.json", "--logtostderr", "--forceNamespaced"]
````
````
    - command: ["nmi"]
      args: ["--host-ip=$(HOST_IP)", "--node=$(NODE_NAME)", "--forceNamespaced"]
````

**Comment by kkmsft** [comment]
@sukhong - Please refer to the image and parameters here: https://github.com/Azure/aad-pod-identity/pull/277/files#diff-9ff9f142ba4c162c6ca13d59c241b47f
(This change has other parts like ReplicaSet and RBAC rules added, hence cannot be directly used until that PR goes in. But can be used for reference:
```
containers:
      - name: mic
        image: "mcr.microsoft.com/k8s/aad-pod-identity/mic:1.3"
        imagePullPolicy: Always
        args:
          - "--cloudconfig=/etc/kubernetes/azure.json"
          - "--logtostderr"
```
Please note the absence of the entry point parameter.

**Comment by sukhong** [comment]
I see, for now I am using above command:[imagename], args:[...], and it is working fine.

I will close this bug. Really looking forward to 1.5 release!
