### ISSUE TITLE
No `nmi` bin in the expected dir

### ISSUE THREAD

**Issue by trstringer** [Azure/aad-pod-identity#30]
For the `nikhilbh/nmi:1.0` image used for the nmi deployment, I'm seeing the following error (Kubernetes):

> container_linux.go:247: starting container process caused "exec: \"--host-ip=x.x.x.x\": executable file not found in $PATH"

_Note: the IP address is populated, I just removed it from the error message_

Running this container locally on my host, I can see that the `nmi` bin is indeed not located in `/bin`.

    docker run --rm -it nikhilbh/nmi:1.0 ls -la /bin

Looking at the Dockerfile for this image, it looks like it should be present there.

**Comment by kkmsft** [comment]
The image has been updated to fix this.

**Comment by trstringer** [comment]
Great thanks!
