### ISSUE TITLE
Documentation chronology

### ISSUE THREAD

**Issue by spaelling** [Azure/aad-pod-identity#300]
I dislike the chronology of the [README.md](../blob/master/README.md), and found it abit confusing. I would like to see a more clear division of what is strictly concerning AAD Pod Identity and what is related to ex. the demo.

My understanding is that step 1. and 4. are the only steps that are necessary to get AAD Pod Identity running, with an extra step in 4. once an _AzureIdentity_ is created for some specific pod/deployment.

The Azure Identity (2. and 3.), and the binding (5.) should be part of a __demo__ section rather. Also you cannot really do 5. before you know what the _aadpodidbinding_ label on the pod is. In the demo deployment it is _demo_, so perhaps use this example instead?

>  6. Set Permissions for MIC

> If the Azure identity is in the same resource group as your AKS cluster nodes, you can skip this section. (For AKS, a resource group was added with an MC_ prefix when you created the cluster.) Otherwise, follow these steps to assign the required permissions:

Wouldn't that be the case in most situations? I found this confused me much more than it helped.

> Find the service principal used by your cluster. Please refer to the AKS docs for details.

You can do that regardless if you specific a SP or not during cluster creation

```bash
az aks show -g <AKS RESOURCE GROUP> -n <AKS CLUSTER NAME> --query servicePrincipalProfile.clientId
```

and for good measure mention that `<full id of the managed identity>` is the one from step 2.

2 more notes for the [debugging wiki](https://github.com/Azure/aad-pod-identity/wiki/Debugging)

there is a newline missing in

```bash
$ kubectl get po busybox0 --show-labels NAME READY STATUS RESTARTS AGE LABELS busybox0 1/1 Running 10 10h aadpodidbinding=select_it,app=busybox0
```
if using VM scale sets the command for the _user identity assignment_ should be

```bash
az vmss identity show -g <resource group> -n <scale set name>
```

**Comment by kkmsft** [comment]
@spaelling - Thank you for raising this issue. As an open source project we are always looking for more contributors :-) Would you be interested in raising PRs for the same ?

**Comment by spaelling** [comment]
Not seeing any way to fork the wiki repository. I added the original wiki files to the forked repo, but the changes does not show up as a commit.

**Comment by kkmsft** [comment]
I modified the two items, the new line and the VMSS instructions. Thank you, @spaelling

**Comment by aramase** [comment]
Closing this issue with #304.
