### ISSUE TITLE
ERROR: logging before flag.Parse in NMI logs

### ISSUE THREAD

**Issue by aramase** [Azure/aad-pod-identity#314]
**Describe the bug**
This message `ERROR: logging before flag.Parse` shows up in the NMI logs when the probes are initialized and started. This is because glog requires `flag.Parse` to be called before any logging is done. Every time glog is called, it'll contain that error message.

**Steps To Reproduce**

**Expected behavior**

**AAD Pod Identity version**

**Kubernetes version**
master

**Additional context**

**Comment by kkmsft** [comment]
Closing with #317.
