### ISSUE TITLE
The Demo App app defaults to  some rando subscription/RG settings

### ISSUE THREAD

**Issue by ivanthelad** [Azure/aad-pod-identity#32]
attempting to run the demo app will result in a bunch of 403 errors as it tries to access a preset subscription, see output{1}, the demo app sets these values as defaults https://github.com/Azure/aad-pod-identity/blob/master/cmd/demo/main.go#L20

Easiest would be to update the deployment resource by setting a "command" and "argument" attribute to  override how the container is started and set the appropriate flags  there.
https://github.com/Azure/aad-pod-identity/blob/master/deploy/demo/deployment.yaml#L15

Readme, should be updated accordingly. 

{1} demoapp output 
`4-c2x24
time="2018-05-31T16:06:01Z" level=error msg="failed list all vm azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/c1089427-83d3-4286-9f35-5af546a6eb67/resourceGroups/MC_nbhatia-eu-01_eu-1_eastus/providers/Microsoft.Compute/virtualMachines?api-version=2017-12-01: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: No AzureAssignedIdentity found for pod:default/demo-c6dc8f664-c2x24\n" podip=10.244.1.9 podname=demo-c6dc8f664-c2x24 podnamespace=demo-c6dc8f664-c2x24
time="2018-05-31T16:06:01Z" level=error msg="failed to refresh ServicePrincipalTokenFromMSI using the MSI VM extension, msiEndpoint(http://169.254.169.254/metadata/identity/oauth2/token)" podip=10.244.1.9 podname=demo-c6dc8f664-c2x24 podnamespace=demo-c6dc8f664-c2x24
time="2018-05-31T16:06:01Z" level=error msg="testMSIEndpoint failed, <nil>" podip=10.244.1.9 podname=demo-c6dc8f664-c2x24 podnamespace=demo-c6dc8f664-c2x24
time="2018-05-31T16:06:01Z" level=error msg="failed list all vm azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/c1089427-83d3-4286-9f35-5af546a6eb67/resourceGroups/MC_nbhatia-eu-01_eu-1_eastus/providers/Microsoft.Compute/virtualMachines?api-version=2017-12-01: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: No AzureAssignedIdentity found for pod:default/demo-c6dc8f664-c2x24\n" podip=10.244.1.9 podname=demo-c6dc8f664-c2x24 podnamespace=demo-c6dc8f664-c2x24
time="2018-05-31T16:06:04Z" level=error msg="failed to refresh ServicePrincipalTokenFromMSI using the MSI VM extension, msiEndpoint(http://169.254.169.254/metadata/identity/oauth2/token)" podip=10.244.1.9 podname=demo-c6dc8f664-c2x24 podnamespace=demo-c6dc8f664-c2x24
time="2018-05-31T16:06:04Z" level=error msg="testMSIEndpoint failed, <nil>" podip=10.244.1.9 podname=demo-c6dc8f664-c2x24 podnamespace=demo-c6dc8f664-c2x24
time="2018-05-31T16:06:04Z" level=error msg="failed list all vm azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/c1089427-83d3-4286-9f35-5af546a6eb67/resourceGroups/MC_nbhatia-eu-01_eu-1_eastus/providers/Microsoft.Compute/virtualMachines?api-version=2017-12-01: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: No AzureAssignedIdentity found for pod:default/demo-c6dc8f664-c2x24\n" podip=10.244.1.9 podname=demo-c6dc8f664-c2x24 podnamespace=demo-c6dc8f664-c2x24
^C
`

**Comment by rite2nikhil** [comment]
Thanks for reporting the issue. Will fix this right away.

**Comment by rite2nikhil** [comment]
This was fixed. https://github.com/Azure/aad-pod-identity/pull/33
