### ISSUE TITLE
Sporadic amount of pods receiving identity

### ISSUE THREAD

**Issue by android2221** [Azure/aad-pod-identity#323]
**Describe the bug**
When releasing about 25 pods into the cluster with Helm, a sporadic amount of them get assigned identities. Errors appear in the NMI log.

**Steps To Reproduce**
Release a large amount of pods into the cluster. Note in the MIC logs that the pods in question do not appear. 

**Expected behavior**
Pods would receive identities like the other pods.

**AAD Pod Identity version**
1.5-rc2

**Kubernetes version**
v1.12.6

**Additional context**
Deleting the pods and allowing them to recreate seems to allow them to sporadically receive an Identity. Some of the pods are replicated, and this affects some, both, or none of the replicated pods sporadically as well - the fact that they are replicated does not seem to matter.

The errors below are present for each of the affected pods in the MIC logs:

`time="2019-07-31T20:27:09Z" level=error msg="failed to get service principal token for pod:<NAMESPACE HERE>/<POD NAME HERE>, adal: Refresh request failed. Status Code = '400'. Response body: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\"\"http://www.w3.org/TR/html4/strict.dtd\">\r\n<HTML><HEAD><TITLE>Bad Request</TITLE>\r\n<META HTTP-EQUIV=\"Content-Type\" Content=\"text/html; charset=us-ascii\"></HEAD>\r\n<BODY><h2>Bad Request - Request Too Long</h2>\r\n<hr><p>HTTP Error 400. The size of the request headers is too long.</p>\r\n</BODY></HTML>\r\n" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.20.33.48
`

**Comment by android2221** [comment]
I should also note that it only seems as though one of the MIC pods happens to be doing work and producing logs, the others are all showing this as their last produced log message, and appear to sit idle: 
`I0731 20:20:20.516979       1 main.go:51] Starting mic process. Version: 1.5-rc2. Build date: 2019-07-27-00:29
W0731 20:20:20.517023       1 main.go:56] --kubeconfig not passed will use InClusterConfig
I0731 20:20:20.517027       1 main.go:59] kubeconfig () cloudconfig (/etc/kubernetes/azure.json)
I0731 20:20:20.517181       1 mic.go:83] Starting to create the pod identity client. Version: 1.5-rc2. Build date: 2019-07-27-00:29
I0731 20:20:20.518518       1 probes.go:44] Initialized and started health probe
I0731 20:20:20.518532       1 mic.go:131] Initiating MIC Leader election
I0731 20:20:20.518538       1 leaderelection.go:175] attempting to acquire leader lease  default/aad-pod-identity-mic...
`

**Comment by aramase** [comment]
@android2221 Thank you for trying out `1.5-rc2`

> When releasing about 25 pods into the cluster with Helm, a sporadic amount of them get assigned identities. Errors appear in the NMI log.

1. How many pods out of the 25 are getting an azure assigned identity? 
2. Are all 25 pods using the same identity and binding?
3. You can deploy MIC with `-v=6` and that will give more verbose logs as to what is happening. 4. Do all the pods have the labels defined in AzureIdentityBinding?
5. The log you posted above from NMI, is that pod supposed to be using a user assigned identity? What is the `type` defined in the AzureIdentity?

> I should also note that it only seems as though one of the MIC pods happens to be doing work and producing logs, the others are all showing this as their last produced log message, and appear to sit idle:

The MIC pods use leader election which means at any given time only 1 pod will obtain the lease and do all the work. If the leader dies, then the other MIC pod will become the leader and take over.

**Comment by android2221** [comment]
Thanks for the information - after popping the NMI pods it seemed to start issuing identities correctly throughout the day. We've used the previous version for a few months now, so we're excited to see this new version out. I'm going to close this issue since it seems to have been a hiccup.
