### ISSUE TITLE
Question: How to support multiple scale sets

### ISSUE THREAD

**Issue by dharmab** [Azure/aad-pod-identity#331]
We run multiple scale sets in our clusters for a variety of reasons (alternate VM types, alternate container runtimes, and for easy rollback of OS upgrades). The pod identity controller only binds identities to the scale set that the controller pod is running on. Can multiple scale sets be supported?

**Comment by kkmsft** [comment]
@dharmab - Thank you for using pod identity. What version are you using ?
Is this AKS-engine cluster or AKS ?

**Comment by dharmab** [comment]
We are running 1.3.0 for the MIC and 1.4.9 for NMI.

We are not using AKS or AKS-engine. We are running our own standalone VMs running Kubernetes 1.15.

**Comment by aramase** [comment]
@dharmab Thank you for the information. I was unable to recreate this on my cluster with 3 node pools. MIC was running in nodepool-2 and my application pod running in nodepool-0. The assigned identity was created and I see the identity has been successfully assigned to the underlying node. 

If the identity is in a different resource group and the SP doesn't have `Managed Identity Operator` access to the identity, then the assignment will fail. The MIC logs should give you more information as to why the identity was not assigned.

**Comment by dharmab** [comment]
Thanks for trying this out, @aramase. We'll give it a shot in our clusters and reopen this issue if we find problems. Thank you!
