### ISSUE TITLE
'size of request headers too long error' from nmi

### ISSUE THREAD

**Issue by smira** [Azure/aad-pod-identity#332]
**Describe the bug**

Seems to happen randomly when pods get launched - it fails to acquire MSI identity.

`mic` logs look clean - identity is assigned, but `nmi` log shows:

```
time="2019-08-08T16:15:16Z" level=info msg="matched identityType:0 clientid:62e24516-4c4a-4540-950e-c4e07d6218a8 resource:https://management.core.windows.net/" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.15.192.25
time="2019-08-08T16:15:16Z" level=error msg="failed to get service principal token for pod:woke/dev-westus-cron-woke-run-1565280900-7zjft, adal: Refresh request failed. Status Code = '400'. Response body: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\"\"http://www.w3.org/TR/html4/strict.dtd\">\r\n<HTML><HEAD><TITLE>Bad Request</TITLE>\r\n<META HTTP-EQUIV=\"Content-Type\" Content=\"text/html; charset=us-ascii\"></HEAD>\r\n<BODY><h2>Bad Request - Request Too Long</h2>\r\n<hr><p>HTTP Error 400. The size of the request headers is too long.</p>\r\n</BODY></HTML>\r\n" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.15.192.25
time="2019-08-08T16:15:16Z" level=info msg="Status (403) took 67315333 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.15.192.25
```

Seems similar to #323 

**Steps To Reproduce**

Not a high load, single pod is launched every 10-15 minutes. Pod sleeps 10 seconds on startup, but still this error.

**Expected behavior**

Identities is assigned as expected.

**AAD Pod Identity version**

1.5

**Kubernetes version**

1.13.5

**Additional context**

**Comment by aramase** [comment]
@smira Thank you for trying out aad-pod-identity. I have a few questions for you as I'm unable to recreate this - 
1. Which client library is the pod `dev-westus-cron-woke-run-1565280900-7zjft` using for requesting token? Which version of the client library is it using?
2. Did this work fine with the old release `mic:1.3 and nmi:1.4`? 
3. Does restarting the nmi help resolve the issue? It did in case of #323. So curious if this is consistent.

> Seems to happen randomly when pods get launched - it fails to acquire MSI identity.
Does this mean it works at times when the pod is launched and fails sometimes? Or is it consistently failing?

**Comment by smira** [comment]
> Which client library is the pod dev-westus-cron-woke-run-1565280900-7zjft using for requesting token? Which version of the client library is it using?

This runs Ansbile 2.8 which is using set of Azure SDKs, from `pip freeze`:

```
azure-cli-core==2.0.35
azure-cli-nspkg==3.0.2
azure-common==1.1.11
azure-graphrbac==0.40.0
azure-keyvault==1.0.0a1
azure-mgmt-authorization==0.51.1
azure-mgmt-batch==5.0.1
azure-mgmt-cdn==3.0.0
azure-mgmt-compute==4.4.0
azure-mgmt-containerinstance==1.4.0
azure-mgmt-containerregistry==2.0.0
azure-mgmt-containerservice==4.4.0
azure-mgmt-cosmosdb==0.5.2
azure-mgmt-devtestlabs==3.0.0
azure-mgmt-dns==2.1.0
azure-mgmt-hdinsight==0.1.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-loganalytics==0.2.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-monitor==0.5.2
azure-mgmt-msi==0.2.0
azure-mgmt-network==2.3.0
azure-mgmt-nspkg==2.0.0
azure-mgmt-rdbms==1.4.1
azure-mgmt-redis==5.0.0
azure-mgmt-resource==2.1.0
azure-mgmt-servicebus==0.5.3
azure-mgmt-sql==0.10.0
azure-mgmt-storage==3.1.0
azure-mgmt-trafficmanager==0.50.0
azure-mgmt-web==0.41.0
azure-nspkg==2.0.0
azure-storage==0.35.1
```

> Did this work fine with the old release mic:1.3 and nmi:1.4

I saw the same behavior with older release, but never tried to dig that deep into the logs, so looked same on pod side, but not sure about the actual error.

> Does restarting the nmi help resolve the issue? It did in case of #323. So curious if this is consistent.

yes, I believe so.

> Does this mean it works at times when the pod is launched and fails sometimes? Or is it consistently failing across all iterations of pod deployment?

don't have a lot of test data, but seems that if it starts failing, it fails many times in a row until the mic/nmi pods are restarted.

@aramase I hope the error message itself gives some clue - as this clearly a problem there.

**Comment by smira** [comment]
So I was usually hitting this error once in a while. Cluster sits idle (no new pods launched for a few days/a week), but then I launch new pod and hit this error. No matter how many times I try it, it fails until I kill the nmi/mic pods. This was the thing with 1.3/1.4. I don't have enough data for 1.5, but the failure above is clearly for 1.5.

**Comment by smira** [comment]
Another cluster, same failure, K8s 1.13.7 (just upgraded from 1.13.5 2 hours ago), as part of the upgrade obviously nmi/mic pods got restarted.

```
time="2019-08-08T20:29:45Z" level=info msg="matched identityType:0 clientid:cb3f0ed4-dd58-4e65-bb30-7ed040628899 resource:https://management.core.windows.net/" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.15.192.37
time="2019-08-08T20:29:45Z" level=error msg="failed to get service principal token for pod:woke/cicd-westus-v1.0.1-12-g33c96f3-run-top-tvg8v, adal: Refresh request failed. Status Code = '400'. Response body: <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\"\"http://www.w3.org/TR/html4/strict.dtd\">\r\n<HTML><HEAD><TITLE>Bad Request</TITLE>\r\n<META HTTP-EQUIV=\"Content-Type\" Content=\"text/html; charset=us-ascii\"></HEAD>\r\n<BODY><h2>Bad Request - Request Too Long</h2>\r\n<hr><p>HTTP Error 400. The size of the request headers is too long.</p>\r\n</BODY></HTML>\r\n" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.15.192.37
time="2019-08-08T20:29:45Z" level=info msg="Status (403) took 47524865 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.15.192.37
```

**Comment by smira** [comment]
my analysis points to this line https://github.com/Azure/aad-pod-identity/blob/master/pkg/auth/auth.go#L57

which goes into adal libs

**Comment by smira** [comment]
my further guess is the problem is this piece of code:

```
https://github.com/Azure/aad-pod-identity/blob/master/pkg/auth/auth.go#L51-L54
```

this does `+= "something"` to global `ua` (user-agent) library each time MSI auth happens, which is soon going to blow up size of the header value.

wrapping this into Go `sync.Once` should help to fix the issue

**Comment by smira** [comment]
I submitted a PR with the fix, deployed fixed version to our test cluster.

**Comment by aramase** [comment]
@smira Thank you for looking at it and the PR. I was wondering the same thing. I'll take a look at the PR. Is the NMI with the fixed version working fine?

**Comment by smira** [comment]
well, too soon to tell, I think it took time (enough requests) for the header value to overflow, but so far it looks good
