### ISSUE TITLE
Missing application/json Content-Type on MSI token responses

### ISSUE THREAD

**Issue by EzequielB** [Azure/aad-pod-identity#340]
**Describe the bug**
Pods retrieve the token successfully but the content type is text/plain

**Steps To Reproduce**
In a test cloud retrieve a token and see the Content-Type header.

**Expected behavior**
The content type header should be application/json

**AAD Pod Identity version**
1.5.1

**Kubernetes version**
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.8", GitCommit:"a89f8c11a5f4f132503edbc4918c98518fd504e3", GitTreeState:"clean", BuildDate:"2019-04-23T04:41:47Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**

**Comment by kkmsft** [comment]
@EzequielB - Thank you using aad-pod-identity, raising the issue and the PR. Can you please specify the use case in this scenario ? Basically curious about how the token is getting consumed by application. Are you using adal libraries in the applications. Is it causing an issue with that ?

**Comment by EzequielB** [comment]
Hi. Glad to help. 
The issue happens using the rest API, not the adal libraries. For what I've checked it doesn't happen on that case (adal).

**Comment by kkmsft** [comment]
Closing with the merge of #341

**Comment by rblock-aw** [comment]
Hi,

I know this issue is closed, but it seems that I am getting an issue similar to this. Briefly, I did the following:
1. Follow the detailed tutorial (which starts with cloning this repo, for reference, the last commit I have cloned locally is 2ab4adc5746085cb12ed30c41a119019d5be2674)
2. Verified that the end result matches the expected result from the tutorial
3. Adapt the managed identity created in the tutorial to grant access to one of our storage accounts
4. Adapt the demo deployment to run a container based on python:3.7.4 and apply the new deployment
5. kb exec -it deploy/demo /bin/bash
6. Install major dependencies (azure, azure-identity, azure-storage-blob, the last one with the --pre flag)
7. Follow [this example](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/identity/azure-identity#authenticating-with-defaultazurecredential) to try and use the managed identity to access our storage account
8. Execute `client.get_account_information()` and see that the ManagedIdentityCredential embedded in the DefaultAzureCredential fails to parse the token because of the content-type being set to text/plain

Can I work around this somehow? Should I be using the ADAL libraries to do all of this? If so, can you give me a pointer on how cover a simple use case like this (i.e. 'give me a client for an Azure service using the correct AAD pod identity).

**Comment by aramase** [comment]
@rblock-aw The fix for this particular issue has been merged, but we are yet to a cut an official release with all the changes. We are hoping to cut release `1.5.3` next week with some improvements, bug fixes including this one.

**Comment by rblock-aw** [comment]
Well that was a fast answer. Looking forward to the release!

**Comment by rblock-aw** [comment]
Hi again, took me a while but I finally got around to testing it. I'm still experiencing the same error with version `1.5.3`. Any suggestions?

**Comment by kkmsft** [comment]
@rblock-aw - we did one more fix after 1.5.3 - https://github.com/Azure/aad-pod-identity/pull/424
This fix is included in the 1.5.4-rc1 image. Can you please try that let us know your feedback.

**Comment by rblock-aw** [comment]
Sure. Is it possible to install this through helm? Or do I need to download and modify the manifest so that all references to 1.5.3 are replaced to 1.5.4-rc1?

**Comment by aramase** [comment]
@rblock-aw You should just be able to change the version in `values.yml` for helm chart and use that with `1.5.4-rc1`.

https://github.com/Azure/aad-pod-identity/blob/master/charts/aad-pod-identity/values.yaml#L27
https://github.com/Azure/aad-pod-identity/blob/master/charts/aad-pod-identity/values.yaml#L81

**Comment by rblock-aw** [comment]
Thanks for the pointer. From what I gather of how `values.yaml` files work in combination with helm charts, I opted for updating my install command to
```
helm install aad-pod-identity/aad-pod-identity \                                                                                                                                       
            --tiller-namespace aw-system \
            --namespace aad-pod-identity \
            --set mic.leaderElection.namespace=aad-pod-identity \
            --set mic.tag=1.5.4-rc1 \
            --set nmi.micNamespac=aad-pod-identity \
            --set nmi.tag=1.5.4-rc1 \
            --set rbac.allowAccessToSecrets=false \
            --name pod-identity
```
This results in following output:
```
NAME:   pod-identity
LAST DEPLOYED: Wed Nov  6 23:28:19 2019
NAMESPACE: aad-pod-identity
STATUS: DEPLOYED

RESOURCES:
==> v1/ClusterRole
NAME                  AGE
aad-pod-identity-mic  0s
aad-pod-identity-nmi  0s

==> v1beta1/ClusterRoleBinding
NAME                  AGE
aad-pod-identity-mic  0s
aad-pod-identity-nmi  0s

==> MISSING
KIND                                        NAME
/v1, Resource=serviceaccounts               aad-pod-identity-nmi
/v1, Resource=serviceaccounts               aad-pod-identity-mic
extensions/v1beta1, Resource=daemonsets     aad-pod-identity-nmi
extensions/v1beta1, Resource=deployments    aad-pod-identity-mic
```
Especially the missing things are what bother me. What does that mean and does it have any impact on my deployment?

Previous question aside, it does seem that it was successfully deployed. I can see from the output from `kubectl describe deploy --namespace aad-pod-identity aad-pod-identity-mic` and `kubectl describe daemonsets --namespace aad-pod-identity aad-pod-identity-nmi` that container images refer to tag with 1.5.4-rc1). Redoing my example from above results in a 'StorageErrorException: The specified resource does not exist.`, but that is probably my mistake. Looking into that.

Thanks for the help!

---
Small side note: during the error handling, I get the Python message `During handling of the above exception, another exception occurred:`, which feels like something is going wrong inside the exception handling. If this is unintentional, raising an exception in the `except` block, it might be useful to raise it using `raise error from None` when raising an error in an except block or so. Or, if just updating the error and re-raising it with additional info, just `raise` without any expression will do the trick. (References: https://docs.python.org/3/reference/simple_stmts.html#the-raise-statement and https://stackoverflow.com/questions/52725278/during-handling-of-the-above-exception-another-exception-occurred)

**Comment by rblock-aw** [comment]
In the mean time I've got it working. Thank you so much for your help!
