### ISSUE TITLE
Reduce number of steps for creating the AzureIdentity

### ISSUE THREAD

**Issue by kkmsft** [Azure/aad-pod-identity#350]
**Describe the request**
Either via 'az cli' or kubectl plugins make the CRD creation and identity creation as single step.

**Explain why AAD Pod Identity needs it**
Simplify the AzureIdentity, role assignment and creating of CRD, potentially make it a single step process. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chewong** [comment]
See https://docs.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity
