### ISSUE TITLE
Namespace param is not used by method GetUserAssignedMS in crd.go

### ISSUE THREAD

**Issue by ivanthelad** [Azure/aad-pod-identity#36]
Namespace parameter is ignored when looking up CRD type "azureassignedidentities" in the method GetUserAssignedMS. only referenced when a error occurs. 
this results in the aad-pod-identity being only useable in the default namespace 
[1]
https://github.com/Azure/aad-pod-identity/blob/master/pkg/crd/crd.go#L190

**Comment by rite2nikhil** [comment]
This s fixed now, thanks for reporting.
