### ISSUE TITLE
Is NMI supposed to respond with application/json?

### ISSUE THREAD

**Issue by migolfi** [Azure/aad-pod-identity#368]
**Describe the bug**

The library for hadoop-azure requests a token in AKS using the metadata endpoint and it fails with error code 200. The response content-type is text/plain but the library is expecting application/json.

```bash
curl -v http://169.254.169.254/metadata/identity/oauth2/token?resource=https://storage.azure.com
*   Trying 169.254.169.254...
* TCP_NODELAY set
> GET /metadata/identity/oauth2/token?resource=https://storage.azure.com HTTP/1.1
> Host: 169.254.169.254
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Fri, 30 Aug 2019 18:48:59 GMT
< Content-Length: 1540
< Content-Type: text/plain; charset=utf-8
< 
{"access_token":"","refresh_token":"","expires_in":"28800","expires_on":"1567213099","not_before":"1567183999","resource":"https://storage.azure.com","token_type":"Bearer"}
```

**Steps To Reproduce**

curl the metadata endpoint or use a library that expects json type response.

**Expected behavior**

The token should return successfully with application/json content-type.

**AAD Pod Identity version**
1.5.2

**Kubernetes version**
v1.14.6

**Additional context**

**Comment by migolfi** [comment]
Is the content type supposed to get set [here](https://github.com/Azure/aad-pod-identity/blob/master/pkg/nmi/server/server.go#L349-L355)?

**Comment by migolfi** [comment]
Sorry I just realized this is a duplicate of #340. Can we get #341 merged?

**Comment by kkmsft** [comment]
Duplicate #340
