### ISSUE TITLE
Cannot access KeyVault while using Managed identity

### ISSUE THREAD

**Issue by RemiGri** [Azure/aad-pod-identity#371]
**Describe the bug**
Setting up an AKS cluster with advanced networking turned on and following the tutorial on this git repo the C# API code does not seem to be able to access Azure KeyVault. I can see in the logs that identity gets bound to my pod but when trying to hit an endpoint in my C# API that is supposed to try to access KeyVault it throws an error saying it tried three different methods to access KeyVault, but none of them worked.

**Steps To Reproduce**
Create a new AKS cluster with advanced networking turned on and RBAC-enabled. Follow this git repo tutorial to install all managed identities.

**Expected behavior**
C# Api should retrieve values from KeyVault using Managed Identity. 

**AAD Pod Identity version**
Latest that is in the tutorial  

**Kubernetes version**
1.14.5

**Additional context**

**Comment by kkmsft** [comment]
@RemiGri:

Can you please confirm if you are using 1.5 series or 1.3-1.4 version ?

Can you please provide us the following (ref: https://github.com/Azure/aad-pod-identity/wiki/Debugging):
1. kubectl get AzureAssignedIdentities --all-namespaces -o yaml
2. MIC logs
3. NMI logs
4. Full application logs from the pod.
Note: Please ensure that sensitive info is kept REDACTED.

**Comment by robinmanuelthiel** [comment]
If you are using ASP.NET Core, you should make sure, you added that latest version of `Microsoft.Azure.Services.AppAuthentication` to your project.

```
<PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.3.1" />
```

Also, make sure to use a Managed Identitiy with a name < 24 characters!
If that doesn't help, please provide the code from your `Program.cs`.

**Comment by kkmsft** [comment]
@RemiGri -  can you please provide the information above.

**Comment by alexmg** [comment]
@robinmanuelthiel I came across this issue looking for something else and wondered what the reason for the recommendation of having a managed identity with a name less than 24 characters. I have managed identities working with aad-pod-identity that have longer names and have not had any problems. Just wanting to know if there is something in particular that I should be watching out for.

**Comment by robinmanuelthiel** [comment]
@alexmg, this was an older issue, that can be found here: https://github.com/Azure/aad-pod-identity/issues/69 Name limit has been exceeded to 128 chars now.

**Comment by alexmg** [comment]
Thanks for the info @robinmanuelthiel.

**Comment by knbnnate** [comment]
> If you are using ASP.NET Core, you should make sure, you added that latest version of `Microsoft.Azure.Services.AppAuthentication` to your project.
> 
> ```
> <PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.3.1" />
> ```
> 
> Also, make sure to use a Managed Identitiy with a name < 24 characters!
> If that doesn't help, please provide the code from your `Program.cs`.

Is there a corresponding client library change required for java use of com.microsoft.azure.credentials.MSICredentials? Updating from aad-pod-identity 0.1.0 to 1.5.2, everything looks good in the new pod-identity namespace (mic logs show bindings applying to pods) but the pods retry/sleep forever when attempting to acquire a token. I can open a new issue and provide the required debug information, but if this is a simple case of "I'm using too old a client" please let me know.

**Comment by kkmsft** [comment]
@RemiGri - are you still facing this issue ?

**Comment by CBaud** [comment]
@kkmsft - I'm facing this issue as well.

**Comment by RobLSDev** [comment]
@kkmsft - I have this problem as well, but it doesn't always fail.  It's currently in a failing state, so I'll try to get the logs for you.

**Comment by RobLSDev** [comment]
@kkmsft - Attached are the logs as promised.

From what I can tell the MIC is correctly assigning the MSI to the nodes, but for whatever reason when the pod makes a request it isn't being handled by the NMI.

[azureAssignedIdentities.txt](https://github.com/Azure/aad-pod-identity/files/3820677/azureAssignedIdentities.txt)
[azureIdenityBindings.txt](https://github.com/Azure/aad-pod-identity/files/3820678/azureIdenityBindings.txt)
[azureIdentities.txt](https://github.com/Azure/aad-pod-identity/files/3820679/azureIdentities.txt)
[pod_heimdallr-6575b9dc47-r5fg2_log.txt](https://github.com/Azure/aad-pod-identity/files/3820680/pod_heimdallr-6575b9dc47-r5fg2_log.txt)
[pod_mic-6fdb84dfbb-zdvkj_log.txt](https://github.com/Azure/aad-pod-identity/files/3820681/pod_mic-6fdb84dfbb-zdvkj_log.txt)
[pod_mic-6fdb84dfbb-zzn8c_log.txt](https://github.com/Azure/aad-pod-identity/files/3820682/pod_mic-6fdb84dfbb-zzn8c_log.txt)
[pod_nmi-g99xn_log.txt](https://github.com/Azure/aad-pod-identity/files/3820683/pod_nmi-g99xn_log.txt)
[pod_nmi-m9m8b_log.txt](https://github.com/Azure/aad-pod-identity/files/3820684/pod_nmi-m9m8b_log.txt)
[vmss_identities.txt](https://github.com/Azure/aad-pod-identity/files/3820685/vmss_identities.txt)

**Comment by aramase** [comment]
@RobLSDev Thank you for the logs. Have a few questions that can help us debug further -
1. How many nodes in your cluster?
2. What is the state of all your NMI pods? From the logs we see one NMI pod has been running since `11/06` while the other has been running only since `11/07`. Are there any restarts? 
3. Does the cluster have only linux nodes only or does it have windows nodes too?
4. What libraries and versions is the application using?

> @kkmsft - I have this problem as well, but it doesn't always fail. It's currently in a failing state, so I'll try to get the logs for you.

When it doesn't fail, do you see the request logs in NMI? Also, when it fails is there any manual remediation steps you take to make it eventually succeed?

In general, when a token request in made from the application, the request is rerouted to NMI based on the iptable rules NMI inserts. NMI will log every request that comes in.  But we don't see any requests in the log which can indicate the iptable rules might not exist/ the request being made is going through our default handler.

**Comment by RobLSDev** [comment]
@aramase I'm running a multi-node cluster, two Linux nodes and one Windows node right now.  The apps making the requests for tokens are running on the one Windows node.  Here's the current status of the pods in the default namespace:

kubectl get pods
NAME                   READY   STATUS    RESTARTS   AGE
mic-6fdb84dfbb-zdvkj   1/1     Running   0          30h
mic-6fdb84dfbb-zzn8c   1/1     Running   0          30h
nmi-g99xn              1/1     Running   2          30h
nmi-m9m8b              1/1     Running   0          30h

In the past when it has been working I would see the requests get logged in NMI.

**Comment by RobLSDev** [comment]
@aramase - If interested I am now logging more of the exception call\causation stack.  Framework.Azure.Platform is our library for putting a facade around the azure-specific stuff:

> [Level] Fatal [Time] 11/8/2019 3:52:31 AM [Host] heimdallr-5b5d7766f5-pjq6f,0 [User] mid-aks-lstest-heimdallr [Thread] 4 [Msg] Uncaught exception.
> System.Exception: Failed to look up secret 'NASKey' from key vault. ---> Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException: Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: . Exception Message: Tried the following 4 methods to get an access token, but none of them worked.
> Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: . Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. Received a non-retryable error. MSI ResponseCode: BadRequest, Response: {"error":"invalid_request","error_description":"Identity not found"}
> Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: . Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. Visual Studio Token provider file not found at "C:\Users\ContainerAdministrator\AppData\Local\.IdentityService\AzureServiceAuth\tokenprovider.json"
> Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: . Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. 'az' is not recognized as an internal or external command,
> operable program or batch file.
> 
> Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.microsoftonline.com/common. Exception Message: Tried to get token using Active Directory Integrated Authentication. Access token could not be acquired. Failed to get user name from the operating system.
> 
>    at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.<GetAuthResultAsyncImpl>d__14.MoveNext()
>    at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.<GetAuthenticationResultAsync>d__18.MoveNext()
>    at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.<GetAccessTokenAsync>d__16.MoveNext()
>    at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.<GetAccessTokenAsync>d__17.MoveNext()
>    at Framework.Azure.Platforms.AzureManagedIdentityTokenProvider.<GetAccessTokenAsync>d__1.MoveNext() in d:\a\1\s\Framework.Azure\Platforms\AzureManagedIdentityTokenProvider.cs:line 13
>    at Framework.Azure.Platforms.AzureKeyVaultKeyStorageProvider.<GetToken>d__19.MoveNext() in d:\a\1\s\Framework.Azure\Platforms\AzureKeyVaultKeyStorageProvider.cs:line 125
>    at Microsoft.Azure.KeyVault.KeyVaultCredential.<PostAuthenticate>d__11.MoveNext()
>    at Microsoft.Azure.KeyVault.KeyVaultCredential.<ProcessHttpRequestAsync>d__13.MoveNext()
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
>    at Microsoft.Azure.KeyVault.KeyVaultClient.<GetSecretWithHttpMessagesAsync>d__66.MoveNext()
>    at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.<GetSecretAsync>d__13.MoveNext()
>    at Framework.Azure.Platforms.AzureKeyVaultKeyStorageProvider.<GetSecretAsync>d__15.MoveNext() in d:\a\1\s\Framework.Azure\Platforms\AzureKeyVaultKeyStorageProvider.cs:line 40
>    --- End of inner exception stack trace ---
>    at Framework.Azure.Platforms.AzureKeyVaultKeyStorageProvider.<GetSecretAsync>d__15.MoveNext() in d:\a\1\s\Framework.Azure\Platforms\AzureKeyVaultKeyStorageProvider.cs:line 47
>    at Heimdallr.App.Program.<LoadSettingsAsync>d__1.MoveNext() in d:\a\1\s\Heimdallr.App\Program.

**Comment by aramase** [comment]
@RobLSDev --

So, `aad-pod-identity` is only supported on linux. Support for windows is ongoing. This means the `NMI` pods only run on the linux nodes. So since your application is running on a windows node, the request for token is not actually going to NMI, but instead going directly to metadata endpoint. NMI adds iptables rules to redirect requests to itself only on linux nodes.

**Comment by RobLSDev** [comment]
At this moment each of the identities will effectively have the same access to resources, so I think for a workaround I'll comment the labels out on all but one of the deployment configs.  This will ensure that a single managed identity is mapped to the node.  That appears to be the situation where things are working fine.

**Comment by rahul24** [comment]
> @RobLSDev --
> 
> So, `aad-pod-identity` is only supported on linux. Support for windows is ongoing. This means the `NMI` pods only run on the linux nodes. So since your application is running on a windows node, the request for token is not actually going to NMI, but instead going directly to metadata endpoint. NMI adds iptables rules to redirect requests to itself only on linux nodes.

Any plans to support windows node soon?

**Comment by kkmsft** [comment]
Closing this. Please reopen if this issue still exists. For windows support please monitor issue #242 .
