### ISSUE TITLE
Guidance / Best Practices how to apply aad-pod-identity in real life

### ISSUE THREAD

**Issue by ChrisRichner** [Azure/aad-pod-identity#374]
The most Content I've found so far described how to set up aad-pod-identity from a technical standpoint. On Docs is also mentioned that it's considered best practice to have aad-pod-identity in place but not exactly how.

I'm looking for more material elaborating what's considered best practice in regard if one Azure Managed Identity for all Pods is ok or each logical Service must have it's own Azure Managed Identity?

Thanks

**Comment by kwaazaar** [comment]
I wondered how to make sure another developer that deploys his solution on the cluster doesn't (accidentally) select the wrong identity, possibly with too much access to the resources.
This is probably only an issue when deploying solutions into the same namespace, but some guidance could be good here.
