### ISSUE TITLE
Use encoding/json.Unmarshal instead of yaml.Unmarshal for cloudconfig initialization

### ISSUE THREAD

**Issue by shanalily** [Azure/aad-pod-identity#375]
**Describe the request**

I suggest using encoding/json.Unmarshal instead of yaml.Unmarshal (from gopkg.in/yaml.v2) for setting the fields in the cloudconfig structure in [aad-pod-identity/pkg/cloudprovider/cloudprovider.go](https://github.com/Azure/aad-pod-identity/blob/270371d43552823c2bc8e074eb4c181d6ae913a3/pkg/cloudprovider/cloudprovider.go#L50) because the json library is more forgiving of differences in case.

**Explain why AAD Pod Identity needs it**

I ran into an issue with subscriptionID vs subscriptionId in an azure.json cloud config file in another codebase. This seems like a common inconsistency considering even the AzureConfig struct [in this codebase](https://github.com/Azure/aad-pod-identity/blob/master/pkg/config/azureconfig.go) has inconsistent capitalization (userAssignedIdentityID vs SubscriptionId).

**Describe the solution you'd like**

The Go JSON library will parse both "subscriptionId" and "subscriptionID" correctly where as the YAML library will set the subscription ID field to an empty string.

Considering that the cloud config is supposed to come from "azure.json", I don't think it's an issue to use the JSON library instead of the YAML library.

**Describe alternatives you've considered**

I understand that [kubernetes also uses yaml.Unmarshal](https://github.com/kubernetes/kubernetes/blob/7d4d17583bef4c9c0226e5d2803eec395567c5cb/staging/src/k8s.io/legacy-cloud-providers/azure/azure_config.go#L87) for initializing their azure cloud config structure and that it might be better to stick with the YAML library because of that.

**Additional context**

**Comment by kkmsft** [comment]
Thank you, @shanalily for the issue. Here is the PR which converted the issue from json.Unmarshal to yaml.Unmarshal: https://github.com/Azure/aad-pod-identity/commit/a3d264327e1d79a4313455c4c272c0049df83732
The core reason is that there were issues in parsing azure.json, which we cannot do without.

**Comment by shanalily** [comment]
Thanks for your response @kkmsft and for linking to the PR. My team is also fixing things in our codebase to work with the yaml.Unmarshal though it's unfortunate there's these small differences between the libraries.
