### ISSUE TITLE
Validation error: unable to recognize "": no matches for kind "AzureIdentity" in version "aadpodidentity.k8s.io/v1"

### ISSUE THREAD

**Issue by Yagil1990** [Azure/aad-pod-identity#381]
**Describe the bug**
We install aad-pod-identity on AKS cluster using following commands (from Helm Readme doc):

helm repo add aad-pod-identity https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts

helm install aad-pod-identity/aad-pod-identity --name "chartName" -f "pathToDynamicValues\dynamic-values.yaml" -f "pathToChartValues\values.yaml"

We removed the managed identity properties (resource Id & client Id) from the Values.yaml, so that it will take from our dynamic-values.yaml file.

We're receiving the following error:
Error: validation failed: [unable to recognize "": no matches for kind "AzureIdentity" in version "aadpodidentity.k8s.io/v1", unable to recognize "": no matches for kind "AzureIdentityBinding" in version "aadpodidentity.k8s.io/v1"]

**Steps To Reproduce**
Execute it on an AKS cluster, using Helm client version 2.14.0 (tried 2.14.3 too)

**Expected behavior**
Aad-pod-identity to be installed on my AKS cluster.
**AAD Pod Identity version**
1.5.2
**Kubernetes version**
Client Version: 1.14.6
ServerVersion: 1.13.10
**Additional context**

**Comment by cwebbtw** [comment]
We are also able to reproduce this.

**Comment by aramase** [comment]
That's because the CR is created before the CRD is installed on the cluster by helm. I've PR to resolve the issue by adding `crd-install` helm hook to ensure the CRD is installed before the rest of the components.
