### ISSUE TITLE
MIC is crashing with a fatal error: concurrent map read and map write when deploying multiple identities to multiple namespaces.

### ISSUE THREAD

**Issue by sheigel** [Azure/aad-pod-identity#390]
**Describe the bug**

MIC is crashing with a fatal error: concurrent map read and map write when deploying multiple identities to multiple namespaces.

Deploying one namespace with 2 identities seems to be fine.
Deploying 2 or more namespaces with 2 identities/namespace starts failing.

fatal error: concurrent map read and map write

goroutine 91450 [running]:
runtime.throw(0x142b3b0, 0x21)
        /usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc00116a2d0 sp=0xc00116a2a0 pc=0x42a9a2
runtime.mapaccess1_faststr(0x1247e00, 0xc000760450, 0x141c6f8, 0x14, 0x10)
        /usr/local/go/src/runtime/map_faststr.go:21 +0x418 fp=0xc00116a340 sp=0xc00116a2d0 pc=0x4119b8
github.com/Azure/aad-pod-identity/pkg/stats.Update(...)
        /go/src/github.com/Azure/aad-pod-identity/pkg/stats/stats.go:56
github.com/Azure/aad-pod-identity/pkg/crd.(*Client).CreateAssignedIdentity(0xc0004a60a0, 0xc00083a700, 0xc01cb6bb01, 0xc000822020)
        /go/src/github.com/Azure/aad-pod-identity/pkg/crd/crd.go:244 +0x38d fp=0xc00116a488 sp=0xc00116a340 pc=0xd0c79d
github.com/Azure/aad-pod-identity/pkg/mic.(*Client).createAssignedIdentity(0xc000133830, 0xc00083a700, 0x3a, 0xc00073abe8)
        /go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:577 +0x3d fp=0xc00116a4b8 sp=0xc00116a488 pc=0x110724d
github.com/Azure/aad-pod-identity/pkg/mic.(*Client).updateUserMSI(0xc000133830, 0xc000a6e000, 0x3c, 0x45, 0xc001194580, 0x15, 0xc0009b0460, 0x2, 0x2, 0x0, ...)
        /go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:719 +0x2c11 fp=0xc00116bf40 sp=0xc00116a4b8 pc=0x110aa81
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00116bf48 sp=0xc00116bf40 pc=0x4573e1
created by github.com/Azure/aad-pod-identity/pkg/mic.(*Client).updateNodeAndDeps
        /go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:701 +0x1c5

**Steps To Reproduce**

Deploy Identity chart with following settings:

forceNamespaced = true
rbac.enabled = true
rbac.allowAccessToSecrets = false
azureIdentity.enabled=false
azureIdentity.type=0

MIC and NMI pod are running in default namespace

Deploy app chart contains identity + binding

Samples

apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: identity-1
  namespace: ns-1
spec:
  ClientID: <Client ID>
  ResourceID: <ResourceID>
  type: 0

apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: identity-2
  namespace: ns-1
spec:
  ClientID: <Client ID>
  ResourceID: <ResourceID>
  type: 0

apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: binding-1
  namespace: ns-1
spec:
  AzureIdentity: identity-1
  Selector: ns-1-identity-1

apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: binding-2
  namespace: ns-1
spec:
  AzureIdentity: identity-2
  Selector: ns-1-identity-2
  
**AAD Pod Identity version**

Chart aad-pod-identity-1.5.2

**Kubernetes version**

AKS v1.13.7

**Comment by kkmsft** [comment]
Thank you for raising the issue @sheigel . The stats issue has been fixed in PR #344 .  This will go out with 1.5.3. Currently we have posted 1.5.3-rc4 which has the stats fix as well other fixes.

**Comment by ombre9** [comment]
Yes we enabled this forceNamespaced = true flag which is supposed to run MIC and NMI with the environment variable: FORCENAMESPACED=true.

**Comment by aramase** [comment]
The concurrent read and write map issue has been fixed in release 1.5.4. Closing this issue. Please reopen if you have any further issues.
