### ISSUE TITLE
Remove assigned identity from create list if creation fails

### ISSUE THREAD

**Issue by aramase** [Azure/aad-pod-identity#410]
**Describe the bug**
If CREATE assigned identity fails, then the assigned identity should be removed from the create list to ensure we don't update the status on non-existent assigned identity resource. 

**Steps To Reproduce**

**Expected behavior**

**AAD Pod Identity version**

**Kubernetes version**

**Additional context**

**Comment by gkannan66235** [comment]
If the attached Pod identity removed manually/ by removing the resource group and while deploying new ingress the k8s cluster azureidentitybinding fails to attach New identity.
_**Error:
  Warning  binding apply error  33m (x305 over 8h)  aadpodidentity.k8s.io  Applying binding hive-qa-appgw-ingctrl-azidbinding-ingress-azure node aks-agentpool-23632721-vmss000001 for pod hive-qa-appgw-ingctrl-ingress-azure-bf6bf6b8d-kqrw9-qa-hive-qa-appgw-ingctrl-azid-ingress-azure resulted in error compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client '9d590046-e0b7-4a12-b4a2-472a58ffd0df' with object id '<objectid>' has permission to perform action 'Microsoft.Compute/virtualMachineScaleSets/write' on scope '/subscriptions/<subid>/resourceGroups/mc_euw-dev-018-tnt-hiveinfra_euw-dev-018-tnt-hiveaks_westeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aks-agentpool-23632721-vmss'; however, it does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action' on the linked scope(s) '/subscriptions/<subid>/resourceGroups/hive-ppe-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/appgwhiveContrIdentityppe778e63,/subscriptions/<subid>/resourceGroups/hive-qa-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/appgwhiveContrIdentityqa138777' or the linked scope(s) are invalid."**_

**Comment by chewong** [comment]
Close via https://github.com/Azure/aad-pod-identity/pull/601
