### ISSUE TITLE
Help needed configuring aad-pod-identity

### ISSUE THREAD

**Issue by deyanp** [Azure/aad-pod-identity#414]
Hi,

Are steps 6 and 4 required?

I perfomed the steps 1,2,3,5, however the access to key vault seems to not work yet ..

`PS C:\Users\Deyan\git\Playground\code\WorkerService> kubectl get AzureIdentity --all-namespaces                                           
NAMESPACE   NAME                   AGE                                                                                                    
default     aks-managed-identity   13h                                                                                                    

PS C:\Users\Deyan\git\Playground\code\WorkerService> kubectl get AzureIdentityBinding --all-namespaces                                    
NAMESPACE   NAME                           AGE                                                                                            
default     demo1-azure-identity-binding   3h                                                                                             

PS C:\Users\Deyan\git\Playground\code\WorkerService> kubectl get AzureAssignedIdentities --all-namespaces                                 
NAMESPACE   NAME                                                              AGE                                                         
default     worker-service104-56c7bd77df-bnljd-default-aks-managed-identity   4m`

I am not sure how to run 
az vm identity show -n <vm name> -g <resource group>

I took the node name as the vm name, and then took an automatically created resource group MC_... as the node name could not be found in my resource grop, in which I put the AKS cluster ... There is no error, but it seems the output is empty to the command ...

I granted access right to the principal to keyvault -> get secrets ... 

As I am new to AKS, I dont know how to execute last 2 steps in the https://github.com/Azure/aad-pod-identity/wiki/Debugging wiki - Component Logs and increase verbosity level.

Code of the service running in the pod is (F#):

`   

                let provider = AzureServiceTokenProvider()
                let keyVaultTokenCallback = (fun auth res scope -> provider.KeyVaultTokenCallback.Invoke(auth,res,scope))
                let kv = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(keyVaultTokenCallback))
                
                let! secret2 = kv.GetSecretAsync("https://xxx-xxxx-xxxx-xxxxxvault.azure.net", "MongoDBConnectionString") |> Async.AwaitTask //.ConfigureAwait(false)  
                logger.LogInformation("Data2 is: {data}", secret2)
 `

Result is the code is hanging and not continuing with error or Data2 is. ... log. My assumption is it cannot access key vault ... 

Any help appreciated!

**Comment by deyanp** [comment]
Looked at the logs of the aad pods (but without redeploying them with another log level), and found the following:

E1009 05:37:58.806898       1 mic.go:739] Updating msis on node aks-agentpool-15204281-0, add [1], del [0] failed with error compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client '999b0fbf-c369-4c18-adcf-4dc784b4d999' with object id '999b0fbf-c369-4c18-adcf-4dc784b4d999' has permission to perform action 'Microsoft.Compute/virtualMachines/write' on scope '/subscriptions/888508d1-1ea8-424f-85bf-aa2a4191f888/resourceGroups/MC_xxx-test3-rg-aks_xxx-test3-aks_westeurope/providers/Microsoft.Compute/virtualMachines/aks-agentpool-15204281-0'; however, it does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action' on the linked scope(s) '/subscriptions/888508d1-1ea8-424f-85bf-aa2a4191f888/resourcegroups/xxx-test3-rg-aks/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-managed-identity' or the linked scope(s) are invalid."

(I have redacted the guids)

**Comment by aramase** [comment]
@deyanp Did you follow the instructions here to provide the necessary roles and permissions - https://github.com/Azure/aad-pod-identity#6-set-permissions-for-mic. 

From the error, it looks like the cluster SP doesn't have the required permission for MSI `/subscriptions/888508d1-1ea8-424f-85bf-aa2a4191f888/resourcegroups/xxx-test3-rg-aks/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-managed-identity`. The MSI is created in the rg `xxx-test3-rg-aks` which is different from cluster rg `MC_xxx-test3-rg-aks_xxx-test3-aks_westeurope`. Once you provide the cluster SP `Managed Identity Operator` role for the specific MSI there should be no errors.

**Comment by deyanp** [comment]
Thanks, I was misled by the statement in step 6 "This step is only required for user-assigned MSI" that it is not needed.
I applied it now but the pod still cannot connect to Azure Key Vault. 

The logs of the mic show now:
I1009 06:39:43.311723       1 event.go:218] Event(v1.ObjectReference{Kind:"AzureIdentityBinding", Namespace:"default", Name:"demo1-azure-identity-binding", UID:"999dee57-e9ec-11e9-8616-0a2b2ee13999", APIVersion:"aadpodidentity.k8s.io/v1", ResourceVersion:"508773", FieldPath:""}): type: 'Normal' reason: 'binding applied' Binding demo1-azure-identity-binding applied on node aks-agentpool-15204281-0 for pod worker-service104-56c7bd77df-tqmch-default-aks-managed-identity

But if I issue the command

az vm identity show -n aks-agentpool-99904281-0 -g MC_XXX-TEST3-RG-AKS_XXX-TEST3-AKS_WESTEUROPE

I still get nothing ...

**Comment by deyanp** [comment]
Sorry, just retried the command and I get now a result!

But as the app is still not working, I checked the nmi logs and I see there the following:

time="2019-10-09T06:38:52Z" level=info msg="Rules for table(nat) chain(aad-metadata) rules(-N aad-metadata, -A aad-metadata ! -s 127.0.0.1/32 -d 169.254.169.254/32 -p tcp -m tcp --dport 80 -j DNAT --to-destination 10.240.0.4:2579, -A aad-metadata -j RETURN)"                      time="2019-10-09T06:39:38Z" level=error msg="no AzureAssignedIdentity found for pod:default/worker-service104-56c7bd77df-tqmch in assigned state, context canceled" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.244.0.41                                      time="2019-10-09T06:39:38Z" level=info msg="Status (404) took 2001056685 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.244.0.41

**Comment by deyanp** [comment]
The timing MIC/NMI looks strange though, it seems that the pod tries to contact Azure Key Vault **before** the identity is assigned?

**NMI:** 
time="2019-10-09T07:55:25Z" level=error msg="no AzureAssignedIdentity found for pod:default/worker-service104-56c7bd77df-2ztbb in assigned state, context canceled" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.244.0.42
time="2019-10-09T07:55:25Z" level=info msg="Status (404) took 2000837908 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.244.0.42
time="2019-10-09T07:55:52Z" level=info msg="node(aks-agentpool-15204281-0) hostip(10.240.0.4) metadataaddress(169.254.169.254:80) nmiport(2579)"

**MIC:**
I1009 07:55:32.495251       1 event.go:218] Event(v1.ObjectReference{Kind:"AzureIdentityBinding", Namespace:"default", Name:"demo1-azure-identity-binding", UID:"1c4dee57-e9ec-11e9-8616-0a2b2ee139dd", APIVersion:"aadpodidentity.k8s.io/v1", ResourceVersion:"508773", FieldPath:""}): type: 'Normal' reason: 'binding removed' Binding demo1-azure-identity-binding removed from node aks-agentpool-15204281-0 for pod worker-service104-56c7bd77df-tqmch
I1009 07:55:32.517557       1 crd.go:231] Got assigned id worker-service104-56c7bd77df-2ztbb-default-aks-managed-identity to assign
I1009 07:55:32.517961       1 crd.go:235] Creating assigned Id: worker-service104-56c7bd77df-2ztbb-default-aks-managed-identity
I1009 07:55:32.568432       1 cloudprovider.go:199] Updating user assigned MSIs on aks-agentpool-15204281-0
I1009 07:55:43.441918       1 crd.go:326] Updating assigned identity default/worker-service104-56c7bd77df-2ztbb-default-aks-managed-identity status to Assigned
I1009 07:55:43.459565       1 mic.go:317] Found 1 pods, 1 ids, 1 bindings
I1009 07:55:43.459586       1 stats.go:65] ** Stats collected **
I1009 07:55:43.459591       1 stats.go:61] Pod listing: 30.101µs
I1009 07:55:43.459599       1 stats.go:61] ID listing: 15.354817ms
I1009 07:55:43.459619       1 stats.go:61] Binding listing: 3.410726ms
I1009 07:55:43.459623       1 stats.go:61] Assigned ID listing: 3.100224ms
I1009 07:55:43.459626       1 stats.go:61] System: 21.900968ms
I1009 07:55:43.459630       1 stats.go:61] Cloud provider get: 26.687804ms
I1009 07:55:43.459660       1 stats.go:61] Cloud provider put: 10.873435158s
I1009 07:55:43.460096       1 event.go:218] Event(v1.ObjectReference{Kind:"AzureIdentityBinding", Namespace:"default", Name:"demo1-azure-identity-binding", UID:"1c4dee57-e9ec-11e9-8616-0a2b2ee139dd", APIVersion:"aadpodidentity.k8s.io/v1", ResourceVersion:"508773", FieldPath:""}): type: 'Normal' reason: 'binding applied' Binding demo1-azure-identity-binding applied on node aks-agentpool-15204281-0 for pod worker-service104-56c7bd77df-2ztbb-default-aks-managed-identity
I1009 07:55:43.459717       1 stats.go:61] Assigned ID addition: 23.709981ms
I1009 07:55:43.460329       1 stats.go:61] Assigned ID deletion: 0s
I1009 07:55:43.460369       1 stats.go:61] Find assigned ids to create: 0s
I1009 07:55:43.460374       1 stats.go:61] Find assigned ids to delete: 0s
I1009 07:55:43.460378       1 stats.go:61] Total time to assign or remove IDs: 10.942010183s
I1009 07:55:43.460441       1 stats.go:61] Event recording: 0s
I1009 07:55:43.460490       1 stats.go:61] Total: 10.963983251s
I1009 07:55:43.460611       1 stats.go:87] *********************

**Comment by deyanp** [comment]
I put 15 seconds sleep in the app, but still I get the same error: 

MIC: 

I1009 08:30:56.865363       1 event.go:218] Event(v1.ObjectReference{Kind:"AzureIdentityBinding", Namespace:"default", Name:"demo1-azure-identity-binding", UID:"999dee57-e9ec-11e9-8616-0a2b2ee13999", APIVersion:"aadpodidentity.k8s.io/v1", ResourceVersion:"508773", FieldPath:""}): type: 'Normal' reason: 'binding applied' Binding demo1-azure-identity-binding applied on node aks-agentpool-15204281-0 for pod worker-service105-676cb4b894-4zv59-default-aks-managed-identity
failed to watch file "/var/log/pods/99953038-e993-11e9-8616-0a2b2ee13999/mic/0.log": no space left on device


NMI: 

time="2019-10-09T08:30:58Z" level=error msg="no AzureAssignedIdentity found for pod:default/worker-service105-676cb4b894-4zv59 in assigned state, context canceled" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.244.0.43
time="2019-10-09T08:30:58Z" level=info msg="Status (404) took 1997220102 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.244.0.43
time="2019-10-09T08:31:52Z" level=info msg="node(aks-agentpool-15204281-0) hostip(10.240.0.4) metadataaddress(169.254.169.254:80) nmiport(2579)"
time="2019-10-09T08:31:52Z" level=info msg="Rules for table(nat) chain(aad-metadata) rules(-N aad-metadata, -A aad-metadata ! -s 127.0.0.1/32 -d 169.254.169.254/32 -p tcp -m tcp --dport 80 -j DNAT --to-destination 10.240.0.4:2579, -A aad-metadata -j RETURN)"
failed to watch file "/var/log/pods/99995537-e993-11e9-8616-0a2b2ee13999/nmi/0.log": no space left on device

(guids are partially redacted)

**Comment by aramase** [comment]
@deyanp From the MIC logs it does look like the `AzureAssignedIdentity` has been created successfully now for the pod. Please note - since the identities are assigned to the underlying node when the pod initially comes up in the cluster, the PUT call to add the identity typically takes ~10-15s for availability sets and ~40-55s for VMSS. You should be able to view the status of assigned identity for the pod by describing the assigned identity (Created/Assigned).

We have internal retries in NMI to accommodate this time required to assign the identity to the underlying node. The retry is for ~100s with 5s intervals. From your NMI logs, it looks like the context is being cancelled for the request. Please increase the context/ request timeout when requesting for token from your application.

**Comment by deyanp** [comment]
@aramase , the app is waiting endlessly to connect to Azure Key Vault ... I surely waited for a couple of minutes before I stopped watching the logs ... Do you mean I should change timeout or similar in the app when connecting to Azure Key Vault? Somewhere in this code:

`let kv = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(keyVaultTokenCallback))
let! secret2 = kv.GetSecretAsync("https://xxx-xxxx-xxxx-xxxxxvault.azure.net", "MongoDBConnectionString") |> Async.AwaitTask //.ConfigureAwait(false)`
?

**Comment by aramase** [comment]
@deyanp PTAL at this - https://stackoverflow.com/questions/33134579/keyvault-getsecretasync-never-returns. I think it might be related to the issue you are seeing?

We have retires in NMI to accommodate for the time taken to assign the identity to the underlying node. However if the request context is cancelled, we stop processing the request. This is what we see in the logs - `context cancelled` which means the request was terminated.

**Comment by deyanp** [comment]
Recreated the pod, and now I get:

MIC:
`
I1014 14:48:58.595036       1 event.go:218] Event(v1.ObjectReference{Kind:"AzureIdentityBinding", Namespace:"default", Name:"demo1-azure-identity-binding", UID:"1c4dee57-e9ec-11e9-8616-0a2b2ee139dd", APIVersion:"aadpodidentity.k8s.io/v1", ResourceVersion:"508773", FieldPath:""}): type: 'Normal' reason: 'binding applied' Binding demo1-azure-identity-binding applied on node aks-agentpool-15204281-0 for pod worker-service-cs100-79b985886-xc6cj-default-aks-managed-identity
I1014 14:48:58.595372       1 stats.go:61] Total: 10.923536744s
`
NMI: 
`
time="2019-10-14T14:48:56Z" level=error msg="no AzureAssignedIdentity found for pod:default/worker-service-cs100-79b985886-xc6cj in assigned state, context canceled" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.244.0.59
time="2019-10-14T14:48:56Z" level=info msg="Status (404) took 1999997670 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.244.0.59
time="2019-10-14T14:49:52Z" level=info msg="node(aks-agentpool-15204281-0) hostip(10.240.0.4) metadataaddress(169.254.169.254:80) nmiport(2579)"
`

**Comment by deyanp** [comment]
Tried Flex Volume based on Pod Identity, and the pod is hanging in ContainerCreating for 4+ minutes now ... 
@aramase  any hints what could be the reason for this hanging? I have probably not configured something, but what?? In case of Flex Volume + Pod Identity there is no wrong custom C#/F# code, as the container is handing upon creation even ... What could cause this hanging?

**Comment by aramase** [comment]
@deyanp The following should help debug what the error is with flexvol + pod identity -
1. Check the `kubectl describe pod <pod>` output for the pod that's in ContainerCreating.
2. Check the `MIC` logs to see if there are any errors while trying to assign identity to node.
3. If no errors in MIC, check if there is an assigned identity created for the pod - `kubectl get azureassignedidentities`. If there is an assigned identity with the pod name, check what is the status of the assigned identity by doing `kubectl get azureassignedidentity <assigned id name> -o yaml`. It should be in `Assigned` state if there is no error.
4. If assigned identity exists in `Assigned` state for the pod, check `NMI` logs to see why the request failed?

Also, if you can ssh into the worker node that the pod is scheduled on, you should be able to see the keyvault flexvolume logs at `/var/log/kv-driver.log`.

**Comment by deyanp** [comment]
Hi @aramase,

Re 1): Access denied. Caller was not found on any access policy ...
`
Events:
  Type     Reason       Age                    From                               Message
  ----     ------       ----                   ----                               -------
  Warning  FailedMount  14m (x84 over 169m)    kubelet, aks-agentpool-15204281-0  MountVolume.SetUp failed for volume "test" : mount command failed, status: Failure, reason: /etc/kubernetes/volumeplugins/azure~kv/azurekeyvault-flexvolume failed, Access denied. Caller was not found on any access policy. r nCaller: appid=88888888-fe96-489c-83de-b6fee90e0144;oid=77777777-3c5f-4d14-927e-d8cfd496c8cc;numgroups=0;iss=https://sts.windows.net/99999999-3b39-4252-9298-e429ecdc9b1a/ r nVault: xxx-yyyy-key-vault;location=westeurope InnerError={code:AccessDenied}
  Warning  FailedMount  4m47s (x73 over 168m)  kubelet, aks-agentpool-15204281-0  Unable to mount volumes for pod "worker-service-cs101-7ff859d4db-bgzrq_default(66666666-eea0-11e9-8616-0a2b2ee139dd)": timeout expired waiting for volumes to attach or mount for pod "default"/"worker-service-cs101-7ff859d4db-bgzrq". list of unmounted volumes=[test]. list of unattached volumes=[test default-token-wq2kl]
`
Re 2) All good in MIC logs:
`
I1014 16:38:02.593983       1 event.go:218] Event(v1.ObjectReference{Kind:"AzureIdentityBinding", Namespace:"default", Name:"demo1-azure-identity-binding", UID:"1c4dee57-e9ec-11e9-8616-0a2b2ee139dd", APIVersion:"aadpodidentity.k8s.io/v1", ResourceVersion:"508773", FieldPath:""}): type: 'Normal' reason: 'binding applied' Binding demo1-azure-identity-binding applied on node aks-agentpool-15204281-0 for pod worker-service-cs101-7ff859d4db-bgzrq-default-aks-managed-identity
`
Re 3) There is assigned identity, and it is in state Assigned:
`
NAME                                                                 AGE                                                                  worker-service-cs101-7ff859d4db-bgzrq-default-aks-managed-identity   2h
`
....
`
Status:                                                                                                                                     availableReplicas: 1
  metadata:
    creationTimestamp: null
  status: Assigned
`
Re 4) NMI logs looking good:
`
time="2019-10-14T19:33:36Z" level=info msg="matched identityType:0 clientid:72d1fef3-fe96-489c-83de-b6fee90e0144 resource:https://vault.azure.net" req.method=GET req.path=/host/token/ req.remote=127.0.0.1
time="2019-10-14T19:33:36Z" level=info msg="Status (200) took 17492038 ns" req.method=GET req.path=/host/token/ req.remote=127.0.0.1
`

To me it seems that somehow the access policy in the key vault is not working .. I have granted the following:

![image](https://user-images.githubusercontent.com/25847560/66778046-e1c37b80-eeca-11e9-8fb9-aa50495b0773.png)

The clientId of the managed identity is 
`
clientid: 72d1fef3-fe96-489c-83de-b6fee90e0144
`
so that should be correct, right?

**Comment by deyanp** [comment]
Ok, it seems that the access policy has to contain also the List Secrets right ... now the GetSecretAsync and the volume mounting work ... to prevent other poor souls wasting there time: 
![image](https://user-images.githubusercontent.com/25847560/66778729-da9d6d00-eecc-11e9-82c8-7588c7844eea.png)

Thank you @aramase for your incredible support!!
