### ISSUE TITLE
Error when installing aad-pod-identity on AKS cluster

### ISSUE THREAD

**Issue by coprisanu** [Azure/aad-pod-identity#423]
**Describe the bug**
We are getting the error "unable to recognize "https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml": the server rejected our request for an unknown reason" when trying to install aad-pod-identity on AKS using the instructions from readme.md

**Steps To Reproduce**
Running "kubectl apply -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml"
**Expected behavior**
aad-pod-identity to be installed on my AKS cluster.

**AAD Pod Identity version**
1.5.3
**Kubernetes version**
1.15.3
**Additional context**

**Comment by aramase** [comment]
@coprisanu which version of `kubectl` are you using? I tried it on my `1.15.2` cluster and it works fine -

```
 ➜ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by coprisanu** [comment]
@aramase Thank you for your quick response.
Please see below the response I'm getting when running "kubectl version"
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:36:53Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Error from server (BadRequest): the server rejected our request for an unknown reason
