### ISSUE TITLE
Choosing a managed identity from many user-assigned managed identities

### ISSUE THREAD

**Issue by VinaiMeyyappan** [Azure/aad-pod-identity#427]
Here is the scenario I am trying to implement with the pod identity

-	Create and add multiple user-assigned managed identities to the cluster
-	Create and deploy an asp,net core Web API to a pod. 
-	The call to the web API will have an id of the user-assigned managed to use in the header.
-	The web api will use that identity to get an access token using the AzureServiceTokenProvider.

To test this scenario, I did the following 

I created and installed 3 Azure Identities - Customer1, Customer2 and app1 - and the associated bindings to the cluster. 
I created a [simple pod](https://github.com/Azure/aad-pod-identity/files/3745165/little-pod.zip)  that can execute curl command. This pod has app1 as the value for the aadpodidbinding property. 
 
Run the following command from the cmd window to get an access token
 $ kubectl exec test-id-pod -it sh
/ # curl  http://169.254.169.254/metadata/identity/oauth2/token/?resource=https://vault.azure.net
This works and I can get the access token. 
 
To test the scenario of using the passed in user-assigned managed identity,  I used the following command

 
$ kubectl exec test-id-pod -it sh
/ # curl  http://169.254.169.254/metadata/identity/oauth2/token/?resource=https://vault.azure.net&**clientid**=xxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
 
It is returning a token, but it is for the app1 identity and not for the clientid passed in the url. It is ignoring the client id parameter. As per the [IMDS ](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service#metadata-apis) API documentation, the client id is a valid parameter. The scenario works when hosting the web api in  Azure App Service or azure functions, but in AKS

**Comment by kkmsft** [comment]
@VinaiMeyyappan - Notes from the debugging sessions:
- Initially only single binding was associated with the  labels which needs to be created were not in place for the pod from which the curl was performed.
- After using two bindings which point to the same identity, which is the way you can associate two identities to the same pod, the issues were resolved.
- The parameter name `client_id` should be used instead of `clientid`.

**Comment by kkmsft** [comment]
@VinaiMeyyappan - Since this is working now, closing this issue. Please re-open if there are further issues.

**Comment by krish-gh** [comment]
Hi @kkmsft, even using client_id, it's not working...we see that it's sometimes returns correct token, and sometimes not. Bit random.
