### ISSUE TITLE
Documentation for az role assignment create doesn't work

### ISSUE THREAD

**Issue by JohnGalt1717** [Azure/aad-pod-identity#430]
This line:

az role assignment create --role "Managed Identity Operator" --assignee <sp id> --scope <full id of the managed identity>

returns "The request did not have a subscription or a valid tenant level resource provider."

I verified the assignee and scope based on what I *think* the values should be since it's very not obvious if it's some fully qualified path or just the guids. (assignee being the aks and scope being the identity created in section 2 as guids)

When I tried to manually add it via the Portal, there is no role "Managed Identity Operator" showing up in the list which I would assume is the issue?

**Comment by kkmsft** [comment]
@JohnGalt1717 - There are few issues which are mentioned in a case with similar error messages - https://github.com/MicrosoftDocs/azure-docs/issues/33497, one being the format and another related to permissions. The scope should begin with /subscriptions/.... Can you please confirm that that is indeed the syntax you used to enter ? Also can you please check if you have enough permissions to make this assignment ?

**Comment by kkmsft** [comment]
@JohnGalt1717 - is this still an issue for you ?

**Comment by JohnGalt1717** [comment]
@kkmsft  I haven't had a chance to try it. I'll do so as soon as possible.

**Comment by kkmsft** [comment]
@JohnGalt1717 - Can you please confirm if this is still an issue for you?

**Comment by gavination** [comment]
Greetings @kkmsft. I'm just confirming that on my end, the format at least works. I've followed this trail of breadcrumbs and got it working on my end. I can't say anything regarding permissions though as I do have elevated permits in my subscription.

**Comment by kkmsft** [comment]
Closing this issue. Please re-open if the issue still persists.
