### ISSUE TITLE
AzureServiceTokenProviderException: Identity not found

### ISSUE THREAD

**Issue by Wema** [Azure/aad-pod-identity#436]
**Describe the bug**
I am getting an error response when trying to retreive token for user assigned identity. The response I am getting is: 
Exception Message: Tried the following 3 methods to get an access token, but none of them worked.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/a266655a-245b-4ab8-8d8f-6be387631120. Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. Received a non-retryable error. MSI ResponseCode: Forbidden, Response: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}

The curious thing is that this only occurs on 1 out of 2 of the pods I have running. Both pods are backed by the same deployment.

**Steps To Reproduce**

**Expected behavior**

**AAD Pod Identity version**
1.5.3

**Kubernetes version**
1.14.5

**Additional context**

**Comment by aramase** [comment]
@Wema I've a few questions -
1. Are you using VMSS or VMAS in the cluster?
2. Do you see an azureassignedidentity created for both the pods of the deployment? `kubectl get azureassignedidentities --all-namespaces`
  - If no, then can you check the MIC logs to see if there are any errors? `kubectl logs -l component=mic`.
3. Can you also check the NMI logs from the NMI pod running on the same node as the application pod that has the issue?

**Comment by Wema** [comment]
@aramase 
1. VMAS
2. Yes
3. Checked the NMI logs and I am getting the following errors:
time="2019-11-02T01:25:01Z" level=info msg="Starting nmi process. Version: 1.5.3. Build date: 2019-10-12-00:23. Log level: info."
ERROR: logging before flag.Parse: E1102 01:25:01.303063       1 reflector.go:322] pkg/mod/k8s.io/client-go@v0.0.0-20180424211516-33f2870a2b83/tools/cache/reflector.go:99: Failed to watch *v1.AzurePodIdentityException: unknown (get azurepodidentityexceptions.aadpodidentity.k8s.io)
ERROR: logging before flag.Parse: E1102 01:25:01.305222       1 reflector.go:322] pkg/mod/k8s.io/client-go@v0.0.0-20180424211516-33f2870a2b83/tools/cache/reflector.go:99: Failed to watch *v1.AzureAssignedIdentity: unknown (get azureassignedidentities.aadpodidentity.k8s.io)
ERROR: logging before flag.Parse: E1102 01:25:01.323774       1 reflector.go:322] pkg/mod/k8s.io/client-go@v0.0.0-20180424211516-33f2870a2b83/tools/cache/reflector.go:99: Failed to watch *v1.Pod: unknown (get pods)
time="2019-11-02T01:25:01Z" level=info msg="CRD lite informers started "
time="2019-11-02T01:25:01Z" level=info msg="Initialized health probe on port &[8080]"
time="2019-11-02T01:25:01Z" level=info msg="Started health probe"
time="2019-11-02T01:25:01Z" level=info msg="Listening on port 2579"
ERROR: logging before flag.Parse: E1102 01:25:02.310021       1 reflector.go:322] pkg/mod/k8s.io/client-go@v0.0.0-20180424211516-33f2870a2b83/tools/cache/reflector.go:99: Failed to watch *v1.AzurePodIdentityException: unknown (get azurepodidentityexceptions.aadpodidentity.k8s.io)
ERROR: logging before flag.Parse: E1102 01:25:02.312633       1 reflector.go:322] pkg/mod/k8s.io/client-go@v0.0.0-20180424211516-33f2870a2b83/tools/cache/reflector.go:99: Failed to watch *v1.AzureAssignedIdentity: unknown (get azureassignedidentities.aadpodidentity.k8s.io)
ERROR: logging before flag.Parse: E1102 01:25:02.339461       1 reflector.go:322] pkg/mod/k8s.io/client-go@v0.0.0-20180424211516-33f2870a2b83/tools/cache/reflector.go:99: Failed to watch *v1.Pod: unknown (get pods)
ERROR: logging before flag.Parse: E1102 01:25:03.317608       1 reflector.go:322] pkg/mod/k8s.io/client-go@v0.0.0-20180424211516-33f2870a2b83/tools/cache/reflector.go:99: Failed to watch *v1.AzurePodIdentityException: unknown (get azurepodidentityexceptions.aadpodidentity.k8s.io)
ERROR: logging before flag.Parse: E1102 01:25:03.319687       1 reflector.go:322] pkg/mod/k8s.io/client-go@v0.0.0-20180424211516-33f2870a2b83/tools/cache/reflector.go:99: Failed to watch *v1.AzureAssignedIdentity: unknown (get azureassignedidentities.aadpodidentity.k8s.io)
ERROR: logging before flag.Parse: E1102 01:25:03.355185       1 reflector.go:322] pkg/mod/k8s.io/client-go@v0.0.0-20180424211516-33f2870a2b83/tools/cache/reflector.go:99: Failed to watch *v1.Pod: unknown (get pods)

**Comment by kkmsft** [comment]
@Wema - the above indicates the right RBAC privileges are not provided to the NMI. How did you deploy aad-pod-identity ?

**Comment by Wema** [comment]
@kkmsft Thanks you are correct I did not change add the watch options to the rules, thanks for this.

**Comment by midhun-mohan** [comment]
could you please let me know what was the fix applied for this issue?

**Comment by Wema** [comment]
@midhun-mohan  The container image was updated but not the associated crd's once I applied the right changes to the crd's this fixed it. You can view the full yaml configuration here:
https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml

**Comment by midhun-mohan** [comment]
Thanks for the reply. but we fixed the issue related to Permission.

But what was the fix applied to fix this error  "Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}"
