### ISSUE TITLE
Kubecon NA 2019: Aad-pod-identity users

### ISSUE THREAD

**Issue by kkmsft** [Azure/aad-pod-identity#437]
Hi Folks,

Me(@kkmsft) and Anish(@aramase) - maintainers of aad-pod-identity project will be at KubeCon NA 2019. We would love to meet the users of aad-pod-identity.

Interested folks please let us know the timings which are convenient.

**Comment by kkmsft** [comment]
^^ @bnookala @sukhong @markusdresch @omerlh @xenalite @droessmj @woutervanvliet @ankrause @zhiweiv @abhisheknsit @yarinm

**Comment by zhiweiv** [comment]
Thanks for the invitation, regret that I am unable to join it.

Btw, aad-pod-identity works good in our clusters for now.

**Comment by cwoolum** [comment]
I'll see you there!
