### ISSUE TITLE
Support for Helm 3

### ISSUE THREAD

**Issue by LennartHaggkvistHM** [Azure/aad-pod-identity#444]
Helm 3 has been released and it would be good if the Chart for aad-pod-identity was updated

**Explain why AAD Pod Identity needs it**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Helm 3 contains changes to how crds works and thus we get the following error

> manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "AzureIdentity" in version "aadpodidentity.k8s.io/v1", unable to recognize "": no matches for kind "AzureIdentityBinding" in version "aadpodidentity.k8s.io/v1"]

**Comment by rohan3usturge** [comment]
Hi BzSpi,
Thanks for adding this support. 
Just wanted to ask , is there a tentative date for this chart to be available for use?

Thanks,
Rohan

**Comment by BzSpi** [comment]
Hi @rohan3usturge.

I'm not maintainer of the repo and don't know about any action regarding my MR.

Maybe @kkmsft know about it ?
