### ISSUE TITLE
Azure Resource is hardcoded to https://management.azure.com/

### ISSUE THREAD

**Issue by xtellurian** [Azure/aad-pod-identity#45]
Changing the resource in the request does not give a different token.

These two requests return the same token, with the same Audience.

`GET http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://management.azure.com/`

`GET http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https://storage.azure.com/`

Root cause may be the resource is hard coded. See line 25 in \pkg\nmi\server\server.go

```go
const (
	azureResourceName                  = "https://management.azure.com/"
	iptableUpdateTimeIntervalInSeconds = 10
)
```

Then on line 182

```go
case aadpodid.UserAssignedMSI:
	logger.Infof("matched identityType:%v clientid:%s resource:%s", idType, clientID, azureResourceName)
	return auth.GetServicePrincipalTokenFromMSIWithUserAssignedID(clientID, azureResourceName)
```

**Comment by rite2nikhil** [comment]
Thanks will get this fixed

**Comment by khenidak** [comment]
@rite2nikhil did we close on this?

**Comment by ritazh** [comment]
I can take a look at this one.

**Comment by ritazh** [comment]
After reviewing this issue a bit more, we seem to have two issues here.
1. we need to support multiple Azure environments (not just Azure public), I have a fix for this coming in few mins, which should also help with item 2.
2. we need to provide a way to pass in what resource the user wants token for. 
`spt, err := adal.NewServicePrincipalTokenFromMSIWithUserAssignedID(msiEndpoint, resource, userAssignedID)`
@xtellurian @rite2nikhil need your opinions here

Below are the possible values for resource. 
```
		ManagementPortalURL:          "https://manage.windowsazure.com/",
		PublishSettingsURL:           "https://manage.windowsazure.com/publishsettings/index",
		ServiceManagementEndpoint:    "https://management.core.windows.net/",
		ResourceManagerEndpoint:      "https://management.azure.com/",
		ActiveDirectoryEndpoint:      "https://login.microsoftonline.com/",
		GalleryEndpoint:              "https://gallery.azure.com/",
		KeyVaultEndpoint:             "https://vault.azure.net/",
		GraphEndpoint:                "https://graph.windows.net/",
		ServiceBusEndpoint:           "https://servicebus.windows.net/",
		BatchManagementEndpoint:      "https://batch.core.windows.net/",
		StorageEndpointSuffix:        "core.windows.net",
		SQLDatabaseDNSSuffix:         "database.windows.net",
		TrafficManagerDNSSuffix:      "trafficmanager.net",
		KeyVaultDNSSuffix:            "vault.azure.net",
		ServiceBusEndpointSuffix:     "servicebus.windows.net",
		ServiceManagementVMDNSSuffix: "cloudapp.net",
		ResourceManagerVMDNSSuffix:   "cloudapp.azure.com",
		ContainerRegistryDNSSuffix:   "azurecr.io",
		TokenAudience:                "https://management.azure.com/",
```

**Comment by xtellurian** [comment]
[Azure services that support MSI](https://docs.microsoft.com/en-us/azure/active-directory/managed-service-identity/services-support-msi)


Service | Resource ID | Status | Date | Assign access
-- | -- | -- | -- | --
Azure Resource Manager | https://management.azure.com/ | Available | September 2017 | Azure portal PowerShell Azure CLI
Azure Key Vault | https://vault.azure.net | Available | September 2017 |  
Azure Data Lake | https://datalake.azure.net/ | Available | September 2017 |  
Azure SQL | https://database.windows.net/ | Available | October 2017 |  
Azure Event Hubs | https://eventhubs.azure.net | Available | December 2017 |  
Azure Service Bus | https://servicebus.azure.net | Available | December 2017 |  
Azure Storage | https://storage.azure.com/ | Preview | May 2018

**Comment by xtellurian** [comment]
The resource should be passed on from Pod to NMI and any other service
