### ISSUE TITLE
Helm 3 skipping unknown hook: "crd-install

### ISSUE THREAD

**Issue by GramozKrasniqi** [Azure/aad-pod-identity#454]
**Describe the request**
Provide a flag to disable installing CRDs

**Explain why AAD Pod Identity needs it**
When using Helm3+ we get ```skipping unknown hook: "crd-install"```
We want to be able to command  the chart to not install CRDs beacuse we will install them manually.

**Describe the solution you'd like**
Please check the elegant solution provided by prometheus-operator helm chart.
https://github.com/helm/charts/tree/master/stable/prometheus-operator#prometheus-operator-1

The flag is called prometheusOperator.createCustomResource

**Additional content**
Of course we understand that this is just a workaround until you migrate to Helm Charts v2

**Comment by fraserdarwent** [comment]
Same issue here

**Comment by BzSpi** [comment]
PR #455 has been merged and released with version 1.5.5.

@aramase @kkmsft any idea why the changelog does not mention the helm 3 update ? Also, bumping the Chart revision number instead of minor or major version is surprising for a such important update.

**Comment by aramase** [comment]
@BzSpi The changelog usually only contains changes (features/bugs/improvements) to the MIC/NMI. Will add helm changes in the release notes the next time. 

Will also bump the chart apiversion as part of the next release.
