### ISSUE TITLE
Add Namespace support to templates

### ISSUE THREAD

**Issue by devlinmr** [Azure/aad-pod-identity#462]
**Describe the request**
Add namespace to metadata in helm templates for namespaced resources.

**Explain why AAD Pod Identity needs it**
We're using tiller-less Helm to deploy the template, we therefore can't use `--namespace` without the corresponding metadata, e.g.:

```
metadata:
  name: {{ template "aad-pod-identity.mic.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
```
**Describe the solution you'd like**
I can raise a PR to add the necessary entries.

**Describe alternatives you've considered**
We're looking at upgrading to Helm 3 in due course, which should negate the issue

**Additional context**

**Comment by kkmsft** [comment]
Closing this since we now support helm3. Please reopen if this is still an issue with helm3.
