### ISSUE TITLE
Dynamic service principals for GitOps flow

### ISSUE THREAD

**Issue by Ant59** [Azure/aad-pod-identity#469]
I came across this project whilst looking for a way to work with Service Principals in a GitOps environment. Services deployed to the cluster via the GitOps operator need a service principal to access Azure resources.

From reading the description in the Azure Docs (https://docs.microsoft.com/en-us/azure/aks/operator-best-practices-identity#use-pod-identities), it seems that this project was what I needed to dynamically create identities for services in the cluster to access Azure resources. However, on looking into the tutorial and descriptions in this repository, I can't see anything that would solve the problem.

As far as I can understand, this project doesn't solve much. It still requires someone to manually create an identity per service, outside of the GitOps flow, preventing declarative source of truth in Git. After all the fanciness with intercepting traffic to the NMI, and creating a load of CRDs, it still at it's core comes down to manual intervention. So what's the point of this project? What am I missing? And, if possible, how do I achieve GitOps, dynamic identities for Kubernetes services?

**Comment by asubmani** [comment]
@Ant59 > I had opened a separate issue for the same. #476 . 

This project does give you flexibility in managing serviceaccounts that need controlled access to Azure resources.
e.g.
Create a group in AAD called "devOps-readers". AAD (Identity team) will control access to this group.  The user assigned Identity would also be part of this group.

kubernetes operator creates ClusterRole and bindings for the user assigned MI
Kubernetes deployments that use this identity will get access to any Azure resource that allows "dev-ops" readers access,

Please note that the part where you assign Role assignments to these dynamic identities does not change in your GitOps flow. All you would need is a naming convention for the user-assigned identities and configure a check to see if the identity is available.

**Comment by aramase** [comment]
@Ant59 The identities need to be created and role assignments need to be done manually. However once after the `AzureIdentity` is created in the cluster, it'll manage the lifecycle of the identity on the cluster. MIC handles the identity assignment/deletion of identities dynamically as workload that needs to use the identity runs/is deleted from the cluster. NMI acts as a soft firewall on the cluster ensuring only pods with access to the identities can fetch token using the identity and thereby access the resources in azure. The pod-identity projects brings the identities to the pods running on the cluster.

Please look at @asubmani comments too. Closing this issue. Please feel free to reopen if you have any more questions.
