### ISSUE TITLE
NMI got 403 from 169.254.169.254 intermittently 

### ISSUE THREAD

**Issue by Shuanglu** [Azure/aad-pod-identity#472]
**Describe the bug**
I followed the https://github.com/Azure/aad-pod-identity#getting-started to deploy the demo but found NMI got 403 intermittently. Sometimes it will succeed later but sometimes it keeps failing.
Any idea/advice why the endpoint returned 403? the MIC works fine.
Logs from NMI

time="2020-01-08T17:19:47Z" level=error msg="no AzureAssignedIdentity found for pod:default/demo-9d676dd44-8zn22 in assigned state, getting assigned identities for pod default/demo-9d676dd44-8zn22 in CREATED state failed after 16 attempts, retry duration [5]s. Error: <nil>" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.244.2.72
time="2020-01-08T17:19:47Z" level=info msg="Status (403) took 80004592160 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.244.2.72
time="2020-01-08T17:19:47Z" level=info msg="matched identityType:0 clientid:b7e8##### REDACTED #####6207 resource:https://management.azure.com/" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.244.2.72
time="2020-01-08T17:19:47Z" level=info msg="Status (200) took 4426116 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.244.2.72
time="2020-01-08T17:19:47Z" level=info msg="matched identityType:0 clientid:b7e8##### REDACTED #####6207 resource:https://management.azure.com/" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.244.2.72

**Steps To Reproduce**
Following https://github.com/Azure/aad-pod-identity#getting-started
**Expected behavior**
NMI always gets 200
**AAD Pod Identity version**
1.5.4
**Kubernetes version**
1.15.4
**Additional context**

**Comment by aramase** [comment]
@Shuanglu When the pod initially comes up, MIC creates azure assigned identity and sets it in `CREATED` state. The azure assigned identity state is changed to `ASSIGNED` when the identity has been successfully assigned to the underlying node. Typically identity assignment takes ~10s for VMAS and ~40s for VMSS. MIC tries to batch process when bulk of pods get scheduled, but it's possible some pods will be queued up for after current work is complete in MIC.

From the logs you posted, it looks like the identity assignment took time. You can see the time taken to assign identity in the stats published in MIC logs.
