### ISSUE TITLE
Azure AssignedIdentities Created in Wrong Namespace when Scope=Namespaced

### ISSUE THREAD

**Issue by kevingbb** [Azure/aad-pod-identity#475]
**Describe the bug**
The AzureAssignedIdentities for pods in a "dev" namespace should be created in the "dev" namespace when scope = namespaced, but the AzureAssignedIdentities are being created in "default" namespace.

**Steps To Reproduce**
1. Install AAD Pod Identity
2. Create AzureIdentity in "dev" namespace
3. Create AzureIdentityBinding in "dev" namespace
4. Install pod workload with proper label.

**Expected behavior**
The AzureAssignedIdentites to be created in the "dev" namespace, not "default".

**AAD Pod Identity version**
mcr.microsoft.com/k8s/aad-pod-identity/mic:1.5.3

**Kubernetes version**
AKS 1.15.7

**Additional context**
# Create AAD Identity
cat <<EOF | kubectl apply -f -
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: akv-identity
  namespace: dev
spec:
  type: 0
  ResourceID: /subscriptions/$SUBID/resourcegroups/$RG/providers/Microsoft.ManagedIdentity/userAssignedIdentities/$AAD_IDENTITY
  ClientID: $AAD_IDENTITY_CLIENTID
EOF
# Create AAD Identity Binding
cat <<EOF | kubectl apply -f -
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: akv-identity-binding
  namespace: dev
spec:
  AzureIdentity: akv-identity
  Selector: bind-akv-identity
EOF

kubectl get azureidentity,azureidentitybinding -n dev
NAME                                               AGE
azureidentity.aadpodidentity.k8s.io/akv-identity   21h
NAME                                                              AGE
azureidentitybinding.aadpodidentity.k8s.io/akv-identity-binding   21h

k get AzureAssignedIdentities -A             
NAMESPACE   NAME                                                     AGE
default     imageclassifierweb-f794d7fc7-pjmgt-dev-akv-identity      5m43s
default     imageclassifierworker-ddf4774f6-ntqw6-dev-akv-identity   5m3s

**Comment by aramase** [comment]
@kevingbb By default pod-identity was designed to create the AzureAssignedIdentity in the default namespace. However you can configure pod-identity to run in force namespaced mode - https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.namespaced.md in which case the `AzureAssignedIdentity` will be created in the same namespace as AzureIdentity and AzureIdentityBinding.

**Comment by kevingbb** [comment]
Thx aramase, that is what I missed. I thought by having the spec.scope set to namespaced on the CRDs did that.
