### ISSUE TITLE
No AzureAssignedIdentity found ... in CREATED state failed after 16 attempts

### ISSUE THREAD

**Issue by samrobillard** [Azure/aad-pod-identity#497]
Followed the doc to install the YAML, user managed identity, AzureIdentity, AzureIdentityBinding, gave the permissions to the SPN on the user managed identity, my deployment has the aadpodbinding tag.

The NMI and MIC are in verbose level 6.

Using version 1.5.5

The NMI throws:

I0204 17:56:07.660043       1 reflector.go:428] pkg/mod/k8s.io/client-go@v0.0.0-20180424211516-33f2870a2b83/tools/cache/reflector.go:99: Watch close - *v1.Pod total 11 items received
I0204 17:56:07.662790       1 round_trippers.go:405] GET https://10.20.0.1:443/api/v1/pods?fieldSelector=spec.nodeName%3Daks-sampoc-14995202-vmss000000&resourceVersion=12814&timeoutSeconds=408&watch=true 200 OK in 2 milliseconds
I0204 17:56:46.579463       1 reflector.go:428] pkg/mod/k8s.io/client-go@v0.0.0-20180424211516-33f2870a2b83/tools/cache/reflector.go:99: Watch close - *v1.AzurePodIdentityException total 0 items received
I0204 17:56:46.581481       1 round_trippers.go:405] GET https://10.20.0.1:443/apis/aadpodidentity.k8s.io/v1/azurepodidentityexceptions?resourceVersion=7734&timeoutSeconds=471&watch=true 200 OK in 1 milliseconds
time="2020-02-04T17:56:55Z" level=error msg="no AzureAssignedIdentity found for pod:default/sam-core-dd6cf4b5f-hwjwx in assigned state, getting assigned identities for pod default/sam-core-dd6cf4b5f-hwjwx in CREATED state failed after 16 attempts, retry duration [5]s. Error: <nil>" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.10.0.18
time="2020-02-04T17:56:55Z" level=info msg="Status (403) took 80002877499 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.10.0.18
I0204 17:59:41.656631       1 reflector.go:428] pkg/mod/k8s.io/client-go@v0.0.0-20180424211516-33f2870a2b83/tools/cache/reflector.go:99: Watch close - *v1.AzureAssignedIdentity total 0 items received
I0204 17:59:41.659029       1 round_trippers.go:405] GET https://10.20.0.1:443/apis/aadpodidentity.k8s.io/v1/azureassignedidentities?resourceVersion=7681&timeoutSeconds=558&watch=true 200 OK in 2 milliseconds
time="2020-02-04T17:59:45Z" level=error msg="no AzureAssignedIdentity found for pod:default/sam-core-dd6cf4b5f-hwjwx in assigned state, getting assigned identities for pod default/sam-core-dd6cf4b5f-hwjwx in CREATED state failed after 16 attempts, retry duration [5]s. Error: <nil>" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.10.0.18
time="2020-02-04T17:59:45Z" level=info msg="Status (403) took 80003362998 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.10.0.18

No identity attached to the VMSS and the MIC doesn't show any errors. I recreated my AKS cluster from scratch and I can't figure out what is wrong.

**Comment by aramase** [comment]
@samrobillard Do you see identity assignment happening in the MIC logs? Also, can you post pod manifest (yaml)?

**Comment by samrobillard** [comment]
Hi,

Thanks for your quick reply. All I can see in the MIC logs is:

I0204 18:36:14.566205       1 reflector.go:286] pkg/mod/k8s.io/client-go@v0.0.0-20180424211516-33f2870a2b83/tools/cache/reflector.go:99: forcing resync
I0204 18:36:14.566268       1 crd.go:222] Identity updated
I0204 18:36:14.566283       1 mic.go:268] Received event: 5
I0204 18:36:14.566342       1 crd.go:390] Appending binding: default/aad-aks-binding001 to list.
I0204 18:36:14.566383       1 crd.go:477] Appending Identity: default/aad-aks-app01 to list.
I0204 18:36:14.566413       1 mic.go:325] del: map[], add: map[]
I0204 18:36:14.672886       1 reflector.go:286] pkg/mod/k8s.io/client-go@v0.0.0-20180424211516-33f2870a2b83/tools/cache/reflector.go:99: forcing resync
I0204 18:36:14.672945       1 crd.go:191] Binding updated
I0204 18:36:14.673077       1 mic.go:268] Received event: 8
I0204 18:36:14.673199       1 crd.go:390] Appending binding: default/aad-aks-binding001 to list.
I0204 18:36:14.673284       1 crd.go:477] Appending Identity: default/aad-aks-app01 to list.
I0204 18:36:14.673391       1 mic.go:325] del: map[], add: map[]
I0204 18:36:14.716570       1 reflector.go:286] pkg/mod/k8s.io/client-go@v0.0.0-20180424211516-33f2870a2b83/tools/cache/reflector.go:99: forcing resync
I0204 18:36:17.902197       1 round_trippers.go:405] GET https://10.20.0.1:443/api/v1/namespaces/default/endpoints/aad-pod-identity-mic 200 OK in 3 milliseconds
I0204 18:36:17.906775       1 round_trippers.go:405] PUT https://10.20.0.1:443/api/v1/namespaces/default/endpoints/aad-pod-identity-mic 200 OK in 4 milliseconds
I0204 18:36:17.906887       1 leaderelection.go:199] successfully renewed lease default/aad-pod-identity-mic

Here are my manifests:

apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: aad-aks-app01
spec:
  type: 0
  ResourceID: ID
  ClientID: ID

apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: aad-aks-binding001
spec:
  AzureIdentity: aad-aks-app01
  Selector: aad-app001

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp 
  labels:
    aadpodidbinding: aad-app001
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      labels:
        name: myapp
        aadpodbinding: aad-app001
        app: myapp
    spec:
      containers:
      - name: myapp
        image: someimage
        ports:
        - containerPort: 80

**Comment by aramase** [comment]
@samrobillard The label needs to be `aadpodidbinding`. 
```
metadata:
  labels:
    name: myapp
    aadpodidbinding: aad-app001
    app: myapp
```

**Comment by samrobillard** [comment]
Yup... the template had aadpodbinding instead of aadpodidbinding. I guess the I don't need to tag the deployment and only the template for the pods? 

Thanks for your help!

**Comment by aramase** [comment]
@samrobillard yes, the tag for the pod template is what is used!

**Comment by samrobillard** [comment]
Issue was between the keyboard and the chair. Thanks @aramase !
