### ISSUE TITLE
Add Helm chart parameters for Pod Annotations

### ISSUE THREAD

**Issue by desek** [Azure/aad-pod-identity#498]
**Describe the request**

I want to be able to set Pod Annotations in the Helm chart.

**Explain why AAD Pod Identity needs it**

To be able to benefit from Pod annotations such as automatic Prometheus scraping.

**Describe the solution you'd like**

Parameters for `nmi.podAnnotations` and `mic.podAnnotations`.  
For an implementation example see the [cert-manager chart](https://github.com/helm/charts/tree/master/stable/cert-manager)

**Describe alternatives you've considered**

**Additional context**

**Comment by kkmsft** [comment]
@desek : Would you be interested in raising a PR for this ? We will help review and merge.
