### ISSUE TITLE
AAD-Pod-Idenity often took long time to be ready in AKS upgrade

### ISSUE THREAD

**Issue by northtyphoon** [Azure/aad-pod-identity#499]
**Describe the bug**

We deployed AAD-Pod-Identity on AKS. When we upgraded AKS version, we noticed many times the AAD-Pod-Idnentity could take very long time (>10 minutes) to get ready to serve MSI token request. Most time we saw the following two typical errors.

```
time="2020-02-07T19:08:09Z" level=error msg="no AzureAssignedIdentity found for pod:xxx/yyy-ff96f64fc-x4brj in assigned state, context canceled" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.244.5.3
time="2020-02-07T19:08:09Z" level=info msg="Status (404) took 1999283199 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.244.5.3
```

```
time="2020-02-07T19:13:33Z" level=error msg="failed to get service principal token for pod:xxx/yyy-5ffd8b86d9-95nxz, Failed to acquire a token using the MSI VM extension. Error: parameter 'resource' cannot be empty" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.244.5.14
time="2020-02-07T19:13:33Z" level=info msg="Status (403) took 332400 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.244.5.14
```

**AAD Pod Identity version**
1.5.3

**Kubernetes version**
The issue happened when we upgraded AKS from 1.13.10 to 1.14.8

**Comment by kkmsft** [comment]
@northtyphoon - By any chance do you have the logs from MIC around that time frame ?

**Comment by aramase** [comment]
@northtyphoon It's possible the time taken for cloud PUT during the upgrade took time. MIC makes a `CreateOrUpdate` call with all the identity list. If that operation takes time, then NMI can serve tokens until the identity is assigned. The next time it happens, please share the logs with us and we can take a look to see which operation is taking a long time.

Closing this issue. Please feel free to reopen the issue if you have logs around that timeframe/ see the issue happen again.
