### ISSUE TITLE
Make cloudconfig host path configurable in Helm chart

### ISSUE THREAD

**Issue by twendt** [Azure/aad-pod-identity#501]
**Describe the request**
The cloudconfig host path is currently hard coded to /etc/kubernetes/azure.json. Rancher uses /etc/kubernetes/cloud-config, therefore it would be great if the path was configurable via values.

**Explain why AAD Pod Identity needs it**
Enable AAD Pod Identity to be used in Kubernetes clusters deployed by Rancher.

**Describe the solution you'd like**
Add cloudConfigHostPath value and use it in the volume hostPath of the mic deployment. The default value should be /etc/kubernetes/azure.json.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by aramase** [comment]
@twendt Would you be interested in opening a PR for this?
