### ISSUE TITLE
Upgrade from 1.5.2 to 1.5.5 not working with Helm

### ISSUE THREAD

**Issue by twendt** [Azure/aad-pod-identity#502]
**Describe the bug**
When trying to upgrade an existing installation of 1.5.2 to 1.5.5 I get the following error:

```
Error: DaemonSet.apps "aad-pod-identity-nmi" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"nmi", "app.kubernetes.io/instance":"aad-pod-identity", "app.kubernetes.io/managed-by":"Tiller", "app.kubernetes.io/name":"aad-pod-identity", "helm.sh/chart":"aad-pod-identity-1.5.5"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable && Deployment.apps "aad-pod-identity-mic" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"mic", "app.kubernetes.io/instance":"aad-pod-identity", "app.kubernetes.io/managed-by":"Tiller", "app.kubernetes.io/name":"aad-pod-identity", "helm.sh/chart":"aad-pod-identity-1.5.5"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

This is caused by #456 The change in that PR causes all labels to be used in the selector as well whereas before the following 2 labels where not used as part of the selector:

```
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ template "aad-pod-identity.chart" . }}
```

**Steps To Reproduce**
Install version 1.5.2 via Helm and update to 1.5.5 with Helm.

**Expected behavior**
The upgrade should work.

**AAD Pod Identity version**
1.5.2 -> 1.5.5

**Kubernetes version**
1.15.4

**Additional context**
I would suggest something like this:

```
{{/*
Common labels.
*/}}
{{- define "aad-pod-identity.labels" -}}
{{- include "aad-pod-identity.selectors" . }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
helm.sh/chart: {{ template "aad-pod-identity.chart" . }}
{{- end -}}

{{/*
Common selectors.
*/}}
{{- define "aad-pod-identity.selectors" -}}
app.kubernetes.io/name: {{ template "aad-pod-identity.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
```

And then use `{{- include "aad-pod-identity.selectors" . | nindent 6 }}` in the selector for the deployment and daemonset.

**Comment by aramase** [comment]
@twendt It's a good suggestion. Are you interested in opening a PR for this change?

**Comment by devlinmr** [comment]
@twendt Thanks, as we're also waiting for a fix for this I've raised a PR with your suggested fix: https://github.com/Azure/aad-pod-identity/pull/518
