### ISSUE TITLE
MIC too late to create AzureAssignedIdentity

### ISSUE THREAD

**Issue by kwaazaar** [Azure/aad-pod-identity#503]
**Describe the bug**
MIC is sometimes way too late to create the AzureAssignedIdentity. This is especially an issue with pods that need the accesstoken on startup, jobs being the most obvious.
It sometimes takes MINUTES to assign the identity, as shown in the logs below.

**Steps To Reproduce**
Occurs sometime. I use a test application scheduled as a job to test which fails a few times a day: https://github.com/kwaazaar/azureappauth

**Expected behavior**
When pod is created, AzureAssignedIdentity is also created almost instantly.

**AAD Pod Identity version**
Latest yaml, no Helm. 1.5.5

**Kubernetes version**
1.14.8 (AKS)

**Additional context**
Cross-checking logs from the pod 'appauthtest-cronjob-1581342000-zk6gk' with MIC shows that MIC created the assigned identity approximately 130 seconds after it was requested. The call to GetAuthenticationResultAsync failed almost 1 minute before MIC created the AzureAssignedIdentity.
Maybe this line in the logs is a good indication: **"Total time to assign or remove IDs: 3m14.026129229s"**

Pod logs:
~~~
kubectl logs appauthtest-cronjob-1581342000-zk6gk
2020-02-10T13:43:29.852 info: AppAuthTest.AppAuthTester[0]
      Requesting accesstoken...
2020-02-10T13:44:50.086 fail: AppAuthTest.AppAuthTester[0]
      Failed to get accesstoken: Parameters: Connection String: RunAs=App, Resource: https://database.windows.net/, Authority: https://login.microsoftonline.com/d8f00f92-64fd-40fe-9f0b-e09e6b0875cc. Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. Received a non-retryable error. MSI ResponseCode: Forbidden, Response: no AzureAssignedIdentity found for pod:development/appauthtest-cronjob-1581342000-zk6gk in assigned state

Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException: Parameters: Connection String: RunAs=App, Resource: https://database.windows.net/, Authority: https://login.microsoftonline.com/d8f00f92-64fd-40fe-9f0b-e09e6b0875cc. Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. Received a non-retryable error. MSI ResponseCode: Forbidden, Response: no AzureAssignedIdentity found for pod:development/appauthtest-cronjob-1581342000-zk6gk in assigned state

   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAuthResultAsyncImpl(String resource, String authority, CancellationToken cancellationToken)
   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAuthenticationResultAsync(String resource, String tenantId, CancellationToken cancellationToken)
   at AppAuthTest.AppAuthTester.StartAsync(CancellationToken cancellationToken) in /home/vsts/work/1/s/AppAuthTest/AppAuthTester.cs:line 33
~~~

MIC logs:
~~~
I0210 13:45:41.618257       1 crd.go:539] Updating assigned identity default/appauthtest-cronjob-1581342000-bx2gc-development-testrobert status to Assigned
I0210 13:45:41.618302       1 crd.go:539] Updating assigned identity default/appauthtest-cronjob-1581342000-tsf85-development-testrobert status to Assigned
I0210 13:45:41.759996       1 mic.go:367] Work done: true. Found 31 pods, 3 ids, 4 bindings
I0210 13:45:41.760020       1 mic.go:368] Total work cycles: 322710, out of which work was done in: 12572.
I0210 13:45:41.760032       1 stats.go:98] ** Stats collected **
I0210 13:45:41.760036       1 stats.go:81] Pod listing: 377.197µs
I0210 13:45:41.760061       1 stats.go:81] ID listing: 5.9µs
I0210 13:45:41.760065       1 stats.go:81] Binding listing: 10.9µs
I0210 13:45:41.760069       1 stats.go:81] Assigned ID listing: 26.1µs
I0210 13:45:41.760072       1 stats.go:81] System: 429.397µs
I0210 13:45:41.760076       1 stats.go:81] CacheSync: 0s
I0210 13:45:41.760079       1 stats.go:81] Cloud provider get: 40.331078ms
I0210 13:45:41.760083       1 stats.go:81] Cloud provider put: 3m13.776542718s
I0210 13:45:41.760086       1 stats.go:81] Assigned ID addition: 134.499129ms
I0210 13:45:41.760090       1 stats.go:81] Assigned ID deletion: 0s
I0210 13:45:41.760093       1 stats.go:88] Number of cloud provider PUT: 1
I0210 13:45:41.760097       1 stats.go:88] Number of cloud provider GET: 1
I0210 13:45:41.760100       1 stats.go:88] Number of assigned ids created in this sync cycle: 2
I0210 13:45:41.760103       1 stats.go:88] Number of assigned ids deleted in this sync cycle: 0
I0210 13:45:41.760107       1 stats.go:81] Find assigned ids to create: 24.6µs
I0210 13:45:41.760110       1 stats.go:81] Find assigned ids to delete: 16.2µs
I0210 13:45:41.760113       1 stats.go:81] Total time to assign or remove IDs: 3m14.026129229s
I0210 13:45:41.760117       1 stats.go:81] Event recording: 0s
I0210 13:45:41.760120       1 stats.go:81] Total: 3m14.026893422s
I0210 13:45:41.760124       1 stats.go:127] *********************
I0210 13:45:41.962464       1 mic.go:787] Processing node aks-agentpool-71662594-7, add [1], del [0]
I0210 13:45:41.962511       1 crd.go:341] Got assigned id appauthtest-cronjob-1581342000-zk6gk-development-testrobert to assign
I0210 13:45:41.962916       1 mic.go:787] Processing node aks-agentpool-71662594-19, add [1], del [0]
I0210 13:45:41.962950       1 crd.go:341] Got assigned id appauthtest-cronjob-1581342000-f5wss-development-testrobert to assign
I0210 13:45:42.113593       1 cloudprovider.go:199] Updating user assigned MSIs on aks-agentpool-71662594-19
I0210 13:45:42.125029       1 crd.go:539] Updating assigned identity default/appauthtest-cronjob-1581342000-zk6gk-development-testrobert status to Assigned
I0210 13:46:53.772507       1 crd.go:539] Updating assigned identity default/appauthtest-cronjob-1581342000-f5wss-development-testrobert status to Assigned
I0210 13:46:53.798495       1 mic.go:367] Work done: true. Found 34 pods, 3 ids, 4 bindings
I0210 13:46:53.798514       1 mic.go:368] Total work cycles: 322711, out of which work was done in: 12573.
I0210 13:46:53.798532       1 stats.go:98] ** Stats collected **
I0210 13:46:53.798537       1 stats.go:81] Pod listing: 933.392µs
I0210 13:46:53.798545       1 stats.go:81] ID listing: 13.3µs
I0210 13:46:53.798548       1 stats.go:81] Binding listing: 22.4µs
I0210 13:46:53.798552       1 stats.go:81] Assigned ID listing: 70.8µs
I0210 13:46:53.798556       1 stats.go:81] System: 1.052492ms
I0210 13:46:53.798559       1 stats.go:81] CacheSync: 0s
I0210 13:46:53.798563       1 stats.go:81] Cloud provider get: 96.45143ms
I0210 13:46:53.798566       1 stats.go:81] Cloud provider put: 1m11.658868719s
I0210 13:46:53.798570       1 stats.go:81] Assigned ID addition: 216.611872ms
I0210 13:46:53.798574       1 stats.go:81] Assigned ID deletion: 0s
I0210 13:46:53.798577       1 stats.go:88] Number of cloud provider PUT: 1
I0210 13:46:53.798581       1 stats.go:88] Number of cloud provider GET: 2
I0210 13:46:53.798584       1 stats.go:88] Number of assigned ids created in this sync cycle: 2
I0210 13:46:53.798588       1 stats.go:88] Number of assigned ids deleted in this sync cycle: 0
I0210 13:46:53.798591       1 stats.go:81] Find assigned ids to create: 194.899µs
I0210 13:46:53.798594       1 stats.go:81] Find assigned ids to delete: 40.899µs
I0210 13:46:53.798598       1 stats.go:81] Total time to assign or remove IDs: 1m11.835558408s
I0210 13:46:53.798601       1 stats.go:81] Event recording: 0s
I0210 13:46:53.798604       1 stats.go:81] Total: 1m11.838124988s
I0210 13:46:53.798608       1 stats.go:127] *********************
~~~

In this closed issue I added a comment that may also point to a timing issue, although a different one: #473.

**Comment by kkmsft** [comment]
@kwaazaar - Thank you ! for using aad  pod identity. 

Please confirm the following. - you are using vm in availability set configuration ? Also how many nodes are part of the cluster ?

As per the MIC logs:

I0210 13:45:41.760083       1 stats.go:81] Cloud provider put: 3m13.776542718s

MIC calls ARM to perform the assignment/deletion of identity. This indicates that the cloud operation took 3m13.776542718s. Please raise a support case with azure support with the specific note on identity assignment times.

**Comment by kwaazaar** [comment]
It's an 'old' cluster, created many months ago, using type AvailabilitySet indeed. The cluster has 22 nodes of type Standard_DS3_v2, no autoscaling enabled.

We plan to recreate our clusters in the near future (to be able to use new AKS-features available and to mitigate other AKS problems). Do you expect this issue to not surface on that new cluster?

**Comment by kkmsft** [comment]
@kwaazaar -  Since you are seeing issues with your current VMA setup, we have to look at it on a case to case basis. Our recommendation is that if you face issues with the new VMSS to raise the support case. We will help transfer to the appropriate team.

**Comment by kwaazaar** [comment]
@kkmsft Support case 120021122002478.

**Comment by franzoir** [comment]
@kwaazaar may I ask what the outcome of your support ticket was? We're also seeing intermittent startup failures that will work moments later when the identity is assigned to the node.

**Comment by kwaazaar** [comment]
Support case is still open. But we upgraded AKS and it's faster on the new nodes. But startup errors you better get used to if you have a large cluster. Our smaller 10-node clusters don't seem to have this issue so far.

**Comment by franzoir** [comment]
Ok, thanks for the update. We're facing the problem in our smaller 7-node cluster with AKS v1.15.10. Actually not occuring that often in our larger cluster at the moment. But we created a support ticket for investigation last week.

**Comment by kagkarlsson** [comment]
We are also experiencing this issue. Have a rather small 4 node cluster and applications that need the token on startup to authenticate against Azure Blob Storage. Seeing about 10% of the `Cloud provider put` operations taking 37s and upwards. On a full stop-start of the deployments, there will be many pods that fail to start due to requests for the token taking too long.

**Comment by aramase** [comment]
@kwaazaar The support ticket is being actively looked at by the internal teams and the fix for identity assignment in `AvailabilitySets` is being rolled out. 

@franzoir @kagkarlsson Are you using VMSS/Availability Sets?

**Comment by kagkarlsson** [comment]
> @franzoir @kagkarlsson Are you using VMSS/Availability Sets?

Yes

**Comment by franzoir** [comment]
> @kwaazaar The support ticket is being actively looked at by the internal teams and the fix for identity assignment in `AvailabilitySets` is being rolled out.
> 
> @franzoir @kagkarlsson Are you using VMSS/Availability Sets?

In our case we're running with VM Availability Sets.

**Comment by chewong** [comment]
Fixed internally. Closing this issue for now but feel free to re-open if you are still experiencing this problem.
