### ISSUE TITLE
Server reported a conflict

### ISSUE THREAD

**Issue by kwaazaar** [Azure/aad-pod-identity#504]
**Describe the bug**
The longer I try to use AAD Pod Identity, the less it seems to work. I'm now seeing these MIC-related errors.

kubectl logs -l component=mic -n default
~~~
E0211 14:02:59.717474       1 crd.go:360] the server reported a conflict (post azureassignedidentities.aadpodidentity.k8s.io)
E0211 14:02:59.717597       1 mic.go:814] the server reported a conflict (post azureassignedidentities.aadpodidentity.k8s.io)
I0211 14:02:59.763439       1 cloudprovider.go:199] Updating user assigned MSIs on aks-agentpool-71662594-17
E0211 14:03:00.111814       1 crd.go:360] the server reported a conflict (post azureassignedidentities.aadpodidentity.k8s.io)
E0211 14:03:00.111867       1 mic.go:814] the server reported a conflict (post azureassignedidentities.aadpodidentity.k8s.io)
E0211 14:03:00.433394       1 crd.go:360] the server reported a conflict (post azureassignedidentities.aadpodidentity.k8s.io)
E0211 14:03:00.433446       1 mic.go:814] the server reported a conflict (post azureassignedidentities.aadpodidentity.k8s.io)
E0211 14:03:00.517374       1 crd.go:360] the server reported a conflict (post azureassignedidentities.aadpodidentity.k8s.io)
E0211 14:03:00.517428       1 mic.go:814] the server reported a conflict (post azureassignedidentities.aadpodidentity.k8s.io)
I0211 14:03:00.554095       1 cloudprovider.go:199] Updating user assigned MSIs on aks-agentpool-71662594-9
E0205 13:23:57.339073       1 leaderelection.go:224] error retrieving resource lock default/aad-pod-identity-mic: Get https://aahnl-kubernetes-ot-78c6386c.hcp.westeurope.azmk8s.io:443/api/v1/namespaces/default/endpoints/aad-pod-identity-mic: EOF
E0205 13:24:13.536585       1 leaderelection.go:224] error retrieving resource lock default/aad-pod-identity-mic: Get https://aahnl-kubernetes-ot-78c6386c.hcp.westeurope.azmk8s.io:443/api/v1/namespaces/default/endpoints/aad-pod-identity-mic: net/http: TLS handshake timeout
~~~

Not sure if related, but this is what the nmi logs state:
~~~
time="2020-02-11T13:23:39Z" level=info msg="Status (403) took 80004975621 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.234.22.215
time="2020-02-11T13:38:14Z" level=warning msg="parameter resource cannot be empty" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.234.22.147
time="2020-02-11T13:38:14Z" level=info msg="Status (400) took 64700 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.234.22.147
time="2020-02-11T13:39:34Z" level=error msg="no AzureAssignedIdentity found for pod:development/appauthtest-cronjob-1581428100-762tj in assigned state, getting assigned identities for pod development/appauthtest-cronjob-1581428100-762tj in CREATED state failed after 16 attempts, retry duration [5]s. Error: <nil>" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.234.22.147
time="2020-02-11T13:39:34Z" level=info msg="Status (403) took 80004490000 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.234.22.147
~~~

**Steps To Reproduce**
?

**Expected behavior**
No errors or more clear errors.

**AAD Pod Identity version**
Latest

**Kubernetes version**
1.14.8

**Additional context**
-

**Comment by aramase** [comment]
@kwaazaar Sorry, you are having issues using pod-identity. Can you help us understand your cluster configuration a little better?

1. How many VMSS node pools in the cluster? How many nodes per VMSS?
2. How many pods are using pod-identity?
3. How many identities are being configured?

The error in NMI indicates no `AzureAssignedIdentity` has been found for the cron job requesting the token. Just to give you a little context - MIC sees the pod/jobs that come in with the `aadpodidbinding` label. Based on the label it gets the associated identity and then assigns the identity to the node. Once the identity is successfully assigned to the node the `AzureAssignedIdentity` is created with the pod name and identity and set to `ASSIGNED` state. NMI looks for this assigned identity to validate the pod requesting the token is in fact allowed to access the identity. 

I see you already an opened an issue for delays in identity assignment - https://github.com/Azure/aad-pod-identity/issues/503 which is the reason NMI is unable to find the `AzureAssignedIdentity`. The delays in identity assignment will need to be investigated by the VMSS team and hopefully they can help with the support ticket. 

For the errors in MIC, they should be transient errors. Around the time you see this error, do you see any high load on the API server? Also these errors should resolve eventually and not show up. Do you see it happen frequently?

**Comment by aramase** [comment]
@kwaazaar Checking in to see if you are still having these issues? If you are still having issues, can you help answer the question and steps to repro?
