### ISSUE TITLE
Question: How to assign user assigned managed identity to Azure Application

### ISSUE THREAD

**Issue by vtiwari227** [Azure/aad-pod-identity#505]
Hi everyone,
We have a App(dummyApplication) registered with Azure and dummyApplication have graph API access. which I can access using ClientID and Secret for given dummyApplication.

Now i want to use azure pod identity for this application pod in AKS cluster. I can create explicit identity (dummyIdentity) and that will help me get Azure AD token for given dummyApplication identity.

Now i need to manage two things, One identity(dummyIdentity) to get Azure AD token and one Client Credentials to access graph API from within pod. Can we create azure identity based on azure application or accessing graph API using user assigned identity.

Thanks

**Comment by aramase** [comment]
@vtiwari227 I'm not completely sure how to achieve that but a google search for this yields a lot of good results. Saw this one thread which talks about it - https://social.msdn.microsoft.com/Forums/en-US/dae34534-f193-4444-b52e-ba9cfa4a1fda/does-azure-msi-support-accessing-graph-api?forum=WindowsAzureAD

Please take a look. 

Closing this issue. Please feel free to reopen if you have any more questions.
