### ISSUE TITLE
Including helm chart version in labels causes selector "immutable" error

### ISSUE THREAD

**Issue by devlinmr** [Azure/aad-pod-identity#507]
**Describe the bug**
Upgrading helm chart fails with the following error:

```
for: "STDIN": DaemonSet.apps "aad-pod-identity-nmi" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"nmi", "app.kubernetes.io/instance":"aad-pod-identity", "app.kubernetes.io/name":"aad-pod-identity"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

**Steps To Reproduce**
Install chart aad-pod-identity-1.5.5
Bump Chart.Version
install new version

**Expected behavior**
The chart applies normally

**AAD Pod Identity version**
1.5.5

**Kubernetes version**
v1.15.7

**Additional context**
This seems related to the following change in Kubernetes: https://github.com/kubernetes/kubernetes/issues/50808

The spec.selector fields are immutable in Kubernetes versions after this was introduced.

The chart includes the standard labels template in the selector, e.g. aad-pod-identity/templates/nmi-daemonset.yaml includes:

```
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: nmi
      {{- include "aad-pod-identity.labels" . | nindent 6 }}
```
But as this includes the chart version upgrades will fail to apply:
```
{{/*
Common labels.
*/}}
{{- define "aad-pod-identity.labels" -}}
app.kubernetes.io/name: {{ template "aad-pod-identity.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
helm.sh/chart: {{ template "aad-pod-identity.chart" . }}
{{- end -}}
```
Either removing the version from the standard labels or using something else for the selector should rectify the problem. I'm happy to do a PR for this if you let me know which option you would prefer.

Thanks!

**Comment by aramase** [comment]
@devlinmr There is a good suggestion in this issue for how we can get around this - https://github.com/Azure/aad-pod-identity/issues/502#issue-562522359. I was able to test this change. I would be happy to review and merge the PR if you are interested in opening one with the change.

**Comment by devlinmr** [comment]
Thanks @aramase I've prepared a branch https://github.com/devlinmr/aad-pod-identity/tree/add-label-selector but every time I try and raise a PR I get a 500.
