### ISSUE TITLE
MIC compute.VirtualMachineScaleSetsClient#CreateOrUpdate LinkedAuthorizationFailed when AKS node-pool uses a subnet from another resource group

### ISSUE THREAD

**Issue by thomas-riccardi** [Azure/aad-pod-identity#511]
**Describe the bug**
When creating a Pod bound to an AzureIdentity, it fails to get properly bound:
- context: trying to setup [AGIC](https://github.com/Azure/application-gateway-kubernetes-ingress), their pod crashloops
- NMI logs:
```
time="2020-02-17T17:45:43Z" level=info msg="Status (404) took 58991319480 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.32.64.23
time="2020-02-17T17:52:03Z" level=error msg="no AzureAssignedIdentity found for pod:kube-system/ingress-azure-db7567987-h78kj in assigned state, context canceled" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=10.32.64.23
```
(in loop)
- MIC logs:
```
I0218 16:19:22.150384       1 mic.go:787] Processing node aks-default-35064155-vmss, add [1], del [0]
I0218 16:19:22.150414       1 crd.go:341] Got assigned id ingress-azure-db7567987-nwzw9-kube-system-ingress-azure to assign
I0218 16:19:22.659039       1 cloudprovider.go:199] Updating user assigned MSIs on aks-default-35064155-vmss
E0218 16:19:22.675387       1 vmss.go:75] compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client 'bbaf8a4c-5733-466a-8f4f-51176b8daab7' with object id 'bbaf8a4c-5733-466a-8f4f-51176b8daab7' has permission to perform action 'Microsoft.Compute/virtualMachineScaleSets/write' on scope '/subscriptions/18b4440b-760f-4fad-9042-4bf6ed286639/resourceGroups/MC_rg-app-dev_aksdeepomatic_westeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aks-default-35064155-vmss'; however, it does not have permission to perform action 'Microsoft.Network/virtualNetworks/subnets/join/action' on the linked scope(s) '/subscriptions/18b4440b-760f-4fad-9042-4bf6ed286639/resourceGroups/rg-network/providers/Microsoft.Network/virtualNetworks/az-vnet-app-dev/subnets/azsubnet-aks-dev' or the linked scope(s) are invalid."
E0218 16:19:22.675434       1 mic.go:831] Updating msis on node aks-default-35064155-vmss, add [1], del [0] failed with error compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client 'bbaf8a4c-5733-466a-8f4f-51176b8daab7' with object id 'bbaf8a4c-5733-466a-8f4f-51176b8daab7' has permission to perform action 'Microsoft.Compute/virtualMachineScaleSets/write' on scope '/subscriptions/18b4440b-760f-4fad-9042-4bf6ed286639/resourceGroups/MC_rg-app-dev_aksdeepomatic_westeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aks-default-35064155-vmss'; however, it does not have permission to perform action 'Microsoft.Network/virtualNetworks/subnets/join/action' on the linked scope(s) '/subscriptions/18b4440b-760f-4fad-9042-4bf6ed286639/resourceGroups/rg-network/providers/Microsoft.Network/virtualNetworks/az-vnet-app-dev/subnets/azsubnet-aks-dev' or the linked scope(s) are invalid."
```

I could not find anywhere in the documentation what where all the permissions needed by aad-pod-identity (using the AKS Service Principal).
Only optional permission documented: https://github.com/Azure/aad-pod-identity#6-set-permissions-for-mic where "Managed Identity Contributor" is needed (by the AKS SP) over the Managed Identity if it's not created in the AKS own Resource Group.

To avoid this I did create the Identity in the AKS RG.

I seems the SP also needs "Network Contributor" over all the Virtual Networks containing subnets used on all the AKS node-pools.
Maybe usually the AKS node-pools use a AKS-created Virtual Network (in the AKS RG) and the permissions are already OK (because the AKS SP is Contributor on the AKS RG); but in my case we forced the use of a Virtual Network Subnet coming from another Resource Group (`az-vnet-app-dev` in the logs).

**Steps To Reproduce**
- create RG A
- create Virtual Network and subnet in RG A
- create an AKS cluster with node-pools using subnet in RG A
- install aad-pod-identity in the cluster
- use it

**Expected behavior**
aad-pod-identity should work.

It seems it needs more permissions than documented:
- document all required permissions

Also, I could not get a verbose log of the request that failed, only it's error message; even with `--v=20`; maybe it could have helped me understand the issue faster.

**AAD Pod Identity version**
1.5.5
**Kubernetes version**
1.15.7
**Additional context**

The fix for me was to give `Network Contributor` role to the AKS SP on the external (`az-vnet-app-dev`) RG, but it's probably too generous: aad-pod-identity should not be able to delete the whole network for example.

**Comment by kkmsft** [comment]
The SP from AKS will need those permission for other operations such as disk attach and load balancer backend pool addition - https://docs.microsoft.com/en-us/azure/aks/kubernetes-service-principal#networking. Were you facing the same issue with any of those operations before setting those permissions ?

**Comment by thomas-riccardi** [comment]
@kkmsft I didn't fully read that page indeed, thanks for the reminder.

That being said, when I created the AKS cluster I did *not* give any Network permission on my external virtual network (in another RG), and everything seemed to work: nodes and pods had network access it seemed.
Only with aad-pod-identity did I need it.

**Comment by elsesiy** [comment]
I can confirm what @thomas-riccardi said, I'm running into the exact same issue and only after assigning "Network Contributor" on the vnet resource group it works

**Comment by asubmani** [comment]
I ran into this issue.  Here are the exact permissions required:

1) "Network Contributor" or custom role on the subnet (not needed at VNET level if the VNET has other subnets) . Custom role is documented here  https://docs.microsoft.com/en-us/azure/aks/kubernetes-service-principal#networking. 
2) The SPN of the AKS cluster (or MSI) needs to have "Managed Identity Operator" role on all of the aad  identities you plan to use for aadpodidentity.. i.e. any resourceid in the kubernetes custom resource "AzureIdentity". If you create your userAssignedManagedIdentities for aadpodidentites in the aks resource group, then grant this role access at the resource group level.
3) I had to restart the `mic` deployment by deleting on of the pods.  you cluld also do
`kubectl rollout restart deployment mic`

**Comment by jldeen** [comment]
I can confirm I am seeing this issue as well - clean cluster, I have assigned both "Managed Identity Operator" and "Network Contributor" as suggested (and as suggested [here](https://github.com/Azure/aad-pod-identity#6-set-permissions-for-mic) and I can't seem to work around it. FWIW, this appears relatively new as I just set this up without issue on a different cluster about a month ago.
