### ISSUE TITLE
Pod Identity Components don't seem to need Operator permissions

### ISSUE THREAD

**Issue by rnettleton** [Azure/aad-pod-identity#512]
**Describe the bug**
I've recently started working with "aad-pod-identity", in order to properly map a managed identity with some pods in my AKS cluster that handle logging. 

I've been using the following online documentation as a starting point: 

https://github.com/Azure/aad-pod-identity#getting-started

I've followed the "Getting Started" guide, and have been able to get some initial deployments working without any errors.  That being said, I've run into a problem with Step 6 of the "Getting Started" guide.  

Some details:

1. I'm using Helm to install the "aad-pod-identity" components, using the Helm charts found at : 

https://github.com/Azure/aad-pod-identity/tree/master/charts

2. I'm using the Helm chart for v1.5.5 of "aad-pod-identity"

3. Using the provided template properties, I add an "AzureIdentity" and "AzureIdentityBinding" that map to the managed identity I need to work with.  

While I was able to get a basic deployment working with the Helm Charts for "aad-pod-identity", I did run into one issue that may or may not be a real problem:

While I used the "**Getting Started**" guide as documentation to setup my cluster, I noticed that Step 6 "Set Permissions for MIC" (https://github.com/Azure/aad-pod-identity#6-set-permissions-for-mic) does not appear to be required in order to get things working.  

This seemed strange to me, as I would have expected the deployments to fail if these permissions were not in place.  I verified that the managed identity in question is in fact a "User assigned managed identity", and that the managed identity is not within the same resource group as the Kubernetes cluster.  

Are there any configuration options I might be missing that might be causing this? Are the Helm charts provided in https://github.com/Azure/aad-pod-identity setting some permissions-specific configuration in this area?

If it sounds like aad-pod-identity is working as expected in this case, could someone provide some pointers regarding how my cluster needs to be configured properly?  

**Steps To Reproduce**
Run the steps in the "Getting Started" guide, but skip Step 6.  Deploy a cluster. 

**Expected behavior**
Based on the aad-pod-identity documentation, I would have expected the deployment to fail if the proper permissions were not set on the K8S operators.  

**AAD Pod Identity version**
1.5.5

**Kubernetes version**
1.13.11

**Additional context**

**Comment by jayush** [comment]
Any updates on this?

**Comment by kkmsft** [comment]
@jayush @rnettleton - What is the scope and role of the service principal used to create the cluster - Does it have subscription wide scope or resource group level scope ?

**Comment by aramase** [comment]
@jayush Did you get a chance to look at the above question?

**Comment by rnettleton** [comment]
@kkmsft , @aramase , Thanks for the replies on this issue. 

We're using the ClientID of the subscription used in order to create the AKS cluster.  

Does this mean that the service principal for this cluster would have subscription-wide scope?  It seems like that would be the case, but I wanted to double-check. 

If the service principal we use to create an AKS cluster has subscription-level scope, does this mean that the steps documented in "Set Permissions for MIC" are not required?  

Thanks!

**Comment by aramase** [comment]
@rnettleton If the service principal has subscription level scope, then the write permission to VM/VMSS need not be explicitly set as its inherited from the subscription level permissions.

**Comment by aramase** [comment]
@rnettleton Closing this issue. Please feel free to reopen if you have any more questions.

**Comment by rnettleton** [comment]
Great.  Thanks @aramase for clarifying this!
