### ISSUE TITLE
Is it possible ? Multiple pod identities in same cluster

### ISSUE THREAD

**Issue by Roy-Barkay** [Azure/aad-pod-identity#513]
**Describe the bug**
Can I use multiple identeties in the same cluster?
for different pods 
**Steps To Reproduce**

**Expected behavior**

**AAD Pod Identity version**

**Kubernetes version**

**Additional context**

**Comment by aramase** [comment]
@Roy-Barkay Yes, it's possible to use multiple identities in the same cluster. An `AzureIdentity` and will need to be created for each identity that needs to be used. An `AzureIdentityBinding` needs to be created for every pod that'll consume the identity or all the pods could use the same label for the identity.

**Comment by kkmsft** [comment]
@Roy-Barkay : The comment above specifies how to use multiple identities. Closing this issue. Please free to re-open if you have any more questions.
