### ISSUE TITLE
Deny requests without metadata header to IMDS 

### ISSUE THREAD

**Issue by hellokangning** [Azure/aad-pod-identity#514]
**Describe the request**

When you query the Instance Metadata Service, you must provide the header `Metadata: true` to ensure the request was not unintentionally redirected. Your can see examples of this header in the [Azure documentation](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/instance-metadata-service#using-headers).

**Explain why AAD Pod Identity needs it**

While Pod Identity fills the metadata header by default, it's against the purpose why this header is applied.

This is critical especially when you [acquire an access token](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-http) as a mitigation againt Server Side Request Forgery (SSRF) attack.

**Describe the solution you'd like**

Introduce a feature flag to deny requests without metadata header for compability

**Comment by aramase** [comment]
closed with https://github.com/Azure/aad-pod-identity/pull/500
