### ISSUE TITLE
Plans for GA

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/aad-pod-identity#524]
**Describe the request**
As far as I know, AAD Pod Identity is still in preview.

Are there any plans for making this GA and incorporated with AKS?

**Comment by kkmsft** [comment]
@sauryadas will be able to answer the AKS+aad-pod-identity time frame.

**Comment by sauryadas** [comment]
end of may possibly ... 

keep any eye on

https://github.com/Azure/AKS/issues/1480

**Comment by aramase** [comment]
Closing this issue. Please follow https://github.com/Azure/AKS/issues/1480 for updates.
