### ISSUE TITLE
Documentation for provisioning POD identity for mulit namespace

### ISSUE THREAD

**Issue by dewanymca** [Azure/aad-pod-identity#528]
We have started using pod idenity for enabling MSI for key vault integration. It works great with default namespace. As we will be having multi namespace per team/microservice so we are looking for topology/steps to enable it. 

POD Identity has different resource some are cluster level and other are namespace level. So we are not sure what it takes to enable different POD identity to different namespace in terms of deployment.

Any documentation toward this will help. else it will be hit and trial method.

Thanks

**Comment by aramase** [comment]
@dewanymca pod-identity can be run in force namespaced mode - https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.namespaced.md

When run in force namespaced mode, the `AzureIdentity`, `AzureIdentityBinding` and pods only in the same namespace will be matched.

**Comment by aramase** [comment]
@dewanymca Hope this answers your question. Closing this issue, Please feel free to reopen if you have any further questions.
