### ISSUE TITLE
Failed to list v1.AzureIdentity ... unexpected character

### ISSUE THREAD

**Issue by jakubneubauer** [Azure/aad-pod-identity#529]
**Describe the bug**
My pod cannot use the created AzureIdentity. From container shell:
```
$ curl -i 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fservicebus.azure.net%2F'

HTTP/1.1 403 Forbidden
Content-Type: text/plain; charset=utf-8
X-Content-Type-Options: nosniff
Date: Mon, 16 Mar 2020 08:56:06 GMT
Content-Length: 111

no AzureAssignedIdentity found for pod:jakub-bob-xk6qi3f4/bob-core-cj58p9uy-6fc668fd7b-5dsn6 in assigned state

```

MIC log:
```
E0316 08:29:59.694444       1 reflector.go:205] pkg/mod/k8s.io/client-go@v0.0.0-20180424211516-33f2870a2b83/tools/cache/reflector.go:99: Failed to list *v1.AzureIdentity: v1.AzureIdentityList.Items: v1.AzureIdentity: v1.AzureIdentity.Spec: v1.AzureIdentitySpec.Type: readUint64: unexpected character: �, error found in #10 byte of ...|","type":"0"}},{"api|..., bigger context ...|rAssignedIdentities/bob-identityba2b035b","type":"0"}},{"apiVersion":"aadpodidentity.k8s.io/v1","kin|...
```
NMI log contains:
```
no AzureAssignedIdentity found for pod:xxx in assigned state, getting assigned identities for pod xxx in CREATED state failed after 16 attempts, retry duration
```

**Steps To Reproduce**

**Expected behavior**

**AAD Pod Identity version**
mcr.microsoft.com/k8s/aad-pod-identity/nmi:1.5.5
mcr.microsoft.com/k8s/aad-pod-identity/mic:1.5.5

**Kubernetes version**

Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-12T13:43:46Z", GoVersion:"go1.13.7", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.12", GitCommit:"524c3a1238422529d62f8e49506df658fa9c8b8c", GitTreeState:"clean", BuildDate:"2019-11-14T05:26:24Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**

**Comment by aramase** [comment]
@jakubneubauer The`type`field in AzureIdentitySpec needs to be an integer. The error above seems to indicate the value is wrapped in quotes which is causing the failure. Can you remove the quotes and try again? (https://github.com/Azure/aad-pod-identity/blob/master/deploy/demo/aadpodidentity.yaml#L6)

**Comment by aramase** [comment]
@jakubneubauer If the issue still persists after trying the above [steps](https://github.com/Azure/aad-pod-identity/issues/529#issuecomment-599624989), Please reopen the issue.
