### ISSUE TITLE
README.msi.md should call out min-access permissions instead of full Contributor

### ISSUE THREAD

**Issue by DrEsteban** [Azure/aad-pod-identity#534]
**Describe the request**
The [README.msi.md](https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.msi.md) document explains that you need to assign full Contributor access to the user-assigned identity for the MC_ resource group.  This allows much more capability than is required, and I suspect it was documented this way more as a convenience.

**Explain why AAD Pod Identity needs it**
To promote good security hygiene for aad-pod-identity users! :)

**Describe the solution you'd like**
Update the document to explain min-access requirements are: "Virtual Machine Contributor" and "Managed Identity Operator" on the MC_ resource group.  (Determined by myself with some trial and error)

**Describe alternatives you've considered**

**Additional context**

**Comment by aramase** [comment]
@DrEsteban Thank you for opening the issue! Would you be interested in opening a PR to update the doc?

**Comment by DrEsteban** [comment]
@aramase Sure thing! PR submitted: #536
