### ISSUE TITLE
please update documentation to state if service its GA or PREVIEW.

### ISSUE THREAD

**Issue by porrascarlos802018** [Azure/aad-pod-identity#541]
**Describe the bug**
please update documentation to state if service its GA or PREVIEW.
**Steps To Reproduce**

**Expected behavior**
please update documentation to state if service its GA or PREVIEW.
**AAD Pod Identity version**

**Kubernetes version**

**Additional context**

**Comment by aramase** [comment]
@porrascarlos802018 Here is a list of projects along with the state - https://github.com/Azure/container-compute-upstream/blob/master/README.md#project-list

You can track the preview status at https://github.com/Azure/AKS/issues/1480
