### ISSUE TITLE
aadpodidbinding for batch/job

### ISSUE THREAD

**Issue by biqas** [Azure/aad-pod-identity#542]
aadpodidbinding is right now not working for kind jobs.

jobs/batch should be treated like deployments, I do not see any reason why job should not also have such abilities to inject secretes.

**Comment by mo-saeed** [comment]
Hello, is there any solution for this ?

**Comment by chewong** [comment]
@mo-saeed you could see https://github.com/Azure/aad-pod-identity/issues/722#issuecomment-667243590 on how to set up pod identity for (Cron)Jobs.
