### ISSUE TITLE
MIC applying binding using indentity already deleted

### ISSUE THREAD

**Issue by danalex07** [Azure/aad-pod-identity#544]
**Describe the bug**
Looking at the logs of the MIC some bindings failed to apply due to the component trying to perform some actions on a component already deleted

**Steps To Reproduce**
Create Identity, AzureIdentity, AzureIdentityBinding and Policies on KV for service then delete the Identity, and then the Resources on AKS

**Expected behavior**
Remove these old entries, and work with the ones created

**AAD Pod Identity version**
1.5.5

**Kubernetes version**
1.14.8

**Additional context**
err log:

E0328 19:47:07.495023       1 mic.go:848] Applying binding azty-eus2-prub-bonos-s-gl-k-gl-azidentity-binding node aks-nodepool1-86996898-vmss000000 for pod documents-d695586fc-9jtmx-bonos-azty-eus2-prub-bonos-s-gl-k-gl resulted in error compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client 'e4578661-89c9-4365-9dca-03fc30f43c20' with object id 'e4578661-89c9-4365-9dca-03fc30f43c20' has permission to perform action 'Microsoft.Compute/virtualMachineScaleSets/write' on scope '/subscriptions/424dlfb0-b988-48c0-9ca6-8367c50e4297/resourceGroups/rg-prub-aks-nodes-eastus2/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool1-86996898-vmss'; however, it does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action' on the linked scope(s) '/subscriptions/424dlfb0-b988-48c0-9ca6-8367c50e4297/resourcegroups/rg-prub-identities-eastus2/providers/Microsoft.ManagedIdentity/userAssignedIdentities/azty-eastus2-prub-motordereglasmdes,/subscriptions/424dlfb0-b988-48c0-9ca6-8367c50e4297/resourcegroups/rg-prub-identities-eastus2/providers/Microsoft.ManagedIdentity/userAssignedIdentities/azty-eastus2-prub-notificaciontokenupdatemdes,/subscriptions/424dlfb0-b988-48c0-9ca6-8367c50e4297/resourcegroups/rg-prub-identities-eastus2/providers/Microsoft.ManagedIdentity/userAssignedIdentities/azty-eastus2-prub-bonos-login' or the linked scope(s) are invalid."

* Manually deprovisioning the user assigned identity from the VMSS didn't resolved the issue.

**Comment by aramase** [comment]
@danalex07 With the current release, a `CreateOrUpdate` call is made on the VMSS to assign/remove the identity from the VMSS (get the current list, add/remove from the list and publish the entire list). This call errors out if the identity has been removed from azure but still exists on the cluster. If you delete the corresponding `AzureIdentity` and `AzureIdentityBinding` from the cluster, MIC should clean up the identities from the VMSS. MIC uses the `AzureIdentity` as reference for identities and doesn't lookup azure to check if the identity exists.

Have a question -
- When you mention delete the identity, do you mean deleting the identity object in azure? Do you remove the AzureIdentity for that identity from the cluster after? If so, do you see any error logs in MIC when it tries to clean up the identity?

Removing all the user assigned identities (`az vmss identity rm`) that are no longer present should resolve the issue.

We are moving to [PATCH update](https://github.com/Azure/aad-pod-identity/pull/522) in the next release which will ignore identities that no longer exist.

**Comment by danalex07** [comment]
> When you mention delete the identity, do you mean deleting the identity object in azure? Do you remove the AzureIdentity for that identity from the cluster after? If so, do you see any error logs in MIC when it tries to clean up the identity?

yes i deleted the Managed Identity on Azure and then i removed the AzureIndentity and AzureIdentityBinding fromthe cluster, and i haven't seen any logs with the MIC trying to clean this up, i even restarted and re-deployed the MIC again....


i don't know if maybe there is some place where this info is stored that way i can clean that and make a fresh deploy of the full addpodidentity solution.....

**Comment by aramase** [comment]
@danalex07 Was the namespace removed? MIC creates `AzureAssignedIdentity` custom resource to create a mapping for `AzureIdentity`, `AzureIdentityBinding` and pod. When any of the 3 resources are deleted, MIC will lookup the `AzureAssignedIdentity` and then clean up the associated identity from the vmss/vm. Deleting the namespace would delete the `AzureAssignedIdentity` which could mean MIC could no longer delete the required identity. 

MIC assigns the identity to the underlying vmss. You should be able to see all the identities in the vmss using `az vmss identity show -g <resource group> --name <vmss name>`. If any of the old identities exist, you can delete them by running `az vmss identity remove`.

Apart from `AzureAssignedIdentity` custom resource, MIC does not use anything else to maintain state.

**Comment by danalex07** [comment]
the namespace was not removed, i'm sure of that because that namespace is very important and can't be removed.

yes, I've found that some identities remain on the vmss after they were deleted so i deleted them manually, but the issue remains.

i wonder if this problem could lead to an `AzureAssignedIdentity` status `CREATED` because come logs related to a not assigned binding

> E0328 19:47:07.495242       1 mic.go:848] Applying binding azty-eus2-prub-bonos-s-gl-k-gl-azidentity-binding node aks-nodepool1-86996898-vmss000001 for pod reportscanales-678b6674c9-2mxqm-bonos-azty-eus2-prub-bonos-s-gl-k-gl resulted in error compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client 'e9678661-89c9-4365-9dca-03fc30f43c20' with object id 'e9678661-89c9-4365-9dca-03fc30f43c20' has permission to perform action 'Microsoft.Compute/virtualMachineScaleSets/write' on scope '/subscriptions/424fcfb0-b988-48c0-9ca6-8367c50e4297/resourceGroups/rg-prub-aks-nodes-eastus2/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool1-86996898-vmss'; however, it does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action' on the linked scope(s) '/subscriptions/424fcfb0-b988-48c0-9ca6-8367c50e4297/resourcegroups/rg-prub-identities-eastus2/providers/Microsoft.ManagedIdentity/userAssignedIdentities/azty-eastus2-prub-motordereglasmdes,/subscriptions/424fcfb0-b988-48c0-9ca6-8367c50e4297/resourcegroups/rg-prub-identities-eastus2/providers/Microsoft.ManagedIdentity/userAssignedIdentities/azty-eastus2-prub-notificaciontokenupdatemdes,/subscriptions/424fcfb0-b988-48c0-9ca6-8367c50e4297/resourcegroups/rg-prub-identities-eastus2/providers/Microsoft.ManagedIdentity/userAssignedIdentities/azty-eastus2-prub-bonos-login' or the linked scope(s) are invalid."

maybe i am wrong because the binding, in fact, is created so i don't know if this has anything to do with the change in status `CREATED` `ASSIGNED` `UNASSIGNED`

**Comment by aramase** [comment]
@danalex07 Are these the identities that need to be assigned? `/subscriptions/424fcfb0-b988-48c0-9ca6-8367c50e4297/resourcegroups/rg-prub-identities-eastus2/providers/Microsoft.ManagedIdentity/userAssignedIdentities/azty-eastus2-prub-motordereglasmdes,/subscriptions/424fcfb0-b988-48c0-9ca6-8367c50e4297/resourcegroups/rg-prub-identities-eastus2/providers/Microsoft.ManagedIdentity/userAssignedIdentities/azty-eastus2-prub-notificaciontokenupdatemdes` and `/subscriptions/424fcfb0-b988-48c0-9ca6-8367c50e4297/resourcegroups/rg-prub-identities-eastus2/providers/Microsoft.ManagedIdentity/userAssignedIdentities/azty-eastus2-prub-bonos-login`? Or these are the old identities? 

MIC creates `AzureAssignedIdentity` in CREATED state first. After successfully assigning the identity for the pod, it'll update the status of `AzureAssignedIdentity` to ASSIGNED. The status goes to UNASSIGNED after the identity has been successfully removed from the node.

**Comment by danalex07** [comment]
@aramase , thanks a lot for you help, this turned out to be some garbage left behind by some previous configurations, come identities deleted and roles left behind without proper assignment, after some auditing and loot of coffee i managed to make it work......Thanks
