### ISSUE TITLE
NMI Pods Showing Errors

### ISSUE THREAD

**Issue by kevingbb** [Azure/aad-pod-identity#553]
**Describe the bug**
I am using Cluster Managed Identities with AKS and after installing AAD Pod Identity I get errors in the NMI pods and I have not done anything yet.

**Steps To Reproduce**
1. Create new AKS Cluster versions 1.16.7 using Cluster Managed Identity (--enable-managed-identity on the az cli)
2. Use kubectl apply to install version 1.5.5 of AAD Pod Identity
3. Run kubectl logs on the nmi pods and see errors

**Expected behavior**
 I would not expect to see any errors as I have not done or applied anything yet.

**AAD Pod Identity version**
Version 1.5.5

**Kubernetes version**
Version 1.16.7

**Additional context**
Even though there were errors I proceeded to try it out and see, and following the MSI directions at https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.msi.md to set the appropriate permissions. After assigning a pod the appropriate label, the azureassignedidentity was created but the pod never starts up as the identity is not found and get bearer authorization failed in the MIC logs. And if the app is deleted the azureassignedidentities stick around and are not cleaned up.

Here is a dump from the MIC logs:
azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/SUBID/resourceGroups/MC_khaks-rg_khaks20200403_eastus/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool1-38406395-vmss?api-version=2018-04-01: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: no AzureAssignedIdentity found for pod:aadpodidentity/mic-769cc76787-g8nmb in assigned state
E0403 12:12:43.073481       1 mic.go:831] Updating msis on node aks-nodepool1-38406395-vmss, add [1], del [0] failed with error azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/SUBID/resourceGroups/MC_khaks-rg_khaks20200403_eastus/providers/Microsoft.Compute/virtualMachineScaleSets/aks-nodepool1-38406395-vmss?api-version=2018-04-01: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: no AzureAssignedIdentity found for pod:aadpodidentity/mic-769cc76787-g8nmb in assigned state

Here is a dump from the NMI logs:
time="2020-04-03T12:11:07Z" level=error msg="no AzureAssignedIdentity found for pod:kube-system/omsagent-dnbqv in assigned state, context canceled" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=100.64.1.15
time="2020-04-03T12:11:07Z" level=info msg="Status (404) took 60058433600 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=100.64.1.15
time="2020-04-03T12:11:41Z" level=warning msg="parameter resource cannot be empty" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=100.64.1.8
time="2020-04-03T12:11:41Z" level=info msg="Status (400) took 59500 ns" req.method=GET req.path=/metadata/identity/oauth2/token req.remote=100.64.1.8

**Comment by aramase** [comment]
@kevingbb when MIC pods land on the same node as the NMI pod, token request from MIC is also intercepted by NMI. 

You can create an AzurePodIdentityException to allow token requests from MIC to go directly to metadata service for fetching token instead of NMI validation.

```
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzurePodIdentityException
metadata:
  name: mic-exception
spec:
  PodLabels:
    app: mic
```

The docs for exception are here - https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.app-exception.md

I'll get this added by default in the next helm release so it doesn't need to be explicitly configured for MIC pods.

**Comment by aramase** [comment]
Please feel free to reopen the issue if you still getting errors after configuring `AzurePodIdentityException`.

**Comment by asubmani** [comment]
I am running into the same issue as @kevingbb 

aadpodIdentity version = 1.6.0
AKS = 1.16.7
VMMS/Cluster-Autoscaler enabled
```yaml
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzurePodIdentityException
metadata:
  name: mic-exception
  namespace: aadpodidentity
spec:
  PodLabels:
    app: mic
```
still getting 

```log
ization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/8cfbd600-1193-40e4-8a27-b4cf086c8675/resourceGroups/jb-aks-eus-dev-nodepool-rg/providers/Microsoft.Compute/virtualMachineScaleSets/aks-jbakspooldev-27686008-vmss?api-version=2019-07-01: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: getting assigned identities for pod aadpodidentity/mic-759d87c9bd-sxb6f in CREATED state failed after 16 attempts, retry duration [5]s. Error: <nil>
```

we have deployed aadpodidentity in its own namespace.
QuestionL: if we have our nginx ingress deployed in say "ingress" namespace, would we deploy the AzurePodIdrntityException CRD in the "Ingress" namespace?

If yes, then what about system pods like omsagent in kube-system?

**Comment by aramase** [comment]
@asubmani The exception needs to be in the same namespace as the pod. If pod-identity is deployed in different namespace, then you need to create the exception in that namespace.

**Comment by aramase** [comment]
When pod-identity is deployed on the cluster, the expectation is that all pods running on the cluster leveraging MSI will need to go through pod-identity. If you wish to bypass pod-identity validation for certain pods, then you need to create the `AzurePodIdentityException` in the namespace and add all the pod labels that you don't require pod-identity to validate.
