### ISSUE TITLE
Triggering identity assignment without creating a new azureidentity resource

### ISSUE THREAD

**Issue by auerl** [Azure/aad-pod-identity#554]
Dear all,

First of all, thanks much for this very useful application. We are using aad-pod-identity in the context of a [JupyterHub](https://jupyter.org/hub) kubernetes deployment, where we create a new Azure Resource Group for each user logging in. Using aad-pod-identity allows us to assign each users pod (running his Jupyter notebook server instance) a unique managed identity, associated with the user, who logs on via Single Sign on. We run a separate custom service, taking care of creating managed identities and resource groups. Everything works perfectly when a user first logs on. The managed identity is assigned to the jupyter-username pod (which has been labelled appropriately by our service) and inside of jupyter one can conveniently access the resource group.

**Describe the bug**
JupyterHub will shut down the pod, whenever a user has been inactive for a while. Now, what we observe is that when a user logs in for the **second time**, and the aadpodidentity and the aadpodidentitybinding resources already exist on the cluster, the jupyter pod, even though it is labelled correctly, would not be properly assigned with the managed identity (the association doesn't appear in the list of _azureassignedidentities_. Interestingly, this doesn't seem to happen always - sometimes all works as expected. The workaround is to delete the MIC pods, which causes the azureassignedidentity to be created properly.

**Steps To Reproduce**
I haven't managed to compile a minimal example of this issue, please let me know if the description above is not enough to understand the issue.

**Expected behavior**
I would have expect that the MIC will correctly assign the azure identity to the new jupyter-username pod, assuming that the creation of a new pod is a "relevant" (c.f. README.md) change which will trigger assignment of identities. 

**AAD Pod Identity version**
Commit 2933223

**Kubernetes version**
1.15.10

**Additional context**
n/a

Is there another way to trigger assignment of identities manually this or how would you suggest going about this, in general? Thanks much in advance for your help!

**Comment by aramase** [comment]
@auerl New pod creation should trigger MIC to assign the identity the underlying node. 

>  the jupyter pod, even though it is labelled correctly, would not be properly assigned with the managed identity (the association doesn't appear in the list of azureassignedidentities. Interestingly, this doesn't seem to happen always - sometimes all works as expected.

What do you see in the MIC logs at the time frame when there is no association? Is MIC in the process of assigning the identity?

**Comment by auerl** [comment]
@aramase 

```
I0406 17:50:05.077448       1 mic.go:787] Processing node aks-nodepool1-35675689-vmss, add [1], del [0]
I0406 17:50:05.077498       1 crd.go:341] Got assigned id jupyter-ludwig-20auer-default-ludwigaueridentity to assign
I0406 17:50:05.118057       1 cloudprovider.go:199] Updating user assigned MSIs on aks-nodepool1-35675689-vmss
I0406 17:50:53.054883       1 crd.go:539] Updating assigned identity default/jupyter-ludwig-20auer-default-ludwigaueridentity status to Assigned
I0406 17:50:53.065401       1 mic.go:367] Work done: true. Found 2 pods, 2 ids, 2 bindings
I0406 17:50:53.065557       1 mic.go:368] Total work cycles: 311, out of which work was done in: 7.
I0406 17:50:53.065667       1 stats.go:98] ** Stats collected **
I0406 17:50:53.065826       1 stats.go:81] Pod listing: 63.2µs
I0406 17:50:53.065990       1 stats.go:81] ID listing: 19.6µs
I0406 17:50:53.066057       1 stats.go:81] Binding listing: 14.6µs
I0406 17:50:53.066139       1 stats.go:81] Assigned ID listing: 4µs
I0406 17:50:53.066219       1 stats.go:81] System: 117.7µs
I0406 17:50:53.066283       1 stats.go:81] CacheSync: 0s
I0406 17:50:53.066335       1 stats.go:81] Cloud provider get: 27.687513ms
I0406 17:50:53.066401       1 stats.go:81] Cloud provider put: 47.936750286s
I0406 17:50:53.066455       1 stats.go:81] Assigned ID addition: 12.826552ms
I0406 17:50:53.066502       1 stats.go:81] Assigned ID deletion: 0s
I0406 17:50:53.066562       1 stats.go:88] Number of cloud provider PUT: 1
I0406 17:50:53.066569       1 stats.go:88] Number of cloud provider GET: 1
I0406 17:50:53.066575       1 stats.go:88] Number of assigned ids created in this sync cycle: 1
I0406 17:50:53.066580       1 stats.go:88] Number of assigned ids deleted in this sync cycle: 0
I0406 17:50:53.066585       1 stats.go:81] Find assigned ids to create: 8.9µs
I0406 17:50:53.066592       1 stats.go:81] Find assigned ids to delete: 3.6µs
I0406 17:50:53.066598       1 stats.go:81] Total time to assign or remove IDs: 47.987937995s
I0406 17:50:53.066604       1 stats.go:81] Event recording: 0s
I0406 17:50:53.066655       1 stats.go:81] Total: 47.988573797s
I0406 17:50:53.066687       1 stats.go:127] *********************
```
This is the MIC log from a successful association (unfortunately I wasn't able to reproduce the issue since this morning).  The only thing I see is that it takes quite a while to assign the identity. Is a duration of ~ 1 min to be expected, in your experience? Could this be related to issues / timeouts Azures side, perhaps due to increased traffic? I noticed other deployment issues, especially in the mornings, when using Azures westeurope region.

**Comment by aramase** [comment]
@auerl Identity assignment (PUT operation on azure) typically takes ~40-50s in case of VMSS. When a new pod is created, MIC will make a cloud operation PUT to assign the identity to the VMSS. Until the operation succeeds, the identity will not be available for use by the pod.

**Comment by auerl** [comment]
@aramase Thanks, good to know that this is normal behavior. I will keep on monitoring and post the logs when the issue recurs.

**Comment by auerl** [comment]
@aramase The issue recurred but there was no log output related to the pod for which identity assignment failed. Is it possible that state changes may be ignored by MIC in case it is currently handling the state changes related to another service (e.g. currently performing the PUT request to Azures API)? Asking because I think this may have been the case when it failed this time... still trying to find a way to reproduce the issue and will keep you posted.

**Comment by aramase** [comment]
@auerl If pod states change when MIC is in the middle of a PUT operation, then all those change events are queued. Once MIC finishes the current PUT, it'll batch process all the events that are in the queue. So you should see MIC processing the pod once the PUT operation is complete. If not, you can increase the log verbosity of MIC to `-v=5` and check the logs. Please share the logs here if you see any issues.

**Comment by auerl** [comment]
@aramase as I haven't observed the described behavior in a few weeks now, I would tend to blame the issue on the unusual amount of traffic in the Azure region I was using (also causing timeouts/issues in other applications), at the time I was reporting this.
