### ISSUE TITLE
Use pod identity across namespace

### ISSUE THREAD

**Issue by biswabandhu21** [Azure/aad-pod-identity#560]
Describe the request 
We have multiple application running in AKS with different namespace.  I wanted to have one MIC setup to attach identity to all the pods across the namespace. This will enable me to managed identity of all pods from single place.

Can we have identity defined with a custom namespace instead of default. If yes then what changes are required. I know it may be a silly query but I am very new to it. We thought of bringing all app in in a single namespace and define identity for that name space.

Can the scope tag be leveraged to do it ?

**Comment by aramase** [comment]
@biswabandhu21 This is what you are looking for - https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.namespaced.md

`AzureIdentity` and `AzureIdentityBinding` can be created in any namespace. By running pod-identity in force namespaced mode, you can ensure only the `AzureIdentity`, `AzureIdentityBinding` in the same namespace as the application pod will be matched.

**Comment by biswabandhu21** [comment]
Thanks @aramase

**Comment by smartaquarius10** [comment]
@aramase , Could you please share the updated link as this one is not working
 https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.namespaced.md

**Comment by aramase** [comment]
@smartaquarius10 I shared in the issue you opened: https://github.com/Azure/aad-pod-identity/issues/1004#issuecomment-800609000

Cross posting for future reference:
Please refer to https://azure.github.io/aad-pod-identity/docs/configure/match_pods_in_namespace/ for more details. All the markdown files have been moved to the docs site at https://azure.github.io/aad-pod-identity/docs
