### ISSUE TITLE
Helm Chart 404

### ISSUE THREAD

**Issue by ferantivero** [Azure/aad-pod-identity#562]
**Describe the bug**
trying to add to the repo the add-pod-identity chart I get a 404: https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts

**Steps To Reproduce**

**Expected behavior**

**AAD Pod Identity version**

**Kubernetes version**

**Additional context**

**Comment by aramase** [comment]
@ferantivero I just tried and was able to add successfully -

```
➜ helm repo add aad-pod-identity https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts
"aad-pod-identity" has been added to your repositories
```

this is my helm version -
```
➜ helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

**Comment by ferantivero** [comment]
thanks for quick turned around @aramse, bad copypasta on my end. Please let me close this
