### ISSUE TITLE
Unable to remove/delete nmi pods

### ISSUE THREAD

**Issue by biswabandhu21** [Azure/aad-pod-identity#563]
Hi

I have deleted the my MIC pod deployment and dont see it anymore on listing pods. But I still see the NMI pods. How can that be deleted.

What I am looking is completed remove the MIC & NMI and restart from blank page.

**Comment by aramase** [comment]
NMI runs as a daemonset on the cluster 

```
kubectl get ds
```

To delete the daemonset, run 

```
kubectl delete ds nmi
```

**Comment by Thaval** [comment]
This is not closed. When I delete the daemonset, it is re-created by the daemonset-controller.

**Comment by SidaliHami** [comment]
Hi ! 

I have the same problem as you @Thaval. I don't know why the nmi daemonset keeps popping when i'm trying to delete it.
I haven't enabled pod-identity explicitly for any of my workloads. I want to install aad-pod-identity in a Standard mode so I can handle my pod identities via **mic** which is not the case with the managed mode which requires to run "az aks pod-identity" OR to create azureidentity and azureidentitybinding and add manually the user identity in the VMSS which is not ideal. 

Any recommandations please ?

**Comment by SidaliHami** [comment]
Hey @Thaval, 
Thank you for your quick response.  This command worked for me : `az aks update -g $MY_RESOURCE_GROUP -n $MY_CLUSTER --disable-pod-identity`. It has to be one of our DevOps Engineers who's ran this command...
You really saved my life, i can know install aad-pod-identity on a standard mode. 
Thanks again !
