### ISSUE TITLE
Sample project to use identity to connect msql & keyvault in springboot

### ISSUE THREAD

**Issue by biswabandhu21** [Azure/aad-pod-identity#566]
I am able to setup identity for my pods. 

can someone redirect me to sample project where I can used the attached identiy to connect to mssql and keyvault. My project is in spring boot.

I dont want to use Flex Volumes as it is not approved by my security team.

**Comment by aristosvo** [comment]
https://aristosvo.github.io/posts/aks-with-msi-for-your-java-services/ contains an example for keyvault, but not for MS SQL. I'll probably extend it in the future with more Azure Services, but MS SQL is probably not among them, MySQL maybe.

**Comment by biswabandhu21** [comment]
@aristosvo : I saw the code but didnt get to understand much. It has only

 @Value("${your.property.name}")
    private String mySecretProperty;

Does it internally pick the secret and stores here based on the 

azure.keyvault.enabled=true
azure.keyvault.uri=${KEYVAULT_URI}

**Comment by biswabandhu21** [comment]
I was able to connect to DB using managed identity , so thanks again for your help
