### ISSUE TITLE
MSAL support?

### ISSUE THREAD

**Issue by involatile** [Azure/aad-pod-identity#570]
**Describe the request**
Is there any plan to use MSAL (instead of ADAL) for authentication?

**Explain why AAD Pod Identity needs it**
MSAL is the latest generation of authentication library that providers high reliability, which is critical for micro-services.

**Describe the solution you'd like**
Replace ADAL calls with MSAL calls. But, first we need a golang version of MSAL.

**Describe alternatives you've considered**
None.

**Additional context**
None

**Comment by aramase** [comment]
Issue to add support in azure-sdk-go - https://github.com/Azure/azure-sdk-for-go/issues/3148

**Comment by Alex-Bowman-Aw** [comment]
Looks like Microsoft are planning to retire support for ADAL and are recommending migration to MSAL

**Comment by aramase** [comment]
AADv2 (MSAL) lib out of Azure AD https://github.com/AzureAD/microsoft-authentication-library-for-go

**Comment by leonard520** [comment]
Any plan/roadmap for this enhancement as ADAL is going to be retired. Thanks a lot.

**Comment by aramase** [comment]
@leonard520 The library https://github.com/AzureAD/microsoft-authentication-library-for-go is not yet in public preview. We'll be able to adopt it and make changes once it's supported.

**Comment by xscript** [comment]
@aramase Any update about this issue?

**Comment by aramase** [comment]
> “Starting June 30th, 2020, we will no longer add new features to ADAL. We’ll continue adding critical security fixes to ADAL until June 30th, 2022. After this date, your apps using ADAL will continue to work, but we recommend upgrading to MSAL to take advantage of the latest features and to stay secure.” - source

We're actively working on the aad-pod-identity v2 solution that'll supersede this project. So we're not adding any new features currently. ADAL will continue to work after that date and we will have the v2 repository available by then.

**Comment by leonard520** [comment]
@aramase , may I know any update for this thread, like how the v2 solution is, and how is the migration path, eta, etc.? Thanks a lot!

**Comment by chewong** [comment]
[Azure Workload Identity](https://azure.github.io/azure-workload-identity), the next generation of AAD Pod Identity, is now available. Feel free to check it out.
