### ISSUE TITLE
Document issue during cluster auto scale event

### ISSUE THREAD

**Issue by aramase** [Azure/aad-pod-identity#573]
When a cluster is scaled up, there might be a scenario where the `kube-scheduler` schedules the workload pod before the NMI pod. In such scenario token request will be directly sent to IMDS instead of being intercepted by NMI. 

There is currently no solution in kubernetes where node can be set to `NoSchedule` until critical addons are deployed to the cluster. There is a KEP for this which is currently being reviewed - kubernetes/enhancements#1003

This needs to be documented so users of pod-identity are aware of this edge case

**Comment by galvesribeiro** [comment]
Hello @aramase. The PR you mentioned was merged. Do you think we still have the auto scale problem?

**Comment by aramase** [comment]
@galvesribeiro The PR I mentioned above was closed without being merged. There is still an ongoing discussion in the kubernetes community for supporting such scenarios to ensure critical addon pods are scheduled before application workload is scheduled on the node. This problem could still exist.
