### ISSUE TITLE
Helm chart link is returing 404: https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts 

### ISSUE THREAD

**Issue by jsangco** [Azure/aad-pod-identity#574]
The Helm chart link recommended in the [documentation ](https://github.com/Azure/aad-pod-identity/tree/master/charts/aad-pod-identity)is returning `404`.

This link:
https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts 

Is the documentation out of date or was it accidentally deleted?
Is there a different link I should be using as a workaround?

**Comment by aramase** [comment]
@jsangco I just tried helm repo add from the doc and it works. 

```
helm repo add aad-pod-identity https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts
```

The link is used to add to helm repo. Directly trying the url will give a 404.

**Comment by aramase** [comment]
@jsangco Closing this issue. Please feel free to reopen if you are still having any issues.
