### ISSUE TITLE
Change status code returned from NMI for errors

### ISSUE THREAD

**Issue by aramase** [Azure/aad-pod-identity#584]
When no `AzureAssignedIdentity` found, then NMI should return `HTTP 400` instead of `HTTP 403` - https://github.com/Azure/aad-pod-identity/blob/master/pkg/nmi/server/server.go#L520-L523 as that mimics the behavior from IMDS

**Comment by surenderssm** [comment]
@aramase - I would love to pick this up, please assign this to me !

**Comment by anshupitlia** [comment]
any update on this?

**Comment by aramase** [comment]
@surenderssm Would you be able to open a PR for this when you get a chance? We would like to include this in the release we plan to cut next week.

**Comment by chewong** [comment]
@anshupitlia @surenderssm since we are planning to cut release for 1.6.1 this week, I opened a PR to address this issue.

**Comment by surenderssm** [comment]
Thank you @chewong for picking this up.
