### ISSUE TITLE
Node taint clarification

### ISSUE THREAD

**Issue by ohorvath** [Azure/aad-pod-identity#591]
**Describe the request**
I've found a very weird behaviour when combining aad pod identity with multiple node pools and node taints. It seems if one of the node pools have a taint which prevents the daemon set to create NMI pods on the nodes, there is no error message at all in the MIC logs or daemonset logs or elsewhere (or I'm missing something). And as there is no NMI on the node, token requests will not be redirected and it's almost impossible to troubleshoot why you get error messages from the endpoint. 

**Explain why AAD Pod Identity needs it**

If you hit this issue, it's really painful to troubleshoot as token requests never reach the NMI/EMSI.

**Describe the solution you'd like**

It would be beneficial if the readme/documentation have a warning about what taints can cause. Also some kind of error message would be a good idea if any nodes missing the NMI but there are bindings on the pods for the particular node.

**Describe alternatives you've considered**

**Additional context**

**Comment by aramase** [comment]
[Taints and Tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) are properties of the pod spec and not specific to AAD Pod Identity. Nodes can be tainted with any label and if there are custom taints, the NMI daemonset can be configured to tolerate those taint with helm chart value. I don't think there is any error message pod identity can generate for this.

Closing this issue.
