### ISSUE TITLE
Releases contain incorrect deployment manifest

### ISSUE THREAD

**Issue by tshak** [Azure/aad-pod-identity#594]
Releases instruct users to use the `master` version of the deployment manifest, which does not contain the corresponding yaml or docker tags for the desired release.

## Repro 

0) Visit the release release: https://github.com/Azure/aad-pod-identity/releases/tag/v1.5.5
0) Inspect the yaml from the link in the release: https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml

## Expected
- That any referenced manifests use tested manifests at the the git release tag, not the `master` branch
- That the referenced manifests use the docker images that match the release

## Actual
- At the time of writing, the docker image tags are `v1.6.0`, and the manifests are from the `master` branch.

## Additional Info

Even if you link directly to the tag, the manifest is wrong: https://raw.githubusercontent.com/Azure/aad-pod-identity/v1.5.5/deploy/infra/deployment-rbac.yaml has docker tags: `v1.5.4`. 

It is customary for Kubernetes controllers to directly attach generated manifests as assets for each release. For example:

Knative Serving release: https://github.com/knative/serving/releases/tag/v0.11.2 has the following asset: https://github.com/knative/serving/releases/download/v0.11.2/serving.yaml

**Comment by aramase** [comment]
@tshak Thank you for opening this issue. 

> Even if you link directly to the tag, the manifest is wrong: https://raw.githubusercontent.com/Azure/aad-pod-identity/v1.5.5/deploy/infra/deployment-rbac.yaml has docker tags: v1.5.4.

I just verified. This seems to be an issue only with the `v1.5.5` tag. The rest of the tags have the matching docker image. 

> It is customary for Kubernetes controllers to directly attach generated manifests as assets for each release. For example:

Makes sense! We'll make sure to do this from the next release.

The master manifests are usually bumped when a new release is cut. We have users using the raw url of deployment manifest from master, so they always get the latest. This manifest is not bumped for rc images either.

**Comment by aramase** [comment]
Closing this issue with the new release - https://github.com/Azure/aad-pod-identity/releases/tag/v1.6.1. Please feel free open if there are any other issues.
