### ISSUE TITLE
Trigger MIC sync when a pod label changes

### ISSUE THREAD

**Issue by tkporter** [Azure/aad-pod-identity#603]
For reasons related to [this comment](https://github.com/Azure/aad-pod-identity/issues/237#issuecomment-611672987), we are changing the label of a pod its own `initContainer` so that different pods in a statefulset can have different identities. It seems like MIC does not detect this, and instead identities will be assigned only when the sync loop runs for some other reason. As a quick solution, I've changed the MIC `syncRetryDuration` to be `1m`.

I think in order to be more robust, `aad-pod-identity` should consider pod label changes. I did a quick scan of the code and I found https://github.com/Azure/aad-pod-identity/blob/83979a80ec17cb4da45a05fc73ecd56365828165/pkg/pod/pod.go#L54. I think there could be some logic in there to run the MIC sync loop if the label changed.

I'm not super confident in my decision to change `syncRetryDuration` to `1m` because the default is 60 minutes (wondering what the performance implications are?), so I think considering pod label changes would be a lot nicer.

I'm considering implementing this in a PR if it'd be welcomed :)

**Comment by chewong** [comment]
@tkporter would you like to open a PR for this feature?

**Comment by tkporter** [comment]
Sorry for the late reply, thanks for doing this :)
