### ISSUE TITLE
error in aks-engine and msi environment

### ISSUE THREAD

**Issue by vossss** [Azure/aad-pod-identity#608]
**Describe the bug**
failed to enable aad-pod-identity in aks-engine cluster which using msi.
**Steps To Reproduce**
Follow the URL below:
https://github.com/Azure/aad-pod-identity
**Expected behavior**
nmi log:
I0508 13:19:31.660294       1 standard.go:72] No clientID in request. demo/demo has been matched with azure identity demo/demo
I0508 13:19:31.660365       1 standard.go:165] matched identityType:0 clientid:1799##### REDACTED #####8c69 resource:https://management.azure.com/
E0508 13:19:31.743255       1 server.go:373] failed to get service principal token for pod: demo/demo, error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named https://management.azure.com/ was not found in the tenant named a12a82ff-eb68-4d6d-b3c7-c4fb2d2220e5. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: 54caaca3-1c6c-4568-aafb-670a06ed0c00\r\nCorrelation ID: 329c85f1-ed67-4f14-aee2-be5cf3dc624d\r\nTimestamp: 2020-05-08 13:19:31Z","error_codes":[500011],"timestamp":"2020-05-08 13:19:31Z","trace_id":"54caaca3-1c6c-4568-aafb-670a06ed0c00","correlation_id":"329c85f1-ed67-4f14-aee2-be5cf3dc624d","error_uri":"https://login.chinacloudapi.cn/error?code=500011"}
I0508 13:19:31.743316       1 server.go:190] Status (403) took 83039239 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.5.9

**AAD Pod Identity version**
1.6.0
**Kubernetes version**
1.15.11
**Additional context**
/etc/kubernetes/azure.json:
{
    "cloud":"AzureChinaCloud",
    "tenantId": "xxxxxxxxxxxxxxx",
    "subscriptionId": "xxxxx-xxxx-xxxx-xxx-xxx",
    "aadClientId": "msi",
    "aadClientSecret": "msi",
    "resourceGroup": "xxxxxxxxxxxxxxxxxxxx",
    "location": "chinanorth2",
    "vmType": "vmss",
    "subnetName": "xxxxxxxxxxxxxxx",
    "securityGroupName": "xxxxxxxxxxxx",
    "vnetName": "xxxxxxxxxxxx",
    "vnetResourceGroup": "rg-dp-connectivity-rehearsal",
    "routeTableName": "k8s-master-81692357-routetable",
    "primaryAvailabilitySetName": "",
    "primaryScaleSetName": "k8s-dpcon-81692357-vmss",
    "cloudProviderBackoffMode": "v2",
    "cloudProviderBackoff": true,
    "cloudProviderBackoffRetries": 6,
    "cloudProviderBackoffDuration": 5,
    "cloudProviderRatelimit": true,
    "cloudProviderRateLimitQPS": 10,
    "cloudProviderRateLimitBucket": 100,
    "cloudProviderRatelimitQPSWrite": 10,
    "cloudProviderRatelimitBucketWrite": 100,
    "useManagedIdentityExtension": true,
    "userAssignedIdentityID": "YYYYYYYYYYY-YYYY-YYYYYYYY-YYYYYY-YYYYYYYY",
    "useInstanceMetadata": true,
    "loadBalancerSku": "Standard",
    "disableOutboundSNAT": false,
    "excludeMasterFromStandardLB": true,
    "providerVaultName": "",
    "maximumLoadBalancerRuleCount": 250,
    "providerKeyName": "k8s",
    "providerKeyVersion": ""
}

**Comment by aramase** [comment]
> The resource principal named https://management.azure.com/ was not found in the tenant named a12a82ff-eb68-4d6d-b3c7-c4fb2d2220e5. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant

@vossss The resource for which the application is requesting for token doesn't belong to the tenant. For `AzureChinaCloud`, the resource manager url is `https://management.chinacloudapi.cn/` (ref: https://github.com/Azure/go-autorest/blob/master/autorest/azure/environments.go#L150). 

NMI gets the resource url from the token request. Can you please make the change in your application to request token from the correct resource url?

**Comment by vossss** [comment]
@aramase  Thanks for your reply. 
Can you provide a guide on how to make the change in our application to request token from the correct resource url?

**Comment by aramase** [comment]
@vossss In your application when you request for the token, you will need to configure the `AzureCloudEnvironment` to match the current env the cluster is running on.

**Comment by vossss** [comment]
@aramase thanks
I added the arg "--aad-resourcename=https://management.chinacloudapi.cn/" to the demo pod, and it works fine.

**Comment by aramase** [comment]
Thank you for confirming @vossss. Closing this issue as its resolved. Please feel free to reopen if you have any other issues.
