### ISSUE TITLE
Demo app fails with LinkedAuthorizationFailed

### ISSUE THREAD

**Issue by smuthusa** [Azure/aad-pod-identity#613]
**Describe the bug**
I just followed the procedure to deploy the demo app, but the following error was thrown
**Steps To Reproduce**
I just followed the steps specified in the README.
following roles are assigned to the identity
Owner, "Managed Identity Contributor"
**AAD Pod Identity version**
1.6.0
**Kubernetes version**
1.15.10
**Additional context**
E0513 08:41:20.308213       1 vmss.go:73] Failed to update VM with error compute.VirtualMachineScaleSetsClient#Update: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client 'xxxx-xxxx-xxxx-xxxx' with object id 'xxx-xxx-xxx-xxx' has permission to perform action 'Microsoft.Compute/virtualMachineScaleSets/write' on scope '/subscriptions/xxxx-xxxx-xxxx-xxxx/resourceGroups/MC_elephant_elephant_eastus/providers/Microsoft.Compute/virtualMachineScaleSets/aks-agentpool-88148177-vmss'; however, it does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action' on the linked scope(s) '/subscriptions/xxxx-xxxx-xxxx-xxxx/resourcegroups/elephant/providers/Microsoft.ManagedIdentity/userAssignedIdentities/elephant' or the linked scope(s) are invalid."
E0513 08:41:20.308271       1 mic.go:1047] Updating msis on node aks-agentpool-88148177-vmss, add [1], del [0] failed with error compute.VirtualMachineScaleSetsClient#Update: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client 'xxxx-xxxx-xxxx-xxxx' with object id 'xxxx-xxxx-xxxx-xxxx' has permission to perform action 'Microsoft.Compute/virtualMachineScaleSets/write' on scope '/subscriptions/xxxx-xxxx-xxxx-xxxx/resourceGroups/MC_elephant_elephant_eastus/providers/Microsoft.Compute/virtualMachineScaleSets/aks-agentpool-88148177-vmss'; however, it does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action' on the linked scope(s) '/subscriptions/xxxx-xxxx-xxxx-xxxx/resourcegroups/elephant/providers/Microsoft.ManagedIdentity/userAssignedIdentities/elephant' or the linked scope(s) are invalid."

**Comment by smuthusa** [comment]
I just noticed that the client id reported in the error message is different from the one I created manually(created as part of identity creation).

**Comment by aramase** [comment]
@smuthusa The error message contains the object id of the clientID. Looks like the SP/managed identity doesn't have the required permissions on `/subscriptions/xxxx-xxxx-xxxx-xxxx/resourcegroups/elephant/providers/Microsoft.ManagedIdentity/userAssignedIdentities/elephant'`. Please review this doc and assign all the required roles - https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.role-assignment.md

**Comment by chewong** [comment]
Please see @aramase for resolution. Feel free to re-open this issue if you are still experiencing any errors.
