### ISSUE TITLE
Managed AAD and aadpodidentity - any upcoming changes?

### ISSUE THREAD

**Issue by asubmani** [Azure/aad-pod-identity#614]
---
name: 💬 Question
about: "Managed AAD v2 for AKS compatibility with aadpodidentity
title: 'Would managed AAD (or AADv2) have any impact on aadpodidentity?'
labels: Question
---

We are planing to update our AKS clusters to use managed AAD plugins for AKS as described [here](https://docs.microsoft.com/en-us/azure/aks/managed-aad). 
We want to run exec probes authenticated by AAD in a container. Initially we thought we can leverage aadpodidentity to do this, but we may still need [kubelogin](https://github.com/Azure/kubelogin) to access kubectl logs.

Would upgrading to AKS Managed AAD have any impact on how we use aadpodidentity. We are using aadpoditentity version 1.6.0

---

If you have a support request or question please submit them to one of these resources:

**Comment by chewong** [comment]
Hi @asubmani, sorry for the late reply. As far as I can tell, I don't think managed AAD and aad-pod-identity interfere with each other. Feel free to open an issue at https://github.com/Azure/AKS/issues or here if you are experiencing any problems.
