### ISSUE TITLE
Deployment using Helm Chart

### ISSUE THREAD

**Issue by HoussemDellai** [Azure/aad-pod-identity#621]
**Describe the request**
In the readme file, we can deploy using the raw YAML file 

> kubectl apply -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml

But can we deploy also using Helm Chart ? i.e
```
$ helm repo add aad-pod-identity https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts
$ helm install aad-pod-identity/aad-pod-identity
```

**Comment by aramase** [comment]
@HoussemDellai You can deploying using helm chart. The instructions are provided here -https://github.com/Azure/aad-pod-identity/tree/master/charts/aad-pod-identity

**Comment by HoussemDellai** [comment]
Great !
I tested it and it worked for me.
Thanks @aramase 
BTW it should be mentioned in the main Readme!

**Comment by chewong** [comment]
Let me add it in https://github.com/Azure/aad-pod-identity/pull/620.
