### ISSUE TITLE
Connecting to a SQL Database hosted on a VM with "Integrated Security"

### ISSUE THREAD

**Issue by user11081980** [Azure/aad-pod-identity#628]
I have an AKS cluster with .NET Core micro-services running on Linux containers.
From one on my pods, I need to query a SQL database hosted on a VM running SQL Server. I need to connect using "Integrated Security", that is, without a username or password.

All the documentation I read online applies to using AAD pod identity with managed (PaaS) SQL databases. In my case, do I need to give the managed identity access to the VM, or/ and do I need to create a login in my SQL database?

**Comment by user11081980** [comment]
Luckily for me I didn't go this route. Great support Microsoft.

**Comment by aramase** [comment]
@user11081980 Sorry for the delay. I believe these 2 links provide details on how to use managed identity with the sql server - 

https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-connect-msi
https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/tutorial-windows-vm-access-sql

You would need to create a contained user as documented here with the User Assigned Identity that has permissions to the sql server.

```
Create a contained user in the database that represents the VM's system-assigned identity
```

MIC component of `aad-pod-identity` will assign the identity to the underlying node on which your application pod is running. When the pod makes a token request to use for querying the sql server, the NMI component of `aad-pod-identity` will ensure the pod has access to the identity it is requesting token for and will return the token. The pod then can consume the token to make the query.
