### ISSUE TITLE
Release 1.6.1 has been published as 2.0.0 on helm chart repo

### ISSUE THREAD

**Issue by arodriguezdlc** [Azure/aad-pod-identity#632]
**Describe the bug**
We can't install 1.6.1 AAD Pod Identity release via helm because it has been tagged as 2.0.0 on helm repo instead of 1.6.1. 

![image](https://user-images.githubusercontent.com/7372079/82798240-8aca4f80-9e78-11ea-88e0-08b25a2abec9.png)

**Steps To Reproduce**

**Expected behavior**
We expect to have on helm repository the release 1.6.1 instead of a 2.0.0 release. 

**AAD Pod Identity version**

**Kubernetes version**

**Additional context**

**Comment by BartVanBerkel** [comment]
It looks like it was on purpose, see #457 
https://github.com/Azure/aad-pod-identity/pull/457/files

**Comment by arodriguezdlc** [comment]
If there is a breaking change, AAD Pod Identity should have also version 2.0.0. As I understand, In this project the software release is the same that the helm chart release. Please let me know if this is incorrect.

**Comment by BartVanBerkel** [comment]
@arodriguezdlc I'm not 100% sure, but the version of the helm chart doesn't necessarily need to follow the appVersion.

**Comment by aramase** [comment]
@arodriguezdlc This is a backward incompatible change only in the helm charts and not in aad-pod-identity. When helm charts were packaged for aad-pod-identity the first time, the chart version and appVersion were the same versions. But when there is a chart only change, only the chart version is bumped.

**Comment by arodriguezdlc** [comment]
Ok, thank you for the explanation. I was confused because versioning was coupled until now.
