### ISSUE TITLE
AAD Pod identity deletes Application Security Groups from VMSS

### ISSUE THREAD

**Issue by tiurikov** [Azure/aad-pod-identity#635]
**Describe the bug**
I found that AAD Pod identity for some reason deletes Application Security Groups from VMSSs.
It happens once a managed identity assigned to a VMSS bu AAD Pod Identity. On Azure portal in the Activity Log of the VMSS I can see that a user assigned to AAD Pod Identity service removes ASGs. It looks like a bug to me.

**Steps To Reproduce**
You need a K8s cluster which run worker nodes with VMSSs. VMSS need to have some ASG assigned to the NICs. Deploy AAD Pod Identity and let it assign an Identity to the VMSS instance. Then check Activity Logs to see the deletion operation..

**Expected behavior**
AAD Pod Identity must not touch VMSS ASGs, that may break communications of worker nodes in a cluster.

**AAD Pod Identity version**
mcr.microsoft.com/k8s/aad-pod-identity/mic:1.5.5

**Kubernetes version**
v1.15.12

**Additional context**

Could you please clarify is this a bug or a known behavior? Should I updated to more recent version of AAD Pod Identity to fix it?

**Comment by aramase** [comment]
@tiurikov `1.5.5` uses `CreateOrUpdate` API for assigning the identities. This means it would get the VMSS, add the identities to the VMSS and then update the entire VMSS. However it does not touch any other field in the VMSS. Was the ASG added at the same time aad-pod-identity was assigning the identity to VMSS?

The latest version of aad-pod-identity `1.6.1` switch to using a PATCH update model for only patching the identities in the VMSS. This will ensure pod-identity will only update the identities and not affect any other VMSS Spec.  Can you please try out the latest version? Carefully review this doc for breaking change in 1.6.x before trying out - https://github.com/Azure/aad-pod-identity#v160-breaking-change

**Comment by tiurikov** [comment]
> Was the ASG added at the same time aad-pod-identity was assigning the identity to VMSS?

right, it was a single Ks cluster provisioning process with multiple addons on top including aad-pod-identity and some other component which use it.

Looks like 1.6.1 fixes the problem. Thanks!
