### ISSUE TITLE
MIC unable to properly make use of the managed identity

### ISSUE THREAD

**Issue by stephaneey** [Azure/aad-pod-identity#636]
**Describe the bug**
Going through all the steps explained in the readme leads to the following:
`E0602 18:56:59.028550       1 vm.go:115] Failed to update VM with error compute.VirtualMachinesClient#Update: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client 'xxx' with object id 'xxx' has permission to perform action 'Microsoft.Compute/virtualMachines/write' on scope '/subscriptions/xxx/resourceGroups/MC_aks_aks_westeurope/providers/Microsoft.Compute/virtualMachines/xxx'; however, it does not have permission to perform action 'Microsoft.ManagedIdentity/userAssignedIdentities/assign/action' on the linked scope(s) '/subscriptions/xxx/resourcegroups/podidentity/providers/microsoft.managedidentity/userassignedidentities/podidentity' or the linked scope(s) are invalid."`

XXX is simply to anonymize the error. Just to test it out, I made the client XXX subscription owner and yet the same permission exception is raised but the error message might be misleading.

**Steps To Reproduce**
Steps on the readme
**Expected behavior**
Output of the demo app
**AAD Pod Identity version**
v1
**Kubernetes version**
AKS 1.14.5

**Comment by chewong** [comment]
Hi @stephaneey. Have you tried re-deploying the demo app after you granted client XXX subscription owner? Are your cluster resource group and your identity resource group within the same subscription?

**Comment by stephaneey** [comment]
Hello,

If by redeploying you mean Deleting the pod and redeploy it through kubectl apply then yes. Both are in the same subscription indeed.

Thanks

**Comment by stephaneey** [comment]
Hello @chewong 

I have scaled down the mic deploy then out again and now it works. Just one thing, I suppose it's not the goal to set the AKS spn subscription owner so what is the recommended permission level? Tried to assign "Managed Identity Contritubor" but that's not enough it seems. 

Best Regards

**Comment by chewong** [comment]
The role that you should assign your service principal should be `Managed Identity Operator` not `Managed Identity Contritubor`. Also, if your user-assigned identity isn't within the same resource group as your cluster resource group, you will need to assign `Managed Identity Operator` to your cluster service principal pointing to that particular user-assgined identity. You can see https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.role-assignment.md#user-assigned-identities-that-are-not-within-the-cluster-resource-group for more details.
