### ISSUE TITLE
Completed pods should have identities unassigned

### ISSUE THREAD

**Issue by aranair** [Azure/aad-pod-identity#637]
**Describe the bug**

- Completed pods, say from (cron)job history leftovers, are not getting their identities unassigned. 
- There can be any number of completed pods on a node.
- For nodes that happen to have >150 completed pods on them, it will become impossible for any new identities to be assigned to them when new pods get scheduled onto them.
- A manual removal of those completed pods brings it back to normal operation.

**Steps To Reproduce**

- Just get any node with >150 pods on them (Completed + Running)
   - One way this could happen is from cronjob/jobs with history set to non-zero and having multiple of these jobs run. 
- Schedule another pod that requires a new identity assignment to the node.
- the MIC pod throws an error along the lines of:

```
...message\":\"User Assigned Identities Number '154' Assign exceed limit '150' in one request...
```

**Expected behavior**

- Either it ignores the identities for completed pods or it should un-assign?

**AAD Pod Identity version**

1.5.4

**Kubernetes version**

1.11.10

**Additional context**

**Comment by aramase** [comment]
@aranair Un-assigning identities is only done when a pod using the identity is removed from the cluster. The event handlers we have get notified on pod termination. 

> User Assigned Identities Number '154' Assign exceed limit '150' in one request...

This looks like an API limitation when trying to pass an identity list that's > 150. We have switched to using PATCH API for assigning new identities starting from 1.6.x release. This means the API call is made only with the list of identities to assign/un-assign in each sync loop in MIC component. Can you try out 1.6.x release when you get a chance?

**Comment by aramase** [comment]
@aranair Closing this issue. Please feel free to reopen if you're still having issues after using the latest release.

**Comment by aranair** [comment]
@aramase -- We've ran into this again in v1.6.3 (through a slightly different way but arrived at the same error) 

I'm going to create a new ticket and reference this.
