### ISSUE TITLE
[Known Issue] Upgrade of an AKS cluster causes deletion of existing User Managed Identities

### ISSUE THREAD

**Issue by aramase** [Azure/aad-pod-identity#639]
### Summary

In Managed Identity AKS clusters, when the cluster is scaled up/upgraded the identities that are associated with the underlying nodes are removed. This can cause applications that use the identity to fail while fetching a token after upgrade/scale. 

In case of `aad-pod-identity` the users can delete the application pod to cause a restart. `aad-pod-identity` will then re-assign the identity to the underlying node.

Similar issue reported - https://github.com/Azure/aad-pod-identity/issues/633

### Bug and Fix
The AKS team are aware of this and have prioritized the fix. Check this issue [Managed Identity AKS clusters - intermittent removal of identities on upgrade/scale](https://github.com/Azure/AKS/issues/1650) for more details and timeline on fix

**Comment by BartVanBerkel** [comment]
@aramase I think that this one can be closed. Issue is fixed in AKS.

**Comment by aramase** [comment]
AKS has fixed the issue with scale up scenarios. They are working on a fix for upgrade scenarios as well, but if the pod is rescheduled, MIC handles re-assigning the identities for the pod. Closing this issue now.

**Comment by aramase** [comment]
Keeping this issue open for upgrade scenarios that's to be fixed in AKS.

Note: MIC reassigns the identity when the pods are rescheduled if the identity has been deleted during the upgrade.

**Comment by asumner** [comment]
@aramase Hi, we have random failures of NMI, how do we check if the underlying vm has and assigned identity? (I had to peform an upgrade of all nodes to 1.17.7. pod identity is 1.6.2.)

**Comment by aramase** [comment]
@asumner What are the random failures you're seeing in NMI? To check if the identity is assigned to the underlying VMSS, run the following command - `az vmss identity show -g <resource group> -n <vmss name>`

**Comment by asumner** [comment]
@aramase we see the identity is on the vmss, I was wondering if the identity can be seen on the underlying VM itself, unless MIC is assigning the identity via ARM to just the scale set and Azure is assigning the Identity to the VM? As I understand it, the purpose of the NMI is to BLOCK non matching requests to the IMDS on the vm unless MIC via client.go cache has a matching entry for the pod. It was working (we thought) but if NMI is on the same node as our APP we see 404 in the NMI logs, at the moment we just removed NMI and it works, which would seem to defeat the purpose? (i.e. if I am understanding it correctly any malicious pod could grab a token and access our keyvault? )  I have not read any documentation that specifically describes pod identity as a securing access to the IMDS?

**Comment by aramase** [comment]
> we see the identity is on the vmss, I was wondering if the identity can be seen on the underlying VM itself, unless MIC is assigning the identity via ARM to just the scale set and Azure is assigning the Identity to the VM?

Identities are only at the scale set level. The identity is assigned to VMSS and is available for use by all the instances.

> As I understand it, the purpose of the NMI is to BLOCK non matching requests to the IMDS on the vm unless MIC via client.go cache has a matching entry for the pod.

That is right. NMI looks for an `AzureAssignedIdentity` in `ASSIGNED` state for the pod. It retries for 80s to find one and if not, returns a 404 or 403 error. It doesn't forward the request to IMDS unless an `AzureAssignedIdentity` is found. 

> (i.e. if I am understanding it correctly any malicious pod could grab a token and access our keyvault? ) I have not read any documentation that specifically describes pod identity as a securing access to the IMDS?

NMI adds iptables rules to redirect all IMDS traffic itself for validation. It validates if the pod request can be forwarded and essentially acts as a soft firewall. If NMI is deleted, then the iptables rules get cleaned up, so traffic will just flow to IMDS. Without NMI in the picture there is no isolation.

**Comment by asumner** [comment]
@aramase Thanks Anish,  We had to study way to hard to come to that conclusion as the documentation and articles don't describe it that way. So, now we really understand how it works we can troubleshoot the NMI 404's, is there any way to increase logging? I didn't see there was anything like the MIC --v=6 etc (we tried ;) )
So we have....
E0817 15:53:51.605717       1 server.go:369] failed to get matching identities for pod: template-manager/test-ctm-api-7456cdf46f-bxrhf, error: context canceled
I0817 15:53:51.605800       1 server.go:190] status (404) took 12366500856 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.0.165
W0817 15:53:58.051171       1 client.go:207] list pod error: <nil>. Retrying, attempt number: 1
W0817 15:53:58.351433       1 client.go:207] list pod error: <nil>. Retrying, attempt number: 2
W0817 15:53:58.651693       1 client.go:207] list pod error: <nil>. Retrying, attempt number: 3
W0817 15:53:58.951959       1 client.go:207] list pod error: <nil>. Retrying, attempt number: 4
E0817 15:53:59.252107       1 server.go:341] failed to get pod info from pod IP: 10.240.1.150, error failed to match pod IP 10.240.1.150 with []
I0817 15:53:59.252256       1 server.go:190] status (500) took 1201155680 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.1.150
E0817 15:55:20.782439       1 server.go:369] failed to get matching identities for pod: template-manager/test-svc-template-567d69f76d-6jqz4, error: getting assigned identities for pod template-manager/test-svc-template-567d69f76d-6jqz4 in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>
I0817 15:55:20.782480       1 server.go:190] status (404) took 80003674410 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.1.150

**Comment by aramase** [comment]
> E0817 15:53:59.252107 1 server.go:341] failed to get pod info from pod IP: 10.240.1.150, error failed to match pod IP 10.240.1.150 with []

This is transient error if API server doesn't provide the new pod in the list of pods for the node. The next time the token was requested, I see the pod name was found `template-manager/test-svc-template-567d69f76d-6jqz4`

> E0817 15:55:20.782439 1 server.go:369] failed to get matching identities for pod: template-manager/test-svc-template-567d69f76d-6jqz4, error: getting assigned identities for pod template-manager/test-svc-template-567d69f76d-6jqz4 in CREATED state failed after 16 attempts, retry duration [5]s, error:


This error means MIC has not assigned the identity for this pod. This could be because of 2 reasons:
1. There was an error when assigning the identity for the pod. This should be in MIC logs.
2. If there is no error in MIC, then this could mean the `aadpodidbinding: <selector>` label doesn't match any of the AzureIdentityBinding.

**Comment by asumner** [comment]
@aramase  I will first ensure the node pools are not undersized, we have other timeouts and issues I think, I'll increase CPU's ram etc and double check we are not under resourced then I'll put back the NMI and check all the logs again and let you know what we find. Thanks for your help Anish.

**Comment by markpenner34** [comment]
@aramase 

Hi,

i have recently upgraded my AKS cluster which was configured and working with AAD pod identity, however i now have multiple failed deployments.

When i describe the pods which are unable to deploy i get the following error 

`failed to get keyvaultClient: failed to get key vault token: nmi response failed with status code: 404`

Upon investigating the logs from the nmi pod i am seeing the following

`E1015 09:27:10.973359       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1.AzurePodIdentityException: azurepodidentityexceptions.aadpodidentity.k8s.io is forbidden: User "system:serviceaccount:default:aad-pod-id-nmi-service-account" cannot list resource "azurepodidentityexceptions" in API group "aadpodidentity.k8s.io" at the cluster scope`

am i encountering this issue?

if so what is the work around.

**Comment by aramase** [comment]
@markpenner34 The error you're seeing isn't related to this issue. That looks like the cluster role and cluster rolebinding you created as part of the aad-pod-identity doesn't exist? Could you check if they exist -

```
kubectl get clusterrole aad-pod-id-nmi-role -o yaml
kubectl get clusterrole aad-pod-id-mic-role -o yaml
```

If they don't exist, you would need to recreate them.

@miwithro Any reason why AKS upgrade would impact aad-pod-identity cluster roles?

**Comment by djj0809** [comment]
Hey guys I also met this clusterrole and clusterrolebing missing issue in
AKS, and AKS confirmed that it’s a bug at their side (they are developing
AKS managed aad pod identity feature, but they somehow introduced this
bug), cluster will automatically delete this two when cluster updates or
randomly. But now they are deploying hotfix on this now.

If you ran into this issue, for now you can add them back and see if they
got removed again. Or you can change the name of these two temporarily, so
that AKS won’t remove it again.

Anish Ramasekar <notifications@github.com>于2020年10月15日 周四23:27写道：

**Comment by djj0809** [comment]
The objects I mentioned is aad-pod-id-nmi-role and it’s corresponding
rolebinding.

Jinqiang Ding <djq2272@gmail.com>于2020年10月15日 周四23:36写道：

**Comment by ekmineev** [comment]
Hi @djj0809, we have seen clustterrole and clusterrolebinding missing on three of our managed AKS clusters in the past week. Is there an issue id tracking the host fix on AKS side so I can follow? Thanks!

**Comment by aramase** [comment]
Closing this issue as MIC reconciliation for missing identities has been added as part of `v1.6.3` release.

**Comment by djj0809** [comment]
@ekmineev I don't have one. However they shared me with the hotfix release progress, and according to that, it should have been fixed now. So you should add them back and they will not be removed again I guess.

**Comment by markpenner34** [comment]
@djj0809  @aramase  Hi Both, 

I spent a good couple of hours doing some investigation yesterday and yes it was the cluster & role binding missing from the nmi role.

It was working correctly for over a week after the upgrade which is what i can't understand.

many thanks for your help on this it would have resolved my problem however i still believe this is a bug.

**Comment by zhiweiv** [comment]
Recently we found add pod identity in some of our AKS clusters broken, cluster & role binding was missing. We added them back manually to fixed it.

We did nothing to our AKS when issue happens.

**Comment by miwithro** [comment]
Yes, we had an issue about the role bindings removal this week and it has been mitigated. We also fixed some clusters affected by this issue from AKS's log, by adding the cluster role aad-pod-id-nmi-role and cluster rolebinding aad-pod-id-nmi-binding back. 

But we may miss some of the clusters. For these clusters, customers can add back the cluster role / cluster role binding by themselves.
