### ISSUE TITLE
Deprecated label "beta.kubernetes.io/os" used in "indeployment-rbac.yaml"

### ISSUE THREAD

**Issue by ohadschn** [Azure/aad-pod-identity#645]
**Describe the bug**
Usage 1: https://github.com/Azure/aad-pod-identity/blob/f4084a15f407b6510bf32d8d10cda8fa516e407c/deploy/infra/deployment-rbac.yaml#L160

Usage 2: https://github.com/Azure/aad-pod-identity/blob/f4084a15f407b6510bf32d8d10cda8fa516e407c/deploy/infra/deployment-rbac.yaml#L268

According to docs, should be replaced with `kubernetes.io/os`:
https://v1-16.docs.kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/#beta-kubernetes-io-os-deprecated

**Comment by aramase** [comment]
@ohadschn Thank you for opening the issue. Would you be interested in opening a PR to update the deployment and charts with `kubernetes.io/os`?
