### ISSUE TITLE
Periodic check on whether the identity referenced by AzureAssignedIdentity is still assigned to the underlying node

### ISSUE THREAD

**Issue by chewong** [Azure/aad-pod-identity#647]
**Describe the request**

Address https://github.com/Azure/aad-pod-identity/issues/644#issuecomment-642408960.

**Explain why AAD Pod Identity needs it**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aramase** [comment]
Periodically reconcile to ensure identities that are defined in `AzureIdentity` and in use by pod still exist on the underlying node. The identity could be removed manually by the user or during scale up/upgrade scenario in AKS. This periodic reconcile loop will add back any missing identities. The reconcile period could be a user configured value to ensure the loop isn't run frequently and can be spaced out when cluster is throttled.
