### ISSUE TITLE
Add E2E scenario tests 

### ISSUE THREAD

**Issue by rite2nikhil** [Azure/aad-pod-identity#65]
e2e tests to validate pod->nmi->mic e2e scenario's
1. Service prinicipal
2. MSI 
3. Flex volume

**Comment by khenidak** [comment]
@rite2nikhil i have seen some e2e tests being merged, was that all that is planned?

**Comment by kkmsft** [comment]
E2e tests are now working with #202 merged. Doc related here - https://github.com/Azure/aad-pod-identity/tree/master/test/e2e
