### ISSUE TITLE
Guidance for assigning managed identity to virtual ACI pods

### ISSUE THREAD

**Issue by Kesudan** [Azure/aad-pod-identity#651]
We use aad pod identity for normal AKS pods which works great, but as we understand this has no plans to be supported for the virtual ACI connector;

https://github.com/Azure/aad-pod-identity/issues/470

Does anyone have any guidance/info on how to get a managed identity assigned to pods deployed through the virtual ACI node?

**Comment by aramase** [comment]
@Kesudan It's not possible to use `aad-pod-identity` with pods running in ACI. `aad-pod-identity` works by assigning the User MSI to the underlying node on which the pod is running. The metadata service running on the node serves the token based on the identity on the node. In case of ACI this is not possible.

**Comment by aramase** [comment]
Closing this issue as this is outside the scope of the project. Please feel free to reopen if you have any other questions.
