### ISSUE TITLE
MIC: Use System MSI for cloud provider operations

### ISSUE THREAD

**Issue by kkmsft** [Azure/aad-pod-identity#66]

**Comment by khenidak** [comment]
hmm can you expand on this issue? I'm not sure i understand

**Comment by kkmsft** [comment]
MIC uses service principle from azure.json currently go create its own auth handles. In a cluster which is configured with MSI, this would not work and we need to use the MSI to arrive at the handles.

**Comment by khenidak** [comment]
MIC should use its own service principals. It should not depend on anything provided by the node including EMSI/MSI.

**Comment by kkmsft** [comment]
MIC will use its own identities. Being tracked here in backlog: https://github.com/Azure/aad-pod-identity/issues/114
