### ISSUE TITLE
Upgrade CRDs to apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by aramase** [Azure/aad-pod-identity#661]
CRDs have been promoted to GA since Kubernetes 1.16:

https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20180415-crds-to-ga.md

`aad-pod-identity` CRDs currently use apiextensions.k8s.io/v1beta1, which will be removed in the future: kubernetes/kubernetes#82022.

**Note:**

- The removal of `apiextensions.k8s.io/v1beta1` is planned for 1.22. So `aad-pod-identity` will continue to use `apiextensions.k8s.io/v1beta1` until the 1.21 release in order to support clusters < 1.16. Before the 1.22 release, we can make the switch to `apiextensions.k8s.io/v1` and set the default kube version of helm chart to 1.16+

**Alternatives:**

helm3 doesn't support templating in the crds dir. If this is possible, then we can determine the k8s version and use the appropriate `apiVersion`.

**Comment by chewong** [comment]
With the introduction of https://github.com/kubernetes/enhancements/pull/1111, we might have to change the name of our CRDS to exclude `.k8s.io`. it's reserved for CRDs created by the Kubernetes community has gone through the API review process. Without the `api-approved.kubernetes.io` annotation, we will receive the following error:

```
Error: failed to instal CRD crds/crd.yaml: CustomResourceDefinition.apiextensions.k8s.io "azureassignedidentities.aadpodidentity.k8s.io" is invalid: metadata.annotations[api-approved.kubernetes.io]: Required value: protected groups must have approval annotation "api-approved.kubernetes.io", see https://github.com/kubernetes/enhancements/pull/1111
```
