### ISSUE TITLE
AzureIdentity "configured", but does not exist

### ISSUE THREAD

**Issue by bq1756** [Azure/aad-pod-identity#669]
**Describe the bug**
I created and AzureIdentity.  Kubectl return code indicates successful creation.  kubectl get AzureIdentities returns "no resources found"

**Steps To Reproduce**
## Deploy aad-pod-identity in kube-system with forceNameSpaced
helm repo add aad-pod-identity https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts
helm install --set mic.leaderElection.namespace="kube-system" --set nmi.micNamespace="kube-system" --set forceNameSpaced=true aad-pod-identity aad-pod-identity/aad-pod-identity
  $vmssClientId=(az aks show --resource-group $resourceGroup --name $clusterName --subscription $subscriptionId --query identityProfile.kubeletidentity.clientId -otsv)

## Create role assignments for VMSS MID
az role assignment create --role "Managed Identity Operator" --assignee $vmssClientId --scope /subscriptions/$subscriptionId/resourcegroups/$k8sResourceGroup
az role assignment create --role "Virtual Machine Contributor" --assignee $vmssClientId --scope /subscriptions/$subscriptionId/resourcegroups/$k8sResourceGroup

## Create "demo" Managed Identity
export SUBSCRIPTION_ID="2c1b982f-xxxxxxxxxxxxxxxxxxx93f8"
export RESOURCE_GROUP="xxxxxxDev-rg"
export IDENTITY_NAME="demo"
export CLUSTER_RG="MC_xxxxxxDev-rg_xxxxxx_centralus"
az identity create -g $CLUSTER_RG -n $IDENTITY_NAME --subscription $SUBSCRIPTION_ID

**Verify:**
az identity show -g $CLUSTER_RG -n $IDENTITY_NAME --query name
 "demo"

## Create an AzureIdentity named demo.
export IDENTITY_CLIENT_ID="$(az identity show -g $CLUSTER_RG -n $IDENTITY_NAME --subscription $SUBSCRIPTION_ID --query clientId -otsv)"
export IDENTITY_RESOURCE_ID="$(az identity show -g $CLUSTER_RG -n $IDENTITY_NAME --subscription $SUBSCRIPTION_ID --query id -otsv)"

cat <<EOF | kubectl apply -f -
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: $IDENTITY_NAME
  namespace: default
spec:
  type: 0
  resourceID: $IDENTITY_RESOURCE_ID
  clientID: $IDENTITY_CLIENT_ID
EOF

**Return text:**
azureidentity.aadpodidentity.k8s.io/demo configured

**Verification fails:**
kc get AzureIdentity
No resources found in default namespace.
kc get AzureIdentity --all-namespaces
No resources found

**Expected behavior**
`kc get AzureIdentity` lists an AzureIdentity named "demo"

**AAD Pod Identity version**
1.6.1

**Kubernetes version**
1.16.9

**Additional context**

**Comment by chewong** [comment]
Hi @bq1756, I wasn't able to repro the error by following your steps. Did you make sure that your KUBECONFIG is pointing to the correct cluster?

**Comment by bq1756** [comment]
I started from scratch and used static names (not variables).  I was not able to reproduce the issue either.  I successfully created AzureIdentity.

**Comment by bq1756** [comment]
Could not reproduce
