### ISSUE TITLE
mic controller periodically panics

### ISSUE THREAD

**Issue by greensombrero** [Azure/aad-pod-identity#67]
We've observed our mic controller periodically crashes with a panic.  In looking at the logs after we see this stack trace:

panic: runtime error: index out of range

goroutine 38 [running]:
github.com/Azure/aad-pod-identity/pkg/cloudprovider.(*Client).RemoveUserMSI(0xc4202c8380, 0xc4208f58c0, 0xb3, 0xc420711240, 0x18, 0x0, 0x0)
	/home/nikhil/go/src/github.com/Azure/aad-pod-identity/pkg/cloudprovider/cloudprovider.go:111 +0xafd
github.com/Azure/aad-pod-identity/pkg/mic.(*Client).RemoveAssignedIDsWithDeps(0xc4202be690, 0xc4205ecc48, 0x0, 0xc420710a20, 0x18)
	/home/nikhil/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:401 +0x156
github.com/Azure/aad-pod-identity/pkg/mic.(*Client).Sync(0xc4202be690, 0xc4200689c0)
	/home/nikhil/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:223 +0x1c2a
created by github.com/Azure/aad-pod-identity/pkg/mic.(*Client).Start
	/home/nikhil/go/src/github.com/Azure/aad-pod-identity/pkg/mic/mic.go:94 +0x16b

Looking at the code it appears on line 111 in cloudprovider.go it tries to assign a value in an empty slice.  From my read of the code there is no way this will ever work so if you get into this if block it will crash as the slice hasn't been initialized anywhere.  I'm wondering if what you really want to do is use the append function which can auto grow the slice.  

I don't have enough context to understand when we do get into this versus when we don't or what the code is actually trying to accomplish.  We can observe things work sometimes but we do crash regularly enough and see intermittent issues that this must be a case that occurs regularly needs to be fixed.

**Comment by kkmsft** [comment]
Thanks @greensombrero for trying out the project and reporting this issue. I am looking into this.

**Comment by kkmsft** [comment]
Test layering has been moved so that this bug is captured in the automated test. The above checkin contains the fix for the issue.

**Comment by greensombrero** [comment]
Just want to make sure I know the right procedure for getting these changes.  If I re-pull master and apply the updated deployment-rbac.yml file it would apply the fixes correct?  It looks like the image reference in the file was updated to a new docker image.  Is that the correct procedure to upgrade?

**Comment by kkmsft** [comment]
Yes, the idea is to use the new image without removing the existing azureidentity objects. Please only create the mic back. You can delete the mic using the "kubectl delete deploy mic" and extract only the mic portion and run a create on it. There is a configuration issue I am seeing when when applying the yaml again with CRDs. Although no side effects were seen (trying to figure out what is going on), meanwhile the above step should help move forward.
