### ISSUE TITLE
"Error validating token: IDX10223" Whilst getting a KeyVault secret

### ISSUE THREAD

**Issue by terrycain** [Azure/aad-pod-identity#675]
**Describe the bug**
After a period of time (a day or so), requesting secret from KeyVault fails with "Error validating token: IDX10223"

**Steps To Reproduce**
Unknown, it happens after a few hours/days, I've had this happen in 3 different environments one after another which follows the same order of when the services were restarted.

**Expected behaviour**
To not get this error

**AAD Pod Identity version**
Running NMI and MIC containers with the image tag 1.6.0

**Kubernetes version**
1.16.11

**Additional context**

Have a similar discussion here - https://github.com/Azure/azure-sdk-for-python/issues/12368

Judging by the fact that it happens across multiple clusters, i.e i deployed in dev,staging and prod one after the other, which took a grand total of 20mins ish, and then a day or so later, I see this error from pods accessing keyvault across all environments in the same rough timespan, I'm inclined to think that an expired token is somehow getting cached and served to the container.

Any ideas how to further debug this?

**Comment by aramase** [comment]
@terrycain `aad-pod-identity` doesn't perform any caching of tokens. It only performs the validation to ensure the pod requesting a token for an identity has access to the identity as defined by `AzureIdentity` and `AzureIdentityBinding`. If yes, then it forwards the request as is to the metadata endpoint and relays back the token to the application.

1. When this error happens, do you a see a log in NMI for the token request from the application?
2. If yes, do you see a subsequent log that the token request succeeded in NMI?

If the above 2 are true, then it might be something we need to check with the metadata endpoint team to see if it's serving an expired token.

**Comment by terrycain** [comment]
@aramase It just happened so I was able to easily dig into it more

So I got the IDX10223 exception at these times (no issues for at least 6 hours before those logs and seems fine after the last error

```
127.0.0.1 - - [13/Jul/2020:08:30:08 +0000] "GET /readyz HTTP/1.1" 500 35 "-" "kube-probe/1.16"
127.0.0.1 - - [13/Jul/2020:08:32:08 +0000] "GET /readyz HTTP/1.1" 500 35 "-" "kube-probe/1.16"
127.0.0.1 - - [13/Jul/2020:08:35:08 +0000] "GET /readyz HTTP/1.1" 500 35 "-" "kube-probe/1.16"
127.0.0.1 - - [13/Jul/2020:08:42:08 +0000] "GET /readyz HTTP/1.1" 500 35 "-" "kube-probe/1.16"
```
The issue is slightly more complicated as there are 2 workers serving requests for /readyz but both should request a token and deal with it appropriately.

These are the logs from the NMI pod on that host

```
I0713 08:20:08.403864       1 standard.go:72] No clientID in request. pod1-54cc5b6fdc-5fng8 has been matched with azure identity pod1
I0713 08:20:08.403938       1 standard.go:165] matched identityType:0 clientid:adf7##### REDACTED #####eec5 resource:https://vault.azure.net
I0713 08:20:08.617855       1 server.go:190] Status (200) took 214117053 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.3.1.101
I0713 08:43:08.403759       1 standard.go:72] No clientID in request. pod1-54cc5b6fdc-5fng8 has been matched with azure identity pod1-identity
I0713 08:43:08.403842       1 standard.go:165] matched identityType:0 clientid:adf7##### REDACTED #####eec5 resource:https://vault.azure.net
I0713 08:43:08.415703       1 server.go:190] Status (200) took 12119465 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.3.1.101
```
So it seems it requested a token at 08:20:08 and 08:43:08, but during that time, the token failed?

Seeing as it doesnt look like AAD identity isnt the issue, should I move this info back to the azure python sdk repo?

**Comment by aramase** [comment]
@terrycain From the logs above, it doesn't look like a `aad-pod-identity` issue as there is no caching performed in NMI. If the issue is reproducible, then either of 2 is possible - caching in the SDK or bug in the Instance Metadata Service running on the VM.

**Comment by aramase** [comment]
@terrycain Did you get a chance to look at the logs or confirm there is caching on the client-side?

**Comment by terrycain** [comment]
Hey, sorry been busy lately :D, there is no caching that I'm doing, I cant speak for the azure sdk itself so will continue the issue i have there with the findings I have here :), will report back if i find out more

**Comment by aramase** [comment]
@terrycain Any updates on this issue?

**Comment by terrycain** [comment]
None atm, I can't seem to reproduce it in my dev environment

**Comment by aramase** [comment]
Thanks for confirming @terrycain! Do you think we can close this issue and re-open if you're able to repro?

**Comment by terrycain** [comment]
Yeah sounds good
