### ISSUE TITLE
Helm install failure with helm3 and helm2

### ISSUE THREAD

**Issue by digeler** [Azure/aad-pod-identity#685]
**Describe the bug**
trying to deploy pod identity 1.6 with helm3 /2  getting the below error : 
```
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "AzureIdentity" in version "aadpodidentity.k8s.io/v1", unable to recognize "": no matches for kind "AzureIdentityBinding" in version "aadpodidentity.k8s.io/v1", unable to recognize "": no matches for kind "AzurePodIdentityException" in version "aadpodidentity.k8s.io/v1"]
helm.go:84: [debug] [unable to recognize "": no matches for kind "AzureIdentity" in version "aadpodidentity.k8s.io/v1", unable to recognize "": no matches for kind "AzureIdentityBinding" in version "aadpodidentity.k8s.io/v1", unable to recognize "": no matches for kind "AzurePodIdentityException" in version "aadpodidentity.k8s.io/v1"]
unable to build kubernetes objects from release manifest
helm.sh/helm/v3/pkg/action.(*Install).Run
        /home/circleci/helm.sh/helm/pkg/action/install.go:256
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:229
main.newInstallCmd.func1
        /home/circleci/helm.sh/helm/cmd/helm/install.go:117
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:83
runtime.main
        /usr/local/go/src/runtime/proc.go:203
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1357
```

**Steps To Reproduce**
use helm3 with latest podidentity version : 
name: aad-pod-identity
sources:
- https://github.com/Azure/aad-pod-identity
version: 1.6.0
on aks 1.16.10 

**Expected behavior**
Podidentity to be install with helm3 /2
**AAD Pod Identity version**
1.6.0
**Kubernetes version**
1.16.10
**Additional context**
i have looked at this : https://github.com/helm/charts/issues/19008
is there something change on 1.16.10 ?

helm versions :
```
helm2 : 
Client: &version.Version{SemVer:"v2.16.9", GitCommit:"8ad7037828e5a0fca1009dabe290130da6368e39", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.9", GitCommit:"8ad7037828e5a0fca1009dabe290130da6368e39", GitTreeState:"clean"}
helm3 : 
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```
helm2 shows the same issue : 
```
 helm install --name aad-pod-identity C:\helm3 --timeout 600 --values C:\helm3\values0.yaml --values C:\helm3\values1.yaml --wait  --dry-run
Error: [unable to recognize "": no matches for kind "AzureIdentity" in version "aadpodidentity.k8s.io/v1", unable to recognize "": no matches for kind "AzureIdentityBinding" in version "aadpodidentity.k8s.io/v1", unable to recognize "": no matches for kind "AzurePodIdentityException" in version "aadpodidentity.k8s.io/v1"]
PS C:\repos\csi-clean\Aorato-Poly\artifacts\bin\Debug\Tools [Eng-PolyDgeUseGcKs]>
```
manual install on aks 1.16.10 works :  
https://github.com/Azure/aad-pod-identity/releases

**Comment by chewong** [comment]
https://github.com/Azure/aad-pod-identity/issues/381 explained the cause of this error, which has already been fixed. Could you provide the command you used to install aad-pod-identity through helm 3?

**Comment by digeler** [comment]
helm 2 : helm install --name aad-pod-identity C:\helm3 --timeout 600 --values C:\helm3\values0.yaml --values C:\helm3\values1.yaml --wait  --dry-run

am also attaching the templates : 

[templates.zip](https://github.com/Azure/aad-pod-identity/files/4923092/templates.zip)

 helm3 install pod-identity C:\helm3\ --debug --values C:\helm3\values0.yaml --values C:\helm3\values1.yaml --dry-run

**Comment by aramase** [comment]
@digeler The `--dry-run` flag is not supported with CRDs according to this PR - https://github.com/helm/helm-www/pull/545/files. If you're running just `helm install` are you seeing errors?

**Comment by digeler** [comment]
i think i know whats going on  here.
when i deploy using helm with this file structure it works  : 
![image](https://user-images.githubusercontent.com/4949529/87566351-91808080-c6cb-11ea-9033-c3991c47c03d.png)

but our code renders the yaml files and the end result  the chart is like this : 
without the crds folder all the files in the same folder , only with the files : 
![image](https://user-images.githubusercontent.com/4949529/87567403-ed97d480-c6cc-11ea-8a9c-8ec34bdce483.png)

seems like the crds are not installed then we get the error.

is there a way to put all the files in the same folder and still control the crds ?

or i must maintain the same file structure , this worked till now with helm 2 
much appriciated.

**Comment by digeler** [comment]
am not sure what change on helm3 but when i use all in the same folder like this : 
![image](https://user-images.githubusercontent.com/4949529/87569424-c42c7800-c6cf-11ea-870a-436b062e35d0.png)

and with helm2 with same files it works : 
helm install --name aad-pod-identity C:\repos\helmorig_15_07\folderpath\src\Tools\Charts\aad-pod-identity\ --values C:\helm3\1.5.5\values0.yaml --values C:\helm3\1.5.5\values1.yaml

![image](https://user-images.githubusercontent.com/4949529/87569627-140b3f00-c6d0-11ea-832b-eb84681c940e.png)

![image](https://user-images.githubusercontent.com/4949529/87569669-26857880-c6d0-11ea-9a9a-ca051f987351.png)

can you help me understand how can i overcome this issue in helm3 please ?

**Comment by chewong** [comment]
For helm 3, CRDs are put inside the `crds` folder instead of the chart directory. See https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you for more details.

**Comment by digeler** [comment]
Thanks chewong , i changed my code to support this folder and now its working.
seems like helm3 does not work with helm2 charts ,i dont think its related to this topic anyway here is my issue : https://github.com/helm/helm/issues/8466
you can close this issue , thank you so much for helping.
