### ISSUE TITLE
[Feature] Get ClientID automatically for Managed Identity

### ISSUE THREAD

**Issue by zhiweiv** [Azure/aad-pod-identity#688]
We can get ClientID of Managed Identity by it's ResourceID, see https://docs.microsoft.com/en-us/rest/api/managedidentity/userassignedidentities/get. Is it good idea to require only ResourceID in CRD AzureIdentity?  NMI can get ClientID from Azure by ResourceID itself. This helps reducing configuration work.

Background:
We configued AzureIdentity with correct ResourceID/wrong ClientID. MIC binded the Identity to VMSS successfully. However  token call failed, we found error "Identity not found" in NMI log. Seems MIC only use ResourceID, NMI uses ClientID.

**Comment by aramase** [comment]
@zhiweiv The clientID is required, so NMI can match the clientID with the request clientID to check if the pod has access to what its requesting token for. NMI doesn't make any calls to azure and doesn't require access to SP/cluster identity. MIC being only 2 pods reduces the # of pods that have access to the SP/cluster-identity. If NMI were to get the clientID for each UserMSI configured, 
- It will require read permission for all the UserMSIs. This means a pod on every node has access.
- This conversion can be expensive in terms of # of ARM calls and latency

**Comment by zhiweiv** [comment]
Thanks for the explanation.
