### ISSUE TITLE
Installing aad-pod-identity with helm3 doesn't work 

### ISSUE THREAD

**Issue by AndreasM009** [Azure/aad-pod-identity#689]
**Describe the bug**
I have an RBAC enabled AKS cluster and installed aad-pod-identity using helm (3) as described in the docs, but in its own namespace. After the installation I can create my resources, but my managed identity is not assigned to the VMSS. I have created all needed role assignments for the AKS cluster's (managed identity enabled) service principal:
- Virtual Machine Contributor
- Managed Identity Operator for my managed identity

**Steps To Reproduce**
Just follow the demo in the docs, but install aad-pod-identity in its own namespace

**Expected behavior**
My managed identity should be assigned to the VMSS
**AAD Pod Identity version**
1.6.1
**Kubernetes version**
1.16.10
**Additional context**

**Comment by aramase** [comment]
@AndreasM009 Coud you check if there are any errors in MIC pod logs?

**Comment by AndreasM009** [comment]
@aramase my bad, I didn't update the helm repo. After an update it works.

**Comment by aramase** [comment]
Glad to know it's working now @AndreasM009. Closing this issue now. Please feel free to reopen if you have any other issues.
