### ISSUE TITLE
(feat): Delete CRDs when installCRDs: true

### ISSUE THREAD

**Issue by lukasmrtvy** [Azure/aad-pod-identity#698]
**Describe the request**
Would be nice to delete CRDs when installCRDs: true, just like cert-manager chart does it ( https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml#L27 )

**Explain why AAD Pod Identity needs it**
There is no clean up involved after deleting/destroying helm release = CRDs will not be deleted 

**Describe the solution you'd like**
Create & Delete CRDs with installCRDs: true flag

**Describe alternatives you've considered**
None  

**Additional context**
None

**Comment by chewong** [comment]
@lukasmrtvy according to [helm 3 documentation](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations):
> There is no support at this time for upgrading or deleting CRDs using Helm. This was an explicit decision after much community discussion due to the danger for unintentional data loss. Furthermore, there is currently no community consensus around how to handle CRDs and their lifecycle. As this evolves, Helm will add support for those use cases.

In what use case would you like to completely delete the CRDs?
