### ISSUE TITLE
Http listen and serve error: listen tcp :8080: bind

### ISSUE THREAD

**Issue by sousadax12** [Azure/aad-pod-identity#702]
Hello,

Yesterday I managed to create an AKS cluster with AAD pod entity working without problems. The day after I reproduce the same steps but i am getting this error:
`Http listen and serve error: listen tcp :8080: bind: address already in use
panic: listen tcp :8080: bind: address already in use
goroutine 48 [running]:
github.com/Azure/aad-pod-identity/pkg/probes.startAsync(0x147d7e3, 0x4)
/go/src/github.com/Azure/aad-pod-identity/pkg/probes/probes.go:28 +0x1cc
created by github.com/Azure/aad-pod-identity/pkg/probes.Start
/go/src/github.com/Azure/aad-pod-identity/pkg/probes/probes.go:36 +0x49`

This error is happening on NMI container.

This are the commands that I am using to deploy this helm chart:

- helm repo add csi-secrets-store-provider-azure https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts
- helm install csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --generate-namehelm repo add aad-pod-identity https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts
- helm install pod-identity aad-pod-identity/aad-pod-identity

Do you know why this is happening?

**Comment by aramase** [comment]
@sousadax12 The NMI pod runs on host network and uses port `8080` for health probe. From the error it looks like port `8080` is already in use. You can configure the nmi probe port to a different value in the helm chart `--set nmi.ProbePort=8081`

```
nmi.probePort | Override http liveliness probe port | If not provided, default is 8080
```

https://github.com/Azure/aad-pod-identity/tree/master/charts/aad-pod-identity#configuration

**Comment by geoarchitect** [comment]
@aramase  - I am getting the same issue, though from the CSI Driver secrets-store:

```
time="2020-07-24T03:21:17Z" level=fatal msg="failed to start manager, error: error listening on :8080: listen tcp :8080: bind: address already in use"
```

Whats peculiar is that I have three other clusters with this same setup now. Looking at the differeces it seems that there is a issue caused by this chart - csi-secrets-store-provider-azure-0.0.9. 

My three working clusters have csi-secrets-store-provider-azure-0.0.7 installed and the broken one is using 0.0.9.

**Comment by geoarchitect** [comment]
@aramase - Confirmed that going back to 0.0.7 fixes the issue for me.

```
helm install csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --generate-name  --version 0.0.7
```

**Comment by aramase** [comment]
@geoarchitect The CSI driver `v0.0.12` release adds a new controller that listens by default on 8080. Since both these run on host network only one of the pods can use `8080`. If `8080` is being used by another process, then nmi health probe can be configured to a different probe port instead of `8080`.

**Comment by geoarchitect** [comment]
Makes sense - can we change the default port for nmi to use port 8081?

**Comment by aramase** [comment]
I think we could do that to avoid conflicts during installation of both components. We will be cutting `1.6.2` release tomorrow, so I think we'll configure the default value in the helm chart and deployment to `8081`.

**Comment by jaiawasthi** [comment]
1 probes.go:27] http listen and serve error: listen tcp :8085: bind: address already in use

If i try to use --set nmi.ProbePort="9085" it doesnt update the port it uses
I'm not sure what the issue is.

**Comment by dollarklavs** [comment]
I'm running a cluster from a terraform configuration that uses the `helm_release` resource to install `aad-pod-identity` and `csi-secrets-store-provide-azure` like so:

```tf
resource "helm_release" "aad_pod_id" {
  name             = "aad-pod-identity"
  repository       = "https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts"
  chart            = "aad-pod-identity"
  version          = "2.0.0"
  namespace        = var.aad_pod_id_ns
  create_namespace = true

  values = [
    <<-EOF
    azureIdentities:
    - name: "${azurerm_user_assigned_identity.mi.name}"
      resourceID: "${azurerm_user_assigned_identity.mi.id}"
      clientID: "${azurerm_user_assigned_identity.mi.client_id}"
      binding:
        name: "${azurerm_user_assigned_identity.mi.name}-identity-binding"
        selector: "${var.aad_pod_id_binding_selector}"
    EOF
  ]

  set {
    name = "nmi.ProbePort"
    value = "8085"
  }
}
```

and 

```tf
resource "helm_release" "kv_csi" {
  name             = "csi-secrets-provider-azure"
  repository       = "https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/charts"
  chart            = "csi-secrets-store-provider-azure"
  version          = "0.0.14"
  namespace        = var.kv_csi_ns
  create_namespace = true
}
```

And I still get a _port in use error_ as seen in the logs when running:
```bash
 kubectl logs -n aad-pod-id pod/aad-pod-identity-nmi-7233 
```
output:
```
I1127 14:06:06.640575       1 main.go:61] Starting nmi process. Version: 1.6.1. Build date: 2020-05-22-17:50.
I1127 14:06:06.742122       1 crd.go:447] CRD lite informers started
I1127 14:06:06.842589       1 main.go:85] Running NMI in namespaced mode: false
I1127 14:06:06.842783       1 nmi.go:52] Initializing in standard mode
I1127 14:06:06.842860       1 probes.go:42] Initialized health probe on port 8080
I1127 14:06:06.842877       1 probes.go:45] Started health probe
I1127 14:06:06.843002       1 metrics.go:329] Registered views for metric
I1127 14:06:06.843144       1 prometheus_exporter.go:22] Starting Prometheus exporter
I1127 14:06:06.843224       1 metrics.go:336] Registered and exported metrics on port 9090
I1127 14:06:06.843307       1 server.go:97] Listening on port 2579
E1127 14:06:06.843766       1 probes.go:27] Http listen and serve error: listen tcp :8080: bind: address already in use
panic: listen tcp :8080: bind: address already in use

goroutine 66 [running]:
github.com/Azure/aad-pod-identity/pkg/probes.startAsync(0x147d7e3, 0x4)
        /go/src/github.com/Azure/aad-pod-identity/pkg/probes/probes.go:28 +0x1cc
created by github.com/Azure/aad-pod-identity/pkg/probes.Start
        /go/src/github.com/Azure/aad-pod-identity/pkg/probes/probes.go:36 +0x49
```

I thought that I had overwritten the nmi probe port using the `name = "nmi.ProbePort"` to a value of 8085, but it still says that the port is 8080. 
Can someone explain what I'm doing wrong?
