### ISSUE TITLE
Helm3 aad-pod-identity charts are failing in Azure Devops pipeline

### ISSUE THREAD

**Issue by prabhakarreddy1234** [Azure/aad-pod-identity#707]
**Trying to automate Pod Identity through Azure Devops Pipelines but failed due to errors**

**Steps To Reproduce**

Ran below script from azure devops powershell task and got the attached errors.

```
helm repo add aad-pod-identity https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts
helm install aad-pod-identity aad-pod-identity/aad-pod-identity
```

![image](https://user-images.githubusercontent.com/1984707/88423871-6b9e5e80-cde4-11ea-8de9-81158d6f8468.png)

**Expected behavior**
These errors may be shown as warning but shouldn't fail the task.

**AAD Pod Identity version : **
2.0.0

**Kubernetes version : **
1.18.2

**Comment by chewong** [comment]
Duplicated issue: https://github.com/Azure/aad-pod-identity/issues/626
