### ISSUE TITLE
specify FORCENAMESPACES with 1.6.2?

### ISSUE THREAD

**Issue by aelmanaa** [Azure/aad-pod-identity#712]
Hello,

is it still required to specify

          - name: FORCENAMESPACED
            value: "true"

after the last release (1.6.2) ?

thanks

**Comment by aramase** [comment]
Thanks for opening the issue 👍 

Yes, it's still required to specify `FORCENAMESPACED` true to force namespaced behavior. The `FORCENAMESPACED` feature was added later in the project and to ensure backward compatibility it isn't enabled by default.

**Comment by aramase** [comment]
Closing this issue. Please feel free to re-open if you have any other questions.
