### ISSUE TITLE
Not able to install aad-pod-identity using helm

### ISSUE THREAD

**Issue by svangeti** [Azure/aad-pod-identity#720]
**Describe the bug**
I am not able install aad-pod-identity for AGIC setup. Getting the below error
`Error: rendered manifests contain a resource that already exists. Unable to continue with install: AzurePodIdentityException "aks-addon-exception" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "aad-pod-identity"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default"`
**Steps To Reproduce**
run `helm install aad-pod-identity aad-pod-identity/aad-pod-identity`
**Expected behavior**
Should install install aad-pod-identity
**AAD Pod Identity version**

**Kubernetes version**
1.15.11
**Additional context**
Just followed the instructions for setup from READ ME.

**Comment by aramase** [comment]
@svangeti I just tried the latest helm charts and they deploy fine - 

```
➜ helm repo update
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "aad-pod-identity" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈

➜ helm install pi aad-pod-identity/aad-pod-identity
NAME: pi
LAST DEPLOYED: Thu Jul 30 13:13:02 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

> Error: rendered manifests contain a resource that already exists. Unable to continue with install: AzurePodIdentityException "aks-addon-exception" in namespace "kube-system" exists and cannot be imported into the current release: invalid ownership metadata

This error indicates the `aks-addon-exception` AzurePodIdentityException was already created before. Helm complains if the resource already exists. Did you install `aad-pod-identity` before using `kubectl apply -f`?

**Comment by svangeti** [comment]
hi @aramase - Yes, I have run the following, before installing helm as per the instructions.

https://github.com/Azure/aad-pod-identity#1-deploy-aad-pod-identity
```
kubectl apply -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml

# For AKS clusters, deploy the MIC and AKS add-on exception by running -
kubectl apply -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/mic-exception.yaml
```
BTW, my AKS cluster has RBAC and Identity enabled. Could that be a problem?

**Comment by aramase** [comment]
@svangeti This section - https://github.com/Azure/aad-pod-identity#1-deploy-aad-pod-identity provides different ways of installing `aad-pod-identity`. If you've already installed using 

```
Deploy aad-pod-identity components to an RBAC-enabled cluster:

kubectl apply -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml

# For AKS clusters, deploy the MIC and AKS add-on exception by running -
kubectl apply -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/mic-exception.yaml
```

then you don't need to install with helm

**Comment by svangeti** [comment]
> @svangeti This section - https://github.com/Azure/aad-pod-identity#1-deploy-aad-pod-identity provides different ways of installing `aad-pod-identity`. If you've already installed using
> 
> ```
> Deploy aad-pod-identity components to an RBAC-enabled cluster:
> 
> kubectl apply -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml
> 
> # For AKS clusters, deploy the MIC and AKS add-on exception by running -
> kubectl apply -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/mic-exception.yaml
> ```
> 
> then you don't need to install with helm

Got it. Thanks Anish @aramase
