### ISSUE TITLE
aad-pod-identity-mic restarted with error retrieving resource lock default/aad-pod-identity-mic: etcdserver: request timed out

### ISSUE THREAD

**Issue by krishnadce** [Azure/aad-pod-identity#723]
**Describe the bug**
aad-pod-identity-mic pod is intermittently restarting. I found the below in the pod logs.

`I0711 14:52:53.670605       1 leaderelection.go:242] attempting to acquire leader lease  default/aad-pod-identity-mic...
E0728 16:07:09.263954       1 leaderelection.go:331] error retrieving resource lock default/aad-pod-identity-mic: etcdserver: request timed out
E0728 19:37:55.906586       1 leaderelection.go:331] error retrieving resource lock default/aad-pod-identity-mic: rpc error: code = Unavailable desc = transport is closing
E0803 05:46:58.721755       1 leaderelection.go:331] error retrieving resource lock default/aad-pod-identity-mic: etcdserver: request timed out
E0803 05:49:14.960865       1 leaderelection.go:331] error retrieving resource lock default/aad-pod-identity-mic: etcdserver: request timed out`

And pod status:

`kubectl get pods`
`NAME                                                      READY   STATUS    RESTARTS   AGE`
`aad-pod-identity-mic-57dbd9f4fb-bnkl4                     1/1     Running   5          22d`
`aad-pod-identity-mic-57dbd9f4fb-r24dv                     1/1     Running   0          22d`
`aad-pod-identity-nmi-2wzq9                                1/1     Running   0          22d`
`aad-pod-identity-nmi-62c4n                                1/1     Running   0          22d`
`aad-pod-identity-nmi-7btkp                                1/1     Running   0          22d`
`aad-pod-identity-nmi-7txz2                                1/1     Running   0          22d`
`aad-pod-identity-nmi-jrvcc                                1/1     Running   0          22d`
`aad-pod-identity-nmi-kg7qj                                1/1     Running   0          22d`

**Steps To Reproduce**
1. Installed AADPodidentity using the helm as follows.
helm repo add aad-pod-identity https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts
helm install aad-pod-identity aad-pod-identity/aad-pod-identity
2. Create Azure Managed Identity and fill the values in AzureIdentity.yaml and AzureIdentityBinding.yaml files and apply them 
kubectl apply -f aadpodidentity.yaml
kubectl apply -f aadpodidentitybinding.yaml

**Expected behavior**
1. no restart of mic pod with etcdserver errors.

**AAD Pod Identity version**
mcr.microsoft.com/k8s/aad-pod-identity/mic:1.6.1

**Kubernetes version**
1.17.7

**Additional context**

**Comment by aramase** [comment]
> I0711 14:52:53.670605 1 leaderelection.go:242] attempting to acquire leader lease default/aad-pod-identity-mic... E0728 16:07:09.263954 1 leaderelection.go:331] error retrieving resource lock default/aad-pod-identity-mic: etcdserver: request timed out E0728 19:37:55.906586 1 leaderelection.go:331] error retrieving resource lock default/aad-pod-identity-mic: rpc error: code = Unavailable desc = transport is closing E0803 05:46:58.721755 1 leaderelection.go:331] error retrieving resource lock default/aad-pod-identity-mic: etcdserver: request timed out E0803 05:49:14.960865 1 leaderelection.go:331] error retrieving resource lock default/aad-pod-identity-mic: etcdserver: request timed out

MIC runs as a deployment with 2 pods, 1 leader and other backup. This pod is backup and is trying to check if it needs to take over as leader, but looks like there might be some issue with this host. 

I would look at resource usage on the host, this is probably a CPU exhaustion or disk I/O issue?

**Comment by krishnadce** [comment]
Thank you Anish. I checked the CPU, Memory usage on the nodes is very low. 

`NAME                                 CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%`
`aks-sccommon-29270115-vmss000001     101m         1%     8244Mi          16%`
`aks-sccommon-29270115-vmss000002     130m         1%     7927Mi          15%`

I checked in Azure portal as well, CPU usage is low. Even disk I/O is low. read ops are 0. and write ops at max. 2/s.

This restarted again twice today. I see a different message in the logs. 

`I0804 08:14:29.661057       1 mic.go:238] Initiating MIC Leader election`
`I0804 08:14:29.706101       1 leaderelection.go:242] attempting to acquire leader lease  default/aad-pod-identity-mic...`
`E0804 08:14:35.320455       1 leaderelection.go:331] error retrieving resource lock default/aad-pod-identity-mic: Get "https://<>:443/api/v1/namespaces/default/endpoints/aad-pod-identity-mic": http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""`

**Comment by aramase** [comment]
I think this is coming from the Kubernetes client code failing to watch the apiserver. It's likely due to the apiserver being up but not yet ready to server requests (this adds to the fact that it appears to be transient).

**Comment by krishnadce** [comment]
ok. But being transient, does this cause MIC to restart? Will MIC retry?

Also, I can't find the termination message when the MIC restarts? Can you help how to find the reason for the pod to restart?

**Comment by aramase** [comment]
> ok. But being transient, does this cause MIC to restart? Will MIC retry?

What do you see in the describe output for the MIC pod? Yes, the client libraries in MIC retry failed connection requests. 

1. `kubectl describe pod <mic pod>`
2. `kubectl logs <mic pod> -p`

**Comment by krishnadce** [comment]
Please find the o/p of the describe and logs:

> kubectl describe pod aad-pod-identity-mic-57dbd9f4fb-bnkl4
Name:               aad-pod-identity-mic-57dbd9f4fb-bnkl4
Namespace:          sc-system
Priority:           0
PriorityClassName:  <none>
Node:               aks-sccommon-29270115-vmss000000/10.6.1.51
Start Time:         Sat, 11 Jul 2020 20:22:45 +0530
Labels:             app.kubernetes.io/component=mic
                    app.kubernetes.io/instance=aad-pod-identity
                    app.kubernetes.io/managed-by=Helm
                    app.kubernetes.io/name=aad-pod-identity
                    helm.sh/chart=aad-pod-identity-2.0.0
                    pod-template-hash=57dbd9f4fb
Annotations:        <none>
Status:             Running
IP:                 10.6.1.229
Controlled By:      ReplicaSet/aad-pod-identity-mic-57dbd9f4fb
Containers:
  mic:
    Container ID:  docker://acf8b6505216e2959a7a6c38f1e5cb269dbfc508284ce3972652676fa8029ff8
    Image:         mcr.microsoft.com/k8s/aad-pod-identity/mic:1.6.1
    Image ID:      docker-pullable://mcr.microsoft.com/k8s/aad-pod-identity/mic@sha256:bd9465be94966b9a917e1e3904fa5e63dd91772ccadf304e18ffd8e4ad8ccedd
    Port:          <none>
    Host Port:     <none>
    Args:
      --cloudconfig=/etc/kubernetes/azure.json
      --logtostderr
    State:          Running
      Started:      Tue, 04 Aug 2020 13:44:29 +0530
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Tue, 04 Aug 2020 13:44:07 +0530
      Finished:     Tue, 04 Aug 2020 13:44:13 +0530
    Ready:          True
    Restart Count:  7
    Limits:
      cpu:     200m
      memory:  1Gi
    Requests:
      cpu:     100m
      memory:  256Mi
    Liveness:  http-get http://:8080/healthz delay=10s timeout=1s period=5s #success=1 #failure=3
    Environment:
      MIC_POD_NAMESPACE:  sc-system (v1:metadata.namespace)
      FORCENAMESPACED:    false
    Mounts:
      /etc/kubernetes/azure.json from k8s-azure-file (ro)
      /etc/kubernetes/certs from certificates (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from aad-pod-identity-mic-token-wqtm6 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  certificates:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/certs
    HostPathType:
  k8s-azure-file:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/azure.json
    HostPathType:
  aad-pod-identity-mic-token-wqtm6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  aad-pod-identity-mic-token-wqtm6
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

=================================
LOGS

> kubectl logs aad-pod-identity-mic-57dbd9f4fb-bnkl4 -n sc-system --tail 100                                                I0804 08:14:29.638927       1 main.go:101] Starting mic process. Version: 1.6.1. Build date: 2020-05-22-17:50
W0804 08:14:29.638980       1 main.go:106] --kubeconfig not passed will use InClusterConfig
I0804 08:14:29.638988       1 main.go:120] kubeconfig () cloudconfig (/etc/kubernetes/azure.json)
I0804 08:14:29.639125       1 main.go:128] Running MIC in namespaced mode: false
I0804 08:14:29.639144       1 main.go:132] Client QPS set to: 5. Burst to: 5
I0804 08:14:29.639159       1 mic.go:136] Starting to create the pod identity client. Version: 1.6.1. Build date: 2020-05-22-17:50
I0804 08:14:29.660405       1 mic.go:142] Kubernetes server version: v1.17.7
I0804 08:14:29.660671       1 cloudprovider.go:126] MIC using user assigned identity: 7159##### REDACTED #####f585 for authentication.
I0804 08:14:29.660929       1 probes.go:42] Initialized health probe on port 8080
I0804 08:14:29.660944       1 probes.go:45] Started health probe
I0804 08:14:29.661005       1 metrics.go:329] Registered views for metric
I0804 08:14:29.661040       1 prometheus_exporter.go:22] Starting Prometheus exporter
I0804 08:14:29.661053       1 metrics.go:336] Registered and exported metrics on port 8888
I0804 08:14:29.661057       1 mic.go:238] Initiating MIC Leader election
I0804 08:14:29.706101       1 leaderelection.go:242] attempting to acquire leader lease  default/aad-pod-identity-mic...
E0804 08:14:35.320455       1 leaderelection.go:331] error retrieving resource lock default/aad-pod-identity-mic: Get "https://10.199.164.1:443/api/v1/namespaces/default/endpoints/aad-pod-identity-mic": http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""

**Comment by aramase** [comment]
Synced with @krishnadce offline. 

There are `etcdserver: request timed out` errors in API server logs at the same time frame when MIC is forced to restart. Next step is checking with support on why there is a time out error.
 
```
E0813 13:46:46.849009       1 status.go:71] apiserver received an error that is not an metav1.Status: rpctypes.EtcdError{code:0xe, desc:""etcdserver: request timed out""}

…

E0813 13:46:48.024738       1 status.go:71] apiserver received an error that is not an metav1.Status: rpctypes.EtcdError{code:0xe, desc:""etcdserver: request timed out""}

```

**Comment by aramase** [comment]
@krishnadce Did you check with support on what the issue was? Could you add a note here on what the support folks responded with? It'll be helpful for other users who come across the same issue.

Closing this issue for now. Please feel free to reopen if you have any questions.

**Comment by krishnadce** [comment]
@aramase The support didn't find the root cause yet and the MIC pod is still restarting. They found that AKS has updated pods running in the master nodes that are maintained by Azure on a later date. And the health check shows healthy. But they could not explain how this caused the API Server/etcd operator errors.  I will update this thread once they found the cause.

`2020-08-14 13:18:20.0000000  Updating UpdatingEtcdOperator UnderlayAPIServerError Unhealthy Unhealthy 0 Succeeded SupportedState: "Supported" PodState: "Error listing pods on underlay: Get https://172.30.0.1:443/api/v1/namespaces/5f09ad90715ed9000170afec/pods: net/http: request canceled (Client.Timeout exceeded while awaiting headers)" `

**Comment by krishnadce** [comment]
There is an update from Azure support. They found that AAD PodIdentity MIC pod restart 2 seconds after etcd timeout errors.  He confirmed that it's normal to occasionally have timeout in apiserver and it won't affect any performance. They have plans to improve etcd performance.
His suggestion is not let timeout to restart your pod or at least retry.
