### ISSUE TITLE
Document deletion and re-creation of identity with same name

### ISSUE THREAD

**Issue by aramase** [Azure/aad-pod-identity#725]

**Comment by galvesribeiro** [comment]
@aramase while the docs aren't out, what do we need to do after delete and re-creation?

**Comment by aramase** [comment]
@galvesribeiro If the identity is deleted and recreated with the same name, then the identity is considered as a completely new identity by VM/VMSS. However VM/VMSS doesn't automatically update the `clientID` for the identity. The `clientID` and `principalID` are null which means they can't be used. There is an item in their backlog to automatically update the identity assigned to the VM/VMSS when the `clientID` changes. 

Steps to take if the identity was deleted and re-created with same name -
1. Remove identity manually from the VMSS by `az vmss identity remove -g <rg> -n <vmss name> --identities <identity resource id>
2. Then update the `AzureIdentity` with the new `clientID` for the recreated identity
3. MIC should see this change in `AzureIdentity` and re-assign the correct identity as the identity was removed in step 1

**Comment by galvesribeiro** [comment]
Ok thanks! That will help a lot!

**Comment by galvesribeiro** [comment]
@aramase 

I've just tried your steps and it don't work for me :/

NMI keeps looping with whis:

```
nmi
E0811 21:32:52.858835 1 server.go:341] failed to get pod info from pod IP: 100.64.1.68, error failed to match pod IP 100.64.1.68 with []
nmi
I0811 21:32:52.858868 1 server.go:190] status (500) took 1200835565 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=100.64.1.68
nmi
W0811 21:32:54.692867 1 client.go:207] list pod error: . Retrying, attempt number: 1
nmi
W0811 21:32:54.993030 1 client.go:207] list pod error: . Retrying, attempt number: 2
nmi
W0811 21:32:55.293254 1 client.go:207] list pod error: . Retrying, attempt number: 3
nmi
W0811 21:32:55.593427 1 client.go:207] list pod error: . Retrying, attempt number: 4
nmi
E0811 21:32:55.893653 1 server.go:341] failed to get pod info from pod IP: 100.64.1.68, error failed to match pod IP 100.64.1.68 with []
nmi
I0811 21:32:55.893688 1 server.go:190] status (500) took 1200848064 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=100.64.1.68
```

After that I've just followed the following steps to try get to an stable state:
1. Completely removed the application chart with `helm uninstall`; (only if you are using Helm)
2. Deleted the identity from AAD;
3. Make sure no residual AzureIdentity or binding CRD instances still lingering around from previous deployment;
4. Removed the "unknown entity" that appears on the VMSS resource group which used to be the identity you just deleted on step 2;
5. Recreated the identity (and the VMSS resource group assignment);
6. Restart NMI pods;
7. Redeploy the app (`helm install`).

It _only_ worked if we restart the NMI pods by killing them all and wait the restart....

**Comment by aramase** [comment]
@galvesribeiro The error you're seeing is #730 that you already have open. But deleting and re-creating identities with the same name only require the 2 steps I added above. For #730, I was unable to repro the issue. 

@chewong is also trying it out on a 1.17.9 cluster with restricted egress. 

The NMI pod looks up the pod name and namespace based on the pod IP. It gets the list of pods from the cache which is populated periodically and loops through the list to find the pod that matches the IP. However in this particular case, there seems to be no pod that's matching the pod IP in the cache. The cache is kept up-to date by Kubernetes client-go. Are there any errors related to watch/connecting to API server.

**Comment by galvesribeiro** [comment]
@aramase but that happens when I remove and try to reinstall the same app (without removing the identity as I mentioned here). I was only able to get it to work following those steps, including kill the NMI pods.

**Comment by aramase** [comment]
@galvesribeiro Does it always happen when you remove and re-install the app? This is Kubernetes specific error and this shouldn't require deletion and re-creation of identity. Restarting NMI will force client-go to refetch the new cache from the API server. But if you see the error every time you remove and re-install the new app, that could be interesting. When you check the error, can you see the pod IP for the pod making the request using `kubectl get pods -o wide`? And also, could you try to run curl command from within the pod to fetch the token repeatedly to see if it ever succeeds when the error happens. You should be able to exec into the pod and run the command as such - https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#get-a-token-using-curl

**Comment by galvesribeiro** [comment]
> Does it always happen when you remove and re-install the app? 

Yep. 

I'll try that and report back later on.
