### ISSUE TITLE
NMI in crashLoopBackOff state in AKS 1.16.10 possible I.P tables issue

### ISSUE THREAD

**Issue by asubmani** [Azure/aad-pod-identity#728]
**Describe the bug**
NMI pods in `crashLoopBackOff` state after deployment. MIC pods are running fine.
This is a new AKS Cluster with only Flux and NGINX on it.

**Steps To Reproduce**
Install aadpodidentity in AKS 1.16.10, AKS VNET in a different resource group

**Expected behavior**
NMI should not crash
**AAD Pod Identity version**
1.6.2

**Kubernetes version**
1.16.10 on Ubuntu 16.04 (default)
VMSS option
**Additional context**
kubelet logs at one of the nodes are full with below:

```shell
I0725 01:47:12.258478    3677 kubelet_network_linux.go:111] Not using `--random-fully` in the MASQUERADE rule for iptables because the local version of iptables does not support it
I0725 01:48:12.277486    3677 kubelet_network_linux.go:111] Not using `--random-fully` in the MASQUERADE rule for iptables because the local version of iptables does not support it
I0725 01:49:12.295451    3677 kubelet_network_linux.go:111] Not using `--random-fully` in the MASQUERADE rule for iptables because the local version of iptables does not support it
I0725 01:50:12.314825    3677 kubelet_network_linux.go:111] Not using `--random-fully` in the MASQUERADE rule for iptables because the local version of iptables does not support it
I0725 01:51:11.408593    3677 container_manager_linux.go:468] [ContainerManager]: Discovered runtime cgroups name: /system.slice/docker.service
I0725 01:51:12.332172    3677 kubelet_network_linux.go:111] Not using `--random-fully` in the MASQUERADE rule for iptables because the local version of iptables does not support it
I0725 01:52:12.351680    3677 kubelet_network_linux.go:111] Not using `--random-fully` in the MASQUERADE rule for iptables because the local version of iptables does not support it
```

**Comment by asubmani** [comment]
To test, I added a new NodePool with just 1 VM and the issue persists. 
Does AKS support manually updating the iptables version ? I see it is at 1.6.0

**Comment by aramase** [comment]
What is the error in the NMI logs? 

> Does AKS support manually updating the iptables version ? I see it is at 1.6.0

I don't believe there is an option to update the iptables version (although I believe this could be done by running a pod with privilege and updating it), but this will be a good question for AKS team.

I've a cluster with `v1.6.1` of iptables and the install works fine - 

```
root@k8s-master-19789384-0:/# iptables --version
iptables v1.6.1
```

**Comment by asubmani** [comment]
I found the issue. Seems like the args for nmi changed between 1.6.1 to 1.6.2

When I reverted to aadpodidentity version 1.6.1, things started working fine.

## nmi:1.6.1 has the below arguments:
```yaml
        args:
          - "--host-ip=$(HOST_IP)"
          - "--node=$(NODE_NAME)"
```
## #  This doesn't work with 1.6.2 and the below error is logged in nmi
```shell
unknown flag: --host-ip
Usage of nmi:
unknown flag: --host-ip
      --MICNamespace string                MIC namespace to short circuit MIC token requests (default "default")
```
## nmi args have been changed to below as per [this sample](https://github.com/Azure/aad-pod-identity/blob/master/deploy/infra/deployment-rbac.yaml) :

```yaml
args:
          - "--node=$(NODE_NAME)"
          - "--http-probe-port=8085"
```
After removing the `--host-ip arg` and adding `--http-probe-port=8085` nmi is working

Need to validate functionality now

**Comment by aramase** [comment]
@asubmani That's right. NMI only listens on `127.0.0.1` from 1.6.2 instead of listening on the node IP which is more secure. The `--host-ip` flag is no longer required. It has been deprecated and removed.

**Comment by asubmani** [comment]
> Need to validate functionality now


Ok I replied too soon. NMI is still terminating (Just not immediate)
# NMI Logs 
```shell
I0807 15:27:09.931719       1 main.go:60] starting nmi process. Version: 1.6.2. Build date: 2020-07-24-20:26.
I0807 15:27:10.136002       1 crd.go:444] CRD lite informers started 
I0807 15:27:10.136028       1 main.go:87] running NMI in namespaced mode: false
I0807 15:27:10.136038       1 nmi.go:52] initializing in standard mode
I0807 15:27:10.136044       1 probes.go:41] initialized health probe on port 8085
I0807 15:27:10.136050       1 probes.go:44] started health probe
I0807 15:27:10.136176       1 metrics.go:329] registered views for metric
I0807 15:27:10.136271       1 prometheus_exporter.go:21] starting Prometheus exporter
I0807 15:27:10.136281       1 metrics.go:335] registered and exported metrics on port 9090
I0807 15:27:10.136295       1 server.go:96] listening on port 2579
W0807 15:27:10.343316       1 iptables.go:123] flushing iptables to add aad-metadata custom chains
I0807 15:27:30.032938       1 server.go:527] received SIGTERM, shutting down
I0807 15:27:30.043863       1 server.go:537] handled termination, awaiting pod deletion
I0807 15:27:40.044157       1 server.go:540] exiting with 0
```
I am reverting back to 1.6.1 with `--host-ip` arg

**Comment by asubmani** [comment]
> @asubmani That's right. NMI only listens on `127.0.0.1` from 1.6.2 instead of listening on the node IP which is more secure. The `--host-ip` flag is no longer required. It has been deprecated and removed.

Thanks @aramase. Shouldn't this be listed as a breaking change?

**Comment by oliverholliday** [comment]
This second set of logs is the behaviour I got too when I upgraded from 1.6.1 to 1.6.2 on kubernetes 1.16.10 (haven't done the command line changes).

**Comment by aramase** [comment]
> Thanks @aramase. Shouldn't this be listed as a breaking change?

@asubmani Typically release manifests are tagged with releases. Just updating the image with the old deployment yaml doesn't work in most of the scenarios as new permissions are added/there are yaml changes. The removal of hostIP is documented in the changelog.

**Comment by aramase** [comment]
> W0807 15:27:10.343316       1 iptables.go:123] flushing iptables to add aad-metadata custom chains
I0807 15:27:30.032938       1 server.go:527] received SIGTERM, shutting down

That indicates NMI is failing liveness probe check and is being restarted by Kubernetes. What do you see in the describe output for the pod?

**Comment by aramase** [comment]
@asubmani If you're manually changing the deployment with the image, I believe the port is not configured right. The health check probe port is configured in 2 places - 

https://github.com/Azure/aad-pod-identity/blob/e8fe01f0860647ed4c6abbcc65513dd554eae8e6/deploy/infra/deployment-rbac.yaml#L128

https://github.com/Azure/aad-pod-identity/blob/e8fe01f0860647ed4c6abbcc65513dd554eae8e6/deploy/infra/deployment-rbac.yaml#L156

If you added `--http-probe-port=8085`, please also make sure the ports match. Updating using the yaml should resolve this issue.

**Comment by aramase** [comment]
@asubmani confirmed offline that the port change in the yaml resolved the problem. Closing this issue. Please feel free to reopen if you have any questions.
