### ISSUE TITLE
MIC Pods won't start - Liveness probe failed

### ISSUE THREAD

**Issue by rlevchenko** [Azure/aad-pod-identity#729]
**Describe the bug**

MIC pods are in the _crashLoopBackOff_ state just after initial deployment. However, NMI pods are running fine. I'm using the latest available AKS 1.17.9.  Azure AKS is private, plus egress traffic is filtered by NVA (necessary rules for AKS egress are configured on the NVA).  aad-pod-identity is deployed using helm in the kube-system namespace, default configuration (no custom args have been specified) 

kubectl describe mic pod:

`Warning  Unhealthy  11m (x19 over 16m)  kubelet, aks-apppool-xxxx  Liveness probe failed: Get http://xxxx:8080/healthz: dial tcp xxxx:8080: connect: connection refused`

Meantime, the mic pods logs are fine.

Possible reasons - iptables/aks private cluster/nva (although, my demo and similar setup on _1.16.10_ doesn't have such issues)

**Steps To Reproduce**

1) Deploy the add-pod-idenity using helm or kubectl
2) Check pods status after 5 mins

**Expected behavior**

MIC pods liveness probe should be in a healthy state

**AAD Pod Identity version**

1.16.2 (also tried 1.16.1 and helm/apply methods)

**Kubernetes version**

1.17.9 (Azure AKS)

**Additional context**

I'll provide kubelet logs a bit later. Maybe someone had the same issues and could help while I get logs)

**Comment by galvesribeiro** [comment]
@rlevchenko I have similar setup (AKS 1.17.9 with restricted egress by Azure Firewall) and after upgrading to 1.17.9 aad-pod-identity stopped to work (see #730). Not exactly same issue as yours, but funny that it was working fine before 1.17.9 upgrade. Will keep an eye here in case something comes up for you.

**Comment by rlevchenko** [comment]
@galvesribeiro thanks for your input. In my demo setup with AKS 1.16.10 , I've not had any issues with private cluster, nva, ingress and aad-pod-identity . They have worked fine. Probably, AKS 1.17.x introduced some breaking changes. I will check that and try to reproduce the liveness failure in my demo though. In your case, is the mic exception configured?

**Comment by galvesribeiro** [comment]
Yeah, I just noticed my ingress (App Gateway Ingress) started to behave weirdly after the upgrade.

**Comment by aramase** [comment]
@rlevchenko Do you see started health probe logs in the MIC pod logs? 

```
I0810 15:45:02.364276       1 probes.go:41] initialized health probe on port 8080
I0810 15:45:02.364290       1 probes.go:44] started health probe
```

Also, could you post MIC pod logs with `-p` so we can see the logs from previous container? MIC reports ready when it's successfully able to communicate to the API server and has initialized all the client caches. 

> Yeah, I just noticed my ingress (App Gateway Ingress) started to behave weirdly after the upgrade.

@galvesribeiro What is the issue you're seeing with app gateway?

**Comment by rlevchenko** [comment]
@aramase thanks for response! I couldn't reproduce the error in my demo setup - pods are running fine. I think the issue is related to NVA config since the "MIC reports ready when it's successfully able to communicate to the API server and has initialized all the client caches". Give me 5 mins, I will gather the logs from the prod.

**Comment by galvesribeiro** [comment]
@aramase sometimes it isn't able to get in touch with ARM to update the AppGateway with similar errors saying that the pod names doesn't match and then get 500 status code as I pointed on #730.

In order to make it work, I have to:

1. I remove the Managed Identity created for the service/pod and create a new one with a different name;
2. `helm upgrade...` with `--force`

That way it works again. But it is really annoying that every time we do an upgrade or reboot a node we do have to do that...

**Comment by aramase** [comment]
@galvesribeiro I don't think you need to delete and recreate a new managed identity. Does just restarting the NMI pods resolve the issue? NMI uses the Kubernetes client-go cache informers to get the pod name and namespace based on the src IP in the token request. It performs a list of pods on the node, filters using the pod IP to get the name. However in the error posted, it looks like there was no pod found in the list of the pods API server returns with the matching pod IP. If it is an issue with the cache in `client-go`, then restarting the NMI pod should resolve the issue.

**Comment by rlevchenko** [comment]
@aramase nothing special

```
0810 16:03:13.747668       1 main.go:101] starting mic process. Version: 1.6.2. Build date: 2020-07-24-20:25
W0810 16:03:13.747717       1 main.go:106] --kubeconfig not passed will use InClusterConfig
I0810 16:03:13.747728       1 main.go:123] kubeconfig () cloudconfig (/etc/kubernetes/azure.json)
I0810 16:03:13.748700       1 main.go:131] running MIC in namespaced mode: false
I0810 16:03:13.748717       1 main.go:135] client QPS set to: 5. Burst to: 5
I0810 16:03:13.748736       1 mic.go:136] starting to create the pod identity client. Version: 1.6.2. Build date: 2020-07-24-20:25
```

**Comment by aramase** [comment]
@rlevchenko If no `kubeconfig` is provided, then `InClusterConfig` is used to initialize the Kubernetes clients. Is this all the logs from the pod that crashed? It looks like the call to initialize the client never returned. The http server for liveness probe is started after initializing the client which is missing in the logs you posted. 

For example, these are the logs from my cluster -

```
I0810 15:45:03.215354       1 main.go:101] starting mic process. Version: 1.6.2. Build date: 2020-07-24-20:25
W0810 15:45:03.215421       1 main.go:106] --kubeconfig not passed will use InClusterConfig
I0810 15:45:03.215428       1 main.go:123] kubeconfig () cloudconfig (/etc/kubernetes/azure.json)
I0810 15:45:03.215547       1 main.go:131] running MIC in namespaced mode: false
I0810 15:45:03.215556       1 main.go:135] client QPS set to: 5. Burst to: 5
I0810 15:45:03.215571       1 mic.go:136] starting to create the pod identity client. Version: 1.6.2. Build date: 2020-07-24-20:25
I0810 15:45:03.239205       1 mic.go:142] Kubernetes server version: v1.17.9
I0810 15:45:03.244398       1 probes.go:41] initialized health probe on port 8080
I0810 15:45:03.244418       1 probes.go:44] started health probe
I0810 15:45:03.244513       1 metrics.go:329] registered views for metric
I0810 15:45:03.244550       1 prometheus_exporter.go:21] starting Prometheus exporter
I0810 15:45:03.244560       1 metrics.go:335] registered and exported metrics on port 8888
I0810 15:45:03.244564       1 mic.go:236] initiating MIC Leader election
I0810 15:45:03.244576       1 leaderelection.go:242] attempting to acquire leader lease  default/aad-pod-identity-mic...
I0810 15:45:24.520021       1 leaderelection.go:252] successfully acquired lease default/aad-pod-identity-mic
I0810 15:45:24.523758       1 mic.go:323] type upgrade status configmap found from version: 1.6.2. Skipping type upgrade!
I0810 15:45:24.624061       1 crd.go:453] CRD informers started
I0810 15:45:24.824041       1 pod.go:72] pod cache synchronized. Took 300.2245ms
I0810 15:45:24.824065       1 pod.go:79] pod watcher started !!
I0810 15:45:25.124072       1 mic.go:390] sync thread started.
```

**Comment by galvesribeiro** [comment]
> @galvesribeiro I don't think you need to delete and recreate a new managed identity. Does just restarting the NMI pods resolve the issue? NMI uses the Kubernetes client-go cache informers to get the pod name and namespace based on the src IP in the token request. It performs a list of pods on the node, filters using the pod IP to get the name. However in the error posted, it looks like there was no pod found in the list of the pods API server returns with the matching pod IP. If it is an issue with the cache in `client-go`, then restarting the NMI pod should resolve the issue.

I tried that, and it didn't worked. The way to get around it was to delete the old identity and create a new one with a different name. :/

**Comment by rlevchenko** [comment]
@aramase I have the same logs in my demo and dev envs. MIC pods are only being failed on the prod where NVA is presented to. I don't access to NVA though. What's a sample request MIC does? just http to the Azure AKS API?

**Comment by aramase** [comment]
@rlevchenko Right, it establishes a connection to the API server using the `KUBERNETES_HOST` env var that's defined in side the MIC pods.

**Comment by aramase** [comment]
> I tried that, and it didn't worked. The way to get around it was to delete the old identity and create a new one with a different name. :/

Was the application pod restarted too when you tried restarting NMI?

**Comment by galvesribeiro** [comment]
Yes, I restarted it after the all the aad-pod-identity pods (not just NMI) were restarted.

Btw, by restart, I meant delete the pods.

**Comment by rlevchenko** [comment]
@aramase thanks for the help. It was DNS connectivity problem between aks pools (as expected.). After adding rules to NVA - aad-pod-identity are running fine.
