### ISSUE TITLE
az login --identity returns 'MSI_ENDPOINT'  was not found

### ISSUE THREAD

**Issue by kenans** [Azure/aad-pod-identity#731]
**Describe the bug**
Running `az login --identity` within a pod labeled `aadpodidbinding`, it says,
```
msrestazure.azure_active_directory : 'MSI_ENDPOINT' required env variable was not found. You might need to restart your app/function
```

Note the container base image is debian and I ran apt installed the Azure CLI. 

I've checked `nmi` logs and `azureassignedidentities` and they all look good. I also verified that the MSI had been assigned to the cluster VMSS so this shouldn't be problematic either. 

I've been using the pod identity with the KV CSI driver and it works well. Right now I'm trying to get the MSI from the pods but it failed. 

BTW, I was wondering if `aad-pod-identity` allows multiple `AzureIdentity`s to be created and working on the cluster?

**Steps To Reproduce**
See above.

**Expected behavior**
`az login --identity` should succeed with the MSI that's linked to the `AzureIdentity`.

**AAD Pod Identity version**
2.0.1

**Kubernetes version**
1.16.10

**Additional context**
NA

**Comment by chewong** [comment]
Could you run `az login --identity --debug` and also paste the logs of the NMI pod that is running in the same node as your pod?

Yes, aad-pod-identity does allow multiple AzureIdentities assigned to a pod. You can achieve that by using the same `aadpodidbinding` label for all of them.

**Comment by kenans** [comment]
Thank you for the response. I just tested with `microsoft/azure-cli` as base image and it works well. But just using `ubuntu` then [installing Azure CLI manaually](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-apt?view=azure-cli-latest), it doesn't work. I guess it is either the problem with Azure CLI or with the environment. I'm cool with the issue since I can get it work now.

For the other question, just to confirm, when saying  

> You can achieve that by using the same aadpodidbinding label for all of them.

do you mean something like this,
```
      labels:
        aadpodidbinding: az-id-1
        aadpodidbinding: az-id-2
        ...
```

**Comment by chewong** [comment]
I figured that it'd be an Azure CLI issue.

You would want to create two AzureIdentityBindings, something like this
```yaml
...
spec:
  azureIdentity: az-id-1
  selector: az-id-selector
...
```

```yaml
...
spec:
  azureIdentity: az-id-2
  selector: az-id-selector
...
```

Then, in your pod spec:

In your pod spec, you would have something like:
```yaml
labels:
  aadpodidbinding: az-id-selector
```

**Comment by chewong** [comment]
Closing this issue for now. Feel free to open a new issue if you have more questions.
