### ISSUE TITLE
MIC only sporadically assigning identities to pods

### ISSUE THREAD

**Issue by lpghartz** [Azure/aad-pod-identity#732]
This is a weird issue, so its hard to even figure out where something might be failing. We've been testing aad-pod-identity as part of migrating service hosting for one of our products from Azure ASE to Kubernetes for a few weeks now. The product relies on MSI in ASE, and we needed aad-pod-identity to allow us to access Azure services without having to refactor code, as well as to pull secrets from KeyVault. 

Its been working fine for a couple weeks, but starting a couple of days ago, all of our test clusters -- some of which hadn't been updated since early last week -- had MIC fail on us when we pushed out a deployment that caused pods to be recycled. The new pods in the existing cluster couldn't retrieve identities -- NMI would return a 404 error. 

MIC was basically not picking up any changes -- it wasn't responding to events at all. 

We've deleted the resource groups and clusters a few times in the last couple of days trying to figure out what is going on, and the problem seems to be consistent. Our clusters all are created from scripts, so the test clusters today are identically configured to the ones a week ago.  What we've found is that we (generally) get identities assigned correctly on a brand new cluster. But after that happens, we never do again. There's no MIC logging showing up at all when the pod states change.

We just get this:
```
I0811 16:01:14.110326       1 crd.go:453] CRD informers started
I0811 16:01:14.510233       1 pod.go:72] pod cache synchronized. Took 500.20951ms
I0811 16:01:14.510257       1 pod.go:79] pod watcher started !!
I0811 16:01:14.610290       1 mic.go:390] sync thread started.
```

Doing a restart of pods, nothing shows up. Doing a reconfigure, same thing. Nothing shows up.  

If we then delete all the deployments, again nothing shows up. Now, strangely, when we then try re-installing the deployments, it wakes up and attempts to delete the identities assigned to the deployments that were already deleted. But it never adds them to the new ones. In some cases, where the system was cycling through pod deployments rapidly as configurations are getting updated, it'll get further behind. Like logs "now" on an update will have an identity being removed from a pod that has been gone for a few updates. And nothing else.

Restarting MIC via a rollout / restart permanently breaks it -- it no longer responds to anything. Deleting and recreating the cluster from scratch is the only fix we've found. MIC never reports any errors -- when it first works, there are no errors and subsequent to that when it is no longer responding to events, there are also no errors. 

NMI continuously returns the same error:

`E0811 16:35:21.068262       1 server.go:232] failed to get identities, error: getting assigned identities for pod default/apiserver-846fb5c54c-q6v59 in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>`

The clusters are MSI-enabled via --enable-managed-identity, the roles are all correct in the resource groups. (The identities are able to be set once, so that's clearly okay.) 

The aad-pod-identity components are installed via:

```
kubectl apply -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml
kubectl apply -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/mic-exception.yaml
```

The installed version, now and when it was reliably working, both report 1.6.2. The clusters have been Kubernetes 1.18.4.

I recognize this is a lousy bug report, but I'm scratching my head and not really sure what I can do to even get more information. The lack of any errors isn't giving me any clue why MIC just stops handling any cluster updates.

**Comment by aramase** [comment]
@lpghartz Thank you for opening the issue. Could you post the `AzureIdentity` and `AzureIdentityBinding` yamls that you're using? You could enable verbose logging on the MIC pods `-v=5` to see if MIC is receiving events for the new pods that are being created and deleted.

**Comment by lpghartz** [comment]
We have two identities we use, which have differing permissions assigned in Azure. Both show the issue.

They're both created like this:
`echo "Applying AzureIdentity to cluster ..."
cat <<EOF | kubectl apply -f -
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: $IDENTITY_NAME
spec:
  type: 0
  resourceID: $IDENTITY_RESOURCE_ID
  clientID: $IDENTITY_CLIENT_ID
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: $IDENTITY_IDP_NAME
spec:
  type: 0
  resourceID: $IDENTITY_IDP_RESOURCE_ID
  clientID: $IDENTITY_IDP_CLIENT_ID

EOF

echo "Installing AzureIdentityBinding to cluster ..."
cat <<EOF | kubectl apply -f -
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: $IDENTITY_NAME-binding
spec:
  azureIdentity: $IDENTITY_NAME
  selector: $IDENTITY_NAME
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: $IDENTITY_IDP_NAME-binding
spec:
  azureIdentity: $IDENTITY_IDP_NAME
  selector: $IDENTITY_IDP_NAME
EOF
`

I'm assuming the specific ids aren't important.

The AzureAssignedIdentities for the pods that are working are all in the resources. We'll get one, two, or more, depending on how many instances there were for that specific revision. Like, if we have "apiserver-1234567890ab-*" we'll successfully get identities for all of them correctly, but when the deployment recycles and we get "apiserver-234567890abc-*", we never get those assigned. And the first set aren't *unassigned* either. But a 3rd deployment, we'll sometimes get some those first ones removed. Its really weird. Its also especially strange because we can pull from git at a changeset from last week, which were behaving correctly, and they are no longer doing so. 

Re: debugging, I don't know how enabling verbose logging works -- we just install MIC via the yaml at https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml. How/where does that get set?

**Comment by lpghartz** [comment]
Yikes sorry about the weird formatting -- I can't figure out how to get it to not flip out. I guess the code quote stuff doesn't escape things properly.

**Comment by aramase** [comment]
@lpghartz No worries. I edited the formatting. You can add `-v=6` to the args here for MIC - https://github.com/Azure/aad-pod-identity/blob/master/deploy/infra/deployment-rbac.yaml#L238-L240. That should print out more verbose logs in terms of incoming events.

**Comment by lpghartz** [comment]
So that generates a MASSIVE amount of logs. I'm not sure what is of interest. 

What I do find, though, is that the logs are mentioning the pods that aren't getting identities. For example, in my current cluster instance, I have a pod "apiserver-6fdfb9455c-h7nlb".

Pulling the logs from the active MIC node, and grepping for it, I find:

```
I0811 17:51:07.951557       1 mic.go:570] checking pod default/apiserver-6fdfb9455c-h7nlb
I0811 17:51:07.951561       1 mic.go:577] pod: default/apiserver-6fdfb9455c-h7nlb. Label value: cluster-identity
I0811 17:51:07.951567       1 mic.go:585] check the binding (pod - default/apiserver-6fdfb9455c-h7nlb): dev-cluster-idp-id
I0811 17:51:07.951573       1 mic.go:585] check the binding (pod - default/apiserver-6fdfb9455c-h7nlb): dev-cluster-id
```

It repeats that a lot. 

The nodes that have an identity (and, actually, already had them) the logs are different:

```
I0811 17:51:07.950865       1 crd.go:651] added to map with key: apiserver-6548dfcd54-5ht28-default-dev-cluster-id
I0811 17:51:07.951993       1 mic.go:570] checking pod default/apiserver-6548dfcd54-5ht28
I0811 17:51:07.951998       1 mic.go:577] pod: default/apiserver-6548dfcd54-5ht28. Label value: dev-cluster-id
I0811 17:51:07.952003       1 mic.go:585] check the binding (pod - default/apiserver-6548dfcd54-5ht28): dev-cluster-idp-id
I0811 17:51:07.952009       1 mic.go:585] check the binding (pod - default/apiserver-6548dfcd54-5ht28): dev-cluster-id
I0811 17:51:07.952014       1 mic.go:587] found binding match for pod default/apiserver-6548dfcd54-5ht28 with binding default/dev-cluster-id-binding
I0811 17:51:07.952025       1 mic.go:605] identity default/dev-cluster-id assigned to default/apiserver-6548dfcd54-5ht28 via default/dev-cluster-id-binding
I0811 17:51:07.952145       1 mic.go:855] making assigned ID:  *snipped* 
```

So, even ignoring if the system is getting events for the topology changes, it seems to know about the pods that don't have identities... it just doesn't seem to be doing anything about it.  All of the deployments tagged in aadpodidentity in the cluster show the same pattern, so that's just an example of one of them. 

Re: changes in deployment, when it first broke, we noticed when we did a "kubectl rollout restart deployment/apiserver" (to use the above apiserver example, but it happens for all the deployments) to pick up a new build. The cluster itself hadn't changed. Since the, with testing, we've been recreating the cluster over and over, but its generated by the same series of scripts every time. Relative to last week, assuming nothing in AKS updated, it should be identically configured. There's stuff we pull from helms that could potentially have picked up a newer version of stuff (like the CSI secret store stuff, etc) but those are dependent on this, not vice versa.

**Comment by lpghartz** [comment]
Oh crap, I just realized something with those added logs -- the identities are changing. aadpodidentity is changing when we do a rollout restart of the pods. That's... weird. 

So there's something else going on. There is no"cluster-identity". So, other than the potential bug that aad-pod-identity isn't logging an error when something isn't found, this must be related to something else going on.  (Something must be disconnected between the deployment template and the running pods...)

I'll follow-up if it looks like its aad-pod-identity related, but it looks like (thanks to that debugging) its not. 

That said, better error messages (ie, any error messages) would probably help for cases like this!

**Comment by aramase** [comment]
@lpghartz Thank you for the feedback. We'll definitely make some of the logs visible by default instead of the high verbosity level.
