### ISSUE TITLE
Add `namespace: {{ .Release.Namespace }}` to Helm charts

### ISSUE THREAD

**Issue by marchenm** [Azure/aad-pod-identity#737]
**Describe the bug**
When using `helm template  aad-pod-identity aad-pod-identity/aad-pod-identity --namespace non-default | kubectl apply -f -` the namespaced objects are still installed in default. 

**Steps To Reproduce**
 `helm template  aad-pod-identity aad-pod-identity/aad-pod-identity --namespace non-default | kubectl apply -f -`

**Expected behavior**
The namespaced objects should be installed in the appropriate namespace
**AAD Pod Identity version**
n/a
**Kubernetes version**
n/a
**Additional context**
[helm/helm#5455](https://github.com/helm/helm/issues/5465)
[helm/helm#3553](https://github.com/helm/helm/issues/3553)

**Comment by aramase** [comment]
Thank you for the feedback. We'll add the `Release.Namespace` to helm chart.
