### ISSUE TITLE
unable to setup nmi pods 

### ISSUE THREAD

**Issue by jaiawasthi** [Azure/aad-pod-identity#740]
1 probes.go:27] http listen and serve error: listen tcp :8085: bind: address already in use

If i try to use --set nmi.probePort=8081 it  updates health endpoint the it uses
the error now is
server.go:98] error creating http server: listen tcp 127.0.0.1:2579: bind: address already in use
cant find any other port param from charts to use

in continuation of https://github.com/Azure/aad-pod-identity/issues/702

**Comment by aramase** [comment]
@jaiawasthi That could mean there is another process on the host running on `2579` or there is another NMI running on the same host which is using the port. Please check if there is another NMI pod and delete if that's the case. Only one NMI pod is required per host.

**Comment by jaiawasthi** [comment]
Thanks,
aad-pod-identity-nmi-5fswq              0/1     CrashLoopBackOff    49         3h45m
aad-pod-identity-nmi-8mngn              0/1     Error               1          5s
aad-pod-identity-nmi-htxmh              0/1     CrashLoopBackOff    1          9s

I havent changed the default chart parameters, so it shuold still run a single pod per host.
If there is any other process using 2579, is there any way i can change the port nmi uses ?

**Comment by aramase** [comment]
I'm suspecting there is another set of NMI pods that might be running. Could you share the output for `kubectl get pods -A -o wide`?

**Comment by jaiawasthi** [comment]
jaawasth@blade-jb:~$ kubectl get pods -A -o wide | grep nmi
default       aad-pod-identity-nmi-5fswq                           0/1     CrashLoopBackOff    53         4h7m    10.240.0.5     aks-agentpool-15899284-vmss000001   <none>           <none>
default       aad-pod-identity-nmi-8mngn                           0/1     CrashLoopBackOff    9          21m     10.240.0.4     aks-agentpool-15899284-vmss000000   <none>           <none>
default       aad-pod-identity-nmi-htxmh                           0/1     CrashLoopBackOff    9          21m     10.240.0.6     aks-agentpool-15899284-vmss000002   <none>           <none>
default       nmi-bnrsj                                            1/1     Running             0          4h33m   10.240.0.6     aks-agentpool-15899284-vmss000002   <none>           <none>
default       nmi-p6nfd                                            1/1     Running             0          4h33m   10.240.0.4     aks-agentpool-15899284-vmss000000   <none>           <none>
default       nmi-sj7fb                                            1/1     Running             0          4h33m   10.240.0.5     aks-agentpool-15899284-vmss000001

**Comment by aramase** [comment]
@jaiawasthi There is already NMI pods running in all the hosts. Looks like aad-pod-identity is being installed twice here, once with helm charts and other with deployment manifests. Please use one of the deployment ways and remove the duplicate deployment.

**Comment by jaiawasthi** [comment]
Sorry, i just realized it i deployed it twice, thanks.
Would you happen to know this error which im getting on running nmi pods 

W0813 12:11:51.421714       1 iptables.go:123] flushing iptables to add aad-metadata custom chains
W0813 12:55:26.845175       1 client.go:207] list pod error: <nil>. Retrying, attempt number: 1
W0813 12:55:27.145370       1 client.go:207] list pod error: <nil>. Retrying, attempt number: 2
W0813 12:55:27.445558       1 client.go:207] list pod error: <nil>. Retrying, attempt number: 3
E0813 12:56:47.749010       1 server.go:369] failed to get matching identities for pod: default/demo, error: getting assigned identities for pod default/demo in CREA
TED state failed after 16 attempts, retry duration [5]s, error: <nil>

**Comment by jaiawasthi** [comment]
it translates to this error while demo 
time="2020-08-13T16:31:28Z" level=error msg="testMSIEndpoint failed, <nil>" podip=10.244.0.126 podname=demo podnamespace=demo
time="2020-08-13T16:38:13Z" level=error msg="failed list all vm azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/bb6612b6-fbba-4bfc-b398-dd093b04bb49/resourceGroups/MC_AKS-RG_AKS-k8s-eastus_eastus/providers/Microsoft.Compute/virtualMachines?api-version=2017-12-01: StatusCode=404 -- Original Error: adal: Refresh request failed. Status Code = '404'. Response body: getting assigned identities for pod default/demo in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>\n" podip=10.244.0.126 podname=demo podnamespace=demo

**Comment by chewong** [comment]
Could you paste the MIC logs?

**Comment by jaiawasthi** [comment]
jaawasth@blade-jb:~/go/src/hanarp/deploy/osvalidator/scripts/osvalidationservice/helm$ kubectl logs mic-6dbd856ff5-g9sjf
I0813 12:11:51.464254       1 main.go:101] starting mic process. Version: 1.6.2. Build date: 2020-07-24-20:25
W0813 12:11:51.464295       1 main.go:106] --kubeconfig not passed will use InClusterConfig
I0813 12:11:51.464303       1 main.go:123] kubeconfig () cloudconfig (/etc/kubernetes/azure.json)
I0813 12:11:51.464436       1 main.go:131] running MIC in namespaced mode: false
I0813 12:11:51.464446       1 main.go:135] client QPS set to: 5. Burst to: 5
I0813 12:11:51.464460       1 mic.go:136] starting to create the pod identity client. Version: 1.6.2. Build date: 2020-07-24-20:25
I0813 12:11:51.493189       1 mic.go:142] Kubernetes server version: v1.16.10
I0813 12:11:51.496075       1 probes.go:41] initialized health probe on port 8080
I0813 12:11:51.496089       1 probes.go:44] started health probe
I0813 12:11:51.496202       1 metrics.go:329] registered views for metric
I0813 12:11:51.496233       1 prometheus_exporter.go:21] starting Prometheus exporter
I0813 12:11:51.496239       1 metrics.go:335] registered and exported metrics on port 8888
I0813 12:11:51.496243       1 mic.go:236] initiating MIC Leader election
I0813 12:11:51.496254       1 leaderelection.go:242] attempting to acquire leader lease  default/aad-pod-identity-mic...
jaawasth@blade-jb:~/go/src/hanarp/deploy/osvalidator/scripts/osvalidationservice/helm$ kubectl logs mic-6dbd856ff5-l74n6
I0813 12:11:51.344194       1 main.go:101] starting mic process. Version: 1.6.2. Build date: 2020-07-24-20:25
W0813 12:11:51.344248       1 main.go:106] --kubeconfig not passed will use InClusterConfig
I0813 12:11:51.344255       1 main.go:123] kubeconfig () cloudconfig (/etc/kubernetes/azure.json)
I0813 12:11:51.344382       1 main.go:131] running MIC in namespaced mode: false
I0813 12:11:51.344390       1 main.go:135] client QPS set to: 5. Burst to: 5
I0813 12:11:51.344405       1 mic.go:136] starting to create the pod identity client. Version: 1.6.2. Build date: 2020-07-24-20:25
I0813 12:11:51.373335       1 mic.go:142] Kubernetes server version: v1.16.10
I0813 12:11:51.392042       1 probes.go:41] initialized health probe on port 8080
I0813 12:11:51.392208       1 probes.go:44] started health probe
I0813 12:11:51.392379       1 metrics.go:329] registered views for metric
I0813 12:11:51.392505       1 prometheus_exporter.go:21] starting Prometheus exporter
I0813 12:11:51.392564       1 metrics.go:335] registered and exported metrics on port 8888
I0813 12:11:51.392642       1 mic.go:236] initiating MIC Leader election
I0813 12:11:51.392702       1 leaderelection.go:242] attempting to acquire leader lease  default/aad-pod-identity-mic...
I0813 12:12:12.614573       1 leaderelection.go:252] successfully acquired lease default/aad-pod-identity-mic
I0813 12:12:12.621121       1 mic.go:323] type upgrade status configmap found from version: 1.6.2. Skipping type upgrade!
I0813 12:12:12.724136       1 crd.go:453] CRD informers started
I0813 12:12:13.121603       1 pod.go:72] pod cache synchronized. Took 500.098278ms
I0813 12:12:13.121635       1 pod.go:79] pod watcher started !!
I0813 12:12:13.221707       1 mic.go:390] sync thread started.

**Comment by chewong** [comment]
Did you deploy AzureIdentity and AzureIdentityBinding before creating the demo pod, as per https://github.com/Azure/aad-pod-identity#demo?

**Comment by jaiawasthi** [comment]
yes, deployed both

**Comment by chewong** [comment]
If you deploy all three components, you should be able to see additional logs after `I0813 12:12:13.221707 1 mic.go:390] sync thread started.`. Could you ensure that there are more logs after that line?

**Comment by jaiawasthi** [comment]
Yes, no logs after that, thats the last line `1 mic.go:390] sync thread started.`

**Comment by aramase** [comment]
@jaiawasthi Can you post the output for `kubectl get azureidentity -o yaml`, `kubectl get azureidentitybinding -o yaml` and `kubectl get pod <demo pod name> -o yaml`?

**Comment by jaiawasthi** [comment]
apiVersion: v1
items:
- apiVersion: aadpodidentity.k8s.io/v1
  kind: AzureIdentity
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"aadpodidentity.k8s.io/v1","kind":"AzureIdentity","metadata":{"annotations":{},"name":"demo-aad1","namespace":"default"},"spec":{"clientID":"##removed##","clientPassword":{"name":"demo-aad1-sp","namespace":"default"},"tenantID":"72f988bf-86f1-41af-91ab-2d7cd011db47","type":1}}
    creationTimestamp: "2020-08-13T10:52:46Z"
    generation: 1
    name: demo-aad1
    namespace: default
    resourceVersion: "2094221"
    selfLink: /apis/aadpodidentity.k8s.io/v1/namespaces/default/azureidentities/demo-aad1
    uid: 8d9d7984-ac2f-4d32-9f74-a8c18f91ad25
  spec:
    clientID: ##removed##
    clientPassword:
      name: demo-aad1-sp
      namespace: default
    tenantID: 72f988bf-86f1-41af-91ab-2d7cd011db47
    type: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""


apiVersion: v1
items:
- apiVersion: aadpodidentity.k8s.io/v1
  kind: AzureIdentityBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"aadpodidentity.k8s.io/v1","kind":"AzureIdentityBinding","metadata":{"annotations":{},"name":"demo-binding","namespace":"default"},"spec":{"azureIdentity":"demo","selector":"demo"}}
    creationTimestamp: "2020-08-13T12:53:49Z"
    generation: 1
    name: demo-binding
    namespace: default
    resourceVersion: "2110858"
    selfLink: /apis/aadpodidentity.k8s.io/v1/namespaces/default/azureidentitybindings/demo-binding
    uid: f0edf3cf-d366-4ae6-b7c8-cb266925b180
  spec:
    azureIdentity: demo
    selector: demo
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""


apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"aadpodidbinding":"demo"},"name":"demo","namespace":"default"},"spec":{"containers":[{"args":["--subscriptionid=##removed##","--clientid=##removed##","--resourcegroup=MC_AKS-RG_AKS-k8s-eastus_eastus"],"env":[{"name":"MY_POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"MY_POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"MY_POD_IP","valueFrom":{"fieldRef":{"fieldPath":"status.podIP"}}}],"image":"mcr.microsoft.com/k8s/aad-pod-identity/demo:1.2","name":"demo"}],"nodeSelector":{"kubernetes.io/os":"linux"}}}
  creationTimestamp: "2020-08-13T12:55:25Z"
  labels:
    aadpodidbinding: demo
  name: demo
  namespace: default
  resourceVersion: "2111081"
  selfLink: /api/v1/namespaces/default/pods/demo
  uid: be4e2c43-9984-4790-817e-fc5729a88539
spec:
  containers:
  - args:
    - --subscriptionid=##removed##
    - --clientid=##removed##
    - --resourcegroup=MC_AKS-RG_AKS-k8s-eastus_eastus
    env:
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: MY_POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    image: mcr.microsoft.com/k8s/aad-pod-identity/demo:1.2
    imagePullPolicy: IfNotPresent
    name: demo
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-qbnjh
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: aks-agentpool-15899284-vmss000000
  nodeSelector:
    kubernetes.io/os: linux
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-qbnjh
    secret:
      defaultMode: 420
      secretName: default-token-qbnjh
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-08-13T12:55:25Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-08-13T12:55:27Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-08-13T12:55:27Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-08-13T12:55:25Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://e3fd6a8ab4cb2e04a103cfbe6f3d26799dc32125d4056d5ea39a4d63cac36481
    image: mcr.microsoft.com/k8s/aad-pod-identity/demo:1.2
    imageID: docker-pullable://mcr.microsoft.com/k8s/aad-pod-identity/demo@sha256:793c76b464271ea905db786e8b84cccc00d6a6e10ff390fb275243e8000c716e
    lastState: {}
    name: demo
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-08-13T12:55:26Z"
  hostIP: 10.240.0.4
  phase: Running
  podIP: 10.244.0.126
  podIPs:
  - ip: 10.244.0.126
  qosClass: BestEffort
  startTime: "2020-08-13T12:55:25Z"

**Comment by aramase** [comment]
```
    azureIdentity: demo
```

`azureIdentity` name in binding is `demo`, but the actual AzureIdentity name is `demo-aad1`. Please update the `azureIdentity` in AzureIdentityBinding to `demo-aad1`.

**Comment by jaiawasthi** [comment]
thanks, it worked :)

**Comment by aramase** [comment]
Perfect. We are planning to add logs on why the pod is ignored in MIC. That'll be helpful in such scenarios. 

Closing this issue as it's resolved. Please feel free to reopen if you have any other issues.
