### ISSUE TITLE
Update Helm charts to support user managed identity

### ISSUE THREAD

**Issue by marchenm** [Azure/aad-pod-identity#743]
**Describe the request**
I'd like to use the Helm Chart with a user managed identity instead of a service principal

**Explain why AAD Pod Identity needs it**
The charts should support the auth methods that AAD Pod Identity supports

**Describe the solution you'd like**
Add values to the charts for a user maanged identity

**Describe alternatives you've considered**

**Additional context**

**Comment by marchenm** [comment]
I didn't deploy the cluster, so I'm not sure on the type of cluster. I did deploy aad-pod-identity using the helm chart with a service principal, but I'd like to use the helm chart and a user managed identity instead.

**Comment by chewong** [comment]
As I mentioned, you will need a Kubernetes cluster hosted on Azure infrastructure (either an [AKS](https://azure.microsoft.com/en-us/services/kubernetes-service/) or [aks-engine](https://github.com/Azure/aks-engine) cluster) to use aad-pod-identity.

**Comment by marchenm** [comment]
The cluster is in Azure. I'm just not sure if the cluster was provisioned with aks-engine or something else.

**Comment by chewong** [comment]
I am assuming it's an AKS cluster. In terms of support for user-assigned identity, you can define multiple user-assigned identities in your helm chart values. See https://github.com/Azure/aad-pod-identity/tree/master/charts/aad-pod-identity#200 for more details.

**Comment by marchenm** [comment]
Its definitely not an AKS cluster. It might have been deployed using kubespary or so other method. What I'd like to do is use a user managed identity for MIC to auth to azure instead of a service principal. Currently I set the values for `AdminSecret`.

**Comment by chewong** [comment]
Got it. I don't think aad-pod-identity would work on clusters not created by AKS or aks-engine. That's because aad-pod-identity reads credential from a file located at `/etc/kubernetes/azure.json` stored on each node.

You could try manually creating the file for each of your nodes and see if it would work. You can check out the schema at https://kubernetes-sigs.github.io/cloud-provider-azure/install/configs/. For VMs that are using managed identity, you should something like:
```json
{
    "cloud": "AzurePublicCloud",
    "tenantId": "REDACTED",
    "subscriptionId": "REDACTED",
    "aadClientId": "msi",
    "aadClientSecret": "msi",
    "resourceGroup": "REDACTED",
    "location": "westus2",
    "vmType": "vmss",
    "subnetName": "REDACTED",
    "securityGroupName": "REDACTED",
    "vnetName": "REDACTED",
    "vnetResourceGroup": "REDACTED",
    "routeTableName": "REDACTED",
    "primaryAvailabilitySetName": "",
    "primaryScaleSetName": "REDACTED",
    "cloudProviderBackoffMode": "v2",
    "cloudProviderBackoff": true,
    "cloudProviderBackoffRetries": 6,
    "cloudProviderBackoffDuration": 5,
    "cloudProviderRateLimit": true,
    "cloudProviderRateLimitQPS": 10,
    "cloudProviderRateLimitBucket": 100,
    "cloudProviderRateLimitQPSWrite": 10,
    "cloudProviderRateLimitBucketWrite": 100,
    "useManagedIdentityExtension": true,
    "userAssignedIdentityID": "REDACTED",
    "useInstanceMetadata": true,
    "loadBalancerSku": "Standard",
    "disableOutboundSNAT": false,
    "excludeMasterFromStandardLB": true,
    "providerVaultName": "",
    "maximumLoadBalancerRuleCount": 250,
    "providerKeyName": "k8s",
    "providerKeyVersion": ""
}
```

As you can see, there are a lot of parameters that aren't controlled by us. You'd have a better experience if you pair aad-pod-identity with AKS clusters.

**Comment by marchenm** [comment]
When using a service principal and `AdminSecret` the helm chart sets the values to the env of the MIC deployment. Would that be possible with a  user managed identity?

**Comment by chewong** [comment]
Could you try setting the following values and see if it works:
```
adminsecret: {}
   cloud: <cloud environment name>
   subscriptionID: <subscription id>
   resourceGroup: <cluster resource group>
   vmType: <`standard` for normal virtual machine nodes, and `vmss` for cluster deployed with a virtual machine scale set>
   tenantID: <service principal tenant id>
   clientID: "msi"
   clientSecret: "msi"
```

**Comment by chewong** [comment]
@marchenm does it work?

**Comment by marchenm** [comment]
Sorry, I didn't get a chance to try it yet. Once I'll try it, I'll let you know.

**Comment by marchenm** [comment]
When specifying MSI I get a 400 error with "Application with identifier 'msi' not found in the directory <my tenant ID>. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant."

**Comment by chewong** [comment]
Could you try adding the following environment variable in your MIC deployment:
```
env:
- name: USE_MSI
   value: "true"
- name: USER_ASSIGNED_MSI_CLIENT_ID
   value: "<Your user-assigned identity client ID>"
```

Basically in https://github.com/Azure/aad-pod-identity/blob/master/pkg/cloudprovider/cloudprovider.go#L81-L90, `AdminSecret`got converted to environment variables except for the two env var above. Please let me know if it works.

**Comment by marchenm** [comment]
That worked. Thanks for the assistance. Can that be added to the helm chart?

**Comment by chewong** [comment]
Sure, would you like to open a PR?
