### ISSUE TITLE
Failed to get ConfigMap default/aad-pod-identity-config

### ISSUE THREAD

**Issue by BarnumD** [Azure/aad-pod-identity#748]
After upgrading from 1.5.5 to 1.6.2, I'm receiving the following error.
```
I0819 15:58:07.934783       1 main.go:101] starting mic process. Version: 1.6.2. Build date: 2020-07-24-20:25
W0819 15:58:07.934840       1 main.go:106] --kubeconfig not passed will use InClusterConfig
I0819 15:58:07.934848       1 main.go:123] kubeconfig () cloudconfig (/etc/kubernetes/azure.json)
I0819 15:58:07.934978       1 main.go:131] running MIC in namespaced mode: false
I0819 15:58:07.934997       1 main.go:135] client QPS set to: 5. Burst to: 5
I0819 15:58:07.935015       1 mic.go:136] starting to create the pod identity client. Version: 1.6.2. Build date: 2020-07-24-20:25
I0819 15:58:07.966215       1 mic.go:142] Kubernetes server version: v1.17.7
I0819 15:58:07.968008       1 probes.go:41] initialized health probe on port 8080
I0819 15:58:07.968026       1 probes.go:44] started health probe
I0819 15:58:07.968124       1 metrics.go:329] registered views for metric
I0819 15:58:07.968174       1 prometheus_exporter.go:21] starting Prometheus exporter
I0819 15:58:07.968192       1 metrics.go:335] registered and exported metrics on port 8888
I0819 15:58:07.968197       1 mic.go:236] initiating MIC Leader election
I0819 15:58:07.968209       1 leaderelection.go:242] attempting to acquire leader lease  default/aad-pod-identity-mic...
I0819 15:58:07.988879       1 leaderelection.go:252] successfully acquired lease default/aad-pod-identity-mic
F0819 15:58:08.046925       1 mic.go:334] type upgrade failed with error: failed to get ConfigMap default/aad-pod-identity-config, error: configmaps "aad-pod-identity-config" is forbidden: User "system:serviceaccount:default:aad-pod-id-mic-service-account" cannot get resource "configmaps" in API group "" in the namespace "default"
```
Additional Details:
I read the 1.6.0 breaking change notice.  It mentions proper case with things like `AzureIdentity`.  However, my config mappings looked the same as what the current [reference yaml](https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml) looks like.  So I wasn't sure what to change.
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: azureidentitybindings.aadpodidentity.k8s.io
spec:
  group: aadpodidentity.k8s.io
  version: v1
  names:
    kind: AzureIdentityBinding
    plural: azureidentitybindings
  scope: Namespaced
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: azureidentities.aadpodidentity.k8s.io
spec:
  group: aadpodidentity.k8s.io
  version: v1
  names:
    kind: AzureIdentity
    singular: azureidentity
    plural: azureidentities
  scope: Namespaced
```

Upon upgrading, the NMI component broke with a message about --host-ip no longer being valid.  Found out I had to remove that.  Secondly, the MIC component complained that it didn't have a namespace (`Please add meta.namespace as env variable MIC_POD_NAMESPACE`).
```
env {
  name = "MIC_POD_NAMESPACE"
  value_from {
    field_ref {
      field_path = "metadata.namespace"
    }
  }
}
```
After adding the above , I am left with the error at the top.

**Expected behavior**
I expected for the configmap to be automatically created, as the doc says, but that's failing.

**AAD Pod Identity version**
1.5.5 -> 1.6.2

**Kubernetes version**
1.17.7

**Additional context**

**Comment by aramase** [comment]
@BarnumD When upgrading a newer release, it's recommended to use the yaml manifests from the repo. With 1.6 release, we also updated RBAC permissions to add configmaps - get, create, update - https://github.com/Azure/aad-pod-identity/blob/master/deploy/infra/deployment-rbac.yaml#L182-L184. From the error it looks like the RBAC rules haven't been added. Could you please try with  https://github.com/Azure/aad-pod-identity/blob/master/deploy/infra/deployment-rbac.yaml? `--host-ip` is not required for NMI and that has been removed from the yaml.

**Comment by BarnumD** [comment]
Thanks.  That was helpful.  However, I have most of those components converted to terraform resources, so I had to compare the yml to those.  Minus one small issue mentioned below, that got it working.
I noticed in my environment that the NMI wouldn't start without `automount_service_account_token  = true` set in the spec of the daemonset.
