### ISSUE TITLE
MIC fails on VirtualMachineScaleSetsClient#CreateOrUpdate with 403

### ISSUE THREAD

**Issue by taurit** [Azure/aad-pod-identity#752]
**Describe the bug**

MIC fails on a Virtual Machine Scale Set operation "CreateOrUpdate" with 403 "LinkedAuthorizationFailed".

```
I0821 10:42:19.198159       1 mic.go:755] Processing node aks-xxxxxxx-21457229-vmss, add [12, del [1
I0821 10:42:19.241452       1 cloudprovider.go:199] Updating user assigned MSIs on aks-xxxxxxx-21457229-vmss
E0821 10:42:19.340740       1 vmss.go:57] compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client has permission to perform action 'Microsoft.Compute/galleries/images/versions/read' on scope '/subscriptions/ec0308fb-8d6e-497a-9dd6-99c7d9ab7962/resourceGroups/xxxxxxx-nonprod-euw-aksresources-rg/providers/Microsoft.Compute/virtualMachineScaleSets/aks-xxxxxxx-21457229-vmss', however the current tenant '9bf8c7a8-xxxx-xxxx-xxxx-ab76976c4bf8' is not authorized to access linked subscription '109a5e88-712a-48ae-9078-9ca8b3c81345'."
E0821 10:42:19.340799       1 mic.go:799] Updating msis on node aks-xxxxxxx-21457229-vmss, add [12, del [1 failed with error compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client has permission to perform action 'Microsoft.Compute/galleries/images/versions/read' on scope '/subscriptions/ec0308fb-8d6e-497a-9dd6-99c7d9ab7962/resourceGroups/xxxxxxx-nonprod-euw-aksresources-rg/providers/Microsoft.Compute/virtualMachineScaleSets/aks-xxxxxxx-21457229-vmss', however the current tenant '9bf8c7a8-xxxx-xxxx-xxxx-ab76976c4bf8' is not authorized to access linked subscription '109a5e88-712a-48ae-9078-9ca8b3c81345'."
E0821 10:42:19.402348       1 mic.go:802] Getting list of msis from node aks-xxxxxxx-21457229-vmss resulted in error identity info is nil
```

The error message is about a lack of access to a subscription which to us seems like a 3rd party subscription (maybe Microsoft's?) where the AKS-Ubuntu image is stored.

![Guid from the error message](https://user-images.githubusercontent.com/7702278/90913680-e2774900-e3dc-11ea-9ed3-1a55057fe1b3.png)

**Steps To Reproduce**
We have this reproducible on all clusters created after 2020-08-19 where aad-pod-identity 1.5.3 is used.

**Expected behavior**

Identities should get assigned without error. This operation succeeds on a different cluster instance that we deployed few days back with the same configuration:
```
I0820 08:16:52.255440       1 cloudprovider.go:199] Updating user assigned MSIs on aks-xxxxxxx-19193461-vmss
I0820 08:17:30.231869       1 crd.go:502] Updating assigned identity cert-manager/cert-manager-5d795d56c9-92flh-cert-manager-xxxxxxx-cert-manager status to Assigned
```

**AAD Pod Identity version**
Version: 1.5.3. Build date: 2019-10-12-00:24
mcr.microsoft.com/k8s/aad-pod-identity/mic:1.5.3

**Kubernetes version**
Kubernetes server version: v1.15.11

**Additional context**
We suspect that this might be connected to the [recent rollout of AKS release](https://github.com/Azure/AKS/releases/tag/2020-08-10).

We have a cluster instance deployed few days earlier with the same setup, and pod-identity works as intended in that instance of AKS. The VMSS seems to refer to the OS image in a different way though, so some defaults must have changed on the AKS or VMSS side.

![VMSS default OS image in an older cluster](https://user-images.githubusercontent.com/7702278/90915806-6848c380-e3e0-11ea-9180-5ee2e0f24208.png)

We'd appreciate hints, as well as confirmation from the community if such problem can also be observed in other clusters worldwide.

**Comment by wi5nia** [comment]
@aramase - but "sending a note to customers" how you define "customers" here? Who should receive this email? In our organization from me and @taurit are with the EA agreement, 150+ Azure Subscriptions the question is - who should receive this notification?
