### ISSUE TITLE
How to configure identity for k8s namespaces

### ISSUE THREAD

**Issue by CBaud** [Azure/aad-pod-identity#76]
My team has a k8s environment with microservices distributed across various namespaces. Based on our observations, it seems like the AzureIdentity and AzureIdentityBinding both need to be applied to the _default_ namespace where the MIC and NMI pods are running, as well as into the namespaces of the microservices that are using the pod identity. Is this the correct approach? Or, are there simpler ways to configure our service?

**Comment by kkmsft** [comment]
Hi Chris,

There seems to be something missing here - the expectation is that although identities are in default namespace, the pod can be in any namespace. Can you please provide a few more details of the steps you followed which worked and which did not work. 

I will review the code and see if there is something which could cause such a scenario.

**Comment by CBaud** [comment]
Our service was only able to authenticate with Azure Key Vault after deploying the AzureIdentity and AzureIdentityBinding to the default namespace **and** the namespace containing the pod that was using the identity.

**Comment by mpp-oliverh** [comment]
I believe I have this issue, the NMI pod just doesn't seem to see updates outside of the 'default' namespace. 

I have installed NMI and MIC into an 'identity' namespace but not really getting anywhere with that either.

My expectation was that I could put the NMI and MIC in their own namespace, along with the CRDs for the bindings, and then each production namespace could have its AzureIdentity and AzureIdentityBinding defined alongside the pods in their own namespaces.

**Comment by AndreasM009** [comment]
I had the same problem as describe by @CBaud . Taking a look to MIC logs shows me that no events are handled outside the default namespace.

**Comment by pjbgf** [comment]
@AndreasM009 @mpp-oliverh The service will only look at AzureIdentity and AzureAssignedIdentity objects from the default namespace, as that is currently hard-coded in the CRD.go file: https://github.com/Azure/aad-pod-identity/blob/master/pkg/crd/crd.go

The customer pods should be able to live anywhere though.

**Comment by AndreasM009** [comment]
@pjbgf Yes that's right. I tried that yesterday and it works. Thx

**Comment by khenidak** [comment]
ref: #115

**Comment by kkmsft** [comment]
Closing this lieu of #115
