### ISSUE TITLE
autorest/adal starts supporting token request with MSI resource id

### ISSUE THREAD

**Issue by feiyushi** [Azure/aad-pod-identity#760]
**Describe the request**
module autorest/adal/v0.9.1 starts supporting resource id in the msi token request.
**Explain why AAD Pod Identity needs it**
a refactor of PR #540 
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by feiyushi** [comment]
Since I didn't follow on the PR's implementation, this issue may not be anything. Just a notice of sort. Please close if no actions needed.

**Comment by chewong** [comment]
Hi @feiyushi, we started supporting token request with user-assigned identity's resource ID. You could try it by running the following command after setting up your `AzureIdentity` and `AzureIdentityBinding`:

```bash
kubectl run azure-cli -it --image=mcr.microsoft.com/azure-cli --labels=aadpodidbinding=demo -- az login -i -u /subscriptions/xxxx/resourcegroups/xxx/providers/Microsoft.ManagedIdentity/userAssignedIdentities/xxx --debug
```

You should be able to log in via azure-cli and see the following log output:
```log
...
msrestazure.azure_active_directory : MSI: Retrieving a token from http://169.254.169.254/metadata/identity/oauth2/token, with payload {'resource': 'https://management.core.windows.net/', 'api-version': '2018-02-01', 'msi_res_id': '/subscriptions/xxxx/resourcegroups/xxx/providers/Microsoft.ManagedIdentity/userAssignedIdentities/xxx'}
...
```
