### ISSUE TITLE
(feat): structured log

### ISSUE THREAD

**Issue by lukasmrtvy** [Azure/aad-pod-identity#764]
Would be nice to provide arg option for structured log format ( json )

**Comment by chewong** [comment]
Hi @lukasmrtvy, I am curious about what your use case is for structured logs. aad-pod-identity uses [klog](https://github.com/kubernetes/klog), which does not support outputting logs in JSON AFAIK. 

However, docker container logs are in JSON format. You can find them in each node at `/var/log/pods/<pod name>/<container name>/0.log`.

**Comment by lukasmrtvy** [comment]
- For example Splunk can autoindex json ( no need to parse log level, etc.. )
- Structured logs since https://github.com/kubernetes/klog/releases/tag/v2.0.0

**Comment by chewong** [comment]
Ah okay we are still using klog v1.0.0. I will leave this issue open in our backlog.
