### ISSUE TITLE
nmi pods not able to find the assigned identity and requests fail

### ISSUE THREAD

**Issue by veboddu** [Azure/aad-pod-identity#770]
**Describe the bug**
Whenever a new application pod is created, requests from the pod to fetch token fails during initialization.

nmi logs - 
```
E0827 **08:30:11.893592**       1 server.go:369] failed to get matching identities for pod: testmemberdeveus/ca-c788bf7cd-wzbqj, error: context canceled
```

mic logs - 
```
I0827 08:30:05.776049       1 crd.go:512] creating assigned id testmemberdeveus/ca-c788bf7cd-wzbqj-testmemberdeveus-testmemberdeveus-abs-mw-dev-eastus-app-msi
I0827 **08:30:14.521471**       1 crd.go:779] updating AzureAssignedIdentity testmemberdeveus/ca-c788bf7cd-wzbqj-testmemberdeveus-testmemberdeveus-abs-mw-dev-eastus-app-msi status to Assigned
```

weirdly, from mic logs, it looks like requests are being raised before identity assignment. This is completely random.

In some cases, even though the identity is assigned, it still fails.

nmi logs - 
```
E0827 **10:17:06.744584**       1 server.go:369] failed to get matching identities for pod: testmemberdeveus/ca-c788bf7cd-tchfg, error: context canceled
```

mic logs - 
```
I0827 10:16:55.476012       1 crd.go:512] creating assigned id testmemberdeveus/ca-c788bf7cd-tchfg-testmemberdeveus-testmemberdeveus-abs-mw-dev-eastus-app-msi
I0827 **10:17:04.258342**       1 crd.go:779] updating AzureAssignedIdentity testmemberdeveus/ca-c788bf7cd-tchfg-testmemberdeveus-testmemberdeveus-abs-mw-dev-eastus-app-msi status to Assigned
```

**Expected behavior**
Requests should go through without failure.

**Workaround**
On pod restart, this works fine.
```
I0827 10:22:24.214226       1 standard.go:79] clientID in request: a3ba##### REDACTED #####583b, testmemberdeveus/ca-c788bf7cd-fsp2f has been matched with azure identity
testmemberdeveus/testmemberdeveus-abs-mw-dev-eastus-app-msi
I0827 10:22:24.380649       1 standard.go:79] clientID in request: a3ba##### REDACTED #####583b, testmemberdeveus/ca-c788bf7cd-fsp2f has been matched with azure identity
testmemberdeveus/testmemberdeveus-abs-mw-dev-eastus-app-msi
I0827 10:22:24.397865       1 standard.go:79] clientID in request: a3ba##### REDACTED #####583b, testmemberdeveus/ca-c788bf7cd-fsp2f has been matched with azure identity
testmemberdeveus/testmemberdeveus-abs-mw-dev-eastus-app-msi
I0827 10:22:24.434865       1 standard.go:79] clientID in request: a3ba##### REDACTED #####583b, testmemberdeveus/ca-c788bf7cd-fsp2f has been matched with azure identity
testmemberdeveus/testmemberdeveus-abs-mw-dev-eastus-app-msi
I0827 10:22:24.564357       1 standard.go:79] clientID in request: a3ba##### REDACTED #####583b, testmemberdeveus/ca-c788bf7cd-fsp2f has been matched with azure identity
testmemberdeveus/testmemberdeveus-abs-mw-dev-eastus-app-msi
```

**AAD Pod Identity version**
1.6.2

**Kubernetes version**
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v**1.18.4**", GitCommit:"8a6cdee2dab2329284444e9448bdf8ab165e1c5c", GitTreeState:"clean", BuildDate:"2020-06-24T18:14:29Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**
We even added retries to our requests(retries for 5mins with 20secs timeout for each request), but it still fails until we restart the pod.

**Comment by aramase** [comment]
@veboddu When the new pod is deployed, MIC needs to assign the identity for the pod to the underlying VM/VMSS. This assignment time is 10-15s for VMAS and 40-50s for VMSS (this is the cloud VM/VMSS update). Only after MIC has finished assigning the identity will NMI be able to fetch a token for the identity. NMI has internal retries in place (5s x 20) to wait for the identity assignment to complete and fetch token. 

>  error: context canceled

This means the pod requesting for the token terminated the token request. If you increase the token request timeout that should be sufficient as there are retries in NMI.

**Comment by ragarcia26** [comment]
Where would we extend the token request?

**Comment by bamvenkatesh** [comment]
Thanks @aramase . this could be because of 40-50s delay. We will try to handle this in our application and will open issue, if we see this recur.

And also, doesn't 40-50s is little high? Any reasons for this and any work in progress in bring this down ?

**Comment by aramase** [comment]
> And also, doesn't 40-50s is little high? Any reasons for this and any work in progress in bring this down ?

This is the time the cloud `UPDATE` operations takes in case of VMSS. We will follow up with the VMSS team to check if there is any way this timing can be optimized. Also note, this is only during the first time the identity is being assigned. Subsequent requests for token with this identity will not incur this additional delay.

Closing this issue for now. Please feel free to reopen if you have any issues after adding retries in application.
