### ISSUE TITLE
nmi pod throwing 404 error: context canceled

### ISSUE THREAD

**Issue by ragarcia26** [Azure/aad-pod-identity#773]
**Describe the bug**
nmi pod complains about matching identity. Actual application pod missing expected permissions 
```
E0828 00:36:19.317711       1 server.go:369] failed to get matching identities for pod: eadp-cloud-infra/hostscaler-6b6885f7bf-xdslg, error: context canceled
I0828 00:36:19.317774       1 server.go:190] status (404) took 9999560094 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.244.1.26
```
**Steps To Reproduce**
Followed guide here https://github.com/Azure/aad-pod-identity and here https://github.com/Azure/aad-pod-identity/blob/master/docs/readmes/README.role-assignment.md#performing-role-assignments to add the extra role assignments to the cluster msi

**AAD Pod Identity version**
Unsure - https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/deployment-rbac.yaml
**Kubernetes version**
1.16.10
**Additional context**
Pretty novice look at this project. We're simply trying to get an application to gain access to compute resources in azure. Since we cannot easily create SP's we decided to look at this project for help using msi's

Kicking our application pod nor mic/nmi pods help with this error (as described in another issue)

**Comment by chewong** [comment]
Hi @ragarcia26. Could you share your AzureIdentity and AzureIdentityBinding setup?

**Comment by ragarcia26** [comment]
We found the direct error to our 404 was due to the matching identity name in the pod label was incorrect! closing this issue as we ultimately were able to get our app running by following the example and debugging. 
The issues we ran into were matching up the names correct (we're driving most of this through TF and helmfile) in addition to setting our app's client configuration to match that of the Demo - https://github.com/Azure/aad-pod-identity/blob/master/cmd/demo/main.go

**Comment by PSanetra** [comment]
In our case we missed to create a `AzureIdentity` resource while the `AzureIdentityBinding` already existed. It helps to look into the mic logs.
