### ISSUE TITLE
No filtering of terminated pods

### ISSUE THREAD

**Issue by KKomarov** [Azure/aad-pod-identity#78]
Here https://github.com/Azure/aad-pod-identity/blob/9f6a8e3bd3cddfaccc64fb3e807a3c58ed3fa86a/pkg/k8s/client.go#L68

is lookup of podns podname from ip address. If there are terminated pods with same ip address as alive pod it might fail on lookup of assignment. Its a stopper for us.

**Comment by rite2nikhil** [comment]
#82
