### ISSUE TITLE
MIC Update VMSS future.WaitForCompletionRef times out

### ISSUE THREAD

**Issue by dsbrng25b** [Azure/aad-pod-identity#789]
**Describe the bug**
When a service calls NMI it hangs for about 80 seconds and then gets back a HTTP 404 error. In the NMI Log we get a lot of these errors:
```
E0910 13:50:03.556942       1 server.go:369] failed to get matching identities for pod: myns/mi-test1, error: getting assigned identities for pod myns/mi-test1 in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>
I0910 13:50:03.556990       1 server.go:190] status (404) took 80007805398 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.0.208
E0910 13:50:29.070926       1 server.go:369] failed to get matching identities for pod: myns/pod-identity-integration-test-02dd0a71, error: getting assigned identities for pod myns/pod-identity-integration-test-02dd0a71 in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>
I0910 13:50:29.070972       1 server.go:190] status (404) took 80004162726 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.0.209
E0910 13:51:23.867529       1 server.go:369] failed to get matching identities for pod: myns/mi-test1, error: getting assigned identities for pod myns/mi-test1 in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>
I0910 13:51:23.867569       1 server.go:190] status (404) took 80005253352 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.0.208
E0910 13:52:44.575571       1 server.go:369] failed to get matching identities for pod: myns/mi-test1, error: getting assigned identities for pod myns/mi-test1 in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>
I0910 13:52:44.575648       1 server.go:190] status (404) took 80003842375 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.0.208
E0910 13:53:20.025297       1 server.go:369] failed to get matching identities for pod: myns/pod-identity-integration-test-02dd0a71, error: getting assigned identities for pod myns/pod-identity-integration-test-02dd0a71 in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>
I0910 13:53:20.025330       1 server.go:190] status (404) took 80003251796 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.0.209
E0910 13:54:04.884187       1 server.go:369] failed to get matching identities for pod: myns/mi-test1, error: getting assigned identities for pod myns/mi-test1 in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>
I0910 13:54:04.884296       1 server.go:190] status (404) took 80004275108 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.0.208
E0910 13:54:24.868722       1 server.go:369] failed to get matching identities for pod: myns/mi-test, error: getting assigned identities for pod myns/mi-test in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>
I0910 13:54:24.868774       1 server.go:190] status (404) took 81205037072 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.0.169
E0910 13:55:24.994472       1 server.go:369] failed to get matching identities for pod: myns/mi-test1, error: getting assigned identities for pod myns/mi-test1 in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>
I0910 13:55:24.994515       1 server.go:190] status (404) took 80005143409 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.0.208
```
Sometimes the error look like this (ASSIGNED instead of CREATED state):
```
failed to get matching identities for pod: mynamespace/mypod, error: getting assigned identities for pod mynamespace/mypod in ASSIGNED state failed after 20 attempts, retry duration [5]s, error: <nil>
```
Unfortunately there is no error message what's causing this problem.

In the logs of MIC about every 15 minutes we see this error:
```
...
0910 12:20:24.439586       1 cloudprovider.go:196] updating user-assigned identities on aks-default-18399963-vmss, assign [5], unassign [0]
E0910 12:35:25.138121       1 mic.go:1077] failed to update user-assigned identities on node aks-default-18399963-vmss (add [6], del [4], update[0]), error: failed to wait for identity update completion for vmss aks-default-18399963-vmss in resource group MC_aks-rg_aks-name_westeurope, error: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded
...
I0910 12:35:59.577606       1 cloudprovider.go:196] updating user-assigned identities on aks-default-18399963-vmss, assign [0], unassign [1]
E0910 12:51:00.232366       1 mic.go:1077] failed to update user-assigned identities on node aks-default-18399963-vmss (add [0], del [1], update[0]), error: failed to wait for identity update completion for vmss aks-default-18399963-vmss in resource group MC_aks-rg_myaks_westeurope, error: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded
...
I0910 12:51:51.584640       1 cloudprovider.go:196] updating user-assigned identities on aks-default-18399963-vmss, assign [0], unassign [1]
E0910 13:06:52.380133       1 mic.go:1077] failed to update user-assigned identities on node aks-default-18399963-vmss (add [0], del [1], update[0]), error: failed to wait for identity update completion for vmss aks-default-18399963-vmss in resource group MC_aks-rg_myaks_westeurope, error: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded
...
I0910 13:10:50.130741       1 cloudprovider.go:196] updating user-assigned identities on aks-default-18399963-vmss, assign [1], unassign [0]
E0910 13:25:50.878329       1 mic.go:1077] failed to update user-assigned identities on node aks-default-18399963-vmss (add [1], del [0], update[0]), error: failed to wait for identity update completion for vmss aks-default-18399963-vmss in resource group MC_aks-rg_myaks_westeurope, error: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded
...

```
So it seems that the update runs into a timeout after 15 minutes. Is it somehow possible to increase this timeout? What could be the reason that this takes so long?
One thing we noticed is that one of the instances in the VMSS is in state `Updating (Running)`. It doesn't seem to be a problem since in AKS the node is ready and workload can be scheduled on it.

**Steps To Reproduce**

**Expected behavior**
NMI returns the token.
**AAD Pod Identity version**
1.6.2

**Kubernetes version**
1.16.13

**Comment by dsbrng25b** [comment]
Here you find some more logs from NMI:
```
E0910 13:50:03.556942       1 server.go:369] failed to get matching identities for pod: myns/mi-test1, error: getting assigned identities for pod myns/mi-test1 in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>
I0910 13:50:03.556990       1 server.go:190] status (404) took 80007805398 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.0.208
E0910 13:50:29.070926       1 server.go:369] failed to get matching identities for pod: crt/pod-identity-integration-test-02dd0a71, error: getting assigned identities for pod crt/pod-identity-integration-test-02dd0a71 in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>
I0910 13:50:29.070972       1 server.go:190] status (404) took 80004162726 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.0.209
E0910 13:51:23.867529       1 server.go:369] failed to get matching identities for pod: myns/mi-test1, error: getting assigned identities for pod myns/mi-test1 in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>
I0910 13:51:23.867569       1 server.go:190] status (404) took 80005253352 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.0.208
E0910 13:52:44.575571       1 server.go:369] failed to get matching identities for pod: myns/mi-test1, error: getting assigned identities for pod myns/mi-test1 in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>
I0910 13:52:44.575648       1 server.go:190] status (404) took 80003842375 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.0.208
E0910 13:53:20.025297       1 server.go:369] failed to get matching identities for pod: crt/pod-identity-integration-test-02dd0a71, error: getting assigned identities for pod crt/pod-identity-integration-test-02dd0a71 in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>
I0910 13:53:20.025330       1 server.go:190] status (404) took 80003251796 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.0.209
E0910 13:54:04.884187       1 server.go:369] failed to get matching identities for pod: myns/mi-test1, error: getting assigned identities for pod myns/mi-test1 in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>
I0910 13:54:04.884296       1 server.go:190] status (404) took 80004275108 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.0.208
E0910 13:54:24.868722       1 server.go:369] failed to get matching identities for pod: myns/mi-test, error: getting assigned identities for pod myns/mi-test in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>
I0910 13:54:24.868774       1 server.go:190] status (404) took 81205037072 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.0.169
E0910 13:55:24.994472       1 server.go:369] failed to get matching identities for pod: myns/mi-test1, error: getting assigned identities for pod myns/mi-test1 in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>
I0910 13:55:24.994515       1 server.go:190] status (404) took 80005143409 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.240.0.208
```

When a service calls NMI it hangs for about 80 seconds and then gets back a HTTP 404 error.

**Comment by aramase** [comment]
@dsbrng25b Is this the `aks-default-18399963-vmss` VMSS that's in `Updating (Running)` state? If it is, then that could be the issue where all VMSS API calls are failing because the state is `Updating`. The default context value is configured in the SDK. If the VMSS state doesn't become `Running`, I would recommend checking with the AKS team on steps to mitigate that.

**Comment by dsbrng25b** [comment]
In the mean time we could resolve the probelem by removing one node from the VMSS and add another one. It seems that one node of our VMSS was in a strange state (`Updating (Running)`). The node was running (it was Ready in AKS, and workload could be scheduled on it) but probably this strange state leds to the problem that the VMSS could not be updated resp. the the wait for the successful update timed out: 

https://github.com/Azure/aad-pod-identity/blob/v1.6.2/pkg/cloudprovider/vm.go#L113

I assume that the actual update itself was successful because in the portal on the VMSS under identities I could observe that the managed identites got assigned and removed.
But as far as I understand since the WaitForCompletionRef failed MIC never got to the point where it would update the status of the AzureAssignedIdentities to `Assigned`.

This was very unpleasent for us beacuase on our whole cluster it let fail all services which rely on MIs althouh only one node of the VMSS was in a bad state and from the prespective of AKS even that node was healthy.

My guess is that everything would have worked but NMI did not try to get the MI token because the status in the AzureAssignedIdentities was not set to Assigned.

Maybe it would make sense not to wait for the completion of the update action on the VMSS and instaed imediately after the update set the status of the AzureAssignedIdentities to Assigned. Then NMI it self then should wait/retry until it gets the requested token.

This would probably speed up the whole assignement process because NMI would return the tokens as soon as they are available and don't wait on the status of the whole VMSS which might not necessarly reflect the actual state of the meta data service.

**Comment by aramase** [comment]
> Maybe it would make sense not to wait for the completion of the update action on the VMSS and instead immediately after the update set the status of the AzureAssignedIdentities to Assigned. Then NMI it self should wait/retry until it gets the requested token.

The `future.WaitForCompletionRef` is to ensure the request succeeded and the identity is in fact assigned to the underlying node before we set the status to `Assigned`. If this is skipped and the background identity assignment call fails, NMI will keep forwarding the request to IMDS and IMDS would return with `identity not found` errors. This will make the token request calls non-deterministic and in cases of applications that don't have retries could cause applications to crash. 

I think the issue primarily here is the VMSS being in `Updating` state for so long. This would result in failure for all [cloud provider calls](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/azure/clients/armclient/azure_armclient.go#L247-L266) too if the VMSS resource provider doesn't respond with a `200OK`.

**Comment by dsbrng25b** [comment]
> I think the issue primarily here is the VMSS being in Updating state for so long. This would result in failure for all cloud provider calls too if the VMSS resource provider doesn't respond with a 200OK.

Sure, the VMSS should not behave like this. I'm currently in contact with the support and they try to figure out how our VMSS got into this state.
But never the less I would appreciate if aad-pod-identity would be less prone to such problems if this could be achieved with some changes.

> If this is skipped and the background identity assignment call fails, NMI will keep forwarding the request to IMDS and IMDS would return with `identity not found` errors. This will make the token request calls non-deterministic and in cases of applications that don't have retries could cause applications to crash.

My idea is that NMI would do the retry and not the application. So NMI should try to get the token (retry if 404 is returned) from the IMDS and if NMI is not able to get the token within a certain time it should return a 500 error.
For that solution probably a new "Failed" status should be introduced for the AzureAssignedIdentity.
This way MIC would either set the status to "Failed" if an MI does not exist or MIC does not have the appropriate permission to assign it otherwise it would perform the update and let NMI do the rest: return 500 if AzureAssignedIdentity is in state Failed or wait unit the token can be received.

I think that aad-pod-identity in general would benefit from this change because I assume that this would reduce the time required to get tokens from NMI. Because as far as I understand the current update logic, MIC starts the assignment/update process as soon as a new pod gets started. If you start another pod only one second later than the second pod first have to wait until MIC has finished the assignment/update process for the first pod and then the assignment/update process runs a second time. That is why the assignment/update process should be kept as short as possible.

**Comment by dsbrng25b** [comment]
We experienced the same problem again. The VMSS got into a strange state and all the updates on it timed out. This time it was even worse because we could not fix the VMSS our self by removing and adding new instances and instead had to wait for the support to fix the VMSS.

> I assume that the actual update itself was successful because in the portal on the VMSS under identities I could observe that the managed identities got assigned and removed.

My assumption is wrong. Although the identities were shown in the Portal they could not be obtained through the IMDS (directly from the node, not through nmi).

Would still be nice if something could be done to make this more stable. But I guess from the aad-podidentity point of view nothing can be done when the VMSS update fails/times out.
