### ISSUE TITLE
Is it possible for a pod to use multiple identities while a different pod uses only 1 of them?

### ISSUE THREAD

**Issue by orsharab** [Azure/aad-pod-identity#792]
**Describe the bug**
It says [here](https://github.com/Azure/aad-pod-identity/blob/e95ed2767c032805773eb78b84b5a48ee6844148/docs/readmes/README.best-practices.md#a-pod-using-multiple-azureidentities) that it's possible for a pod to use multiple identities, but what if a different pod need only one of the identities? do I have to create another identity binding for this?

I would like to match between a pod and 1 or more identities, for example 1 pod needs access to key vault, another pod needs access to key vault and cosmosDB, another pod needs access to cosmosDB and blob storage etc.
**Steps To Reproduce**

**Expected behavior**

**AAD Pod Identity version**

**Kubernetes version**

**Additional context**

**Comment by chewong** [comment]
Hi @orsharab, AzureIdentity and AzureIdentityBinding have a 1:1 relationship, i.e. you should create an AzureIdentityBinding for each AzureIdentity you created. Then you can combine them by defining the same selector in your AzureIdentityBindings.
