### ISSUE TITLE
Error creating http server: address already in use

### ISSUE THREAD

**Issue by francescocristallo** [Azure/aad-pod-identity#811]
I followed the Readme installation multiple times for days, but I'm unable to make pod-identity work.
My steps:

1. Created a new AKS Cluster version 1.18.8, 1 Node Pool, all default parameters
2. Assigned Roles and Deployed pod identity using Helm 3
3. Created new Identity
4. Assigned reader role
5. Deployed AzureIdentity and Azure IdentityBinding
6. Deployed Demo

I did this moltiple times with the same outcome,  aad-pod-identity-nmi is in CrashLoopBackOff. 

kubectl logs shows:

 **error creating http server: listen tcp 127.0.0.1:2579: bind: address already in use**, and **http listen and serve error: listen tcp :8085: bind: address already in use**

![Screenshot 2020-09-30 002432](https://user-images.githubusercontent.com/9793825/94646206-5bf33880-02b3-11eb-817e-d22c43876742.jpg)

I can't understand what I'm doing wrong. 
Some screenshots from the Azure Panel:

![Screenshot 2020-09-30 001541](https://user-images.githubusercontent.com/9793825/94645755-44678000-02b2-11eb-9f86-7b56d99dc278.jpg)

![Screenshot 2020-09-30 001616](https://user-images.githubusercontent.com/9793825/94645758-46314380-02b2-11eb-8872-8695bcc75608.jpg)

To Deploy aad-pod-identity I call

```
helm repo add aad-pod-identity https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts
helm install aad-pod-identity aad-pod-identity/aad-pod-identity
```
Should I deploy the MIC and AKS add-on exception too in addition to the above helm package?

To add to my confusion, looks like the demo displays the correct output.

![InkedScreenshot 2020-09-30 001914_LI](https://user-images.githubusercontent.com/9793825/94646065-0a4aae00-02b3-11eb-873f-226c46b21f1c.jpg)

Any help or insights would be really appreciated, what I'm trying to do, is use Managed Identities to connect an Asp.Net Core Application pod to KeyVault.

**Comment by chewong** [comment]
Looks like you have two aad-pod-identity deployments, one from the deployment YAML and one from helm chart. Could you uninstall one of them and try again?

**Comment by francescocristallo** [comment]
Thank you, I created a new Cluster and retried manually all the steps, I was calling the kubectl YAML as well in addition to Helm.
