### ISSUE TITLE
Timeout for getting token in our application, when upgrading to v1.6.3

### ISSUE THREAD

**Issue by mhsh64** [Azure/aad-pod-identity#821]
Hi
When we upgrade to 1.6.3 our application were not able to refresh token and getting timeout
We have netpol which has port 2579 open to pod identity nanespace and we did not have any issue in 1.6.1
I noticed you removed `—host-ip` From nmi definition.
Is that relevant?
Appreciate if you can help

**Comment by aramase** [comment]
@mhsh64 That's right. NMI prior to release 1.6.2 bound to all interfaces with `:2579`. With 1.6.2 release we switched to listening on localhost as that's more secure. If you have network policies configured, then you would need to allow egress traffic for `localhost:2579`.

**Comment by mhsh64** [comment]
@aramase 
Thanks
But is that a kind of breaking change? I did not find it in Release note

We have allow egress traffic to nmi_ip:2579 in our application namespace
Is there something else we need to configure?

**Comment by mhsh64** [comment]
Or you mean we define that polcy you mentioned in aad pod identity namespace?

**Comment by aramase** [comment]
@mhsh64 The change is part of changelog but is not documented as a breaking change. This is a similar issue - https://github.com/Azure/aad-pod-identity/issues/716. Instead of `<nodeIP>:2579` the egress rules are required only for `localhost:2579`.
