### ISSUE TITLE
Identity binding logs to stderr

### ISSUE THREAD

**Issue by marty2bell** [Azure/aad-pod-identity#822]
**Have you**

- [X] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [X] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [X] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
When a pod starts and the nmi pod retrieves a security token, the logs for that process are written to stderr rather than stdout, for example:

I1008 21:11:58.290846       1 standard.go:72] no clientID or resourceID in request. default/kong-mfsrd has been matched with azure identity default/pod-identity
I1008 21:11:58.290909       1 standard.go:178] matched identityType:0 clientid:00dc##### REDACTED #####e3d3 resource:https://vault.azure.net
I1008 21:11:58.296668       1 server.go:190] status (200) took 5865792 ns for req.method=GET reg.path=/host/token/ req.remote=127.0.0.1

This causes false alerts within our cluster monitoring as we see a number of logs appearing on stderr.

**Steps To Reproduce**
delete a pod and monitor the nmi pods

**Expected behavior**
This seems to be expected behaviour so should be written to stdout

**AAD Pod Identity version**
nmi:v1.6.3

**Kubernetes version**
1.18.6

**Additional context**

**Comment by aramase** [comment]
@marty2bell We use klog for `aad-pod-identity` and there is a flag called --logtostderr for klog, which it enables by default. You can set the flag to false in the NMI manifests.

**Comment by chewong** [comment]
it looks like `kubectl logs` if `--logtostderr` is set to false, since all logs will be written to files only. By default, `klog` (the logger we use) writes to stderr, but we could have a flag to redirect logs to stdout using `klog.SetOutput`. WDYT?

**Comment by aramase** [comment]
Looks like there is `SetOutputBySeverity` option. So we can set `ERROR`, `FATAL` to stderr , `INFO` and `WARNING` to stdout.

**Comment by chewong** [comment]
I did some investigation and found the following:
- `klog.Warning` writes the message to the `io.Writer` of `INFO` and `WARNING` 
- `klog.Error` writes the message to the `io.Writer` of `INFO`, `WARNING` and `ERROR`
- `klog.Fatal` writes the message to the `io.Writer` of `INFO`, `WARNING`, `ERROR` and `FATAL`

So if I `klog.Error` something and run `kubectl logs` after, it seems like it logs the same message twice but it actually just logs to both  `stderr` and `stdout`. I don't think this behavior is something we want. WDYT?

**Comment by aramase** [comment]
@chewong Yeah duplication of logs is definitely not something we want.

**Comment by chewong** [comment]
closing this issue for now since it's not technically feasible unless we change our logger.
