### ISSUE TITLE
Show more information in kubectl get AzureIdentity

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/aad-pod-identity#829]
**Describe the request**
Show more information in kubectl get AzureIdentity to help operators get an understanding of what is provisioned when using `-o wide`

**Explain why AAD Pod Identity needs it**
Make it more operable and easier to use

**Describe the solution you'd like**
Information concerning `type`, `resourceID` & `clientID`

**Comment by chewong** [comment]
Fixed by #1093

**Comment by tomkerkhove** [comment]
Thanks!
