### ISSUE TITLE
Show more information in kubectl get AzureIdentityBinding

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/aad-pod-identity#830]
**Describe the request**
Show more information in kubectl get AzureIdentityBinding to help operators get an understanding of what is provisioned when using `-o wide`

**Explain why AAD Pod Identity needs it**
Make it more operable and easier to use

**Describe the solution you'd like**
Information concerning `azureIdentity` & `selector`

**Comment by tomkerkhove** [comment]
keep-alive

**Comment by chewong** [comment]
Fixed by #1093
