### ISSUE TITLE
aad-pod-identity-nmi pods suddenly start crashing (AKS, RBAC enabled)

### ISSUE THREAD

**Issue by arianmotamedi** [Azure/aad-pod-identity#835]
This is similar to: https://github.com/Azure/aad-pod-identity/issues/784

**Describe the bug**
NMI (with RBAC enabled) pods that have been working fine for days suddenly start crashing with these errors:

```
E1015 16:55:30.026821       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:platform:aad-pod-id-nmi-service-account" cannot list resource "pods" in API group "" at the cluster scope
E1015 16:55:30.026946       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1.AzurePodIdentityException: azurepodidentityexceptions.aadpodidentity.k8s.io is forbidden: User "system:serviceaccount:platform:aad-pod-id-nmi-service-account" cannot list resource "azurepodidentityexceptions" in API group "aadpodidentity.k8s.io" at the cluster scope
E1015 16:55:30.027075       1 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1.AzureAssignedIdentity: azureassignedidentities.aadpodidentity.k8s.io is forbidden: User "system:serviceaccount:platform:aad-pod-id-nmi-service-account" cannot list resource "azureassignedidentities" in API group "aadpodidentity.k8s.io" at the cluster scope
```

**Steps To Reproduce**
N/A, randomly started happening

**Expected behavior**
NMI pods should have access to all required APIs and scopes with RBAC enabled

**AAD Pod Identity version**
Latest (v1.6.3)

**Kubernetes version**
Happened on three versions: 1.16.10, 1.16.13, and 1.17.11

**Additional context**
I investigated this on my end and noticed that **aad-pod-id-nmi-role** and **aad-pod-id-nmi-binding** were somehow missing from the cluster. We didn't do any deployments or manual changes to have caused them to be removed, so I looked at AKS audit logs in our Log Analytics workspace and noticed these two curious records:

```
AzureDiagnostics
| where Category == "kube-audit"
| where log_s contains "aad-pod-id-nmi-role" or log_s contains "aad-pod-id-nmi-binding"
| extend Log = parse_json(log_s)
| where Log.verb == "delete"
| project TimeGenerated, Log, Log.verb, Resource
```

```
{
	"kind": "Event",
	"apiVersion": "audit.k8s.io/v1",
	"level": "RequestResponse",
	"auditID": "371ccc0c-759c-46c9-90bc-f7629ac51f42",
	"stage": "ResponseComplete",
	"requestURI": "/apis/rbac.authorization.k8s.io/v1/clusterroles/aad-pod-id-nmi-role",
	"verb": "delete",
	"user": {
		"username": "aksService",
		"groups": ["system:masters", "system:authenticated"]
	},
	"sourceIPs": ["172.xx.xx.xx"],
	"userAgent": "kubectl/v1.17.11 (linux/amd64) kubernetes/3a36121",
	"objectRef": {
		"resource": "clusterroles",
		"name": "aad-pod-id-nmi-role",
		"apiGroup": "rbac.authorization.k8s.io",
		"apiVersion": "v1"
	},
	"responseStatus": {
		"metadata": {},
		"status": "Success",
		"code": 200
	},
	"requestObject": {
		"kind": "DeleteOptions",
		"apiVersion": "rbac.authorization.k8s.io/v1",
		"propagationPolicy": "Background"
	},
	"responseObject": {
		"kind": "Status",
		"apiVersion": "v1",
		"metadata": {},
		"status": "Success",
		"details": {
			"name": "aad-pod-id-nmi-role",
			"group": "rbac.authorization.k8s.io",
			"kind": "clusterroles",
			"uid": "fdf1413b-a4dc-4b5e-9daa-2acfde3e3b65"
		}
	},
	"requestReceivedTimestamp": "2020-10-13T18:15:34.2379730Z",
	"stageTimestamp": "2020-10-13T18:15:34.2496570Z",
	"annotations": {
		"authorization.k8s.io/decision": "allow",
		"authorization.k8s.io/reason": ""
	}
}
```

and 

```
{
	"kind": "Event",
	"apiVersion": "audit.k8s.io/v1",
	"level": "RequestResponse",
	"auditID": "837e7adb-3bb2-41b1-a30a-f62e27187959",
	"stage": "ResponseComplete",
	"requestURI": "/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/aad-pod-id-nmi-binding",
	"verb": "delete",
	"user": {
		"username": "aksService",
		"groups": ["system:masters", "system:authenticated"]
	},
	"sourceIPs": ["172.xx.xx.xx"],
	"userAgent": "kubectl/v1.17.11 (linux/amd64) kubernetes/3a36121",
	"objectRef": {
		"resource": "clusterrolebindings",
		"name": "aad-pod-id-nmi-binding",
		"apiGroup": "rbac.authorization.k8s.io",
		"apiVersion": "v1"
	},
	"responseStatus": {
		"metadata": {},
		"status": "Success",
		"code": 200
	},
	"requestObject": {
		"kind": "DeleteOptions",
		"apiVersion": "rbac.authorization.k8s.io/v1",
		"propagationPolicy": "Background"
	},
	"responseObject": {
		"kind": "Status",
		"apiVersion": "v1",
		"metadata": {},
		"status": "Success",
		"details": {
			"name": "aad-pod-id-nmi-binding",
			"group": "rbac.authorization.k8s.io",
			"kind": "clusterrolebindings",
			"uid": "dff68782-255c-441c-aae5-69d5642365ac"
		}
	},
	"requestReceivedTimestamp": "2020-10-13T18:15:33.9714280Z",
	"stageTimestamp": "2020-10-13T18:15:33.9787150Z",
	"annotations": {
		"authorization.k8s.io/decision": "allow",
		"authorization.k8s.io/reason": ""
	}
}
```

Both the role and role binding were deleted at the same time by `aksService`.

Needless to say, applying the role and role binding fixed it, but, this has happened in **3 different regions** so far at different dates. Here are the timestamps for the deletions:

Southeast Asia: 10/13/2020, 6:15:34.000 PM (UTC)
Australia East: 10/7/2020, 11:05:40.000 PM (UTC)
Canada Central: 10/7/2020, 11:07:27.000 PM (UTC)

Would be great if we could see if an AKS change caused these to be removed. This is extremely high priority as it has caused 3 outages in production for us thus far (and I have no confidence that it won't happen in other regions either).

**Comment by aramase** [comment]
@arianmotamedi PTAL at this - https://github.com/Azure/aad-pod-identity/issues/639#issuecomment-709409012. This is an AKS bug that's causing the deletion of `aad-pod-identity` cluster roles. They are currently deploying the hotfix based on the comment.

cc @miwithro

**Comment by arianmotamedi** [comment]
Thanks @aramase. This is effectively a sev2 - is there anything on the AKS side I can use to check the status?

**Comment by aramase** [comment]
@arianmotamedi I've tagged Michael in the comment above. Michael is the AKS PM and he should be able to provide more details.

**Comment by roben0** [comment]
This has occurred twice this week for us in the same cluster in Australia East. 
AAD Pod Identity Version v1.6.3
Kubernetes version 1.16.8
Was able to workaround the issue by re-creating the roles.

**Comment by bcho** [comment]
@arianmotamedi @roben0 

(I am AKS eng) AKS had fixed this issue with a hotfix. Manually add the cluster role and cluster role binding (https://gist.github.com/bcho/22ff2098b310f496cc525b0377d725b9) back can fix this issue. Sorry for the inconvenience! We will provide detailed advisory in the AKS issue.

**Comment by pbalexlear** [comment]
We have also noticed this issue in UKS and EUN 
AAD Pod Identity Version v1.6.3
Kubernetes version 1.16.8

**Comment by miwithro** [comment]
Yes, we had an issue about the role bindings removal this week and it has been mitigated. We also fixed some clusters affected by this issue from AKS's log, by adding the cluster role aad-pod-id-nmi-role and cluster rolebinding aad-pod-id-nmi-binding back. 

But we may miss some of the clusters. For these clusters, customers can add back the cluster role / cluster role binding by themselves.

**Comment by bcho** [comment]
For the advisory / mitigation, please see: https://github.com/Azure/AKS/issues/1903

**Comment by chewong** [comment]
See https://github.com/Azure/AKS/issues/1903 for mitigation steps.
