### ISSUE TITLE
Role Assignment

### ISSUE THREAD

**Issue by bruun365** [Azure/aad-pod-identity#837]
Shouldn't the **_cluster_ resource group refers to the resource group with a MC_ prefix** be changed to **_node_ resource group refers to the resource group with a MC_ prefix**

Because the cluster resource group contains the AKS cluster resource and the node resource groups contains the VMSS. If i specify a custom node resource group the VMSS and the user managed identity (kubelet) are deployed in the node resource group (and not the cluster resource group). Therefore i think there's a typo.

**Comment by chewong** [comment]
Would you like to open a PR to resolve this issue?
