### ISSUE TITLE
Unable to create pod identity

### ISSUE THREAD

**Issue by matthewbrumpton-oddsbods** [Azure/aad-pod-identity#838]
Support request ID | 120101924003470

**AAD Pod Identity version 1.6.3 **

**Kubernetes version 1.18.8**

 1 cloudprovider.go:210] updating user-assigned identities on aks-apppool-78790466-vmss, assign [1], unassign [0]
E1019 14:02:27.978668       1 mic.go:1093] failed to update user-assigned identities on node aks-systempool-78790466-vmss (add [1], del [0], update[0]), error: failed to update identities for aks-systempool-78790466-vmss in MC_oblive-ne-rg_oblive-ne-aks_northeurope, error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/185bd685-2d36-430b-bd36-f0c279e033a9/resourceGroups/MC_oblive-ne-rg_oblive-ne-aks_northeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aks-systempool-78790466-vmss?api-version=2019-07-01: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: failed to get service principal token, error: failed to refresh token, error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}
E1019 14:02:28.038058       1 mic.go:1110] failed to apply binding default/oblive-ne-aks-id-binding node aks-systempool-78790466-vmss000000 for pod pod-identity/demo, error: failed to update identities for aks-systempool-78790466-vmss in MC_oblive-ne-rg_oblive-ne-aks_northeurope, error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/185bd685-2d36-430b-bd36-f0c279e033a9/resourceGroups/MC_oblive-ne-rg_oblive-ne-aks_northeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aks-systempool-78790466-vmss?api-version=2019-07-01: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: failed to get service principal token, error: failed to refresh token, error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}
E1019 14:02:28.092603       1 mic.go:1093] failed to update user-assigned identities on node aks-apppool-78790466-vmss (add [1], del [0], update[0]), error: failed to update identities for aks-apppool-78790466-vmss in MC_oblive-ne-rg_oblive-ne-aks_northeurope, error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/185bd685-2d36-430b-bd36-f0c279e033a9/resourceGroups/MC_oblive-ne-rg_oblive-ne-aks_northeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aks-apppool-78790466-vmss?api-version=2019-07-01: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: failed to get service principal token, error: failed to refresh token, error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}
E1019 14:02:28.148108       1 mic.go:1110] failed to apply binding default/oblive-ne-aks-agentpool-binding node aks-apppool-78790466-vmss000000 for pod oblive-dash/oddsbods-frontends-dashboard-6997b56bbd-mhkkl, error: failed to update identities for aks-apppool-78790466-vmss in MC_oblive-ne-rg_oblive-ne-aks_northeurope, error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/185bd685-2d36-430b-bd36-f0c279e033a9/resourceGroups/MC_oblive-ne-rg_oblive-ne-aks_northeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aks-apppool-78790466-vmss?api-version=2019-07-01: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: failed to get service principal token, error: failed to refresh token, error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Ide

**Comment by chewong** [comment]
Could you see if you are experiencing symptoms similar to https://azure.github.io/aad-pod-identity/docs/known-issues/#user-assigned-managed-identity-deleted-and-recreated-with-the-same-name-in-azure?

**Comment by matthewbrumpton-oddsbods** [comment]
Thanks for the link but we have tried creating new identities and they so not work either, I am about to restart out VMSS node pools as suggested by support.

**Comment by chewong** [comment]
If the above method did not work for you, it's probably due to an IMDS caching issue. Please let us know if restarting your VMSS node works.

**Comment by matthewbrumpton-oddsbods** [comment]
Yup, caching issue, working now
