### ISSUE TITLE
we have windows nodes and it looks like not working. Did you test with windows nodes.

### ISSUE THREAD

**Issue by dariuszbz** [Azure/aad-pod-identity#849]

**Comment by dariuszbz** [comment]
I mean:
aad pod are still on linux in in namespace: aaddev

i developed the solution and deployed into windows node under the same namespace: aaddev.

windows solution fails to get credentials :(

**Comment by chewong** [comment]
Duplicated issue: https://github.com/Azure/aad-pod-identity/issues/242
