### ISSUE TITLE
Issue with Daemon Set Starting up

### ISSUE THREAD

**Issue by philthynz** [Azure/aad-pod-identity#857]
**Describe the bug**

A container in the daemon set for the NMI did not start. The error is `0/2 nodes are available: 1 Too many pods, 1 node(s) didn't match node selector.`

![image](https://user-images.githubusercontent.com/17504095/98068576-4c25d000-1ec1-11eb-98e0-6158c60c66b4.png)

**Steps To Reproduce**

Deploy via Terraform Helm:

```
resource "helm_release" "aad-pod-identity" {
  name       = "aad-pod-identity"
  repository = "https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts"
  chart      = "aad-pod-identity"

  set {
  name  = "rbac.enabled"
  value = "true"
  }
}
```

In AKS, under daemon set's, one is failed with `0/2 nodes are available: 1 Too many pods, 1 node(s) didn't match node selector.` in the Events.

**Expected behavior**

Daemon set runs

**AAD Pod Identity version**

2.0.2

**Kubernetes version**

1.19.0

**Comment by chewong** [comment]
Looks like it's a scheduling problem:
- Too many pods: are you running a lot of workload on your clusters? Having too many pods scheduled to your nodes might lead to the inability to schedule additional workload.
- didn't match node selector: we only have `kubernetes.io/os: linux` as the node selector, so I am not sure why you are getting this error if you only have Linux nodes.

**Comment by philthynz** [comment]
@chewong So I'm only running the default set of pods that AKS needs to do the AzureAD integration, RBAC, Monitoring...

![image](https://user-images.githubusercontent.com/17504095/98071938-bcd0ea80-1ec9-11eb-9a60-ba7da117ca86.png)

And yes "didn't match node selector" is strange because there is [only one nodeselector in the yaml.](https://github.com/Azure/aad-pod-identity/blob/e1e9bc9edd3b9bc1a61b0698935561d8023c1505/charts/aad-pod-identity/values.yaml#L142)

**Comment by philthynz** [comment]
Managed to fix the issue. I was settings the nodes to only run a certain amount of pods... Silly me...
