### ISSUE TITLE
NMI pod CrashLoopBackOff state

### ISSUE THREAD

**Issue by Hareeshyalamasetty** [Azure/aad-pod-identity#875]
Deployed Pod identity using helm charts  
Node managed identity pod going to be CrashLoopBackOff state

  ----     ------     ----                  ----               -------
  Normal   Scheduled  18m                   default-scheduler  Successfully assigned default/nmi-6dbm5 to aks-default-11479314-vmss000000
  Normal   Pulling    18m (x4 over 18m)     kubelet            Pulling image "mcr.microsoft.com/oss/azure/aad-pod-identity/nmi:v1.7.0"
  Normal   Pulled     18m (x4 over 18m)     kubelet            Successfully pulled image "mcr.microsoft.com/oss/azure/aad-pod-identity/nmi:v1.7.0"
  Normal   Created    18m (x4 over 18m)     kubelet            Created container nmi
  Normal   Started    18m (x4 over 18m)     kubelet            Started container nmi
  Warning  BackOff    3m48s (x78 over 18m)  kubelet            Back-off restarting failed container

**Comment by aramase** [comment]
@Hareeshyalamasetty Could you check the NMI pod logs to see why it's crashing?

**Comment by Hareeshyalamasetty** [comment]
Thanks for the inputs.
Identified the issue, Here am using AKS v1.18 
kubenet networking plugin does not support the pod identity.

**Comment by aramase** [comment]
Thank you for confirming. The logs will contain the doc URL, but reposting it here for you're reference: https://azure.github.io/aad-pod-identity/docs/configure/aad_pod_identity_on_kubenet/

**Comment by aramase** [comment]
Closing this issue as it's now resolved. Please feel free to reopen if you have any more questions.
