### ISSUE TITLE
NMI pods in crash loop

### ISSUE THREAD

**Issue by mbmha** [Azure/aad-pod-identity#892]
**Have you**

- [X] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [X] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [X] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
We are running k8s on AKS. I had to reset the credentials for the default cluster service principal. After doing so, we are no longer able to start the nmi pods.
**Steps To Reproduce**
Install aad-pod-identity with the default settings on a RBAC cluster
**Expected behavior**
nmi pod starts successfully
**AAD Pod Identity version**
1.7.0
**Kubernetes version**
1.18.10
**Additional context**
 I1203 19:15:00.444171       1 main.go:84] starting nmi process. Version: v1.7.0. Build date: 2020-11-13-00:18.
I1203 19:15:00.547608       1 crd.go:447] CRD lite informers started 
I1203 19:15:00.647901       1 main.go:111] running NMI in namespaced mode: false
I1203 19:15:00.647958       1 nmi.go:53] initializing in standard mode
I1203 19:15:00.647967       1 probes.go:41] initialized health probe on port 8085
I1203 19:15:00.647973       1 probes.go:44] started health probe
I1203 19:15:00.648062       1 metrics.go:341] registered views for metric
I1203 19:15:00.648140       1 prometheus_exporter.go:21] starting Prometheus exporter
I1203 19:15:00.648151       1 metrics.go:347] registered and exported metrics on port 9090
I1203 19:15:00.648164       1 server.go:98] listening on port 2579
E1203 19:15:00.648439       1 prometheus_exporter.go:28] failed to run Prometheus scrape endpoint, error: listen tcp :9090: bind: address 
already in use
F1203 19:15:00.648534       1 server.go:100] error creating http server: listen tcp 127.0.0.1:2579: bind: address already in use
goroutine 1 [running]:

**Comment by chewong** [comment]
Did you re-install the pod identity deployment?

**Comment by mbmha** [comment]
Yes, I deleted the deployment and the nmi daemonset. The issue still persists.

**Comment by chewong** [comment]
Have you verified that there is no application occupying port 9090 of the host network?

**Comment by aramase** [comment]
@mbmha Could you also post the output for `kubectl get ds -A`?

**Comment by sanjkuma** [comment]
I also hit this issue today. @chewong How can I find out if there is any application occupying port 9090 of the host network?
PS C:\> kubectl get ds -A
NAMESPACE     NAME                                                              DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                 AGE
default       csi-secrets-store-provider-azure-1607649598                       3         3         3       3            3           kubernetes.io/os=linux        6h14m
default       csi-secrets-store-provider-azure-1607649598-secrets-store-csi-d   3         3         3       3            3           kubernetes.io/os=linux        6h14m
default       geneva-services                                                   3         3         3       3            3           <none>                        27h
kube-system   aad-pod-identity-nmi                                              3         3         0       3            0           kubernetes.io/os=linux        2m8s
kube-system   kube-proxy                                                        3         3         3       3            3           beta.kubernetes.io/os=linux   24d
kube-system   omsagent                                                          3         3         3       3            3           <none>                        24d
kube-system   omsagent-win                                                      0         0         0       0            0           <none>                        24d

**Comment by chewong** [comment]
A really quick way to check:
1. Download https://github.com/kvaps/kubectl-node-shell
2. kubectl node-shell <affected node name>
3. `lsof -i:<port>`

**Comment by aramase** [comment]
@sanjkuma reached out to me on teams. The cluster is using kubenet and he is following the docs: https://azure.github.io/aad-pod-identity/docs/configure/aad_pod_identity_on_kubenet/ to enable pod identity on that cluster.

**Comment by aramase** [comment]
@mbmha Is the issue resolved now? Can we close this?

**Comment by aramase** [comment]
Closing this issue now.
