### ISSUE TITLE
Make Helm Chart release more clear

### ISSUE THREAD

**Issue by pierluigilenoci** [Azure/aad-pod-identity#897]
**Describe the request**

I would like, whenever a new version of the Helm Chart is released, it will be posted on the releases page. https://github.com/Azure/aad-pod-identity/releases
As does ingress-nginx, for example: https://github.com/kubernetes/ingress-nginx/releases

**Explain why AAD Pod Identity needs it**
To be notified whenever it happens and keep clusters up to date without having to proactively verify this repo. 

**Describe the solution you'd like**
Not relevant

**Describe alternatives you've considered**
Move the chart to another repo

**Additional context**
Please 🙏

**Comment by pierluigilenoci** [comment]
Makes sense. But what happens if the released chart is broken and you need to make an urgent fix only to that?

**Comment by aramase** [comment]
We test the helm charts as part of the CI which is a blocker for release. If the chart as part of the release is broken, we republish the charts with the same version. We have not made a chart only release so far.

**Comment by aramase** [comment]
Closing this issue now. Please feel free to reopen if you've any questions.
