### ISSUE TITLE
User Assigned Identity removed from VMSS Identity

### ISSUE THREAD

**Issue by rem-k** [Azure/aad-pod-identity#898]
**Describe the bug**
Not sure if this is a bug or a faulty configuration on my side but I noticed that the User Assigned Identity is removed from VMSS Identity when deleting an app pod (eg. kubectl delete nginx). The User Assigned Identity is added again to the VMSS when I deploy the app pod again.

If however I delete the pod and uninstall the aad-pod-identity helm chart then the VMSS is left without a User Assigned Identity.

Reinstalling the helm chart and deploying the application pod again and MIC cannot find the identity. 
```
E1204 13:28:53.189184       1 mic.go:1094] failed to update user-assigned identities on node aks-default-12319176-vmss (add [1], del [0], update[0]), error: failed to update identities for aks-default-12319176-vmss in MC_rg-dev_aks-dev-fdfsf1_westeurope, error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/<subscr>/resourceGroups/MC_rg-dev_aks-dev-fdfsf1_westeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aks-default-12319176-vmss?api-version=2019-07-01: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: failed to get service principal token, error: failed to refresh token, error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}
E1204 13:28:53.263699       1 mic.go:1112] failed to apply binding aad-identity/identity-aks-kv-binding node aks-default-12319176-vmss000000 for pod aad-identity/nginx-pod, error: failed to update identities for aks-default-12319176-vmss in MC_rg-dev_aks-dev-fdfsf1_westeurope, error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/<subscr>/resourceGroups/MC_rg-dev_aks-dev-fdfsf1_westeurope/providers/Microsoft.Compute/virtualMachineScaleSets/aks-default-12319176-vmss?api-version=2019-07-01: StatusCode=403 -- Original Error: adal: Refresh request failed. Status Code = '403'. Response body: failed to get service principal token, error: failed to refresh token, error: adal: Refresh request failed. Status Code = '400'. Response body: {"error":"invalid_request","error_description":"Identity not found"}
```

**Steps To Reproduce**
- spin up AKS cluster with service principal
- create managed identity in resource group rg-dev
- grant the managed identity "Managed Identity Operator" role on resource group  containing the VMSS (MC_rg-dev_aks-dev-fdfsf1_westeurope)
- grant the managed identity "Virtual Machine Contributor"  role on resource group  containing the VMSS (MC_rg-dev_aks-dev-fdfsf1_westeurope)
- grant the managed identity "Managed Identity Operator" role on resource group containing the AKS cluster (rg-dev)
- add the managed identity to VMSS User Assigned Identity
- helm install aad-pod-identity with specifying the just created User Assigned Identity
```
adminsecret:
   cloud: "AzurePublicCloud"
   subscriptionID: <subscription id>
   resourceGroup: MC_rg-dev_aks-dev-fdfsf1_westeurope
   vmType: vmss
   tenantID: <tenant id>
   clientID: msi
   clientSecret: msi
   useMSI: "true"
   userAssignedMSIClientID: <client id from the managed identity>
```
- deploy an app with aad binding
- delete the app
- helm uninstall aad-pod-identity
- helm install aad-pod-identity
- install the app

**Expected behavior**
If it is a prerequisite that the VMSS should already contain the User Assigned Identity then a kubectl delete pod should not remove the Identity from VMSS. 

If however removing the Identity from VMSS when the pod is deleted is expected behaviour then the User Assigned Identity should be added automatically too when the pod is deployed.

**AAD Pod Identity version**
1.7.0

**Kubernetes version**
1.18.10

**Additional context**
Our setup is AKS with an UDR and thus AKS is provisioned with a service principal. For pods connecting to KeyVault we were hoping that we could still make use of managed identity.

**Comment by aramase** [comment]
```
   clientID: msi
   clientSecret: msi
```

this means MIC has been instructed to use a user-assigned identity to authenticate with azure. MIC removes the identity from the underlying VMSS when no pods are configured to use that identity (through AzureIdentityBinding). In this case if you're using the same identity for MIC auth and application, then when the application is deleted, identity will be removed and subsequent token calls will fail.

**Comment by rem-k** [comment]
Clear, thank you! I missed the bit where the application identity is actively being removed when no pods are making use of it any more. Using a separate identity for MIC and the application works like a charm.
