### ISSUE TITLE
Clarification on Service Principal security

### ISSUE THREAD

**Issue by vslepakov** [Azure/aad-pod-identity#90]
Hi,

I just want to be sure that I get the functionality right...

So aad-pod-identity enables me to have a separate identity per application which is cool.
MIC uses cluster service principal to access Azure resources (including Managed Identities) so I assume that cluster service principal (secret) is still accessible on all the nodes correct?
Having access to that I could access all other identities and escalate.

Do I miss something? 

Thanks!

**Comment by khenidak** [comment]
@kkmsft @rite2nikhil FYI

**Comment by kkmsft** [comment]
@vslepakov - our plan is to separate out the usage of cluster SP and use a separate one for the MIC. This way the cluster level identities will not be used by MIC. This is something we are tracking in our back log. I am starting to track the backlog/features we are working on here: https://github.com/Azure/aad-pod-identity/issues/114. 

Having said that the SP being accessible to all nodes is an existing situation in AKS/acs-engine clusters.

**Comment by vslepakov** [comment]
Thanks!
