### ISSUE TITLE
Update Azure documentation to link to AAD Pod Identity preview page

### ISSUE THREAD

**Issue by phillipgibson** [Azure/aad-pod-identity#903]
We need to update the docs at <https://docs.microsoft.com/en-us/azure/aks/operator-best-practices-identity> for the "Use pod identities" section.

**Describe the bug**
Outdated docs at <https://docs.microsoft.com/en-us/azure/aks/operator-best-practices-identity#use-pod-identities>

**Expected behavior**
Link to preview doc at <https://docs.microsoft.com/en-us/azure/aks/use-azure-ad-pod-identity>

**AAD Pod Identity version**
N/A

**Kubernetes version**
N/A

**Additional context**
N/A

**Comment by asubmani** [comment]
For the sake of existing pod-identity users who install it manually; please mention in the docs that this will work as a managed mode; i.e. no MIC
I just verified this.

**Comment by aramase** [comment]
@phillipgibson are you still working on this?

**Comment by phillipgibson** [comment]
Let me see if I can close the loop with the Docs team.

**Comment by phillipgibson** [comment]
MSFT docs PR is currently in review https://github.com/MicrosoftDocs/azure-docs/pull/68924

**Comment by aramase** [comment]
@phillipgibson Is the PR in the private repo merged? Can we close this issue now?

**Comment by phillipgibson** [comment]
Yes this has been merged. The initial PR was associated to the wrong docs repo.

**Comment by aramase** [comment]
Thanks, Phil!
