### ISSUE TITLE
Question: Migrating from Standard to Managed Mode

### ISSUE THREAD

**Issue by asubmani** [Azure/aad-pod-identity#917]
# Standard to Managed Mode migration steps

The managed mode docs show how to create a new podidentity setup in managed mode. However if one has an existing setup with "standard" mode and wants to migrate to "Managed"; would the below sequence be correct:

NOTE: `kubectl delete -f  https://github.com/Azure/aad-pod-identity/blob/master/deploy/infra/deployment-rbac.yaml`
This should not be done in a migration as this would delete the Managed Identity CRD and the "AzureIdentity" & AzureIdentityBindings" from every namespace

1. Run VMSS assignment to assign all identities to all scalesets.
 
2. Edit (I have NMI in a custom ns) and deploy only the managed mode deployment `kubectl apply -f https://raw.githubusercontent.com/Azure/aad-pod-identity/master/deploy/infra/managed-mode-deployment.yaml`  

**OR**
              
`kubectl patch ds --patch ./managed-mode-depoyment.yaml`

3.  Delete the mic deployment, service accounts(`aad-pod-id-mic-service-account`), the `aad-pod-id-mic-role` clusterrole, clusterRoleBinding
4.  Apart from these 4 objects, is there anything else one needs to delete?

Would this be the right way to migrate without downtime (or with minimal)?

Would this require restarting the pods?
    I had to bounce my demo pod, but will try the entire operation again to confirm.

**Comment by asubmani** [comment]
we have ~ 250 identities and ~ 500 pods in 4 nodepools, aadpodidentity works well but we are getting API throttling issues on management.azure.com and bouncing the service usually takes a while to catch up.

Using 1.6.3

**Comment by aramase** [comment]
The order of steps looks right. If you're deleting the MIC, you might also want to delete the `AzureAssignedIdentities` manually. The `AzureAssignedIdentity` contains a finalizer to prevent deletion. 

Please refer to this [doc](https://azure.github.io/aad-pod-identity/docs/troubleshooting/#unable-to-remove-azureassignedidentity-after-mic-pods-are-deleted) on how to delete the `AzureAssignedIdentities` after deleting MIC. 

The app pods aren't required to be restarted.

**Comment by asubmani** [comment]
Thanks @aramase .. I presume after deleting the `AzureAssignedIdentities` we should also delete the associated CRD. i.e. `kubectl delete crd azureassignedidentities.aadpodidentity.k8s.io`

**Comment by aramase** [comment]
@asubmani That's correct.
