### ISSUE TITLE
Unable to install aad-pod-identity as a chart dependency

### ISSUE THREAD

**Issue by kongbb** [Azure/aad-pod-identity#929]
I created a chart, add aad-pod-identity as a dependency, Chart.yaml contains below dependency configuration:

dependencies:
  - name: aad-pod-identity
    version: 3.0.0
    repository: https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts
    enabled: true

run "helm dependency update" successfully download ...tgz to charts folder.
but run "helm install myrelease mychart" fail with following error:
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "AzurePodIdentityException" in version "aadpodidentity.k8s.io/v1"

I am using helm3

**Comment by chewong** [comment]
We had a couple of similar issues in the past. Could you quickly go through them at https://github.com/Azure/aad-pod-identity/issues?q=unable+to+recognize+%22%22 to see if it resolves your issue?

**Comment by kongbb** [comment]
I had gone through these and believe this is a different issue.

To be clear, I am able to install aad-pod-identity using helm 3.  Now I want to put add-pod-identity helm as a chart dependency, that's how I encounter this issue.

**Comment by chewong** [comment]
I saw `UPGRADE FAILED` in your error message. Did you uninstall aad-pod-identity before installing your chart?

**Comment by aramase** [comment]
@kongbb I just tried the pod identity helm chart as dependency to another chart and can confirm it work as expected.

1. Added to `requirements.yaml`

```yaml
- name: aad-pod-identity
  repository: https://raw.githubusercontent.com/Azure/aad-pod-identity/master/charts
  version: 3.0.3
  condition: aad-pod-identity.install
```

2. Added to `values.yaml`

```
aad-pod-identity:
  install: true
```

3. Ran helm install and can confirm the crds exists and the pod identity components are running as expected:

```bash
➜ kubectl get crds
NAME                                                        CREATED AT
azureassignedidentities.aadpodidentity.k8s.io               2021-03-05T17:46:58Z
azureidentities.aadpodidentity.k8s.io                       2021-03-05T17:46:58Z
azureidentitybindings.aadpodidentity.k8s.io                 2021-03-05T17:46:58Z
azurepodidentityexceptions.aadpodidentity.k8s.io            2021-03-05T17:46:58Z
secretproviderclasses.secrets-store.csi.x-k8s.io            2021-03-05T17:47:03Z
secretproviderclasspodstatuses.secrets-store.csi.x-k8s.io   2021-03-05T17:47:03Z

➜ kubectl get pods
NAME                                         READY   STATUS              RESTARTS   AGE
aad-pod-identity-mic-545689bb48-4zpj8        0/1     ContainerCreating   0          10s
aad-pod-identity-mic-545689bb48-d75q2        0/1     ContainerCreating   0          10s
aad-pod-identity-nmi-dkts6                   0/1     ContainerCreating   0          10s
csi-csi-secrets-store-provider-azure-2jdgm   0/1     ContainerCreating   0          10s
csi-secrets-store-csi-driver-bhrq9           0/3     ContainerCreating   0          10s
```

Helm version
```
➜ helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

**Comment by aramase** [comment]
@kongbb Any updates on this one?

**Comment by kongbb** [comment]
@aramase I can confirm that can work. Thanks.
