### ISSUE TITLE
'parameter resource cannot be empty' 

### ISSUE THREAD

**Issue by elsesiy** [Azure/aad-pod-identity#932]
**Have you**

- [x] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [x] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [x] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
Since `v1.7.0` we're seeing the following sequence in the logs (redacted):
```
W0109 04:09:11.676300       1 server.go:336] parameter resource cannot be empty
I0109 04:09:11.676328       1 server.go:192] status (400) took 41602 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.4.66.134
I0109 04:09:11.676985       1 standard.go:73] no clientID or resourceID in request. ns/pod has been matched with azure identity ns/azureidentity
I0109 04:09:11.677052       1 standard.go:179] matched identityType:0 clientid:2469##### REDACTED #####ea89 resource:https://management.azure.com
I0109 04:09:11.689775       1 server.go:192] status (200) took 12888364 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.4.66.134
W0109 04:09:11.741605       1 server.go:336] parameter resource cannot be empty
I0109 04:09:11.741626       1 server.go:192] status (400) took 30802 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.4.66.134
I0109 04:09:11.742278       1 standard.go:73] no clientID or resourceID in request. ns/pod has been matched with azure identity ns/azureidentity
I0109 04:09:11.742327       1 standard.go:179] matched identityType:0 clientid:2469##### REDACTED #####ea89 resource:https://management.azure.com
I0109 04:09:11.753863       1 server.go:192] status (200) took 11675401 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.4.66.134
```

It seems like one of the requests intercepted is deemed "bad". I tried increasing logging verbosity via `-v=8` for NMI to trace the request but that only adds the IP table traces to the logs. 

Is there anything else I can do to help trace the request and find the root cause for this?
Thanks!

**AAD Pod Identity version**
`1.7.0` & `1.7.1` show the same behavior

**Kubernetes version**
`1.17.13`

**Additional context**
The log is emitted because of https://github.com/Azure/aad-pod-identity/blob/5225b06bba9ad3d6c8d857aa45efa598cac415fc/pkg/nmi/server/server.go#L227
There's no impact to the functionality since subsequent requests succeed but it would be nice to have a way of tracing the incoming http requests from NMI perspective. The producing app doesn't show any error logs w.r.t to adal request validation.

**Comment by chewong** [comment]
Based on past issues, I am suspecting that the ADAL library is doing some sort of health check by sending requests to IMDS without including `request` parameter. Which ADAL library are you using?

**Comment by elsesiy** [comment]
Thanks for the quick reply @chewong, we're using `github.com/Azure/go-autorest/autorest/adal v0.9.10` but it's the same behavior in earlier versions.

**Comment by chewong** [comment]
AFAIK ADAL library in Go does not perform health check (I think only C# one does). There might be other applications in your cluster sending requests to IMDS. I agree that there should be more info on invalid requests. I will put this issue in our next milestone.

**Comment by chewong** [comment]
@aramase any idea on where the request can originate from?

**Comment by aramase** [comment]
ADAL doesn't perform any validation of the request. However IMDS will error out if the request doesn't contain the `resource` which is why NMI imposes the same limitation. 

The ADAL library also seems to be doing health check in the recent releases: https://github.com/Azure/go-autorest/blob/master/autorest/adal/token.go#L962 which could be what we are seeing.

**Comment by chewong** [comment]
Closing this issue since it's simply a health check from the ADAL library.

**Comment by elsesiy** [comment]
@chewong Can we not exclude the healthcheck from logging this warn? It's not ideal the way it is now.

**Comment by aramase** [comment]
@elsesiy There is no ideal way for pod identity to distinguish an actual token/health check request. All the requests that come in to pod identity for the token uri are validated in the same way.

**Comment by elsesiy** [comment]
@aramase I understand the problem but I'd argue that the current warn log is not very useful either. There's no way for us to disable the adal healthcheck & this is flooding logs unnecessarily. Can we increase the logging verbosity for this item or make it configure to ignore certain requests?

**Comment by elsesiy** [comment]
@aramase Do you have any thoughts on my proposal?

**Comment by aramase** [comment]
@elsesiy There is no way to distinguish the request here to determine if it's a health check or a legit token request. From the logs posted:

```bash
W0109 04:09:11.741605       1 server.go:336] parameter resource cannot be empty
I0109 04:09:11.741626       1 server.go:192] status (400) took 30802 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.4.66.134
```

This could be a token request with no `resource` header or a health check. However the URI for both is `/metadata/identity/oauth2/token` which means we can't really distinguish here. The warning is logged so if it's a valid token request that's missing the `resource` header then NMI logs that so user can take actions. 

```bash
I0109 04:09:11.742278       1 standard.go:73] no clientID or resourceID in request. ns/pod has been matched with azure identity ns/azureidentity
I0109 04:09:11.742327       1 standard.go:179] matched identityType:0 clientid:2469##### REDACTED #####ea89 resource:https://management.azure.com
I0109 04:09:11.753863       1 server.go:192] status (200) took 11675401 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=10.4.66.134
```

this is a valid token request which also has the same URI: `/metadata/identity/oauth2/token` and the correct `resource` header.

Increasing the warning would mean the user will no longer be able to see the error by default unless they increase the verbosity. I think we should log these errors by default.
