### ISSUE TITLE
Configuration/Installation with Managed AD

### ISSUE THREAD

**Issue by dvob** [Azure/aad-pod-identity#939]
We have installed a new cluster and enabled the managed AD integration. This way it seems that MIC by default uses the managed identity called `<clustername>-agentpool`. This is the identity which gets returned if you run:
```
az aks show --subscription my-subscription --name cluster-name --resource-group resource-group-name | jq .identityProfile.kubeletidentity
```
Unfortunately this identity does not have permission to update the VMSS of the AKS cluster, so it is not able to assign the managed identities.
There is another identity which belongs to the AKS cluster which would have the contributor role on the VMSS, so enough permission to update it.  If I open the identity it tells me that it is an "Enterprise Application". This identity gets retuned if you run:
```
az aks show --subscription my-subscription  --name cluster-name --resource-group resource-group-name | jq .identity
``` 
How can we configure MIC to use this identity?

**Comment by chewong** [comment]
Could you try uninstalling aad-pod-identity before installing it again? You can append `--debug` at the end of the command to view the helm debug log.

**Comment by chewong** [comment]
> Unfortunately this identity does not have permission to update the VMSS of the AKS cluster, so it is not able to assign the managed identities.

You will have to run our [role assignment](https://azure.github.io/aad-pod-identity/docs/getting-started/role-assignment/) script to grant the necessary permission to `<clustername>-agentpool`. Note that AKS only uses one managed identity per cluster (shown in `.identityProfile.kubeletidentity`) when you enable managed identity so I don't think there is a way to specify which managed identity to use for MIC.

**Comment by dvob** [comment]
Thank you for pointing us to the role-assignment script.
