### ISSUE TITLE
error token: spark job is blocked to acquire the token from NMIs.

### ISSUE THREAD

**Issue by calvinShan** [Azure/aad-pod-identity#947]
**Have you**

- [ ] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [ ] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [ ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
 we run spark job to realize big data analytics and calculations in AKS. The job is blocked to acquire the token from NMIs 

It works to distribute the token and connect to the database. However, when we launch the spark job, it takes one hour waiting for the response(error response). 
However, when we restart the NMI pods during waiting time, it works immediately.

we have no errors like 'not have permission to perform action'.
We have already assigned the role 'reader' to the managed identity  in the MC rg, and created the user from external and data_owner role for the sql database in Azure.

Logs from NMI:
E0111 15:22:27.869809 1 server.go:370] failed to get matching identities for pod: data/***-job-slq67, error: getting assigned identities for pod data/***-job-slq67 in CREATED state failed after 16 attempts, retry duration [5]s. Error: <nil>

E0111 16:44:28.564103 1 server.go:370] failed to get matching identities for pod: data***-exec-1, error: getting assigned identities for pod data/***-1610383376540-exec-1 in CREATED state failed after 16 attempts, retry duration [5]s. Error: <nil>

I0111 16:44:28.564139 1 server.go:191] Status (404) took 80007138161 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=*.*.*.*
**Steps To Reproduce**
when we restart the NMI pods during waiting time, it works immediately. Otherwise, it doesn't work

Logs from MIC pods: 
**no** errors like 'not have permission to perform action'

The only errors from the MIC are like these:
W0115 14:46:35.378275       1 mic.go:1265] Unable to get node aks-pool2-...-vmss... while updating user msis. Error
node "aks-pool2-...-vms..." not found
W0115 15:14:15.691054       1 mic.go:1265] Unable to get node aks-pool2-..-vmss... while updating user msis. Error
node "aks-pool2-...-vmss..." not found

**Expected behavior**

**AAD Pod Identity version**
nmi:1.6.1
**Kubernetes version**
aks 1.18.8
**Additional context**
To deploy an API with a managed identity to access Azure SQL Database: 
val connectionProperties = new Properties()
      connectionProperties.put("loginTimeout", "300")
      connectionProperties.put("authentication", "ActiveDirectoryMSI")
      connectionProperties.put("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver")
      connectionProperties.put("msiClientId",clientID)
val mainInstall = spark.read.jdbc("***", table ="(select *** from " + "dbo.****" + ") as mainInstall", connectionProperties)      mainInstall.show()

**Comment by chewong** [comment]
Could you also share the MIC log?

**Comment by calvinShan** [comment]
> Could you also share the MIC log?

Yes, logs in MIC are standard, the only errrors from MIC are like these:
W0115 14:46:35.378275 1 mic.go:1265] Unable to get node aks-pool2-...-vmss... while updating user msis. Error
node "aks-pool2-...-vms..." not found
W0115 15:14:15.691054 1 mic.go:1265] Unable to get node aks-pool2-..-vmss... while updating user msis. Error
node "aks-pool2-...-vmss..." not found

**Comment by chewong** [comment]
Thanks for providing the logs. Could you include your `AzureIdentity` and `AzureIdentityBinding` spec? I am suspecting that something is set up incorrectly

**Comment by calvinShan** [comment]
> Thanks for providing the logs. Could you include your `AzureIdentity` and `AzureIdentityBinding` spec? I am suspecting that something is set up incorrectly

We have set up several APIs that work very well by using the MIs, yes, we haved created AzureIdentity and AzureIdentityBinding for each MI/API
The only problem is about the MI used by a spark job, something does not work in NMI to delivery the token for the driver pod

**Comment by chewong** [comment]
@aramase any idea?

**Comment by aramase** [comment]
@calvinShan 

1. Is the spark job using its own identity?
2. How often is the job created and deleted?
3. The NMI error you posted above indicates an error in MIC while assigning the identity. NMI relies on MIC to assign the identity and set the status using a custom resource called `AzureAssignedIdentity`. That error implies MIC has not created the `AzureAssignedIdentity` for this pod and binding.

The next time the error occurs, could you check the following:
1. Logs for NMI pod running on the same node as the spark job pod.
2. MIC pod logs for the same timeframe to understand what MIC is doing.
3. Also, check if there is an `AzureAssignedIdentity` created for the spark job pod: `kubectl get azureassignedidentity -A | grep <spark job pod name>` and then dump the output of `kubectl get azureassignedidentity <name> -n <namespace> -o yaml`.

> W0115 14:46:35.378275 1 mic.go:1265] Unable to get node aks-pool2-...-vmss... while updating user msis. Error
node "aks-pool2-...-vms..." not found

These errors in MIC seem to indicate the `GET` vmss is failing because the cloud API call is returning a `404`?

**Comment by calvinShan** [comment]
we are able to resolve this by adding these lines of code to your Spark job:
options.getConf().put("spark.kubernetes.driver.label.aadpodidbinding", job.getRunAs());               
options.getConf().put("spark.kubernetes.executor.label.aadpodidbinding", job.getRunAs());

**Comment by chewong** [comment]
Thanks for letting us know. We can put this solution on our documentation in case anyone encounters the same problem in the future.
