### ISSUE TITLE
Control access to use the right MI by the API

### ISSUE THREAD

**Issue by calvinShan** [Azure/aad-pod-identity#958]
**Have you**

- [ ] Read [Troubleshooting Guide](../../docs/readmes/README.troubleshooting.md)
- [ ] Read [Known Issues](../../docs/readmes/README.known-issues.md)
- [ ] Searched on [GitHub issues](https://github.com/Azure/aad-pod-identity/issues)

**Describe the bug**
We need to configure role-based access control  to limit access to the MI

case:
we have a spark api  and a job api in one namespace ,
and we have created two managed identities : mi-job and mi-spark for each other.

we want to configure RBAC to make sure that, the spark api can ONLY use the mi-spark and the job api can ONLY use the mi-spark.
We use the aadpodidbinding label to associate MI with the API. However, the azureIdentity and azureIdentityBinding are finally taken by NMI/MIC. We can't control access to use the right MI at the level of PODs/API

 It causes a security problem, because we have assigned different roles for different MIs

**Expected behavior**
We need to configure role-based access control  to limit access to the MI
**AAD Pod Identity version**
nmi:1.6.1
**Kubernetes version**
1.18.8

**Comment by chewong** [comment]
Even with [namespaced mode](https://azure.github.io/aad-pod-identity/docs/configure/match_pods_in_namespace/) enabled, all `AzureIdentity` and `AzureIdentityBinding` are shared across the pod level. If there are security concerns, is it possible for the two workloads in separate namespaces?

**Comment by calvinShan** [comment]
> Even with [namespaced mode](https://azure.github.io/aad-pod-identity/docs/configure/match_pods_in_namespace/) enabled, all `AzureIdentity` and `AzureIdentityBinding` are shared across all pods in the same namespace. If there are security concerns, is it possible for the two workloads in separate namespaces?

Thanks for your reply, we have considered using namespaced mode. But we cannot move these two workloads in separate namespaces, because we cannot create one namespace for every api

**Comment by aramase** [comment]
@calvinShan Thank you for the response. The namespace is the security boundary. All the pods within a namespace can access the identities defined for that namespace. Apart from the namespace boundary, we can't impose access for a single pod to a single MI unless they are different namespaces.

**Comment by calvinShan** [comment]
> @calvinShan Thank you for the response. The namespace is the security boundary. All the pods within a namespace can access the identities defined for that namespace. Apart from the namespace boundary, we can't impose access for a single pod to a single MI unless they are different namespaces.

Yes, thanks for your confirmation. However, we need to control the access inside the namespace. SO could we code this control in our application? another solution is to control the access by using Dynamic Admission Control ?

**Comment by aramase** [comment]
> Yes, thanks for your confirmation. However, we need to control the access inside the namespace. SO could we code this control in our application? another solution is to control the access by using Dynamic Admission Control ?

@calvinShan Yeah, you can control this in the app. If the app requests token only for a specific clientid, NMI will check if the app pod has access to the `AzureIdentity` with the client id. If not, it'll return an error. Dynamic Admission Control is another way to control which pods use which label for `aadpodidbinding`. That'll ensure pod's don't get deployed with labels for `AzureIdentity` they shouldn't have access to.

**Comment by calvinShan** [comment]
> Yeah, you can control this in the app. If the app requests token only for a specific clientid, NMI will check if the app pod has access to the `AzureIdentity` with the client id
@aramase thanks for the reply. Every Pod Developer can add the aadpodidbinding label to his/her pod and use each Azure Identity he wants in the namespace. How could NMI return an error if the pod has not the access? given that we have already assigned the role to the MI for the managed resource group in azure

**Comment by aramase** [comment]
@calvinShan NMI gets the `AzureIdentityBinding` that matches the label on the pod. It then uses the `AzureIdentity` referred to in the binding and fetches a token for the clientID. If each `AzureIdentityBinding` has a distinct label and you've control over which pod uses which labels, pod identity will honor it.

**Comment by calvinShan** [comment]
> @calvinShan NMI gets the `AzureIdentityBinding` that matches the label on the pod. It then uses the `AzureIdentity` referred to in the binding and fetches a token for the clientID. If each `AzureIdentityBinding` has a distinct label and you've control over which pod uses which labels, pod identity will honor it.

However, our problem is about the way to control over  which pod uses which labels. In the same namespace, every pod can use every labels, and NMI never returns an error, because the pod always has access to use every label. do you have some ideals about how to control the access at level of pod

**Comment by calvinShan** [comment]
> > @aramase However, our problem is about the way to control over which pod uses which labels. In the same namespace, every pod can use every label, and NMI never returns an error, because the pod always has access to use every label. do you have some ideas about how to control the access at level of pod
> 
> At the pod level is a little tricky. Typically the namespace is the boundary and it's safe to assume all the pods within the namespace can access all identities defined for the namespace. To control which pods can use which labels, you would need an admission controller or configure policies to deny pod requests with certain labels.

Hi @aramase  do you have an idea or an example how to use admission controller/ policies in order to deny pod requests with the label aadpodidbinding? Thanks

**Comment by aramase** [comment]
@calvinShan Have you looked at using gatekeeper policies to maybe define mutually exclusive labels? If `label1` is present, then expected `aadpodidbinding` should only have `selector1` and if using `selector2` then fail.
