### ISSUE TITLE
Between 600 to 700 managed identities token requests from single pod ?

### ISSUE THREAD

**Issue by V4A001** [Azure/aad-pod-identity#980]
I see in my azure ad that about 600-700 requests per day are make to the AD from the Kubernetes managed identity. I do not believe this is normal or needed as tokens normally have 1 hour to live.

![image](https://user-images.githubusercontent.com/9630343/109416532-1bf9c400-79bf-11eb-9507-b3b7d685146e.png)

**Steps To Reproduce**
Not sure how to do this. Just have a .net core installed with 2 pod identities.

**Expected behavior**
Only once per hour or upon need a token refresh/ request?

**AAD Pod Identity version**
v1.7.2

**Kubernetes version**
v1.19.3

**Additional context**

**Comment by aramase** [comment]
@V4A001 Pod identity requests token from the IMDS running on the VM. IMDS is the one that fetches the token and returns from AAD. AFAIK IMDS returns the token from cache if it's valid. 

@rkammara12 Do you have any thoughts on this?

**Comment by rkammara12** [comment]
@aramase yes that is correct, things to note:
1. All the AAD tokens have 24hr token lifetime (currently there is no way that this can be changed)
2. IMDS always looks if there is a token available in the cache and returns it if it is valid. At the same time, as part of proactive renewal if a token is requested at times T1 and T2 where T2 - T1 >= 1hr, IMDS calls AAD to fetch a new token.

Please let me know if something is not clear.

**Comment by V4A001** [comment]
@aramase : thank you. But why in the Azure AD I see my pod identity requesting > 600 times of access in last 24 hrs?

**Comment by aramase** [comment]
> @aramase : thank you. But why in the Azure AD I see my pod identity requesting > 600 times of access in last 24 hrs?

By pod identity here, are you referring to the token requests from pod identity on behalf of the app pod or pod identity token requests by MIC to assign/unassign the identity?

This behavior is not something that's configured by pod identity. This could be how the underlying SDK is implemented. There is no client side caching/logic to determine the validity of the token. When requesting the token IMDS handles all the caching and token validation.

**Comment by V4A001** [comment]
My 2 k8s clusters even report > 1200 over last 24 hrs. It are both the omsagent- and agentpool which are present. These are the identities which are present in the vm cluster resource group and are listed in the IAM of the k8s management cluster. In the nmi and mic pods I see a lot of these:

nmi:
0301 19:43:18.147907       1 server.go:192] status (200) took 63964619 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=192.168.1.43
I0301 19:44:27.344389       1 server.go:358] exception pod kube-system/omsagent-np4tq token handling
I0301 19:44:27.344480       1 server.go:301] fetching token for user assigned MSI for resource: https://monitoring.azure.com/
I0301 19:44:27.353060       1 server.go:192] status (200) took 8728671 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=192.168.1.70
I0301 20:08:18.414975       1 server.go:358] exception pod kube-system/omsagent-rs-679f977967-j749n token handling
I0301 20:08:18.414996       1 server.go:301] fetching token for user assigned MSI for resource: https://monitoring.azure.com/
I0301 20:08:18.519178       1 server.go:192] status (200) took 104283243 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=192.168.1.43
I0301 20:09:27.671137       1 server.go:358] exception pod kube-system/omsagent-np4tq token handling
I0301 20:09:27.671159       1 server.go:301] fetching token for user assigned MSI for resource: https://monitoring.azure.com/
I0301 20:09:27.678624       1 server.go:192] status (200) took 7529561 ns for req.method=GET reg.path=/metadata/identity/oauth2/token req.remote=192.168.1.70

A lot of these in mic:
I0301 20:27:25.467244       1 mic.go:1449] reconciling identity assignment for [/subscriptions/79d66a

**Comment by aramase** [comment]
The reconciliation loop in MIC is to ensure identities are still assigned correctly to the underlying VMSS. The default reconciliation period is 3m, but you can configure that using the helm chart value `mic.identityAssignmentReconcileInterval` https://github.com/Azure/aad-pod-identity/tree/master/charts/aad-pod-identity#configuration.

There is no caching in pod identity for the tokens. The token requests is always sent to IMDS which determines if the token it has cached is valid and if not calls AAD.

**Comment by aramase** [comment]
Closing this issue now as pod identity doesn't make calls to AAD directly. The request is sent to IMDS which requests token from AAD. IMDS has caching mechanism.

Please feel free to re-open if you have any questions.
