### ISSUE TITLE
IMDS endpoint availability is delayed

### ISSUE THREAD

**Issue by PSanetra** [Azure/aad-pod-identity#992]
The IMDS endpoint, which is created by the NMI, is not always directly available after Pod startup. This causes critical issues with libraries, which expect the endpoint to be always available: https://github.com/Azure/azure-sdk-for-net/issues/18312

There is currently one generic workaround available by adding an `initContainer` to the pods, which are using the IMDS endpoint. The container should poll the IMDS endpoint until it becomes available, so that the actual containers can start regularly.

As far as I have understood, the developers of those libraries do not want to change the assumption, that the IMDS endpoint is always available. So the only option I see is, that the aad-pod-identity project needs to ensure that the IMDS endpoint is on all Pods, which are using the IMDS endpoint, available at startup time. This may be generically achievable with a mutating admission webhook, which adds an additional `initContainer` to all Pods, using the `aadpodidbinding` label. (See https://github.com/Azure/azure-sdk-for-net/issues/18312#issuecomment-781729340)

**Steps To Reproduce**

* See https://github.com/Azure/azure-sdk-for-net/issues/18312

**Expected behavior**

* The IMDS endpoint must be available when Pod containers start, which are using the IMDS endpoint.

**AAD Pod Identity version**

* AAD Pod Identity 1.7.1

**Kubernetes version**

* AKS 1.17.11

**Related issues**
* https://github.com/Azure/aad-pod-identity/issues/846
* https://github.com/Azure/azure-sdk-for-net/issues/18312

**Comment by chewong** [comment]
I think the delay is caused by underlying identity assignment to the node described in https://azure.github.io/aad-pod-identity/docs/best-practices/#retry-on-token-retrieval. One workaround, as you mentioned, is to implement a init container that probes the IMDS endpoint until it's available. You can also look into managed mode (https://azure.github.io/aad-pod-identity/docs/configure/pod_identity_in_managed_mode/), where you assign the identity to the node manually before deploying the workload to bypass the delay.

**Comment by PSanetra** [comment]
@chewong anyway, I think this is a problem which must be handled by Microsoft. Either by making sure that the libraries (in this case the Azure .NET SDK) are fault tolerant against these types of errors (which is currently not the case) or by providing some out-of-the-box solution like a mutating admission webhook in Kubernetes to apply that workaround to all affected pods by default.

**Comment by mpp-petew** [comment]
We are also seeing this problem and it's causing a bit of havoc. Nothing really to add other than our voice to the chorus of those affected by the `ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found` error, which so far as I can tell is due to the IMDS endpoint not being available.

**Comment by aramase** [comment]
Thank you for reporting the issue.

aad-pod-identity doesn't create the IMDS endpoint. It essentially adds the iptable rules to redirect all IMDS traffic to itself, so it can perform validation based on `AzureIdentity`, `AzureIdentityBinding` and forward only the requests that's valid. The delay you're observing here is the time taken to assign the identity to the underlying VM/VMSS. This is the equivalent of "az vm|vmss identity assign". The identity is assigned when the 1st pod consuming it is created and is un-assigned when all pods consuming it are deleted. This identity assignment takes ~10s for VMAS and about ~40s for VMSS. During this time token requests at NMI will be retried until the identity is assigned. 

We're looking into an option to return a status code with `retry-after` header from NMI when the identity is still being assigned. This will improve the behavior for SDK's that retry on status codes and honor the retry-after header but I doubt this'll help with the dotnet sdk as you mentioned there are no retries. 

In addition to aad-pod-identity in standard mode (MIC and NMI), we have pod identity available in managed mode (only NMI) where the identities are manually assigned by the user beforehand. This means there is no additional delay at the time of the pod requesting token: https://azure.github.io/aad-pod-identity/docs/configure/pod_identity_in_managed_mode/. AKS pod-identity add-on uses the aad-pod-identity in managed mode.
