### ISSUE TITLE
NMI fails on non-AKS cluster due to kubenet check

### ISSUE THREAD

**Issue by twendt** [Azure/aad-pod-identity#997]
**Describe the bug**
We have some Kubernetes clusters running in Azure that are deployed with Rancher. These clusters are not AKS. AAD Podidentity used to work without any issues here. Since 1.7 introduced the check if kubenet is enabled, the NMI fails now. There is no kubelet config file available on the node at all.

This is the related code:
```go
	// check if the cni is kubenet from the --network-plugin defined in kubelet config
	isKubenet, err := utils.IsKubenetCNI(*kubeletConfig)
	if err != nil {
		klog.Fatalf("failed to check if CNI plugin is kubenet, error: %+v", err)
	}
	if !*allowNetworkPluginKubenet && isKubenet {
		klog.Fatalf("AAD Pod Identity is not supported for Kubenet. Review https://azure.github.io/aad-pod-identity/docs/configure/aad_pod_identity_on_kubenet/ for more details.")
	}
```

We have been able to work around the issue by passing for instance /etc/hostname as the filename for the kubelet config just to make the check return false:

```go
func IsKubenetCNI(kubeletConfig string) (bool, error) {
	var isKubenet bool
	// read the kubelet config
	bytes, err := ioutil.ReadFile(kubeletConfig)
	if err != nil {
		return isKubenet, err
	}
	return strings.Contains(string(bytes), "--network-plugin=kubenet"), nil
}
```

Would it be possible to change the code so that it works on non-AKS clusters?

**Steps To Reproduce**

N/A

**Expected behavior**

NMI should start if kubelet config file does not exist

**AAD Pod Identity version**

1.7.4

**Kubernetes version**

1.19.7

**Comment by aramase** [comment]
> Would it be possible to change the code so that it works on non-AKS clusters?

@twendt Where is the kubelet config for clusters deployed with Rancher?

**Comment by twendt** [comment]
@aramase I could not find any. Kubelet runs as a docker container that was deployed by rke. The network-plugin is configured in the container entrypoint command line options.

**Comment by aramase** [comment]
@twendt Thank you. I think we can change the code to skip the check for the kubelet config file if `--allow-network-plugin-kubenet` is set to true. I'll add this to the next release.

**Comment by twendt** [comment]
@aramase Great thank you for your quick response.
